### ISSUE TITLE
Unable to connect to the outside world.

### ISSUE THREAD

**Issue by denellum** [Nyr/openvpn-install#100]
I am currently running a Cent 7 box and this is a VPS at OVH. I can connect (have firewalld disabled) but I can not ping anything outside of it's network, nor go to any websites. I did set this up with it's external facing IP. Here are the options i chose : 

[root@vpn ~]# sh openvpn-install.sh 

Welcome to this quick OpenVPN "road warrior" installer

I need to ask you a few questions before starting the setup
You can leave the default options and just press enter if you are ok with them

First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: 149.202.62.xx

What port do you want for OpenVPN?
Port: 1194

What DNS do you want to use with the VPN?
   1) Current system resolvers
   2) OpenDNS
   3) Level 3
   4) NTT
   5) Hurricane Electric
   6) Google
DNS [1-6]: 1

Finally, tell me your name for the client cert
Please, use one word only, no special characters
Client name: denellum

Any help would be appreciated, and thank you so much for setting this script up for us all :)

~den

**Comment by lukebarone** [comment]
What resolvers do you have in `/etc/resolv.conf`? What if you choose a different DNS server to test?

**Comment by denellum** [comment]
First of all, thank you for the help :)

here is my resolv.conf 
[user@vpn ~]$ cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search local anomaly.ws
nameserver 213.186.33.99
[user@vpn ~]$ ping google.com
PING google.com (173.194.45.64) 56(84) bytes of data.
64 bytes from par03s13-in-f0.1e100.net (173.194.45.64): icmp_seq=1 ttl=55 time=5.39 ms
64 bytes from par03s13-in-f0.1e100.net (173.194.45.64): icmp_seq=2 ttl=55 time=5.17 ms
64 bytes from par03s13-in-f0.1e100.net (173.194.45.64): icmp_seq=3 ttl=55 time=5.10 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 5.107/5.225/5.395/0.136 ms

I set it up with using the current resolvers. I will change it to google and try again.

**Comment by Nyr** [comment]
This is likely a firewall related problem or some other kind of conflict. Try on a clean CentOS install.

Definitively not a DNS issue since you selected the current system resolvers option.

**Comment by zenithteq** [comment]
Is SELinux disabled on the VPS?

I have some CentOS 7 servers on OVH but they are VMs on ESXi, Nyr's script works for me very well though as he says you need a very clean CentOS install (and Nyr is usually right....)

I tend do a minimal CentOS7 install, then disable SELinux & disable firewalld and then install iptables.

**Comment by denellum** [comment]
It ended up being the network i was testing it on at work. Works perfect when off their network :P thanks all! And Nyr, again, thank you for this awesome script :)
