### ISSUE TITLE
problem with ips in ipp.txt

### ISSUE THREAD

**Issue by IMIEEET** [Nyr/openvpn-install#1001]
lets say i removed a user through script and that client had a static ip assigned to it in ipp.txt
shouldn't script also delete the user from ipp.txt to prevent ips from overlapping?
is there another way to delete also from ipp.txt?
i was thinking of deleting the file and reassigning ips to users, is that ok?

**Comment by Nyr** [comment]
`ipp.txt` is generally speaking, not the place to configure static IP addresses for clients.

You are free to delete the file if you want, but you should not worry much about it.
