### ISSUE TITLE
Error 503 hostname doesn't match against certificate

### ISSUE THREAD

**Issue by eetsceeck1** [Nyr/openvpn-install#1009]
hello, 

something wrong today with the path, it did happen just several hours ago cause i successfully installed openvpn with it approximately 12 hours ago, 
![image](https://user-images.githubusercontent.com/43915916/207948949-e83306c5-a686-4181-977f-79631a22e45c.png)

**Comment by Nyr** [comment]
That does not have anything to do with this project.
