### ISSUE TITLE
Error 503 hostname doesn't match against certificate

### ISSUE THREAD

**Issue by eetsceeck1** [Nyr/openvpn-install#1010]
Sorry what do you by That does not have anything to do with this project.?

this path shows that error, in the browser and on the installation in debian
https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh 

![image](https://user-images.githubusercontent.com/43915916/207950232-a0a83b85-bc7e-4ef3-93d2-75b2191fd153.png)

![image](https://user-images.githubusercontent.com/43915916/207950919-83b36d75-bba4-4348-af4d-af70f96a0d0e.png)

**Comment by Nyr** [comment]
Your first screenshot lacked an important part of information, apparently `raw.github.com` is broken.

Anyway nothing I can do about the root cause of the problem, in case it does not get resolved by GitHub in a few hours I will change the URL..

Meanwhile, you can use this URL:
`https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh`

**Comment by Nyr** [comment]
GitHub has just updated the [status page](https://www.githubstatus.com/) and they are aware of the issue.

**Comment by eetsceeck1** [comment]
thank you!

can you please point me if its related to the script or not or what should i do? 
cause i am getting many errors it cant copy some certificates and keys, 
i have no idea if the script were should take care of this or i am the one who is guilty not doing something?

![image](https://user-images.githubusercontent.com/43915916/207954277-1b45994d-fa10-4285-ae08-3033fc22dbfc.png)

**Comment by Nyr** [comment]
Parts of GitHub are broken at the moment, and maybe some dependencies were not downloaded correctly. Use the uninstall option and try again later when GitHub is working fine.

**Comment by eetsceeck1** [comment]
thanks thanks! understood...
