### ISSUE TITLE
how to add password in client ?

### ISSUE THREAD

**Issue by bibekhazard** [Nyr/openvpn-install#1019]
hello Nyr i just want to ask you . how can i add password in my client config while using this script.i think adding password will be better  from security point of view.

**Comment by Shandeika** [comment]
+1

**Comment by Farhanadabi** [comment]
+1

**Comment by feddevanderlist** [comment]
In the script on 2 lines is the following code: `./easyrsa --batch --days=3650 build-client-full "$client" nopass` remove the nopass and it will request you to input a password. I don't have time to make it a pull request yet. Maybe someone else can do it. (with a question and a boolean) :)

**Comment by zhangxx2015** [comment]
+1
