### ISSUE TITLE
Server cannot ping to client

### ISSUE THREAD

**Issue by bafben10** [Nyr/openvpn-install#1020]
I cannot ping connected clients from the server computer or from any other computer on the network. I have turned on client-to-client and am able to communicate between clients.

I have tried this script with a fresh install of both Debian and Ubuntu. Here are the different settings that I have changed and/or verified:

IP Forwarding is turned on
client-to-client has been added to the config file
I've added a "push route" line to the config file
I've set up static routing in my network router (I'm confident this is working correctly since any pc on the network can ping 10.8.0.1)
I've done a fresh OS install, re-installed OpenVPN through the script, and re-applied all of the above settings

**Comment by bafben10** [comment]
In case anyone needs this functionality in the meantime, it seems to be working with Turnkey Wireguard and Turnkey OpenVPN.

**Comment by Nyr** [comment]
Duplicate. You can search previous issues on this matter.
