### ISSUE TITLE
Seeing real IP on my VDS and the new IP everywhere else

### ISSUE THREAD

**Issue by Darkzarich** [Nyr/openvpn-install#1026]
So, I installed it following the script and when I try to check my IP with https://www.myip.com/ everything works fine, I see the IP of my VDS meaning the VPN works. But for some reason my VDS still sees my real IP when I open some internal resource, say, admin panel. 

I want to protect some internal resources on my VDS, allow to open them only if using VPN but since my VDS still sees my real IP I can't set IP Access List. My real IP is seen in, for example, NGINX access logs.

What could be changed in the config to get it to work the way I want?

Cheers!

**Comment by Nyr** [comment]
What you describe is normal and how routing works. You can restrict the resources to listen only on the internal VPN network.
