### ISSUE TITLE
No internet conection after machine reboot

### ISSUE THREAD

**Issue by jpsanchezl10** [Nyr/openvpn-install#1027]
After I reboot my Ubuntu 22.10 machine(server) I still get connection to the OpenVPN server from the client, but there is no connection to the internet(client).

**Comment by zhangxx2015** [comment]
+1

**Comment by plashenkov** [comment]
The same. It would be nice to understand what's wrong and how to solve it.

![photo_2023-05-21_13-52-21](https://github.com/Nyr/openvpn-install/assets/2331932/4731d33e-2d1a-473d-abc3-f5565b38af06)

**Comment by Nyr** [comment]
I do not think that there is anything wrong with the installer.

Check if your server uses any kind of dynamic IP addressing. It is common on servers behind NAT, for example. The script requires a static IP address.
