### ISSUE TITLE
VPN will fail every few days. 

### ISSUE THREAD

**Issue by peiyun1982** [Nyr/openvpn-install#1028]
VPN can be used when the server is just deployed. However, after 5-7 days, it cannot be connected. only reinstall it again. This problem has occurred twice. I can ping this server. Restarting the server doesn't help。
Please help me see what's wrong, thank you!

![屏幕截图 2023-03-06 233942](https://user-images.githubusercontent.com/16250376/223157947-66e647fd-cb64-4c67-8ba9-9f52f4378983.png)

**Comment by Nyr** [comment]
Which client are you using? Try the official OpenVPN community package [here](https://openvpn.net/community-downloads/).

Are you connecting from China?

**Comment by peiyun1982** [comment]
yes，I using OpenVPN.and connecting from China.

**Comment by Nyr** [comment]
- I see you are using Azure. If your VM is behind NAT and the IP address changes, that can be problematic.
- OpenVPN from China is a hit and miss

Either way, nothing I can do about it.
