### ISSUE TITLE
problem with some site with this script

### ISSUE THREAD

**Issue by mahmoodhojabri** [Nyr/openvpn-install#103]
Hello, thanks for your supporting, i install this script, but when i conect to vpn, opengui write ip address is:10.4.xx.xx but when i go to whatismyip.com my ip is 40.117.93.xx (my vps ip) and i can not open youtube.com, facebook.com or other block site. i get connection timeout error. please help
Fri Dec 11 19:11:01 2015 C:\WINDOWS\system32\route.exe ADD 40.122.175.58 MASK 255.255.255.255 192.168.1.1
Fri Dec 11 19:11:01 2015 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index
=8]
Fri Dec 11 19:11:01 2015 Route addition via IPAPI failed [adaptive]
Fri Dec 11 19:11:01 2015 Route addition fallback to route.exe
Fri Dec 11 19:11:01 2015 env_block: add PATH=C:\Windows\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Fri Dec 11 19:11:01 2015 ERROR: Windows route add command failed [adaptive]: returned error code 1
Fri Dec 11 19:11:01 2015 C:\WINDOWS\system32\route.exe ADD 192.168.1.1 MASK 255.255.255.255 192.168.1.1 IF 8
Fri Dec 11 19:11:01 2015 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index
=8]
Fri Dec 11 19:11:01 2015 Route addition via IPAPI failed [adaptive]
Fri Dec 11 19:11:01 2015 Route addition fallback to route.exe
Fri Dec 11 19:11:01 2015 env_block: add PATH=C:\Windows\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Fri Dec 11 19:11:01 2015 ERROR: Windows route add command failed [adaptive]: returned error code 1
Fri Dec 11 19:11:01 2015 C:\WINDOWS\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 10.8.0.1
Fri Dec 11 19:11:01 2015 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index
=28]
Fri Dec 11 19:11:01 2015 Route addition via IPAPI failed [adaptive]
Fri Dec 11 19:11:01 2015 Route addition fallback to route.exe
Fri Dec 11 19:11:01 2015 env_block: add PATH=C:\Windows\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Fri Dec 11 19:11:01 2015 ERROR: Windows route add command failed [adaptive]: returned error code 1
Fri Dec 11 19:11:01 2015 C:\WINDOWS\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 10.8.0.1
Fri Dec 11 19:11:01 2015 ROUTE: route addition failed using CreateIpForwardEntry: Access is denied.   [status=5 if_index
=28]
Fri Dec 11 19:11:01 2015 Route addition via IPAPI failed [adaptive]
Fri Dec 11 19:11:01 2015 Route addition fallback to route.exe
Fri Dec 11 19:11:01 2015 env_block: add PATH=C:\Windows\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
Fri Dec 11 19:11:01 2015 ERROR: Windows route add command failed [adaptive]: returned error code 1
Fri Dec 11 19:11:01 2015 Initialization Sequence Completed

**Comment by mahmoodhojabri** [comment]
Hello, i change my vps to ubuntu 15.04 and now, i can not open any site after connect.

**Comment by mahmoodhojabri** [comment]
I ping 4.2.2.4, 8.8.8.8 after connect to vpn but i get request timeout. in azure, i open port 1194 and 443 in endpoint.

**Comment by Nyr** [comment]
On the first log, it looks like you weren't running OpenVPN as an admin on the client.

For the second, take a look at #99 and good luck.

**Comment by mahmoodhojabri** [comment]
Hello, no, i creat vm classic for ubuntu 15.04
but i don't have a internet connection.

**Comment by mahmoodhojabri** [comment]
read this last 1week
