### ISSUE TITLE
TLS Issues

### ISSUE THREAD

**Issue by JinQiang-Huang** [Nyr/openvpn-install#1030]
![image](https://user-images.githubusercontent.com/76467401/225858123-1cd437d5-ef34-4c8c-8597-e0bf909e2b08.png)
After the installation script was deployed, I downloaded ovpn to the client. When the client connected, the error message was connection timeout. I checked the log and the above error was displayed! Why is that?

**Comment by zhangxx2015** [comment]
+1

**Comment by Nyr** [comment]
This has to do with filtering/censorship in your country, not a problem with the installer.
