### ISSUE TITLE
ERROR 500" on a Debian-derived OS

### ISSUE THREAD

**Issue by Noratya** [Nyr/openvpn-install#1032]
![error](https://user-images.githubusercontent.com/83046915/229065693-9a080a60-71ae-4aeb-932f-655830d57615.PNG)

An error occurred before the installation script was deployed
Is this a default setting on Kali linux that I cannot use?

I also got the same error on Raspberry Pi OS.
Is it not available on Debian derivatives?

**Comment by Nyr** [comment]
This was a temporary server error not specific to this project.
