### ISSUE TITLE
Deprecation warning when installing OpenVPN version 2.5.1 on Raspbian Pi (Bullseye)

### ISSUE THREAD

**Issue by aslak47** [Nyr/openvpn-install#1035]
Notice
------
An updated CRL has been created.
CRL file: /etc/openvpn/server/easy-rsa/pki/crl.pem
2023-04-13 09:29:08 WARNING: **Using --genkey --secret filename is DEPRECATED**.  **Use --genkey secret filename instead**.
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-iptables.service → /etc/systemd/system/openvpn-iptables.service.
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-server@server.service → /lib/systemd/system/openvpn-server@.service.

**Comment by Nyr** [comment]
Read the previous 10 duplicate issues about this.
