### ISSUE TITLE
Domain support

### ISSUE THREAD

**Issue by wangwanjie** [Nyr/openvpn-install#1036]
Hi, thanks for supprting a so handsome script. I have been use ocserv for a long time, and i am willing to use domain instead of ip address. I am new in openvpn, can you consider add domain guide support to this script?

**Comment by Nyr** [comment]
Currently you can use domain names with this installer when setting up servers behind NAT.

If your server is not behind NAT, you will not have the chance to specify a domain name, except if you edit the script to achieve this. That said, and considering the script design, using domain names will not be very useful in most cases.

**Comment by wangwanjie** [comment]
> Currently you can use domain names with this installer when setting up servers behind NAT.
> 
> If your server is not behind NAT, you will not have the chance to specify a domain name, except if you edit the script to achieve this. That said, and considering the script design, using domain names will not be very useful in most cases.

thanks, I will try again later. Two more questions, the first one, would you be interested in writing a script similar to this one for deploying ocserv? Second, how to set up pac or no-route (similar to ocserv)?

**Comment by Nyr** [comment]
> would you be interested in writing a script similar to this one for deploying ocserv?

No

> how to set up pac or no-route (similar to ocserv)?

Read the OpenVPN manual.

**Comment by wangwanjie** [comment]
alright, thank you very much
