### ISSUE TITLE
openvpn.service working but issues with openvpn-server@1.service

### ISSUE THREAD

**Issue by John-Telek** [Nyr/openvpn-install#1037]
I attempted several scripts from github and elsewhere and the striesand script complains about some ansible thing.
But the best results I had were still broken.  Could someone shine a light on this pleas.

user@user-All-Series:~/bin$ sudo systemctl status openvpn-server@1.service
○ openvpn-server@1.service - OpenVPN service for 1
     Loaded: loaded (/lib/systemd/system/openvpn-server@.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:openvpn(8)
             https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
             https://community.openvpn.net/openvpn/wiki/HOWTO

Apr 16 14:08:29 user-All-Series systemd[1]: Failed to start OpenVPN service for 1.
Apr 16 14:08:34 user-All-Series systemd[1]: openvpn-server@1.service: Scheduled restart job, restart counter>
Apr 16 14:08:34 user-All-Series systemd[1]: Stopped OpenVPN service for 1.
Apr 16 14:08:34 user-All-Series systemd[1]: Starting OpenVPN service for 1...
Apr 16 14:08:34 user-All-Series openvpn[48350]: Options error: In [CMD-LINE]:1: Error opening configuration >
Apr 16 14:08:34 user-All-Series openvpn[48350]: Use --help for more information.
Apr 16 14:08:34 user-All-Series systemd[1]: openvpn-server@1.service: Main process exited, code=exited, stat>
Apr 16 14:08:34 user-All-Series systemd[1]: openvpn-server@1.service: Failed with result 'exit-code'.
Apr 16 14:08:34 user-All-Series systemd[1]: Failed to start OpenVPN service for 1.
Apr 16 14:08:37 user-All-Series systemd[1]: Stopped OpenVPN service for 1.

And the service file

user@user-All-Series:~/bin$ more /lib/systemd/system/openvpn-server@.service
[Unit]
Description=OpenVPN service for %I
After=network-online.target
Wants=network-online.target
Documentation=man:openvpn(8)
Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO

[Service]
Type=notify
PrivateTmp=true
WorkingDirectory=/etc/openvpn/server
ExecStart=/usr/sbin/openvpn --status %t/openvpn-server/status-%i.log --status-version 2 --suppress-timestamps
 --config %i.conf
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_S
YS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
ProtectSystem=true
ProtectHome=true
KillMode=process
RestartSec=5s
Restart=on-failure

[Install]
WantedBy=multi-user.target

Any more info needed please ask.

Cheers,
   John.

**Comment by TinCanTech** [comment]
`systemctl` is looking for a server config file called: `/etc/openvpn/server/1.conf`, is there a file by that name ?

**Comment by John-Telek** [comment]
I spent most of the day trying 1 manual and 2 scripted ways installing
it. Eventuall I got a script off github and it kind of worked. The
openvpn.service was running and I was succesfull in cinnecting from a
client on my phone. but what is this ***@***.*** which keeps
fritzing out ??

Anyway it was an educational execise. I discovered my new modem has
got built in servers for multiple vpn solutions and as the modem is
open source hardware and firmware I wasn't surprised and I'm very happy
with it. And It solved my dilema of of port forwarding. I just added my
rules, hit save and bob's your uncle.

I will say it's a messy pieco of code to get right snd setup right.

Cheers,
  John.

**Comment by John-Telek** [comment]
I spent most of the day trying 1 manual and 2 scripted ways installing
it. Eventuall I got a script off github and it kind of worked. The
openvpn.service was running and I was succesfull in cinnecting from a
client on my phone. but what is this ***@***.*** which keeps
fritzing out ??

Anyway it was an educational execise. I discovered my new modem has
got built in servers for multiple vpn solutions and as the modem is
open source hardware and firmware I wasn't surprised and I'm very happy
with it. And It solved my dilema of of port forwarding. I just added my
rules, hit save and bob's your uncle.

I will say it's a mes

**Comment by Nyr** [comment]
No offense, but the mess is created by using multiple, conflicting software tools for the same purpose. Try using my installer in a clean system, and it will work for sure.

The only service unit this script uses is `openvpn-server@server.service`. So if you have services with other names, they have not been created by my installer.

**Comment by John-Telek** [comment]
No worries mate. I have a Pi 3/4b. Will your script work on ARM64 ?

Cheers,
    JT.

**Comment by John-Telek** [comment]
Ok, I'll check it out.  Will this script work on the raspberry, pi four or
three?

**Comment by Nyr** [comment]
I have not personally tested, but it should work, and I have seen reports that it works in the past.

**Comment by John-Telek** [comment]
Thanks, I'll check it out.
