### ISSUE TITLE
How to modify the configuration to allow multiple customers to connect to OpenVPN at the same time

### ISSUE THREAD

**Issue by 837609420** [Nyr/openvpn-install#1051]
local 
port 
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 208.67.222.222"
push "dhcp-option DNS 208.67.220.220"
push "block-outside-dns"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
explicit-exit-notify

**Comment by krimtsev** [comment]
duplicate-cn

**Comment by MohamadSafi** [comment]
Hello I had this issue before and I solved it by changing the following line in the bash file.
Look for the line that starts with server and defines the VPN subnet. It typically looks like this:
`server 10.8.0.0 255.255.255.0`
You can increase the number of allowed clients by changing the subnet mask to a larger one. For example:
`server 10.8.0.0 255.255.255.128`
This allows up to 126 clients to connect (the first and last IP addresses are reserved).

**Comment by Nyr** [comment]
> duplicate-cn

This is the correct response.

But you should just use one certificate per client. Sharing certificates is not a good idea in 99% of the cases.
