### ISSUE TITLE
Pushing this lovely shell script further? Thanks for saving me a lot of time and pain ! 

### ISSUE THREAD

**Issue by gyrusdentatus** [Nyr/openvpn-install#1054]
FIRST OF ALL - **(!!! <3) ... Huuuuge thanks,** gonna send ya some sats if you add LNBTC, ATOM or NYM and XMR hehe :P 

#### For donations addresses:
Use [pastenym](pastenym.com) for the most bleeding edge **pastebin** running over **_NYM mixnet_** (big new stuff coming out this summer btw with their coconut...I mean zk-nym credentials etc)
Chelsea Manning or someone somewhere said even _**Snowden**_ is using **pastenym** nowadays :) 

I could not find where I got the script lol until I started going through the actual shscript after initing a new repo. 

### My proposal for collaboration/enhancement
How about making a project together that asks users if they want to deploy this and that (**openvpn, wg,** **what are the expectations etc, you know - do you want a truckload of pork or just one chop mister?** hehe )

- I think **pure `bash` or even `sh` are the best for these tasks**, simply because they are present on almost all *NIX based systems from the get go. 

- I could start by forking your latest WG project and make a PR against your repo, how about it? I want me some fancy colors and cool user input, robust options or no options (kinda like the good ol Rust installer that you pipe to sh from curl ) ... 

CHEERS and THANKS ! ! !

**Comment by gyrusdentatus** [comment]
oh yeah now I know why I did open the actual code haha, it was to see if I can use it for a WIN-DOS client - only runs Steam and nothing else so ... and I need to play JA3 while I'm away from my network :d MSDOS HAD BETTER LISTEN TO WHAT I WANT IT TO DO :)

**Comment by Nyr** [comment]
Sorry, but no.

While I have maintained this project for almost 11 years and am still committing to maintain and keep it updated and secure, I am not interested in adding many significant changes.
