### ISSUE TITLE
reloading csf -ra triggers lose connections

### ISSUE THREAD

**Issue by mrEckendonk** [Nyr/openvpn-install#1056]
Hello,

When using the CSF firewall and changing something to the firewall that needs to reload it csf -ra, all created open-vpn connections fail.
The firewall rules created by the script are not loaded anymore.

what do we need to do to enable the iptables again, without removing and installing the script again?

Thanks!

**Comment by Nyr** [comment]
`systemctl restart openvpn-iptables.service`
