### ISSUE TITLE
Fails to connects (kvm ubuntu server, ubuntu host)

### ISSUE THREAD

**Issue by aTm12** [Nyr/openvpn-install#1057]
installation complete on ubuntu 22.04lts  KVM-qemu with NAT  ethernet 
during installation on the server i wrote the public IP correctly 
however i wasn't able to  connect from  host pc (ubuntu)   openvpn file  fails to connect  
I try to connect Locally only on the same pc 
i assume remotely won t work as well ! 
ow to solve this issue

**Comment by hostingfuze** [comment]
check forward port

**Comment by aTm12** [comment]
ufw is enabled and port is set correctly,  i used port orward  port checker  site it shows that the port is closed, i tried many different ports all of them are closed ....
