### ISSUE TITLE
debian12

### ISSUE THREAD

**Issue by liurongdong** [Nyr/openvpn-install#1061]
<img width="1613" alt="image" src="https://github.com/Nyr/openvpn-install/assets/16183649/afddc58b-5bcd-4ad9-9af0-eb675cd6b1c5">

**Comment by ByloTonix** [comment]
try to edit the flags in the installation script, as here
https://forums.openvpn.net/viewtopic.php?t=33536

**Comment by Nyr** [comment]
This installer does not make use of the `--status` parameter.
