### ISSUE TITLE
getcwd() failed

### ISSUE THREAD

**Issue by Null-Ouwenjie** [Nyr/openvpn-install#1062]
ubuntu 22.04 64, root user
run in path:  /root
can not install openvpn, fail reason is : sh: 0: getcwd() failed: No such file or directory.

log history:
`
Notice
------
An updated CRL has been created:
* /etc/openvpn/server/easy-rsa/pki/crl.pem

2023-09-13 14:22:55 WARNING: Using --genkey --secret filename is DEPRECATED.  Use --genkey secret filename instead.

Finished!

The client configuration is available in: /root/client.ovpn
New clients can be added by running this script again.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libpkcs11-helper1
Use 'apt autoremove' to remove it.
sh: 0: getcwd() failed: No such file or directory
The following packages will be REMOVED:
  openvpn*
sh: 0: getcwd() failed: No such file or directory
0 upgraded, 0 newly installed, 1 to remove and 54 not upgraded.
sh: 0: getcwd() failed: No such file or directory
After this operation, 1,663 kB disk space will be freed.
sh: 0: getcwd() failed: No such file or directory
(Reading database ... 80464 files and directories currently installed.)
Removing openvpn (2.5.5-1ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
(Reading database ... 80380 files and directories currently installed.)
Purging configuration files for openvpn (2.5.5-1ubuntu3.1) ...
sh: 0: getcwd() failed: No such file or directory

OpenVPN removed!
openvpn-install.sh: line 580: syntax error near unexpected token `else'
openvpn-install.sh: line 580: `                 else'
`

**Comment by Null-Ouwenjie** [comment]
it almost install success, look like remove `libpkcs11-helper1` has error ?

**Comment by Nrpk46** [comment]
AZAMSSRV_AFE8E6CAAC6E9815AD972BBB182CFCAF
