### ISSUE TITLE
How to add tow factor authtication to the configuration file

### ISSUE THREAD

**Issue by MohamadSafi** [Nyr/openvpn-install#1065]
I am trying to add a Two-Factor Authentication to my open vpn server I am not sure if we can do this using the bash file to write it in the configuration file if this possible it will be very helpful to add it or help in how to actually add it manually to the `openvpn.conf` file.
The authentication process should look something like this:
![image](https://github.com/Nyr/openvpn-install/assets/101475647/f47babff-dcee-47fc-bfc6-027e7c1d732e)

**Comment by Nyr** [comment]
This feature is not supported by the installer.
