### ISSUE TITLE
Upgrade OpenVPN -> "IP packet with unknown IP version=0 seen", can connect but not reach internal ips

### ISSUE THREAD

**Issue by nepixl** [Nyr/openvpn-install#1068]
Running your script some time now and Im happy about that. btw: thanks for this awesome script and your work behind!

Im running `OpenVPN 2.5.7` on OpenSSL 1.1.1s at this moment and wanted to update to `2.6.6` via `sudo apt install openvpn`.

After the update was successful the clients can connect but iPhones f.e. sends this error:
`IP packet with unknown IP version=0 seen`

iPhones can connect but can't reach internal ips.

Any ideas?

### Servercfg:

> local xxx.xxx.xxx.xxxx
> port xxx
> proto udp
> dev tun
> ca ca.crt
> cert server.crt
> key server.key
> dh dh.pem
> auth SHA512
> tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RS>
> tls-crypt tc.key
> tls-version-min 1.2
> topology subnet
> server 10.8.0.0 255.255.255.0
> push "redirect-gateway def1 bypass-dhcp"
> ifconfig-pool-persist ipp.txt
> push "dhcp-option DNS xx"
> push "dhcp-option DNS xx"
> push "dhcp-option DNS x"
> keepalive 10 120
> ncp-ciphers AES-256-GCM:AES-192-GCM:AES-128-GCM
> user nobody
> group nogroup
> persist-key
> persist-tun
> verb 3
> crl-verify crl.pem
> explicit-exit-notify
> management 127.0.0.1 17562
> status openvpn-status.log

### ClientCfg:

> client
> dev tun
> proto udp
> remote externalServerIP defined Port
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> remote-cert-tls server
> auth SHA512
> cipher AES-256-CBC
> ignore-unknown-option block-outside-dns
> block-outside-dns
> verb 3
> < certificate stuff >
> ....

I've searched the internet for that error, that points me to compressing stuff but I've nowhere (un)set this. How can I enable or disable this feature without sending all certificates to the user again? (50 accounts).
It looks like its a problem with mobile devices?

Any idea what going wrong? Help is really appreciated.

Thanks and regards

**Comment by Nyr** [comment]
v2.6.6 is not in any of the distro's repos, so I guess you are using the official OpenVPN repo, which should work but is unsupported.

Additionally you are not using the configuration from my installer so I can not provide support for that. I wonder if you are even using my installer at all.
