### ISSUE TITLE
A warning will be displayed

### ISSUE THREAD

**Issue by pikesaury** [Nyr/openvpn-install#1071]
Hello.
A warning message appears when connecting in the following environments.

---

host

uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

cat /etc/debian_version
12.2

client

Windows 11
OpenVPN GUI v 11.44.0.0

---

DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305). OpenVPN ignores --cipher for cipher negotiations. 
---

This is an option that will not be available in the future and should be corrected.
Please fix.
sorry poor english.

**Comment by Nyr** [comment]
There is nothing to fix. The warning is harmless and ensures compatibility with some old clients. The affected parameter will be removed in the future, but not yet.
