### ISSUE TITLE
easy-rsa support suggestion

### ISSUE THREAD

**Issue by pikesaury** [Nyr/openvpn-install#1072]
You can download the latest version this way.

curl -s https://api.github.com/repos/OpenVPN/easy-rsa/releases/latest | grep "browser_download_url" | grep -v "sig" | grep "tgz" | cut -d : -f 2,3 | tr -d \" | wget -Ni -

Please consider if needed.

**Comment by Nyr** [comment]
I am well aware of this.

But then who will read the change log, test the new version and make changes to the installer if needed?
