### ISSUE TITLE
How to upgrade openvpn

### ISSUE THREAD

**Issue by erdong01** [Nyr/openvpn-install#1073]

**Comment by Nyr** [comment]
`apt-get update && apt-get upgrade`

**Comment by karran-d** [comment]
I installed yesterday openvpn server on ubuntu 22.04 with this script and the openvpn server version installed was 2.5.5. The latest version is 2.6.6. So I ran sudo apt-get update && sudo apt-get upgrade but the version is still 2.5.5.
Am I missing here something?

**Comment by Nyr** [comment]
It is using the Ubuntu repos. This is normal.
https://packages.ubuntu.com/jammy/openvpn

Do you have any good reason to run v2 6.6 or just want the higher number?

**Comment by karran-d** [comment]
I am assuming that a newer version means a lot of bug fixes, improved performance, security fixes and enhanced features.
Am I wrong?

**Comment by Nyr** [comment]
The linked package is not available for Ubuntu 22.04.

New versions of course mean new features, but Linux distributions usually lag behind in their repositories and this is normal/expected. My installer currently does not make use of any feature newer than OpenVPN 2.4.0, so I see no reason to install a newer package from a different source than the distro repos.

If you insist, you can probably set up the OpenVPN repos for Ubuntu:
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos#DebianUbuntu:UsingOpenVPNaptrepositories

But I see no reason for the average user of my installer to do that.
