### ISSUE TITLE
Creating new user - ovpn file

### ISSUE THREAD

**Issue by csimlinger** [Nyr/openvpn-install#1075]
Thanks for this amazing script.
I have a beginners question I cant figure out:

I set up the VPN server, create my own user and was able to download the .ovpn file.
When I load it into my VPN client, it works perfectly but does not ask for a username/password.

Now I tried to create another user but I can not get a new .ovpn file.
As I don't need a username/password to connect (only the .ovpn) file, I guess the .ovpn file is specific for the first user I created (myself).

How can I get the .ovpn file for the newly created users?

Thanks a lot!

**Comment by Nyr** [comment]
About the username/password, that is normal. OpenVPN has many authentication methods, with the most common being certificates. Your .ovpn file includes the certificate required for authentication, which is actually safer than a password.

About the .ovpn files for further clients, they will be in your home directory.

**Comment by csimlinger** [comment]
Thanks a lot!
