### ISSUE TITLE
Create new user without internet access

### ISSUE THREAD

**Issue by csimlinger** [Nyr/openvpn-install#1076]
In order to create a new user, I run:

`wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh`

When I activate my firewall (only few incoming IPs allowed), I can not run the command.

If I try to run `sudo bash openvpn-install.sh` nothing happens. I was hoping that I could create users that way without the script being able to access the internet. Any way to do that?

Thanks!

**Comment by Nyr** [comment]
The one loner does not use sudo, while you are using sudo when running manually. That is the only difference. You do not need to use sudo if your user is root or has superuser privileges.
