### ISSUE TITLE
[Feature Request] Allow MAC filter disabling 

### ISSUE THREAD

**Issue by hizani** [Nyr/openvpn-install#1077]
I'm using per network MAC randomization on my devices, so I can't use same certificate in different networks. Is there a way to disable MAC filter for certain clients? If no, it would be cool to have this feature in the future.

**Comment by Nyr** [comment]
Are you confusing MAC addresses with HMAC?

Anyway you can use the same certificate from as many networks as you want. Just one connection per certificate at a time. This can be changed with the `duplicate-cn` directive and it is always better to use one certificate per client.
