### ISSUE TITLE
disable client to client traffic

### ISSUE THREAD

**Issue by Ahshawky01** [Nyr/openvpn-install#1078]
thanks too much it is very smart script 

i need to make clients  dont talk to each other

**Comment by Ahshawky01** [comment]
<img width="726" alt="Screenshot 2023-12-01 201020" src="https://github.com/Nyr/openvpn-install/assets/152063347/70844091-7951-4d20-a93c-4c3fa0d83cf5">

i didnot  have these string

**Comment by Nyr** [comment]
Yes, you do. Remove the string from the file.

**Comment by Ahshawky01** [comment]
thanks to your valuable time 
but i remove string and still clients can be able to ping each other

i tried to remove the file and restart the openvpn-server
worked but still the same issue 


details :
ubuntu 
firewall disabled
