### ISSUE TITLE
Can't find client config

### ISSUE THREAD

**Issue by celfa** [Nyr/openvpn-install#108]
Hi. I've tried your script, and in the end, I got this message:
"Your client config is available at ~/MyUser.ovpn"

But then I look at my home folder and this file doesn't exist. I've tried to use "which" and "find" to search for the file, but with no result. Is it possible to change the script, so I can choose where my client config is located?

**Comment by firsttris** [comment]
~/ 
=
/root/

**Comment by celfa** [comment]
Aha. Thank you.
