### ISSUE TITLE
After connecting, unable to access the internet.

### ISSUE THREAD

**Issue by star2k** [Nyr/openvpn-install#1080]
The one-click script successfully installed on the VPS, and the local client also connected to the OpenVPN server. However, it was found that the client computer could not access the internet. What could be the reason for this?

**Comment by yuqiangabab** [comment]
so am i

**Comment by vadjs** [comment]
Same issue

**Comment by fannur** [comment]
same problem

**Comment by foreversolar** [comment]
same problem

**Comment by wuzhejia** [comment]
same problem

**Comment by Nyr** [comment]
Saying "same" is useless to troubleshoot the issue. We have six replies by now and absolutely no actionable information.

- Which distro and version is the server running?
- Is the server behind NAT?
- Does the server have a firewall installed?
- Have you tried connecting from a different client device?
- Are you trying to connect from a place with significant internet censorship? If so: from where?
- Provide a client connection log
