### ISSUE TITLE
On some Dual Stack machines, the shell did not successfully recognize the two Stacks

### ISSUE THREAD

**Issue by Marrrrrrrrry** [Nyr/openvpn-install#1089]
I'm ubuntu 23.10
I have successfully deployed and connected with this shell on some Dual Stack machines. 
But on 23.10 I am getting a stable reproduction of the problem like the title.
 the shell only recognizes IPv4. I hope that in the next version there will be an option for the user to select the protocol Stack.

**Comment by Nyr** [comment]
Unable to reproduce, works fine in Ubuntu 23.10.
