### ISSUE TITLE
How to get files to .p12

### ISSUE THREAD

**Issue by Jayman47** [Nyr/openvpn-install#109]
In order to use openvpn on a chromebook the cert needs to be .p12, not .ovpn. Anyway to have certificate type as an option?

**Comment by Nyr** [comment]
This is an advanced/niche option so not planned. Convert it manually.

**Comment by Jayman47** [comment]
help me? :)

**Comment by Nyr** [comment]
https://www.google.ru/search?q=openvpn+p12
