### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by unecc** [Nyr/openvpn-install#1097]
Hi, i'm gettin this tutorial 
https://pve.proxmox.com/wiki/OpenVPN_in_LXC

when i try 
git clone https://github.com/Nyr/openvpn-install

this is my error
root@OpenVPN-CT:~# git clone https://github.com/Nyr/openvpn-install
Cloning into 'openvpn-install'...
fatal: unable to access 'https://github.com/Nyr/openvpn-install/': Could not resolve host: github.com

i've try also to use 
git config --global --unset http.proxy &&
git config --global --unset https.proxy
what's wrong?

**Comment by Nyr** [comment]
This is most likely a connectivity problem inside your container. Make sure it has internet access.

**Comment by unecc** [comment]
Thanks for your helping, effectly was a static ip conflict in my router. 👍
