### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by aabosh** [Nyr/openvpn-install#110]
Would it be possible if you could add an option allowing TCP or UDP? Would be really appreciated.

**Comment by Nyr** [comment]
No, sorry. I understand it has some use cases, but TCP over TCP is generally not a good idea and I don't want users misunderstanding this choice.

For anyone who needs it, switching to TCP is easy enough :)

**Comment by zabullet** [comment]
@aabosh  

You can look at 

https://github.com/pl48415/openvpn-install-advanced

or my fork 

https://github.com/zabullet/openvpn-install-advanced

**Comment by aabosh** [comment]
@zabullet Your fork worked great, thank you!
