### ISSUE TITLE
Future Request ： Supporting network environments with only IPv6 public network and has no IPv4 public network

### ISSUE THREAD

**Issue by wljince007** [Nyr/openvpn-install#1103]

**Comment by Nyr** [comment]
There are no plans for this, sorry.

**Comment by ElryGH** [comment]
sorry to kick in like this but openvpn works with just ipv6, so whats stopping you from implementing this ?
Its such a shame as most home networks only have access to a public ipv6 and some ipv4 thats Carrier-Grade NAT (Unusable)
