### ISSUE TITLE
FEATURE REQUEST: Split Tunneling

### ISSUE THREAD

**Issue by a-warner-knight** [Nyr/openvpn-install#1115]
Can we add an option for split tunneling? I implemented by modifying client-common.txt to include:
> route-nopull
> route 10.8.0.0 255.255.255.0
> route 192.168.0.0 255.255.0.0

but obviously the 192.16.8.x.x private subnet would have to be prompted for (or detected?).
Or should this be implemented by server.conf?

I love this script. Happy to attempt a PR if anybody +1s this.

**Comment by Nyr** [comment]
Not interested in this. sorry.
