### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by GrampusV** [Nyr/openvpn-install#1119]
https://github.com/Nyr/openvpn-install/blob/62781749e530830acb803d17566c3ef4ec8bd7e1/openvpn-install.sh#L258C19-L258C25

258 openvpn --genkey secret /etc/openvpn/server/tc.key

Correct

258 openvpn --genkey **--secret** /etc/openvpn/server/tc.key

**Comment by Nyr** [comment]
Wrong. The actual syntax is correct since OpenVPN v2.5, read the manual. The previous syntax is deprecated.

**Comment by GrampusV** [comment]
> Wrong. The actual syntax is correct since OpenVPN v2.5, read the manual. The previous syntax is deprecated.

Thank you! I pointed this out just in case.
