### ISSUE TITLE
Issues with Scaleway

### ISSUE THREAD

**Issue by Issam2204** [Nyr/openvpn-install#112]
Hello, and thank you kindly for this great installer!

I'm having issues making work a Scaleway instance. After installation I try to connect with the .ovpn file from my laptop. The connection seems to go well (green OpenVPN icon), but I have no internet access.

Do you know of any known issues with Scaleway?

**Comment by Nyr** [comment]
IIRC they do use NAT so it's very likely that you didn't correctly specify the correct IP address during the first installation step.

You need to use the internal IP address on this first step and then specify the public one when asked later.

**Comment by Issam2204** [comment]
Thank you for the answer Nyr!

When prompted the IP address I automatically see the internal IP selected. I changed it to the public one. So this is wrong. I need to confirm the internal IP and then specify the public later.

Correct?

Thank you and happy new year!

**Comment by Nyr** [comment]
Yes, that's it.

Happy New Year :)

**Comment by Issam2204** [comment]
Hi Nyr!

First of all happy new year :)

As you suggested, I inserted my internal IP and then later (when asked) I put my public IP. However, it is still not working. I've tried with Ubuntu (15.10) and Debian (8.2).

With my Windows 7 laptop it connects and I have a green little icon in the systemtray, but no internet connection.
With my Windows 10 laptop it can't connect. This is part of the log:

    Fri Jan 01 12:45:53 2016 VERIFY EKU OK
    Fri Jan 01 12:45:53 2016 VERIFY OK: depth=0, CN=server
    Fri Jan 01 12:45:53 2016 Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
    Fri Jan 01 12:45:53 2016 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
    Fri Jan 01 12:45:53 2016 Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
    Fri Jan 01 12:45:53 2016 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
    Fri Jan 01 12:45:53 2016 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
    Fri Jan 01 12:45:53 2016 [server] Peer Connection Initiated with [AF_INET]MY_IP:1194
    Fri Jan 01 12:45:55 2016 MANAGEMENT: >STATE:1451648755,GET_CONFIG,,,
    Fri Jan 01 12:45:56 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:01 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:07 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:12 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:18 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:23 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:28 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:33 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
    Fri Jan 01 12:46:38 2016 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)´

Would you prefer me to write in GitHub?

Thank you for everything so far!

**Comment by Nyr** [comment]
Are you running the client as an administrator?

**Comment by Issam2204** [comment]
Yes, I'm. However, please ignore the error/log on Windows 10: I tried to run two instances simultaneously. Once I realized that, I connected to the Scaleway server successfully (like in Windows 7) but no internet connection was available.

They even have an image you can install called "OpenVPN Image" that supposedly would give an OpenVPN server out of the box. That is not working either.

If I can I'll try to solve this issue and poste back here.

Thank you kindly for the help so far!
