### ISSUE TITLE
Failed to connect to to raw.github.com

### ISSUE THREAD

**Issue by Officer-Henrih** [Nyr/openvpn-install#1123]
Using 
wget https://git.io/vpn -O   
Get an error below
``
--2024-09-21 09:22:42--  https://git.io/vpn  
Resolving git.io (git.io)... 140.82.112.22                                                                   
Connecting to git.io (git.io)|140.82.112.22|:443... connected.                                               
HTTP request sent, awaiting response... 301 Moved Permanently                                                
Location: https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh [following]                   
--2024-09-21 09:22:43--  https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh                
Resolving raw.github.com (raw.github.com)... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8002::154, .
..                                                                                                           
Connecting to raw.github.com (raw.github.com)|2606:50c0:8003::154|:443... failed: Connection timed out.      ``

**Comment by Nyr** [comment]
This is an issue in your end. Try later, or transfer the file in a different way.
