### ISSUE TITLE
Super user access needed

### ISSUE THREAD

**Issue by psychoAuby** [Nyr/openvpn-install#1126]
Hi I am very new to linux so I know this is very likely a stupid issue but when I run the command as is it says I need superuser privileges. I have also tried running the command with sudo at the start and it says the same thing

**Comment by Nyr** [comment]
Once you have the script downloaded, you can do `chmod +x openvpn-install.sh` to set execution permissiones for the script.

Then, do `sudo openvpn-install.sh`.
