### ISSUE TITLE
Static routes for new users

### ISSUE THREAD

**Issue by TheBakler** [Nyr/openvpn-install#1127]
Hi, how do I add static routes to the script for new users? I'm probably not looking carefully, I'd like to add static routes to the script when creating a new client. Where can I do it?

**Comment by TheBakler** [comment]
Hi, found a template file for clients client-common.txt. There I specified a list of routes. Can you tell me if this is the right solution, maybe there are other ways?

**Comment by Nyr** [comment]
That is a decent solution, as that file is sourced with every client creation.
