### ISSUE TITLE
Install script tells me server is behind a NAT and asks for the public IPv4

### ISSUE THREAD

**Issue by bucklevision** [Nyr/openvpn-install#1131]
This is fine but the IPv4 will change as it is behind a DDNS, is it necessary to have the public IP - my current implementation on an existing machine just listens on a local port and accepts anything sent to it rather than requiring knowledge of it's place in the public world.

**Comment by Nyr** [comment]
It is not "necessary" but it is how this installer works as it is more efficient, and for other reasons.

You could change iptables/firewalld rules from `MASQUERADE` to `POSTROUTING` manually after install, if that is what you need, but I have no plans to include this in the installer.

[Here](https://github.com/Nyr/openvpn-install/issues/427#issuecomment-419977391) you have slightly outdated information on the matter.
