### ISSUE TITLE
OpenVPN does not pass traffic through itself

### ISSUE THREAD

**Issue by MoskalenkoM** [Nyr/openvpn-install#1132]
Hello!
I tried your openvpn configuration, there is a connection to openvpn, but there is no traffic through openvpn, the network is unavailable.
In May-June, everything worked correctly, but now it does not work.
I have servers in different locations on Ubuntu 22.04 and 24.04.
If you need a log of connecting to openvpn and a log of trying to log on to the network, then I will attach a file. I am not strong in networks, but maybe something is blocking iptables, I can also attach a config, I did not find a solution to the problem on the network.
Thank you for the answer!

**Comment by MoskalenkoM** [comment]
Scanning ports to a server with openvpn working and not working gives the same results.
But there is a difference in the output of the commands: `netstat -ntlp` and `ip address show`

**Comment by Nyr** [comment]
Try on a different client and you will see if it is a client or server side issue.

Also the netstat command you mentioned will not print UDP ports, which is where OpenVPN listens by default. Anyway, if you can connect, then the server is accessible.

**Comment by MoskalenkoM** [comment]
The server is available, external resources can be pinged from the server.
The client connects to OpenVPN, but there is no traffic through OpenVPN.
If it is important, but /var/log/openvpn is empty.
The different client also does not work through OpenVPN.
This is the behavior of OpenVPN on all VDS where I run your script.

**Comment by MoskalenkoM** [comment]
[poland-test.log](https://github.com/user-attachments/files/17559504/poland-test.log)

**Comment by MoskalenkoM** [comment]
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 TLS: Initial packet from [AF_INET]213.24.125.241:22025, sid=d041c59d 862f5cb9
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 VERIFY OK: depth=1, CN=Easy-RSA CA
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 VERIFY OK: depth=0, CN=poland-test-2
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_VER=3.10_qa
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_PLAT=ios
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_NCP=2
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_TCPNL=1
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_PROTO=2974
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_MTU=1600
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_CIPHERS=AES-128-CBC:AES-192-CBC:AES-256-CBC:AES-128-GCM:AES-192-GCM:AES-256-GCM:CHACHA20-POLY1305
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_AUTO_SESS=1
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.5.0-6000
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_SSO=webauth,crtext
Oct 29 15:28:37 anxiouschemical openvpn[9630]: 213.24.125.241:22025 peer info: IV_BS64DL=1
Oct 29 15:28:38 anxiouschemical openvpn[9630]: 213.24.125.241:22025 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256
Oct 29 15:28:38 anxiouschemical openvpn[9630]: 213.24.125.241:22025 [poland-test-2] Peer Connection Initiated with [AF_INET]213.24.125.241:22025
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 MULTI_sva: pool returned IPv4=10.8.0.3, IPv6=fddd:1194:1194:1194::1001
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 MULTI: Learn: 10.8.0.3 -> poland-test-2/213.24.125.241:22025
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 MULTI: primary virtual IP for poland-test-2/213.24.125.241:22025: 10.8.0.3
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 MULTI: Learn: fddd:1194:1194:1194::1001 -> poland-test-2/213.24.125.241:22025
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 MULTI: primary virtual IPv6 for poland-test-2/213.24.125.241:22025: fddd:1194:1194:1194::1001
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 Data Channel: using negotiated cipher 'AES-256-GCM'
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 SENT CONTROL [poland-test-2]: 'PUSH_REPLY,redirect-gateway def1 ipv6 bypass-dhcp,dhcp-option DNS 1.1.1.1,dhcp-option DNS 1.0.0.1,block-outside-dns,tun-ipv6,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig-ipv6 fddd:1194:1194:1194::1001/64 fddd:1194:1194:1194::1,ifconfig 10.8.0.3 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Oct 29 15:28:38 anxiouschemical openvpn[9630]: poland-test-2/213.24.125.241:22025 PUSH: Received control message: 'PUSH_REQUEST'
Oct 29 15:29:51 anxiouschemical qemu-ga: info: guest-ping called
