### ISSUE TITLE
sorry, you need to run this as root!

### ISSUE THREAD

**Issue by varunteja3634** [Nyr/openvpn-install#115]
hi i tried running the command 
`sudo wget git.io/vpn --no-check-certificate -O openvpn-install.sh && bash openvpn-install.sh`

but i got this
![screenshot from 2016-01-30 16 20 00](https://cloud.githubusercontent.com/assets/15001874/12695242/aa90d906-c76d-11e5-8f56-a30055c4ca5e.png)

but i am running this as `sudo` superuser. ok i also tried changing to root directory and ran this again. but same error! please help as i'm new to ubuntu!

**Comment by liyangyijie** [comment]
In fact , only the root user can run it .
So ...
`su -`

**Comment by lukebarone** [comment]
The sudo you're using is just for the wget command. You need either a sudo on the actual script itself, or else run the whole thing as root (preferred)

**Comment by varunteja3634** [comment]
liyangyijie  In Fact,  IAM the root and the super user. so you `su`.
lukebarone how?

**Comment by lukebarone** [comment]
Use sudo bash, then run the script.

**Comment by Nyr** [comment]
Thanks guys.

**Comment by varunteja3634** [comment]
oh, sorry actually after 15 min i did work thanks. sorry for the late reply 
`sudo -c 'wget git.io/vpn --no-check-certificate -O openvpn-install.sh && bash openvpn-install.sh'`
