### ISSUE TITLE
feature request: client-to-client option

### ISSUE THREAD

**Issue by ddavidebor** [Nyr/openvpn-install#118]
I've always done it manually, but i think it could be nice if there was an option in this script to add the client-to-client option to server.conf. 

I've noticed sometimes clients can reach each other if they're on the same network  (and on very vanilla networks, it does not seems to work across corporate subnets) and it can be misleading at first.

**Comment by valery1707** [comment]
This option exists in [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet
