### ISSUE TITLE
show active certificate when going into option 3

### ISSUE THREAD

**Issue by shakisha** [Nyr/openvpn-install#120]
Is there an easy way to show which certificate are active (the name) before removing it?

**Comment by lukebarone** [comment]
Active in what way?

**Comment by lukebarone** [comment]
Active in what way? You mean when you go to uninstall open VPN?

**Comment by shakisha** [comment]
no, I mean when going to revocate some certificates

**Comment by shakisha** [comment]
no, I mean when going to revocate some certificates

**Comment by Nyr** [comment]
Do you mean a list of the previously generated certificates?

If so, this should already be shown.

If you are asking about currently connected clients, this is not supported.

**Comment by shakisha** [comment]
yes, i mean a list of previously generated certificates :-) 

where is it shown?

**Comment by Nyr** [comment]
Doesn't this show for you?

![captura de pantalla 2016-02-11 a las 18 24 11](https://cloud.githubusercontent.com/assets/739489/12984136/b7857a9e-d0ec-11e5-9dbb-3584e3a8f10e.png)

**Comment by shakisha** [comment]
oh, maybe i have an old version, looking it now

<img width="344" alt="captura de pantalla 2016-02-11 a las 18 26 14" src="https://cloud.githubusercontent.com/assets/7482626/12984198/f45a3360-d0ec-11e5-83a0-a1515758aefe.png">

**Comment by shakisha** [comment]
how i can update without having issues with active clients and without having troubles with easyrsa? (i have got a full machine backup in case of disaster :-)  )

**Comment by Nyr** [comment]
New versions break compatibility because of the easy-rsa upgrade.

Nothing I can do about it, they didn't make it backwards compatible.

**Comment by shakisha** [comment]
ok, so, i need to use new script in the future :+1: 

Thank you

**Comment by Nyr** [comment]
For now, you can view certificates and their status looking at `/etc/openvpn/easy-rsa/2.0/keys/index.txt`.

I know it's not ideal, but better than nothing.
