### ISSUE TITLE
iptables rule masquerades packets from server to client

### ISSUE THREAD

**Issue by dimitrovs** [Nyr/openvpn-install#122]
I noticed that the script adds this rule to the rc.local file:

`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to XXX.XXX.XXX.XXX
`
This translates to:

SNAT       all  --  10.8.0.0/24          anywhere             to:XXX.XXX.XXX.XXX

which masquerades packets coming from the server interface (10.8.0.1) to the client (for example 10.8.0.2) making them have source IP XXX.XXX.XXX.XXX (i.e. the external interface IP of the server). In my setup this makes it impossible to ping the client from the server, while the other way around (client->server) works fine. I resolved it by specifying the client IP as source in the iptables rule, but do you have an idea why this problem may be happening and if there can be a generic solution in the script?

**Comment by Nyr** [comment]
I don't understand what's the problem?

The public IP appears as source when pinging from the server but the client can get back to the server since it has a route to the public IP too.

![captura de pantalla 2016-02-14 a las 20 32 10](https://cloud.githubusercontent.com/assets/739489/13035909/6ca4f5ac-d35a-11e5-8c75-0c0f6f72782f.png)

**Comment by dimitrovs** [comment]
But the route to the public IP is through the external interface, not tun0. Which interface are you monitoring above? If I monitor the tun0 interface I don't see the replies, I assume they are going out eth0 which is as expected. Should we not specify the interface in the iptables rule?

**Comment by Nyr** [comment]
The screenshot is from tun0.

Specifying the interface is not needed and you can't always assume it's tun0.
