### ISSUE TITLE
Using easy-rsa 2.x.x results in empty .ovpn config file

### ISSUE THREAD

**Issue by kingo55** [Nyr/openvpn-install#123]
Love how simply this script creates new users for Open VPN however as I'm on easy-rsa 2.2.2, the one easy-rsa binary doesn't exist.

This results in the following output when creating a new user:
```

Client name: test
openvpn-install.sh: line 84: ./easyrsa: No such file or directory
cp: cannot stat ‘/etc/openvpn/client-common.txt’: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/ca.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/issued/test.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/private/test.key: No such file or directory

Client test added, certs available at ~/test.ovpn
```

Going to take a closer look and report back on how I work it out.

**Comment by kingo55** [comment]
Easiest solution was to re-install everything. In fact it's all possible managed through this script.

1. Run the script on the server where OpenVPN is installed and you should be able to hit "3" for the prompt to remove OpenVPN.
2. Re-run the script and walk through the installation.

Far easier than forcing install of easy-rsa 3.x.x on Ubuntu or writing backwards compatibility with 2.x.x.

**Comment by Nyr** [comment]
Unfortunately easy-rsa 3 broke compatibility with 2.x, not much I could do about it.

Reinstalling is indeed the easier way to upgrade.
