### ISSUE TITLE
Use ECDSA and ECDA

### ISSUE THREAD

**Issue by Angristan** [Nyr/openvpn-install#124]
Hi,

I suggest to add the compatibility with ECDSA and ECDHE as it's faster and more secure.

https://github.com/OpenVPN/openvpn/commit/bd9aa06
https://github.com/OpenVPN/openvpn/blob/master/README.ec

**Comment by Nyr** [comment]
No.

- That's not the default and will not be for a very long time. This script uses the defaults where reasonable/possible.
- That commit is very recent. The script works with way older OpenVPN versions which don't support this option.

**Comment by Angristan** [comment]
Ok, that is your choice.
