### ISSUE TITLE
Config to run server over tcp protocol?

### ISSUE THREAD

**Issue by dylanypyen** [Nyr/openvpn-install#130]
Hi, is there a way to run the server via the TCP protocol and not UDP as I am trying to set this up for use in China, and the Great Firewall uses DPI and blocks on all UDP ports :/ thanks.

**Comment by valery1707** [comment]
This option exists in [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet

**Comment by Nyr** [comment]
Thanks @valery1707.

Aditionally, if you want to use my script, you can change `proto udp` to `proto tcp` in the client and server configuration files.
