### ISSUE TITLE
Revoke certificate without restarting

### ISSUE THREAD

**Issue by shakisha** [Nyr/openvpn-install#132]
Imagine an environment where more than 10 clients are connected;

in this moment, when the script revoke a certificate, restarts openvpn.
Is not possible to avoid this?

**Comment by Nyr** [comment]
Addressed with https://github.com/Nyr/openvpn-install/commit/3a96224d1f6646f86acb1bf9e611ae385b59047e.

Thanks for reporting this.

**Comment by baptx** [comment]
@Nyr it looks like if someone is connected to the VPN and we want to revoke his certificate, we need to restart OpenVPN with `sudo service openvpn-server@server restart` to disconnect the user, is it normal that a restart is needed to revoke a connected user? By the way, why can't we just restart OpenVPN with `sudo service openvpn restart`?

**Comment by Nyr** [comment]
> is it normal that a restart is needed to revoke a connected user?

If I remember correctly, yeah. The CRL is checked on client connection.

> why can't we just restart OpenVPN with sudo service openvpn restart?

Modern distributions use systemd. The right command is:
`systemctl restart openvpn-server@server.service`

**Comment by baptx** [comment]
@Nyr thanks, can't we restart OpenVPN with the command `systemctl restart openvpn` instead of `systemctl restart openvpn-server@server.service`?

**Comment by Nyr** [comment]
`systemctl` should be used.

**Comment by baptx** [comment]
@Nyr I meant, when using `systemctl restart`, can't we add `openvpn` instead of `openvpn-server@server.service`? What is the difference?

**Comment by Nyr** [comment]
`systemctl restart openvpn-server@server`

That's the shortest you could do.

**Comment by baptx** [comment]
@Nyr Ok, do you know why there are 2 systemd services, `openvpn` and `openvpn-server@server.service`? With `systemctl status openvpn`, I can see that there is a file `/lib/systemd/system/openvpn.service` in addition to `/lib/systemd/system/openvpn-server@.service`.

**Comment by Nyr** [comment]
Long story short, the `openvpn` service is maintained for compatibility and deprecated while `openvpn-server` is the new modern unit which should be used.

If you need further information please ask elsewhere, this is a tracker just for issues with the script.
