### ISSUE TITLE
Connection Failed when connecting to .ovpn? (Newbie)

### ISSUE THREAD

**Issue by paesuthi** [Nyr/openvpn-install#134]
Wed Mar 09 18:17:56 2016 OpenVPN 2.3.10 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKCS11] [IPv6] built on Feb  1 2016
Wed Mar 09 18:17:56 2016 Windows version 6.2 (Windows 8 or greater)
Wed Mar 09 18:17:56 2016 library versions: OpenSSL 1.0.1r  28 Jan 2016, LZO 2.09
Wed Mar 09 18:17:56 2016 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Wed Mar 09 18:17:56 2016 Need hold release from management interface, waiting...
Wed Mar 09 18:17:56 2016 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Wed Mar 09 18:17:56 2016 MANAGEMENT: CMD 'state on'
Wed Mar 09 18:17:56 2016 MANAGEMENT: CMD 'log all on'
Wed Mar 09 18:17:56 2016 MANAGEMENT: CMD 'hold off'
Wed Mar 09 18:17:56 2016 MANAGEMENT: CMD 'hold release'
Wed Mar 09 18:17:57 2016 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Mar 09 18:17:57 2016 UDPv4 link local: [undef]
Wed Mar 09 18:17:57 2016 UDPv4 link remote: [AF_INET]94.23.214.156:1194
Wed Mar 09 18:17:57 2016 MANAGEMENT: >STATE:1457511477,WAIT,,,
Wed Mar 09 18:18:57 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Mar 09 18:18:57 2016 TLS Error: TLS handshake failed
Wed Mar 09 18:18:57 2016 SIGUSR1[soft,tls-error] received, process restarting
Wed Mar 09 18:18:57 2016 MANAGEMENT: >STATE:1457511537,RECONNECTING,tls-error,,
Wed Mar 09 18:18:57 2016 Restart pause, 2 second(s)
Wed Mar 09 18:18:59 2016 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Mar 09 18:18:59 2016 UDPv4 link local: [undef]
Wed Mar 09 18:18:59 2016 UDPv4 link remote: [AF_INET]94.23.214.156:1194
Wed Mar 09 18:18:59 2016 MANAGEMENT: >STATE:1457511539,WAIT,,,
Wed Mar 09 18:19:59 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Mar 09 18:19:59 2016 TLS Error: TLS handshake failed
Wed Mar 09 18:19:59 2016 SIGUSR1[soft,tls-error] received, process restarting
Wed Mar 09 18:19:59 2016 MANAGEMENT: >STATE:1457511599,RECONNECTING,tls-error,,
Wed Mar 09 18:19:59 2016 Restart pause, 2 second(s)
Wed Mar 09 18:20:01 2016 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Mar 09 18:20:01 2016 UDPv4 link local: [undef]
Wed Mar 09 18:20:01 2016 UDPv4 link remote: [AF_INET]94.23.214.156:1194
Wed Mar 09 18:20:01 2016 MANAGEMENT: >STATE:1457511601,WAIT,,,
Wed Mar 09 18:21:01 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Mar 09 18:21:01 2016 TLS Error: TLS handshake failed
Wed Mar 09 18:21:01 2016 SIGUSR1[soft,tls-error] received, process restarting
Wed Mar 09 18:21:01 2016 MANAGEMENT: >STATE:1457511661,RECONNECTING,tls-error,,
Wed Mar 09 18:21:01 2016 Restart pause, 2 second(s)
Wed Mar 09 18:21:03 2016 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Mar 09 18:21:03 2016 UDPv4 link local: [undef]
Wed Mar 09 18:21:03 2016 UDPv4 link remote: [AF_INET]94.23.214.156:1194
Wed Mar 09 18:21:03 2016 MANAGEMENT: >STATE:1457511663,WAIT,,,
Wed Mar 09 18:22:03 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Mar 09 18:22:03 2016 TLS Error: TLS handshake failed

and keeps repeating. I'm not sure what is wrong?

**Comment by Nyr** [comment]
Looks like your server is behind a NAT and you are trying to connect on port 1194 which isn't going to work.

You'll need to use one of your forwarded ports instead of 1194.

**Comment by paesuthi** [comment]
Hi, thanks for your reply!

However, I'm not so knowledgable in Linux scripting. 

Can you give me some instructions on how to set up a forwarding port on a NAT?

Thanks!

**Comment by Nyr** [comment]
I am not 100 % sure but it's likely that your host has assigned you some forwarded or "open" ports which you can use to connect via IPv4.

This has nothing to do with Linux scripting, contact your host if you don't know what those ports are, I can't tell you.

**Comment by paesuthi** [comment]
Ah, I have contacted my host and asked for the forwarding port. I am now able to connect! Thanks heaps for the assistance!  :+1:
