### ISSUE TITLE
What about version for Docker ?

### ISSUE THREAD

**Issue by mamashin** [Nyr/openvpn-install#136]
I think it wi'll be great :)

**Comment by Nyr** [comment]
Not planned, sorry.

**Comment by anthonydahanne** [comment]
Why wouldn't you use this docker image ?

https://github.com/kylemanna/docker-openvpn

This project, openvpn-install, is great for people who can't / don't want to install and use docker

**Comment by TheDoctorsLife** [comment]
This could also make supporting every distro easier.

**Comment by Nyr** [comment]
Let's be honest: [nearly everyone](http://w3techs.com/technologies/details/os-linux/all/all) is using either a Debian-based distro or CentOS for their Linux servers. Anything else is either niche or only common for the enterprise, so I'm happy with the current support. I highly prefer to have only a few supported distros and do it right, than add support for a ton of them and not being able to maintain it.

And if someone wants to set this up on a container, LXC is there anyway.

> This could also make supporting every distro easier.

Maybe if I forget about this project and stop maintaining it, which I'm not going to do. Else, I would need to maintain two separate projects, which I'm not going to do either.

**Comment by anthonydahanne** [comment]
right, this project focused on vps and even lowend vps, that probably can't run docker (I've bought 2 lowend vps form 2 different providers, they both shipped with a Linux 2.6.x kernel -> forget about Docker & co)

To have experimented both projects, 

- https://github.com/kylemanna/docker-openvpn is perfect for Docker, the keys setup is even done using containers, a volume is being used to persist the certs, etc. - I'm using it on a host that I did not want to "pollute" with specific software installation
- this project is perfect for a debian (even 7) / centos (like you said 90% of market share) on a cheap host where you can't (kernel < 3.10) / don't want (if you just want to host a vpn server )to use docker

Both work perfectly, maybe openvpn-install from @Nyr is easier to setup than docker-openvpn thanks to the wizard

**Comment by gulaholic** [comment]
Oh that is why I can't install OpenVpn with my Docker.

Thanks for pointing this.

**Comment by vahidshirvani** [comment]
I have the script running in docker. Please see https://github.com/vahidshirvani/openvpn-install
