### ISSUE TITLE
Is there admin web ui?

### ISSUE THREAD

**Issue by droidkevlar** [Nyr/openvpn-install#137]
First off, thanks for making this. I setup OpenVPN before for my job and when I used it, there was a web gui that I (or any other admin) could login to see current users, time on, etc etc. Is that possible with this install?

Thanks again.

**Comment by williclarkam** [comment]
I think what you mean, is OpenVPN access server, this one I don't think doesn't include any GUI.

**Comment by Nyr** [comment]
Indeed, [OpenVPN-AS](https://openvpn.net/index.php/access-server/overview.html) is what you want.

But that's the commercial offer from OpenVPN, nothing to do with this script.

If you are comfortable with using the command line, logging for what you want is available and could be enabled, take a look at the OpenVPN manual for that.
