### ISSUE TITLE
Not working on Scaleway servers

### ISSUE THREAD

**Issue by Angristan** [Nyr/openvpn-install#138]
Installation is successful but the traffic is not routed trough the server.

More info here : https://community.scaleway.com/t/i-dont-have-a-working-vpn/1790

**Comment by Nyr** [comment]
The thread doesn't actually have any information at all, more like disinformation.

You can also see that it's working for others, so you could probably consider that this issue could be in your end and not a problem with the script or Scaleway.

Still, I have just created one Scaleway instance to check for you, and it works. I wanted to check on the ARM servers too, but they are likely out of capacity and wouldn't let me get one so I just tested with the Avotons.

**Comment by Nyr** [comment]
It could be that you just didn't set up the NAT correctly.

You need to specify the internal IP address on the first installation step (which is there by default) and then specify the public one when asked later.

**Comment by Angristan** [comment]
> You need to specify the internal IP address on the first installation step (which is there by default) and then specify the public one when asked later.

Later ? It only asks one time for the IP adress.

So I have to keep it this way ? 

```
First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: 10.2.0.215
```

**Comment by Nyr** [comment]
Try to actually READ what the script is asking you for:

> First I need to know the **IPv4 address of the network interface you want OpenVPN
listening to**.

Do a `ifconfig` and check what's the freaking **IP address assigned to the network interface** (eth0).

If you specify the right IP you are asked for, the script will later detect the NAT and ask you for the public IP and will work perfectly.

I now see you haven't even bothered to read the script at all and look at how it works. I would consider this reasonable except for the fact you are actually maintaining a fork of this script which you apparently don't even understand.

So please, refrain from opening any issue in the future.

**Comment by Angristan** [comment]
I am not familiar with NAT, sorry.

So when I see :

> First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.

Why would I put a private IP ?? 

Now I understand, it explains a lot ^^

_The noob apologizes_

**Comment by Nyr** [comment]
> Why would I put a private IP ??

Because it is the actual **IP address assigned to the interface**, which is what the script is asking about.

**Comment by Angristan** [comment]
Yep that's right, no public IP on ifconfig ^^

**Comment by Angristan** [comment]
(I'd just like to point out that I wasn't the only one confused with Scaleway) https://github.com/Nyr/openvpn-install/issues/112

**Comment by Nyr** [comment]
The right IP address is detected by default and user needs to manually break the configuration for it to fail.

Not my problem if people doesn't read what they are asked about.

**Comment by psellers89** [comment]
I set the both correct IPs but it is still not routing internet traffic. I used a x64 machine with ubuntu 16.04 from scaleway. Any updates about scaleway relative problems ?

**Comment by BrainBlasted** [comment]
> The right IP address is detected by default and user needs to manually break the configuration for it to fail.

I have run the script more than once, changing absolutely nothing, using an Ubuntu 17.04 droplet. Now, the IP detected by the script matches the inet section in eth0. Is that the correct configuration?

**Comment by BrainBlasted** [comment]
Running the iptables commands  in https://github.com/Nyr/openvpn-install/issues/92 results in an empty output.

**Comment by Nyr** [comment]
@BrainBlasted you are using an EOL distribution and as such, is not supported. But yes, the instructions on this thread still stand.
