### ISSUE TITLE
which missing on CentOS 7

### ISSUE THREAD

**Issue by Angristan** [Nyr/openvpn-install#139]
`./openvpn-install.sh: line 311: which: command not found`

You should add "which" to the list of the packages to install on CentOS.

**Comment by Angristan** [comment]
https://github.com/Angristan/OpenVPN-install/commit/f49f187de2d2b227f8f785c51e18e6c29b581825

**Comment by Angristan** [comment]
Well, after installing it, I get this : 
`which: no sestatus in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)`

**Comment by Nyr** [comment]
Not sure where did you test, but `which` is available by default in CentOS 7.

The `sestatus` output is also fine. I don't get why are you complaining about it, try to read the script and understand why it's happening.

Please, double check before you report yet another "issue", because you make me lose time testing and double checking. Considering you maintain a fork, I would expect you to be already familiar with the script and not report silly things.

**Comment by Angristan** [comment]
*Sorry* '-'

The OpenVZ template from PulseHeberg does not have which...
I tested with Vultr and it works.

*Sorry*

**Comment by Nyr** [comment]
So the next time, say that a OVZ template from a random provider doesn't have it available, which is different to what you reported initially.

I actually installed CentOS 7 from the ISO just to double check this.

**Comment by Angristan** [comment]
Actually, it wasn't a "random provider". OpenVZ is used a lot, and there is 2 official templates for CentOS 7 : https://openvz.org/Download/template/precreated

`centos-7-x86_64.tar.gz` includes `which` but the minimal version **DOES NOT**.

So, the problem is probably present on every OpenVZ provider, and not just a "random" one.

**Comment by Nyr** [comment]
That's actually useful, thank you.

Check https://github.com/Nyr/openvpn-install/commit/7fb12dc5cbd08904a88f8eead1c75f43590f7457, should be fixed (and is a better approach, too).

**Comment by Angristan** [comment]
Works perfectly on CentOS 7 minimal. Thx !

**Comment by Nyr** [comment]
Just to clarify: Cent OS 7 minimal includes `which`. It was removed from that OVZ template.

**Comment by Angristan** [comment]
Where do you see which ? Which path (if I may say) ?

**Comment by Nyr** [comment]
Check by yourself... `type which`.

Usually, it should be `/usr/bin/which`.

**Comment by Angristan** [comment]
`-bash: which: command not found`

**Comment by Nyr** [comment]
So it's either not on your `$PATH` or not in your system at all.

**Comment by Angristan** [comment]
That's what I'm telling you.

Nothing in PulseHeberg's minimal template : 
```
[root@server ~]# find / -name "which*"
/usr/lib64/python2.7/whichdb.py
/usr/lib64/python2.7/whichdb.pyc
/usr/lib64/python2.7/whichdb.pyo
```
Nothing in the official minimal template from OpenVZ website : 
```
/usr/lib64/python2.7/whichdb.py
/usr/lib64/python2.7/whichdb.pyc
/usr/lib64/python2.7/whichdb.pyo
```
Only present in the full template :
```
/etc/profile.d/which2.sh
/etc/profile.d/which2.csh
/usr/bin/which
/usr/lib64/python2.7/whichdb.py
/usr/lib64/python2.7/whichdb.pyc
/usr/lib64/python2.7/whichdb.pyo
/usr/share/doc/which-2.20
/usr/share/info/which.info.gz
/usr/share/man/man1/which.1.gz
```

**Comment by Nyr** [comment]
Try using the official CentOS 7 minimal ISO and not some shitty OVZ template...

By minimal I always meant the official image, not some OVZ template called "minimal".

**Comment by Angristan** [comment]
That's not the point, many users who will use this script will use it on a cheap VPS. And what is best for cheap VPS ? OpenVZ ¯\_(ツ)_/¯
I don't say that OVZ templates are good, but it's a fact : OpenVZ is widely used.

But, yes, the "real" CentOS includes `which`. Strange, but anyway, the problem is solved :)

**Comment by Nyr** [comment]
I am glad that this got reported and fixed. 

My hope is always for compatibility everywhere as long as it's reasonable and although this was "not my fail", it needed to be addressed.

Also, OVZ is perfectly fine for just a personal VPN :)
