### ISSUE TITLE
When revoking Certificates, they are not appearing in alphabetical order.

### ISSUE THREAD

**Issue by shakisha** [Nyr/openvpn-install#141]
I have something like 100 certificates, and when revoking, i would like to know if it is possible to list in alpahabetical order, because, in case of a lot of certificates, is hard to find someone which you don't exactly know the name

**Comment by Nyr** [comment]
Cool to know you are using this script with quite a bit of users!

They are currently sorted by order of creation. If sorting alphabetically would suit your needs better, you can modify the script to do that do that. Just add the `sort` command to the pipes used to list the current users.

Check for the two appearances of this line on the script:
`tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep "^V" | cut -d '=' -f 2`

And add the `sort` command so it looks like this:
`tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep "^V" | cut -d '=' -f 2 | sort`

That should do it :)
