### ISSUE TITLE
When connected to OpenVPN, it says DNS cannot be found when browsing webpages.

### ISSUE THREAD

**Issue by paesuthi** [Nyr/openvpn-install#142]
When connected to OpenVPN, it says DNS cannot be found when browsing webpages.

I don't know why it happens..

Does anyone have an idea? 

Thanks

**Comment by williclarkam** [comment]
Where does it say "DNS cannot be found"?
Try `ping 8.8.8.8`
and
`ping google.com`

if you didn't get reply, pinging the second one that there is some DNS issue, cd to `/etc/openvpn/server.conf` and make sure the DNS(es) are `8.8.8.8` and `8.8.4.4` respectively 

```
push "dhcp-option DNS 8.8.8.8" 
push "dhcp-option DNS 8.8.4.4" 
```

**Comment by paesuthi** [comment]
When i open a web page such as google chrome etc. It can't get the DNS, then says DNS cannot be found, then afterwards, Err_no_Internet.

When i connect to the VPN, i pinged 8.8.8.8. No response.

I'm not sure how to do the last part you said.

> if you didn't get reply, pinging the second one that there is some DNS issue, cd to /etc/openvpn/server.conf and make sure the DNS(es) are 8.8.8.8 and 8.8.4.4 respectively

push "dhcp-option DNS 8.8.8.8" 
push "dhcp-option DNS 8.8.4.4"

**Comment by paesuthi** [comment]
I'm not sure if i did it right but i tried this:

> [root@server ~]# /etc/openvpn/server.conf
/etc/openvpn/server.conf: line 1: port: command not found
/etc/openvpn/server.conf: line 2: proto: command not found
/etc/openvpn/server.conf: line 3: dev: command not found
/etc/openvpn/server.conf: line 4: sndbuf: command not found
/etc/openvpn/server.conf: line 5: rcvbuf: command not found
/etc/openvpn/server.conf: line 6: ca: command not found
/etc/openvpn/server.conf: line 7: cert: command not found
/etc/openvpn/server.conf: line 8: key: command not found
/etc/openvpn/server.conf: line 9: dh: command not found
/etc/openvpn/server.conf: line 10: topology: command not found
/etc/openvpn/server.conf: line 11: server: command not found
/etc/openvpn/server.conf: line 12: ifconfig-pool-persist: command not found
/etc/openvpn/server.conf: line 13: push: command not found
/etc/openvpn/server.conf: line 14: push: command not found
/etc/openvpn/server.conf: line 15: keepalive: command not found
/etc/openvpn/server.conf: line 16: comp-lzo: command not found
/etc/openvpn/server.conf: line 17: persist-key: command not found
/etc/openvpn/server.conf: line 18: persist-tun: command not found
status: Unknown job: openvpn-status.log
/etc/openvpn/server.conf: line 20: verb: command not found
/etc/openvpn/server.conf: line 21: crl-verify: command not found

**Comment by williclarkam** [comment]
so I am pretty sure you chose the first option when the installation asked you which DNS Resolver you want (current DNS resolver and your server doesn't have resolver or doesn't allow other devices) do the following.
`cd /etc/openvpn/`
`nano server.conf`
this is the server.conf, now look for something like this -> push` "dhcp-option DNS X.X.X.X"`
and replace it with the following 
```
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4" 
```
PS: all these steps should be done, using root access.

**Comment by paesuthi** [comment]
Hello, thanks for the help.

I put the server.conf as what you said, and when connected to SSH tunnel on my VPS to ping 8.8.8.8 / google.com, it works fine.

But when i connect to the VPN through OpenVPN on my desktop, (windows), i open command prompt and ping 8.8.8.8. 
Connection timed out.

When i use a web browser, it says the DNS cannot be found, no internet.

Do you know what is the cause?

Thank you

**Comment by williclarkam** [comment]
hmm.... it's possible that your firewall is blocking OpenVPN port! which distro are you using? check iptables rules or firewalld rules to see if "`OpenVPN-PORT`" is allowed.
PS: don't forget to run OpenVPN GUI client in windows as administrator/You may wanna test it with `OpenVPN for android app` for Android (if you have of course an android device)
PS2: double check if IPv4 forwarding is enabled too. On Ubuntu/Debian it is located in `/etc/sysctl.conf`
edit it using your favorite editor (e.g. `nano`) and check if this line is uncommented AND is given the value =1
`net.ipv4.ip_forward=1
`

**Comment by Nyr** [comment]
This looks like either a firewall issue or some other kind of conflict.

- Is your server behind a NAT by any chance? LowEndSpirit, NanoVZ, ScaleWay...
- Check from a different client machine, does it work there?
- Try the script again on a clean server

It's likely one of those 3.

Closing since this isn't an issue with the script itself, but feel free to continue troubleshooting anyway :)

**Comment by paesuthi** [comment]
@Nyr 

Server IS behind NAT. Using i-83's hosting
Checked from a different client machine (Imported OpenVPN profile from computer into my iPhone and connected) - Able to connect, but still the same problem persists. Once connected, it cannot open any web-pages.
Tried the script on a clean server, problem persists.

@williclarkam 

# Kernel sysctl configuration file for Red Hat Linux
#
# For binary values, 0 is disabled, 1 is enabled.  See sysctl(8) and
# sysctl.conf(5) for more details.

# Controls IP packet forwarding
net.ipv4.ip_forward = 1

# Controls source route verification
# net.ipv4.conf.default.rp_filter = 1

# Do not accept source routing
# net.ipv4.conf.default.accept_source_route = 0

# Controls the System Request debugging functionality of the kernel
# kernel.sysrq = 0

# Controls whether core dumps will append the PID to the core filename.
# Useful for debugging multi-threaded applications.


I tried OpenVPN on iPhone ,it didnt work, but it WAS able to connect to the VPN. (Can't open any web-pages)

-----

My OpenVPN worked for a while, but now it doesn't and I don't know why!

**Comment by Nyr** [comment]
Check [this](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353) issue.

If you are 100 % sure that you did specify the NAT correctly, contact your provider and link them to this. It could be that they stopped forwarding UDP or something like that.

**Comment by williclarkam** [comment]
I searched "i-83 hosting" and google have redirected me to this webpage "[](https://serveraza.com/provider/i-83/)". If you are using from this provider then you are on OpenVZ. I have never used OpenVZ because I have heard they have some issues with VPN(s) and this kind of scripts, but check out this issue [](https://github.com/Nyr/openvpn-install/issues/92) , it may help you figuring this problem out.

**Comment by paesuthi** [comment]
@Nyr I have used the correct (internal IP) for the configuration, and the script has worked once before but stopped working

So I've contacted my provider asking about UDP.

@williclarkam 
I have yet to do that, but when I have I will tell you.

@williclarkam @Nyr 
The weird thing about it is.. Whenever I'm logged into something like a instant messenger app (not web-based), or connecting SSH to my server WHILE connected to the VPN, these things work
But i can't open web-pages!
Pinged google.com on CMD:

> Ping request could not find host google.com. Please check the name and try again.

Pinged 8.8.8.8 on CMD:

> Pinging 8.8.8.8 with 32 bytes of data:
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.

Pinged 8.8.8.8 on server:

> 64 bytes from 8.8.8.8: icmp_seq=129 ttl=55 time=4.70 ms
> 64 bytes from 8.8.8.8: icmp_seq=130 ttl=55 time=4.30 ms
> 64 bytes from 8.8.8.8: icmp_seq=131 ttl=55 time=4.25 ms
> 64 bytes from 8.8.8.8: icmp_seq=132 ttl=55 time=4.45 ms
> 64 bytes from 8.8.8.8: icmp_seq=133 ttl=55 time=4.40 ms
> 64 bytes from 8.8.8.8: icmp_seq=134 ttl=55 time=4.26 ms
> 64 bytes from 8.8.8.8: icmp_seq=135 ttl=55 time=4.29 ms

It seems like the configuration is correct then? But I don't know whats wrong! arghh

**Comment by Nyr** [comment]
So this has nothing to do with your ISP forgetting to NAT UDP, please tell them you were mistaken and close the ticket.

Are you sure you don't have a firewall on the server preventing the OpenVPN NAT? Can you please try the script on a clean install? Because it's very likely at this point that there is something wrong in your server configuration.

**Comment by paesuthi** [comment]
@Nyr  well since the script stopped working I've reinstalled Centos 6 (64-bit minimal) on my server machine and run your script and it didnt work

maybe the firewall rule is still there after a clean reinstall? 

can you tell me how to check it? as I'm a newbie at this... thanks!

**Comment by Nyr** [comment]
> I've reinstalled Centos 6 (64-bit minimal) on my server machine and run your script and it didnt work

On 100 % clean install?

If you want me to take a look at this: reinstall the CentOS template, do nothing more and email me login details for this VPS. I'll check it out.

**Comment by paesuthi** [comment]
@Nyr  I'm not sure if it was a clean install or not but I reinstalled the OS from CPanel

**Comment by Nyr** [comment]
From the control panel, you mean? It's considered clean then.

**Comment by paesuthi** [comment]
yeah from the control panel, ill send you details in a sec

**Comment by paesuthi** [comment]
having some trouble issuing a reinstall haha

**Comment by paesuthi** [comment]
I've emailed you. @Nyr

**Comment by Nyr** [comment]
Tested with the user provided VPS: it works as it should.

Whatever the problem was, has nothing to do with this script.
