### ISSUE TITLE
[Feature Request] Key Strength

### ISSUE THREAD

**Issue by ProbieK** [Nyr/openvpn-install#143]
I'd like to see a question added to the beginning of the script that will ask what size you want all of the keys to be; from the CA down to the client key.

I'd like to be able to run this script with 4096 bit keys without having to go behind it and revoke/reissue everything.

**Comment by valery1707** [comment]
This option exists in [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet

**Comment by ProbieK** [comment]
Thanks!
