### ISSUE TITLE
Working with a DNS Proxy

### ISSUE THREAD

**Issue by haniag** [Nyr/openvpn-install#144]
I know this might not be related to you, but any help would be appreciated.

Your solution installs great on a KVM VPS on RamNode, and I can connect and browse internet. However, after I install a DNS Proxy (https://github.com/ab77/netflix-proxy), when I try to connect in OSX, I get "Waiting for server response".

To give you more background, in order for the DNS Proxy to install, I disable IPv6 in  /etc/network/interfaces (comment last 3 up lines) and /etc/sysctl.conf (add net.ipv6.conf.eth0.disable_ipv6 = 1). Afterwards, I believe the build enables IPv6 through tunnel broker among other things.

I really hope this will be something trivial to enable both solutions working together.

**Comment by Nyr** [comment]
Likely a malfunction with your DNS server and nothing to do with OpenVPN at all.

Just do `dig google.com @8.8.8.8` from your OS X Terminal. Do you get a valid response? If so, your DNS proxy isn't working.
