### ISSUE TITLE
Question - possible to use both udp and tcp?

### ISSUE THREAD

**Issue by gaining** [Nyr/openvpn-install#147]
Does this script have functionality to set-up a dedicated server on both udp and tcp?

**Comment by Nyr** [comment]
This isn't supported by the script, but isn't difficult to do.

You need to run two different daemons with different `server.conf` files, one with `proto udp` and other with `proto tcp`.

**Comment by valery1707** [comment]
Or you can use project [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet - it can configure `tcp` and `udp` server

**Comment by gaining** [comment]
Thanks! @valery1707  and @Nyr  Seems like zabullets's mod is what I was looking for.
