### ISSUE TITLE
Access to server but not navigate

### ISSUE THREAD

**Issue by matteos1** [Nyr/openvpn-install#151]
I start the script. After create certificate I access to the server but I cannot navigate.
On raspberry with raspbian jessie. I also open  port 1194 on the router

**Comment by Nyr** [comment]
Is your RPi behind a NAT? If so, check https://github.com/Nyr/openvpn-install/issues/138

Are you using a firewall? If so, you need to add exceptions.

Please, don't open new issues for common problems which had been addressed plenty of times already and aren't bugs with with the script anyway.
