### ISSUE TITLE
It's not support Ubuntu 16.04

### ISSUE THREAD

**Issue by al03** [Nyr/openvpn-install#153]

**Comment by Nyr** [comment]
This script has indeed been tested in Ubuntu 16.04 (among many other distros).

If you have an specific issue, you'll need to write a more detailed report.

PS: you are going to have trouble using OpenVPN directly from China. I'd suggest Shadowsocks instead if that's what you want.

**Comment by al03** [comment]
I am using the VPS of DigitalOcean in US.
````
openvpn-install.sh: 11: openvpn-install.sh: [[: not found
openvpn-install.sh: 17: openvpn-install.sh: [[: not found
openvpn-install.sh: 28: openvpn-install.sh: [[: not found
openvpn-install.sh: 31: openvpn-install.sh: [[: not found
openvpn-install.sh: 31: openvpn-install.sh: -e: not found
Looks like you aren't running this installer on a Debian, Ubuntu or CentOS system
````
system
````
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
````

**Comment by al03** [comment]
Problem resolved
`http://unix.stackexchange.com/questions/155838/shell-script-throws-a-not-found-error-when-run-from-a-sh-file-but-if-entered-ma`

**Comment by Nyr** [comment]
Since this is not the first time that someone gets confused about this, I've pushed https://github.com/Nyr/openvpn-install/commit/52f419e0d5b1ef7a137cbbb25c6262e169a9171c.

This will let the user know if he's doing it wrong.
