### ISSUE TITLE
Hardened Setup?

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [Nyr/openvpn-install#154]
A hardened setup would be much appreciated.

Example:
- proto tcp
- port 443 (+- UDP/53?)
- DH generates 4096 .pem instead of default 2048
- Generate TLS-Auth key
- Use AES256 bit cipher for data encryption
- Use SHA512/SHA256 for integrity
- Use TLS-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-128-GCM-SHA256 (the only Forward Secure, TLS 1.2, Non-CBC mode ciphers in the current OpenVPN stable build)
- Drop privileges, i.e. add:

user openvpn_server
group nogroup
- Set log to
verb 0
- An option to install DNSCrypt and route clients DNS requests through that.

**Comment by Nyr** [comment]
I have already lost count of the amount of issues opened about this.
