### ISSUE TITLE
Option to disable logging

### ISSUE THREAD

**Issue by acs-ferreira** [Nyr/openvpn-install#155]
Just a suggestion, add an option to completely disable logging, like:
```
log /dev/null
status /dev/null
verb 0
```
With something like:
`Do you wish to DISABLE all OpenVPN logs? (y/n)`

**n** = maintain actual script options wich are good
**y** = disables the option like the example on this post _(maybe other options too, if pertinent)_

**Comment by Nyr** [comment]
Not planned.

This could actually be misleading to some users, since the ISP is going to keep logs anyway.
