### ISSUE TITLE
VERIFY ERROR: depth=1, error=certificate is not yet valid: CN=ChangeMe

### ISSUE THREAD

**Issue by ambross** [Nyr/openvpn-install#158]
After setting up openvpn if I go to initiate openvpn I get this error message. still trying to connect my vpn but it is not working. 
> Sat Jun  4 05:03:01 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sat Jun  4 05:03:01 2016 Control Channel Authentication: tls-auth using INLINE static key file
Sat Jun  4 05:03:01 2016 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Jun  4 05:03:01 2016 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sat Jun  4 05:03:01 2016 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat Jun  4 05:03:01 2016 UDPv4 link local: [undef]
Sat Jun  4 05:03:01 2016 UDPv4 link remote: [AF_INET]
Sat Jun  4 05:03:01 2016 TLS: Initial packet from [AF_INET], sid=c3664dac ea1d79b2
Sat Jun  4 05:03:03 2016 VERIFY ERROR: depth=1, error=certificate is not yet valid: CN=ChangeMe
Sat Jun  4 05:03:03 2016 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Sat Jun  4 05:03:03 2016 TLS Error: TLS object -> incoming plaintext read error
Sat Jun  4 05:03:03 2016 TLS Error: TLS handshake failed
Sat Jun  4 05:03:03 2016 SIGUSR1[soft,tls-error] received, process restarting
Sat Jun  4 05:03:03 2016 Restart pause, 2 second(s)

**Comment by Nyr** [comment]
Fix the time/date in your server or client, this isn't a issue with the script.

**Comment by ambross** [comment]
Hi thanks for quick response! Can you please give me any simple example how can I fix this?

**Comment by Nyr** [comment]
Just set the correct time and date in both your client and server systems, it has nothing to do with OpenVPN or this script.

**Comment by guenp** [comment]
I also got this error - interestingly enough the problem was that the server was on PST while my laptop (client) was on GMT+1. Changing the laptop to PST solved the issue.

**Comment by qdbgw3ihnjw** [comment]
openvpn server:
1. remove openvpn;
2. Fix the time/date with `date -s`;
3. bash openvpn-install.sh again

**Comment by samshine89** [comment]
> Fix the time/date in your server or client, this isn't a issue with the script.

that right.thank man!

**Comment by rajat1saxena** [comment]
Thank you. In my case, my client's (Windows 10) time was not correct.

**Comment by chary-art** [comment]
thanks it starts to work

**Comment by estaji** [comment]
that works for me too, thanks
