### ISSUE TITLE
"Failover IP" ??

### ISSUE THREAD

**Issue by hyloc** [Nyr/openvpn-install#159]
Hi

I have used your script on many servers now so thank you for that.

I now have a vps from OVH with came with a French IP.  I added an Irish Failover IP (so i can see Ireland win the Euro 2016;)

I have tried the script entering the Irish IP but server not connecting.

Both IPs are pinging good.

Would you have any ideas?

Many, many thanks

Owen

**Comment by Nyr** [comment]
I have no idea about how OVH sets up the failover IP for VPS.

Does it show properly when doing an `ifconfig`?

My only guess is that this failover IP is NATed and you just get a private IP routed to your VPS. If this is the case, check https://github.com/Nyr/openvpn-install/issues/138.
