### ISSUE TITLE
Affiliate link

### ISSUE THREAD

**Issue by gokaygurcan** [Nyr/openvpn-install#163]
Hello,
I liked the idea! And big thanks for the script. 

I have one problem though: please put a warning before or after Host1Plus url which indicates that the url is a referral url and you'll earn some kind of points or credits. 

Thanks a lot.

**Comment by k0nsl** [comment]
This is a non-issue for me.

**Comment by Nyr** [comment]
The affiliate link is not hidden or deceiving anyone nor is influencing the project or my views in any way.

For those wondering: it has made less than $10 within the last month.

My only "income" during that period, by the way. I'm not exactly drowning in money lately ;)
