### ISSUE TITLE
Change to cipher AES-256-CBC?

### ISSUE THREAD

**Issue by Yzord** [Nyr/openvpn-install#166]
Can i easily change the cipher AES-128-CBC into cipher AES-256-CBC in the script to get a harder security?

**Comment by Nyr** [comment]
Just replace `AES-128-CBC` with `AES-256-CBC` in the script.

This change will not improve real world security but will noticeably decrease performance.

The advantage of maintaining an open source project vs being a commercial VPN provider is that I don't need to use shitty and false marketing with my users ;)

**Comment by DonZheng** [comment]
Hi @Nyr ,
I replaced 'AES-256-CBC' with 'AES-128-CBC', but saw system log like this:
'Sat Jan 26 17:03:30 2019 client/106.220.176.95:12720 PUSH: Received control message: 'PUSH_REQUEST'
Sat Jan 26 17:03:30 2019 client/106.220.176.95:12720 SENT CONTROL [client]: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.160 255.255.252.0,peer-id 158,cipher AES-256-GCM' (status=1)
Sat Jan 26 17:03:30 2019 client/106.220.176.95:12720 Data Channel: using negotiated cipher 'AES-256-GCM'
Sat Jan 26 17:03:30 2019 client/106.220.176.95:12720 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Jan 26 17:03:30 2019 client/106.220.176.95:12720 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
'

Does that mean that no matter what we cipher we put in server.conf or client.ovpn, it won't make any difference. OpenVPN server will dictate what cipher will be used?

**Comment by DonZheng** [comment]
Hi @Nyr 

By saying AES-256-GCM is a 'superior' choice, I assume you mean it is superior in terms of security. How about its impact on network throughput?

Kindly advise, please

**Comment by Nyr** [comment]
> How about its impact on network throughput?

It depends, but generalizing a lot, GCM is actually a little bit faster in most real world situations.

Please do not quote me on this because there are many factors to consider, I'm oversimplifying it.

**Comment by grtfou** [comment]
Hi,
I'm not a security expert. I just have a question.
I see the code use **AES-256-CBC** by default.
Do we need to change **AES-256-GCM** for avoid padding attack?

https://security.stackexchange.com/questions/201144/is-aes-128-cbc-already-broken

Thanks, :)

**Comment by Nyr** [comment]
@grtfou no.

AES-256-CBC is configured for compatibility purposes. But as already mentioned in this thread, in modern OpenVPN versions AES-256-GCM will be negotiated during connection.
