### ISSUE TITLE
Concurrent users

### ISSUE THREAD

**Issue by NicolasLoew** [Nyr/openvpn-install#167]
Hello there, I am using your OpenVPN script over at github but I am having a problem: Every time multiple users connect to my VPN at the same time using the same cert it does disconnect all users but one. Do I need to create a cert for each user?

**Comment by Nyr** [comment]
Yes, this has been discussed many times already.

The proper way is to generate a certificate per each user/device and only one connection is allowed per certificate.

Multiple connections per certificate can be allowed adding the `duplicate-cn` directive to `/etc/openvpn/server.conf`, if you really want.
