### ISSUE TITLE
Key location output

### ISSUE THREAD

**Issue by surfingtime** [Nyr/openvpn-install#170]
Hi there,

since I don't find any resulting key in the "~/" path I'm wondering if this line (94)
```echo "Client $CLIENT added, certs available at ~/$CLIENT.ovpn"``` 
has to be changed with the actual path where the key is created. What do you think?

Thanks for the great job!

**Comment by Nyr** [comment]
Actually, `~/$CLIENT.ovpn` is where the configuration files with in-line certificates are created, not sure what the problem is.
