### ISSUE TITLE
Vanilla CentOS

### ISSUE THREAD

**Issue by lukasz-pawlowski** [Nyr/openvpn-install#171]
Vanilla CentOS 7 x64 requires epel-release

yum -y install epel-release && yum -y install openvpn easy-rsa iptables-services

**Comment by Nyr** [comment]
`epel-release` is already being installed when needed, I don't understand what the issue is?

**Comment by lukasz-pawlowski** [comment]
Yes, sorry, I appoached problem from wrong direction.
Here is part of install log file being problematic. Yes, I am running as root
[problem.txt](https://github.com/Nyr/openvpn-install/files/367843/problem.txt)
It seems like EasyRSA is being downloaded but something is wrong with file paths
uname -a : 
Linux [removed] 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Nyr** [comment]
I can't understand how this the log you attached is happening.

If `mv ~/EasyRSA-3.0.1/ /etc/openvpn/` happened (no error there according to your log), the following line (`mv /etc/openvpn/EasyRSA-3.0.1/ /etc/openvpn/easy-rsa/`) should surely work too.

Something weird is going on with your setup, I doubt this is a clean CentOS install. Not sure why you mentioned installing `easy-rsa` from the repos in the first message, by the way.

**Comment by lukasz-pawlowski** [comment]
OK, I found out problem. 
Yes, CentOS install was vanilla and I did mention easy-rsa because it helped to move ahead.
OpenVPN was not being installed completely and script was breaking halfway through because of low RAM memory.
Thanks for help.
Best regards,
Lukasz
