### ISSUE TITLE
easyrsa path

### ISSUE THREAD

**Issue by xelerated** [Nyr/openvpn-install#175]
Hey, in the following..
cd /etc/openvpn/easy-rsa/
			./easyrsa build-client-full $CLIENT nopass

There is no easyrsa in /etc/openvpn/easy-rsa/
do you link the executable or am I missing something?

**Comment by acs-ferreira** [comment]
Read the https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh#L214 part on the script.

**Comment by xelerated** [comment]
Duh, thanks, i figured I was missing something obvious, thanks!
