### ISSUE TITLE
Slow VPN Connection

### ISSUE THREAD

**Issue by ChaosPower** [Nyr/openvpn-install#177]
Hi All,

I am struggling to find solutions for the slow VPN connection. Tried setting buffers fixed (UDP) and at 0 (TCP).

I used the installer, the client is connected but is very slow.

**Comment by acs-ferreira** [comment]
Nothing to see with the script, it could be plenty of things. Server throughput, server configuration, server load, ethernet load, client configuration, etc...

See http://winaero.com/blog/speed-up-openvpn-and-get-faster-speed-over-its-channel/ and https://community.openvpn.net/openvpn/wiki/Gigabit_Networks_Linux

**Comment by Nyr** [comment]
The connection between your ISP and the server could be congested too, this is by far the most common cause of slowness (and hardly fixable).

Whatever it is, this isn't an issue with the script.
