### ISSUE TITLE
This script ain't worth shit yo

### ISSUE THREAD

**Issue by manolon67** [Nyr/openvpn-install#181]
I've been trying to use this script to set up a VPN connection to my provider (Telecentro Lora del Río) and it's not working thus far--all I get when I run it is some creepy 500-pages manifesto which tries to persuade me into having sex with my own mother.

This is what I think of your script:

![2016-08-09_09-31-39](https://cloud.githubusercontent.com/assets/20922225/17508228/6d05c61e-5e03-11e6-9069-893b69b10277.jpg)

**Comment by xedis** [comment]
Put down the crack pipe

**Comment by Leproide** [comment]
Fuck you , drugged Hispanic troll.

http://www.vandal.net/foro/mensaje/812377/conoceis-la-historia-de-manolon67/
http://www.3djuegos.com/foros/tema/28903494/0/la-historia-de-manolon67/

**Comment by Nyr** [comment]
Buena foto, le faltó una polla en leche, pero buena foto.

For anyone wondering about the Manolón history: he is the guy in the photo and he's very creepy. He met some "girls" online and traveled around Spain to "meet them" multiple times, sent money to at least one of them and some more things which I don't remember.

He's now bankrupt and had legal problems. The person trolling this issue has gone as far as traveling with others to be present in court when Manolón lost his home.
