### ISSUE TITLE
read UDPv4: Connection reset by peer (WSAECONNRESET) (code=10054)

### ISSUE THREAD

**Issue by BloodMan29** [Nyr/openvpn-install#182]
Hi,
Sorry to bother you, but i installed your script on a nat vps and i think it worked i put the external ip thingy at the end of the script and got my cert off but when i want to use it with the client i'm getting out this error : read UDPv4: Connection reset by peer (WSAECONNRESET) (code=10054)
I've searched for a while on google but nothing worked out of my searches (port forwarding ..) so here am i to ask you if you had this issue in the past.

Thanking in advance !
Best regards,

**Comment by Nyr** [comment]
This could be caused by a firewall or a restricted network. Also if the NAT is not set up correctly.

Try connecting from another client/network, does the issue persist? If so, check your NAT.

**Comment by BloodMan29** [comment]
How can i set up the nat ? what should i check ? 
Because I opened the port up on my router and that doesn't change anything :(
I added rules to my firewall but as well as my router, that doesn't work :(

Best regards,
