### ISSUE TITLE
Setup Fail2Ban in port 1194

### ISSUE THREAD

**Issue by rhbkweb** [Nyr/openvpn-install#186]
Hi @Nyr 

Great script! Just one question:

I want to have Fail2Ban protecting the VPN 1194 port and after researching i have found 2 websites with 2 different configurations. I leave the links for both sites bellow.

http://eon01.com/blog/brute-force-secure-openvpn-with-fail2ban/
https://blogs.fsfe.org/stefan.a/2014/03/30/monitor-block-openvpn-logins-fail2ban/

Can you please help me and tell me the proper way to setup Fail2Ban in order to work with your script to protect VPN 1194 port?

Thanks and keep up the good work!

**Comment by auyongcheemeng** [comment]
This is unrelated and not an issue with the script.

 OpenVPN community wiki has notes on server hardening. The related section is "Use of --tls-auth"

**Comment by rhbkweb** [comment]
@auyongcheemeng 

Yes i know there is not any issue with the script and i'm sorry to have posted here. But i did not find other place where i can clarify this Fail2Ban question.

**Comment by Nyr** [comment]
@auyongcheemeng is right, what do you want protection from?

Fail2ban is useless, specially considering that `tls-auth` is set up by default.

Just forget about it.
