### ISSUE TITLE
Suggestion - TCP option?

### ISSUE THREAD

**Issue by apemanzilla** [Nyr/openvpn-install#192]
Very handy script, the only suggestion I have would be adding an option to generate configs that use TCP instead of UDP. (e.g. for disguising traffic as HTTPS via 443/tcp)

It's pretty easy to do manually, just modifying the server and client configs, but it would be nice to have it supported by the script.

**Comment by stefancrain** [comment]
This will get closed, @NYR doesn't want to support TCP : [see all of these issues](https://github.com/Nyr/openvpn-install/issues?utf8=%E2%9C%93&q=is%3Aissue%20TCP%20
)

**Comment by Nyr** [comment]
Yeah, TCP support is currently not planned. If you really need it, it's pretty easy to change :)

PS: port 53 UDP often works where 443 TCP is unrestricted, that's what I personally use.

**Comment by valery1707** [comment]
You can use project [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet - it can configure `tcp` and `udp` server
