### ISSUE TITLE
Please add type of Proto (tcp/udp)

### ISSUE THREAD

**Issue by layers-gedanken** [Nyr/openvpn-install#197]

**Comment by Nyr** [comment]
This is like the... 10th time that an issue about this exact matter has been opened, I don't think that I'm exaggerating at all.

**Comment by esraerdem2** [comment]
Are enough change server and client conf UDP to TCP? Need I change iptables, etc?

**Comment by Nyr** [comment]
Just change the server and client configuration. And restart the server.

**Comment by esraerdem2** [comment]
Thank you!
