### ISSUE TITLE
mv: cannot stat ‘/etc/openvpn/EasyRSA-3.0.1/’: No such file or directory

### ISSUE THREAD

**Issue by x011** [Nyr/openvpn-install#198]
2016-09-18 16:08:34 (207 KB/s) - ‘/root/EasyRSA-3.0.1.tgz’ saved [40960/40960]

mv: cannot stat ‘/etc/openvpn/EasyRSA-3.0.1/’: No such file or directory
chown: cannot access ‘/etc/openvpn/easy-rsa/’: No such file or directory
openvpn-install.sh: line 221: cd: /etc/openvpn/easy-rsa/: No such file or directory
openvpn-install.sh: line 223: ./easyrsa: No such file or directory
openvpn-install.sh: line 224: ./easyrsa: No such file or directory
openvpn-install.sh: line 225: ./easyrsa: No such file or directory
openvpn-install.sh: line 226: ./easyrsa: No such file or directory
openvpn-install.sh: line 227: ./easyrsa: No such file or directory
openvpn-install.sh: line 228: ./easyrsa: No such file or directory
cp: cannot stat ‘pki/ca.crt’: No such file or directory
cp: cannot stat ‘pki/private/ca.key’: No such file or directory
cp: cannot stat ‘pki/dh.pem’: No such file or directory
cp: cannot stat ‘pki/issued/server.crt’: No such file or directory
cp: cannot stat ‘pki/private/server.key’: No such file or directory
cp: cannot stat ‘/etc/openvpn/easy-rsa/pki/crl.pem’: No such file or directory
chown: cannot access ‘/etc/openvpn/crl.pem’: No such file or directory
openvpn-install.sh: line 234: openvpn: command not found
5061
Failed to restart openvpn@server.service: Unit openvpn@server.service failed to load: No such file or directory.
Failed to execute operation: No such file or directory

Looks like your server is behind a NAT!

If your server is NATed (e.g. LowEndSpirit), I need to know the external IP
If that's not the case, just ignore this and leave the next field blank

**Comment by Nyr** [comment]
Very likely the OpenVPN installation (yum/apt-get) was killed because your VPS was out of memory.
