### ISSUE TITLE
openvpn on ubuntu 16.04 wont start or connect client after installation and client01 file generation.

### ISSUE THREAD

**Issue by ali2077** [Nyr/openvpn-install#199]
service openvpn status
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset:
   Active: active **(exited)** since Tue 2016-09-20 10:19:25 EDT; 6h ago
 Main PID: 1905 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openvpn.service

Sep 20 10:19:25 localhost systemd[1]: Starting OpenVPN service...
Sep 20 10:19:25 localhost systemd[1]: Started OpenVPN service.
Sep 20 10:38:42 localhost systemd[1]: Started OpenVPN service.

**Comment by Conver** [comment]
I'm on `Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-generic x86_64)` and it's working fine for me.

**Comment by csolg** [comment]
Can you attach logs from /var/log/syslog for openvpn?

**Comment by ali2077** [comment]
never mind. Instead I've installed ubuntu 14.04 and it works well with it.  
it's weird though I couldnt run it on 16.04.

**Comment by Nyr** [comment]
Just to clarify: not sure what your problem was, but the script is designed to be compatible with Ubuntu 16.04.
