### ISSUE TITLE
OpenVPN exits setup with error.

### ISSUE THREAD

**Issue by NicolasLoew** [Nyr/openvpn-install#200]
` openvpn@vpnname.service - OpenVPN connection to vpnname
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset
   Active: failed (Result: exit-code) since Fri 2016-09-23 11:34:22 EEST; 2min 2
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 7272 ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openv

Sep 23 11:34:22 15432.s.t4vps.eu systemd[1]: Starting OpenVPN connection to vpnn
Sep 23 11:34:22 15432.s.t4vps.eu ovpn-vpnname[7272]: Options error: In [CMD-LINE
Sep 23 11:34:22 15432.s.t4vps.eu ovpn-vpnname[7272]: Use --help for more informa
Sep 23 11:34:22 15432.s.t4vps.eu systemd[1]: openvpn@vpnname.service: Control pr
Sep 23 11:34:22 15432.s.t4vps.eu systemd[1]: Failed to start OpenVPN connection
Sep 23 11:34:22 15432.s.t4vps.eu systemd[1]: openvpn@vpnname.service: Unit enter
Sep 23 11:34:22 15432.s.t4vps.eu systemd[1]: openvpn@vpnname.service: Failed wit
lines 1-15/15 (END)
`

**Comment by Nyr** [comment]
Sorry for the late reply, is this still an issue for you?

If so, please attach the full log, the provided one is incomplete.

Also: which distro and version are you using? Try on a clean template.

**Comment by NicolasLoew** [comment]
Was running on Ubuntu 14.x/15.x didn't work. Using CentOS6 now without any problems :)
