### ISSUE TITLE
Setting validity of issued certificate.

### ISSUE THREAD

**Issue by vik-y** [Nyr/openvpn-install#202]
Right now the issued certificate has a validity of 3650 days by default. I have done some changes in my fork to give an option to change that while adding a client certificate. Is it a useful feature? Should I raise a pull request?

**Comment by Nyr** [comment]
Is it an useful feature for your specific use case? Good for you, that's cool.

Is it a feature which I see as important/common enough to be implemented in the main branch? No.

By the way, in case you didn't know: you can modify this values by using global variables for easy-rsa, without modifying the script itself.
