### ISSUE TITLE
Check if port is defined correctly. If not use modify command.

### ISSUE THREAD

**Issue by AaronJWhite** [Nyr/openvpn-install#204]
Ran into a small issue using this script.
I was getting the error below in my messages log when trying to use port 636 (ldap port, also default used by Streisand VPN).
```shell
openvpn: TCP/UDP: Socket bind failed on local address [undef]: Permission denied
openvpn: Exiting due to fatal error
```
It turns out since that port was already defined in my selinux the commands in your script for setting the port were being ignored. Once I used the modify command below I was able to restart OpenVPN and everything worked correctly.
```shell
semanage port -m -t openvpn_port_t -p udp 636
```
I'm thinking it might be helpful to have the script also do a check after issuing the add sellinux command (semanage port -a -t openvpn_port_t -p udp $PORT). If OpenVPN is still not set to correct port then confirm with the user that it's ok to do a modify command (semanage port -a -t openvpn_port_t -p udp $PORT).

Thanks

**Comment by Nyr** [comment]
The script expects an unused port from the user, in which case this is not needed. I think that's a reasonable expectation.

It is also suggested to use a clean OS, or at least one where there are no leftovers from conflicting software, to avoid situations like this.

Finally, it's not my work to cleanup said conflicting leftovers from other software. For one, my script does actually remove its own SELinux rules on removal.
