### ISSUE TITLE
VPN service not working on scaleway VC1 instance

### ISSUE THREAD

**Issue by Dratas** [Nyr/openvpn-install#207]
Hello,i have installed this openvpn thing,but its not working,i mean is connected but no online services is available,that means no web surfing is possible,just long loading,os debian jessie with all updates.I tried with all dns services,like google,huricane electrics and no lucky.Maybe i do some thing wrong.In that step where asking internal ip,i writted corrected internal vps ip like 10.2.98.xx,where asking public i writted public public like 212.47.xxx.xx,so where is the problem,fork also not working.

**Comment by Nyr** [comment]
What you are describing, usually happens when the NAT is incorrectly set up or if there is a firewall interfering.

For correctly setting up the NAT: in the first step you should leave the default shown by the script, it is correctly detected for Scaleway. Then, you just need to specify the public IP when asked.

**Comment by Dratas** [comment]
in first step i leaved ip as is,noting changed,in second step,when asking me to type public ip/domain i entered server public ip,wich is real and correct,so maybe os is not right,firewall is not installed on server.

**Comment by MasterGroosha** [comment]
Same problem for me. Provided internal IP on first step and external on second step.
Connection timeout :(

**Comment by Nyr** [comment]
You just need to leave the internal IP as is when first asked (which is automatically detected) and then specify the server's public IP.

If it isn't working, you're doing something wrong. I can't make it easier.

**Comment by MasterGroosha** [comment]
@Nyr That's **exactly** what I did. I don't know how pressing "Enter" can be wrong, but it is what it is.

**Comment by Nyr** [comment]
I have just checked 5 minutes ago with a VC1S container running Ubuntu Xenial.

They are using the same CGNAT as always. The script works, as always.

**Comment by MasterGroosha** [comment]
Paris or Amsterdam? I'm using Amsterdam VC1S

**Comment by Nyr** [comment]
Network setup is the same for both locations.

This is how your responses should look like: https://pastebin.com/raw/CCaj2qsA

**Comment by MasterGroosha** [comment]
Well, I have completely the same response. Do I need to reboot VDS afterwards?
https://pastebin.com/mw7p0NPd

**Comment by Nyr** [comment]
From the paste, I can see that you aren't using a clean image for this. Try again using a clean VM.

If after that you still have issues, you have the following options:
- Something is causing a conflict within the sever
- You have connectivity issues or you are on a censored/restricted network
- Something is wrong client-side

Check if the selected UDP port is reachable from the outside. You can use [this](https://check-host.net/check-udp) tool for it. If the port is reachable, your problem isn't server-side.

**Comment by MasterGroosha** [comment]
> you can use this tool

Result: Open or filtered (all lines)
Yes, I'm not using a clean image, however, only nginx installed with extra python modules.

FYI: `nmap localhost -p 1194` returns `1194/tcp closed openvpn`

**Comment by Nyr** [comment]
You were checking 1194 TCP with Nmap, not UDP. But probing from localhost doesn't tell us if the port is connectable from the outside or not, that's why I suggested the website.

I insist that you need to try my script on a clean image. I can't support everyone's custom setup and I have zero intel on your environment, so I can't troubleshoot with so many unknown variables.

**Comment by MasterGroosha** [comment]
Okay, I'll run clean VM later and try your script then. Will post results as soon as possible.

**Comment by MasterGroosha** [comment]
I've created a fresh VC1S instance and your script works fine for me. I'm sorry for taking your time, will try to solve the problem with the existing VM.
If you have any ideas, please let me know. Anyway, now I can confirm that your script works fine with fresh Scaleway VC1S (Amsterdam) instance.
