### ISSUE TITLE
server side ping client side does not working

### ISSUE THREAD

**Issue by yanboyang713** [Nyr/openvpn-install#208]
Hi all,
I have meet a weird issue. I have used this script set up server side and add a cert for a new user.  I have run sudo openvpn --config *.ovpn in my arch linux. Once connected the my arch linux ping the server have feedback, However the server ping my arch linux have not feedback all package will lost.
but arch linux can open web page no problems. I also try using my android phone connect server using openvpn that no any problems. server can ping my phone. Does you guys have any idea about this problem. Thanks. Have a good day

**Comment by Nyr** [comment]
Must be a client side issue. Make sure that there isn't anything filtering incoming ICMP in your client.

**Comment by yanboyang713** [comment]
I have stop my firewall that is still the same issue. OMG I don't know what
is my problems

*kind regards,*
*Boyang YAN (William)*
*-------------------------------------------------------------------------*
*Alternate Email: by932@uowmail.edu.au <by932@uowmail.edu.au>*
*Phone Number:0415950713*
*Callsign: VK2FIAC*

*University of Wollongong*
