### ISSUE TITLE
TCP Conncetion?

### ISSUE THREAD

**Issue by Ximoria** [Nyr/openvpn-install#210]
is there any way to make this use tcp instead of udp? thanks just a question i didn't know where to put it.

**Comment by Nyr** [comment]
Already discussed lots of times, see previous issues on this matter.

**Comment by valery1707** [comment]
You can use project [openvpn-install-advanced](https://github.com/zabullet/openvpn-install-advanced) by @zabullet - it can configure `tcp` and `udp` server

**Comment by Nyr** [comment]
Reminder that the fork is not up to date and doesn't include some very important security features available in my work.

For example: Blowfish is now considered insecure and should no longer be used. It also has DNS leaks in Windows 10.

Please, avoid those dangerous suggestions in the future.
