### ISSUE TITLE
Can't install under Fedora 58.3

### ISSUE THREAD

**Issue by noa-the-doggo** [Nyr/openvpn-install#213]
Hola soy nieves. Neus. Como he parido tantos bebes este ano pasado y este y yo sola no puedo criarlos a todos. Los tienen a los bebes las monjas de patraix las agustinas y como yo quiero que tengan todos una buena educacion y se crien todos los hermanos juntos he hablado con los abogados y pedido hablen con las monjas por que en massanassa detras de mi casa hay un terreno donde se puede edificar un colegio y yo quiero pagarlo todo para que el colegio sea fundado yo he pensado en un colegio de ensenanza donde mis hijos y otros esten internos y haya tambien sitio para externos que vayan al colegio solo a las clases y convivan todos juntos dice que esto lo hacen las teresianas. Y hay bastante terreno para edificar una clinica donde haya pediatria y psiquiatria que yo tambien pagaria la fundacion de la finca y esto dice lo hacen las catalinas y entonces en massanassa estarian las monjas de siempre las hermanas de la caridad estarian las teresianas y las catalinas. David dice que quiere crear tambien un supermercado en la planta baja de la clinica. Para suministrar al colegio ademas de para todos los vecinos que no tienen cerca comercio. Se fundarian estos edificios en la calle catarroja y san pedro de massanassa. Yo con el dinero que se recauda de todo lo que sale mio en internet contribuyo en todo lo que pueda al mantenimiento de estos fines. Hola Tengo a mis bebes en las monjas de patraix las agustinas en valencia y yo sola no puedo criarlos. Les he dado a las monjas el numero de mi cuenta bancaria en cajamar para la compra de un terreno en massanassa y la construccion de un colegio de monjas teresianas para que esten mis hijos junto a otros hasta los 18 anos. Le he pedido ayuda para la compra del terreno a juan jose castilla y necesito vuestra ayuda por que mi familia miente y quiere impedir este prposito por eso necesito ayudeis y apoyeis a las monjas y juan contra mis familiares que les mienten. Yo pago el terreno y la construccion del colegio y a poder ser su mantenimiento. En el terreno queriamos tambien un supermercado para suministrar al colegio y vecinos que no tienen cerca comercio y construir una clunica que hubiese pediatria que hubiese trauma y psiquiatria. Yo corro con los gastos que esto ocasione. Pero necesito vuestra ayuda contra mis familiares que mienten que ayudeis a las monjas a juan jose castilla y david alejo para conseguir este proposito. Los que estan impidiendo mi proposito son juan jose castilla y david alejo me traicionan por que los convence la psiquiatra celia que quiere impedir mis fines quedarse con mi dinero y que mis hijos pasen ambre convence la psiquiatra celia al resto de mis familiares para que mientan haya difamacion y un fraude si asi es me traiciona juan jose castilla y david alejo a mi neus. Por favor ayudar a las monjas agustinas y teresianas para la fundacion del colegio y la clinica y supermercado en el terreno de massanassa calle san pere y catarroja. David alejo y juanjo castilla le hablan a la psiquiatra celia como si fuese una sexologa y atribuyen su mal de forma fisica. El problema de ellos es de cabeza de psiquiatria no fisico de sexologia. Celia es psiquiatra y ellos no estan bien de la cabeza tienen un problema mental david y juanjo son enfermos mentales. Lo que cabe en esas cabezas y como les funciona no es problema sexual es de psiquiatria no estan bien de la cabeza no necesitan sexologa necesitan psiquiatra los convence celia. La terebel forsan es la que me ha echo la rotura de rotula por telepatia contrayendome el musculo y ordenandome girar el pie hacia aqui o hacia alla. Terebel forsan es masajista deportiva y estudia psicologia. Me ha echo una rotura de rotula en la pierna izquierda y queria hacerme lo mismo en el brazo izquierdo para que confunda el medico y la gente los sintomas y crean que me ha entrado un ataque y es por el emisferio del cerebro que tengo sano se crean que es el que no me funciona. Terebel forsan le dice a los hombres que soy yo la asesina la de la agresion sexual y le dan credibilidad a terebel forsan vienen a mi casa a violarme y es ella la que le dice a lad amigas me manden a sus maridos y que no vuelvan con ellas hasta que me follen. Les cuenta lo que le pasa a mi marido david alejo conmigo y quieren que les haga a los hombres lo mismo que a mi marido yo no quiero no es lo mismo yo solo quiero hacerlo con mi marido. Terebel forsan al igual que julia la psicologa y josefa grau ferrer me envian hombres a mi casa y obligan a tener relaciones sexuales con ellos hasta con mi hermano jose. Diselo a la guardia civil. Por favor sale todo por internet. Y me dan acido urico para que no recuerde lo que me hacen todo en mi casa. En mi habitacion mientras duermo con el efecto del tratamiento psiquiatrico les ha explicado la psiquiatra celia como hacermelo a las mujeres y hombres.

**Comment by Nyr** [comment]
Un drama.
