### ISSUE TITLE
IPV6 Support?

### ISSUE THREAD

**Issue by VBQL** [Nyr/openvpn-install#216]
As title, would there be ipv6 support in the future or this is it? Would love to have it added but totally understandable if not.

**Comment by Nyr** [comment]
Plenty of previous discussion on the matter:

https://github.com/Nyr/openvpn-install/issues?utf8=✓&q=IPv6

I would love to add IPv6 support but is not really practical at this time. If situation improves in the future, I'd really like to.

**Comment by VBQL** [comment]
Ok, yeah sorry for not reading the entire issues list before. My mistake.
