### ISSUE TITLE
can't connect to it fom Windows with openvpn 

### ISSUE THREAD

**Issue by transonly** [Nyr/openvpn-install#217]
Hi,

Unable to connect to it from my W8 with client download from here: http://help.unotelly.com/support/solutions/articles/184301-openvpn-desktop-client-setup-windows

error messgae: OpenVPNClient start ingrid_p8694: process started and then immediately exited: []

from linux it works fine with openvpn --config file.ovpn

**Comment by Mohitsharma44** [comment]
It's most likely a permission issue on the client.

Try running OpenVPN in 'elevated privileged' mode. Add `verb 5` to client config and post the OpenVPN log file here.

**Comment by Nyr** [comment]
Why are you using that weird client? Remove it and use the official OpenVPN client:
https://openvpn.net/index.php/open-source/downloads.html

If this still doesn't solve the issue, provide a client connection log.

Closing the issue since it isn't a problem with the script, feel free to reply anyway.

**Comment by transonly** [comment]
Indeed the problem was with the client used. :-) Rhanks for answering!

**Comment by wupme** [comment]
That "weird" client is the official client from OpenVPN. There is more than just the one you seem to know.

**Comment by Nyr** [comment]
@wupme please do not refloat old issues again.

The mentioned client is used by the commercial VPN product sold by OpenVPN, which is independent from the community OpenVPN project used by my installer. I am well aware of its existence.

Also, the provided link is to an unofficial source and likely an old version of such software. The commercial OpenVPN client shouldn't be used at all by users of my script, but much less that outdated installer hosted by a random third party.
