### ISSUE TITLE
Unable to connect to it from my W8

### ISSUE THREAD

**Issue by transonly** [Nyr/openvpn-install#218]
Hi,

Unable to connect to it from my W8 with client download from here: http://help.unotelly.com/support/solutions/articles/184301-openvpn-desktop-client-setup-windows

error messgae: OpenVPNClient start ingrid_p8694: process started and then immediately exited: []

from linux it works fine with openvpn --config file.ovpn

**Comment by Nyr** [comment]
You already opened an issue: https://github.com/Nyr/openvpn-install/issues/217
