### ISSUE TITLE
Future changes and improvements

### ISSUE THREAD

**Issue by Nyr** [Nyr/openvpn-install#220]
This issue is regularly updated and contains a list of pending improvements to the script. Those haven't been implemented yet to preserve compatibility with older environments but will likely be implemented in the long term:

- Switch from the iptables service to whatever becomes the new default in supported distributions. For Debian 11 that [could be](https://ral-arturo.org/2019/10/14/debian-netfilter.html) firewalld. In Ubuntu, ufw doesn't get loaded by default, so the less intrusive option could be using nftables user-space tools directly, if they don't adopt firewalld.

**Comment by acs-ferreira** [comment]
One question, _(seems obvious, but...)_: once the script is changed, should we regenerate **`.ovpn`** files for each client? Thanks.

**Comment by Nyr** [comment]
You should always keep using the script version downloaded at the time of install. You can upgrade OpenVPN via the distro package manager for (virtually) as long as you want.

Using a newer version of the script with an older install can cause problems when hard forks need to happen (for example, the switch to LZ4).

**Comment by acs-ferreira** [comment]
O, i understand, but as i'm the only user of my OpenVPN install, is there a problem if:

**a)** i update OpenVPN Server via distro package,
**b)** update OpenVPN Clients on my machines and
**c)** update the script and generate newer `.ovpn` files

Thanks.

**Comment by Nyr** [comment]
Yes, there would eventually be a problem because you also need to upgrade configuration server-side for some of the big changes.

The easiest solution for you would be to use the removal option of the script, then download the latest version and reinstall. I know this is not ideal, but new and important changes happen from time to time and the script can't keep using outdated settings forever to preserve compatibility.

**Comment by acs-ferreira** [comment]
Thanks @Nyr 

One more question: i've a lot of issues using **SFTP** when i'm under VPN (timeouts). When i disconnect from VPN no more issues. No issues while browsing or even in speed bandwidth on https://fast.com

Do you believe this is something to do with actual script configuration ?

**Comment by Nyr** [comment]
Connection quality is poor, I guess. Not related to the script.

Please do not derail the topic anymore, this has nothing to do with it.

**Comment by acs-ferreira** [comment]
Ok noted, feel free to delete the last 3 posts to "clean" the topic, no problem!

**Comment by infiSTAR** [comment]
will you keep this repository updated? :)

**Comment by Nyr** [comment]
@infiSTAR absolutely.

The last commit is 3 months old, but that's only because the script is pretty stable and bug-free as is.

I have not abandoned the script and will keep supporting it as always.

**Comment by infiSTAR** [comment]
thank you very much :)! 👍

**Comment by maltokyo** [comment]
Hello, I know this is controversial, but I have been waiting for OpenVPN 2.4 support for a while.
It seems that Angristan version already has it.
If I need to install and use now, and want your improvements listed above, would you recommend to go with his version?

**Comment by Nyr** [comment]
@maltokyo I'm not sure what you mean by "2.4 support", but neither of the scripts has any 2.4 specific features implemented. My script is version agnostic, so technically it is 2.4 compatible right now.

I will officially support OpenVPN 2.4 as soon as the stable version is available (likely within weeks) but this doesn't mean it will install 2.4: that depends on what's available in your repositories. Since my script doesn't impose one specific repository upon the user, you are able to choose between your distro's (likely 2.3.x, but more architectures and better long-term support), the official OpenVPN ones (faster, will get 2.4 soon), unstable repos, backports... whatever you want, my script works with all of them!

I provide the means for you to freely choose what you want, but will never claim official support for unstable versions. My personal suggestion is to only use stable versions of security software, but again, that's your choice :)

**Comment by maltokyo** [comment]
Perfect. Thank you! Didn't know that.

**Comment by Nyr** [comment]
Status on OpenVPN 2.4:
- It is now abundantly clear that AES-256-CBC will be the default cipher for OpenVPN 2.4, so I'm not delaying the change any further. Remember that if both sides are GCM compatible (OpenVPN 2.4 and supported by the SSL library), they will negotiate an upgrade to AES-256-GCM. From OpenVPN 2.4, the cipher will no longer be a hardcoded choice.
- Sadly, it looks like devs will not make the upgrade to LZ4 compression adaptative. Due to this, LZO will need to be used for the foreseable future. I do not like this, but it's out of my hand: forcing the upgrade would break support for architectures and distros which are not getting 2.4 packages anytime soon. I'm sure someone else will happily jump at the chance to advertise his fork as LZ4 compatible.

I think that's it. Of course I'll take a look again when the final version of OpenVPN 2.4 is released, but RC1 is already out so no significant changes are to be expected at this stage.

**Comment by wicknet** [comment]
Since OVPN 2.4 was formally released on 12/27/16, just checking when you hope to have the script modified to install OpenVPN 2.4 by default on a new VPS. I plan to use Ubuntu 16.04 for the OS. 

Many thanks for your fine work... it is head and shoulders above in stability and features than all the OpenVPN "advanced" installs piggybacking on your script.

**Comment by Nyr** [comment]
@wicknet the script is already 100 % compatible with OpenVPN 2.4. Which version it installs will depend on whatever your distro has available in the repos, nothing to do with the script itself.

Want to install OpenVPN 2.4? The official OpenVPN repositories have that available:
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

Why I do not force those upon the user if they are more often updated? Mainly because they don't support as many platforms as the official ones from the distros (among other reasons, but I prefer to just give the choice to the user).

**Comment by wicknet** [comment]
Perfect. Thanks!

**Comment by Nyr** [comment]
Nearly missed this: `explicit-exit-notify` is now available for UDP servers (not needed for TCP).

It just does a control channel "RESTART", so compatible with older clients. Only server needs to be 2.4+.

Not a critical option, but useful anyway. Will be implemented in the future.

**Comment by paul-goggin** [comment]
Is it possible to add an option to create a profile for chromebooks as they do not allow standard ovpn configuration files

**Comment by Nyr** [comment]
@paul-goggin this issue is about new OpenVPN features so please stay on topic and don't make feature requests for the script here.

Anyway, this is not planned. Mainly because using a separate PKCS #12 file would prevent us from using inline certificates and because it's not the default/standard for OpenVPN.

**Comment by ThomasRed20** [comment]
Hey, Random Suggestion,

Would it be possible to create an option during client creation for a password to be set to use the client key?

**Comment by Nyr** [comment]
I have deleted multiple off-topic messages from this topic since it had become a bit cluttered.

Remember, this issue is about new OpenVPN features only. Please, no unrelated questions or feature requests here.

**Comment by Nyr** [comment]
Another thing I noticed: the script is still using the old `rc.local` file to save iptables.

That's fine for now, but since it's getting deprecated, we should consider to create a systemd service in the future.

**Comment by AndKe** [comment]
I would like to see more interaction with current config, delete, add user.
-Another neat feature would be to add simple email notification of connections.
-An option for password secured connection 

- Thank you.

**Comment by Abdullaor** [comment]
I really hate guys like you Nyr... who lick the ass of the big company even if they offer shitty service to theyr users just to take the money. You're the rotten here. Not me.

Adesso blocca pure questa discussione, ritardato di merda. Mettici un cazzo dentro quella bocca aperta che tieni come avatar, sfigato lel

**Comment by wicknet** [comment]
@nyr - I setup a Streisand server (https://github.com/jlund/streisand) recently and although I didn’t use all the censorship defeating software it sets up, it’s design of the OpenVPN component  might be of interest to this project. 

The Streisand OpenVPN server listens simultaneously on multiple non-standard ports like udp 8757 and tcp 636 and 443. What I find particularly helpful is that the client profile automatically cycles through those ports, and depending on which one is available, connects. That seems like a fairly elegant solution to restrictive workplace scenarios - the client prefers UDP for speed and performance, and if those ports are blocked, falls back on tcp 443 to get out of a restrictive network. See beginning of client profile below: 

<connection>
remote 12.34.56.789 8757 udp
</connection>
<connection>
remote 12.34.56.789 636 tcp
connect-timeout 10
</connection>
<connection>
remote 12.34.56.789 443 tcp
connect-timeout 10
</connection>

Just sharing it, in case it's of any interest!

**Comment by wicknet** [comment]
@nyr - Wondering if you might have any interest in modifying your script to setup OpenVPN server to listen on udp 1194 AND tcp 443 ports simultaneously? The generated client profile can then cycle through both connection options, preferring udp for speed and performance, and falling back to tcp 443 in case udp connections are blocked.

Saw something similar implemented in JLund's Streisand project and thought it was an elegant solution to a common VPN problem of choosing speed or defeating censorship.

**Comment by Kcchouette** [comment]
@Nyr can we know when these changes will be available please?

**Comment by Nyr** [comment]
@Kcchouette when software versions implementing those changes can be reasonably expected to be found in every supported system. Improvements are good, but not breaking compatibility is very important too.

It's out of my hand, but if you want a gross estimation: a few years from now.

**Comment by CyberCam1969** [comment]
I have 2 requests... 
1. I need to be able to get my internal machines, how can I do this? what can I add to script to do this?
2. Can you implement a password to connect to the server instead of auto connecting?

**Comment by Noiwex** [comment]
nice work, this script does what openvpn developers don't even bother to try

**Comment by shsu** [comment]
@Nyr is there plans to create a new branch or `openvpn-install-2.4.sh` for breaking changes? All my clients/server support v2.4.2 now.

**Comment by Nyr** [comment]
@shsu No. The only "relevant improvement" which affects this script is LZ4 support, and even then, is not that big of an improvement. The rest of the changes are literally useless at this stage. Sure, they're nice to have, but don't make a difference in the real word.

On a personal note, I have absolutely zero interest in maintaining bleeding edge branches or those which only work for specific setups. They would end up being abandoned, like in most open source projects. My intention is to keep maintaining a stable script which is secure and "works everywhere".

Improvements will of course come, but when they are widely supported, not when they just got released.

**Comment by taccoboss1973** [comment]
Very good script. I just wanna say that it won't work on Ubuntu 16.04 on a OpenVZ  VPS. To make it work, you have to edit ' /lib/systemd/system/openvpn\@.service ' and comment  ' LimitNPROC=10 ' . Restart your VPS and everything will be ok. I hope it helps someone. Good job!

**Comment by derpadoo** [comment]
This is a sweet script...thanks for working on it.  Could you provide a mechanism to perform unattended / non-interactive installs by providing a config file?

**Comment by rezkibimo** [comment]
How do I check if I have the latest version of ovpn and how to update it?

**Comment by pehden** [comment]
is there anyway you can show me how i can edit this or the openvpn.conf to make the samba files be seen from all clients on the vpn
as if they were in a lan

**Comment by pehden** [comment]
is there anyway you can show me how i can edit this or the openvpn.conf to make the samba files be seen from all clients on the vpn
as if they were in a lan

Sorry i didnt see any where else to post this, other then the email i sent you

**Comment by Silencer1069** [comment]
how can I download the .ovpn file? please help me.

**Comment by Noiwex** [comment]
scp

**Comment by Silencer1069** [comment]
aw ok thank you. how about setting for username and password for every clients to connecT?

**Comment by garrettwil** [comment]
This script allows me to access the VPN but i have no access to the internet when connected to the VPN. Don't know if this is a missing feature or a problem with setup.

**Comment by asimzeeshan** [comment]
Support for IPv6?

**Comment by bryceml** [comment]
Including optional support for ipv6 would be nice.  Basically just automatically do the steps here: https://blog.apnic.net/2017/06/09/using-openvpn-ipv6/

**Comment by VirgilChen97** [comment]
May be ipv6 support can be added to this script?

**Comment by davidheryanto** [comment]
Hi! Thanks for the wonderful script that makes setting up VPN server super easy.
What do you think of creating a configurable VPN subnet for the script?
Currently the client subnet is fixed to `10.8.0.0/24`, i.e. from the line `server 10.8.0.0 255.255.255.0`

Of course, we can just change this value from `server.ovpn` then update the iptables rules correspondingly. But do you think it will be better the script can ask for this value instead during setup?

**My use case:**
I want to setup multiple VPN servers on different network. But if these 2 vpn servers have the same client subnet `10.8.0.0/24`, when the client connects to these 2 vpn servers simultaneously, the subnet from one setting will override the other and the VPN route won't work correctly.

**Comment by Nyr** [comment]
I have now locked this issue since some users are unable to understand that this thread is not the right place to comment with unrelated feature requests.

If you someone feels like there is anything interesting to add for the list on the first post, please open a new issue referencing this one.
