### ISSUE TITLE
client-to-client Communications

### ISSUE THREAD

**Issue by KeithIMyers** [Nyr/openvpn-install#223]
Good Morning,
What would be the best method to enable Client to Client communications with this setup script. I am using this as a private VPN to allow me to access items at home when remote. I would like to be able to connect to the OpenVPN server on my tablet and ssh into my home desktop (which is also connected to the OpenVPN server).

If I connect to the VPN on my tablet (10.8.0.5) and try to ssh into my desktop (10.8.0.2) it times out.

**Comment by Nyr** [comment]
Take a look at https://github.com/Nyr/openvpn-install/issues/211.

**Comment by KeithIMyers** [comment]
Thanks, Final question. If I want to ssh into the OpenVPN server and from there, ssh into a machine that is connected to the VPN, what is the best way to do this? 

This is in the event that I am not on a machine that I can run the OpenVPN client on and need to grab something off of one of my machines.

**Comment by Nyr** [comment]
Just SSH into the server and from there SSH into whatever machine you want, the VPN is not even needed in your side.
