### ISSUE TITLE
Running on Raspberry pi

### ISSUE THREAD

**Issue by thejohnha** [Nyr/openvpn-install#224]
Just curious if anyone has tested this on the Raspberry pi? I have an rpi2 running Raspbian (which is debian based). I've forwarded port 1194 to the pi on my home router. My macOS VPN client can connect successfully to the pi, but when I try to load google.com for example, it times out (no network connectivity).

Nyr, thank you for the wonderful script! I've had great success with it when running on a rented VPS, but I thought I'd try to tinker with a home setup too. Thank you again! You're a wizard.

**Comment by Nyr** [comment]
Raspbian is officially unsupported but it will work just fine.

Check [this](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353) issue for how to properly set up the script under a NAT.

**Comment by thejohnha** [comment]
Ah, wonderful thank you so much for the link. Very impressed with how on top of it you are. Much obliged.  :-)
