### ISSUE TITLE
Logless

### ISSUE THREAD

**Issue by mist3ry0s0** [Nyr/openvpn-install#225]
Hi I'm new here..

want to ask if it's logless?

thanks

**Comment by zenithteq** [comment]
I believe you can minimise the logging by changing the following in /etc/openvpn/server.conf

 `verb 3`

to

`verb 0`

This will make the logging silent except for fatal errors.

**Comment by mist3ry0s0** [comment]
I see thanks..

**Comment by Nyr** [comment]
No, it is not "logless".

In case you were wondering: changing that value is not going to make your connection private/anonymous/untraceable. Other than obtaining that false sense of untraceability, I don't get why would anyone want to disable basic logging.

Internet stuff in general is quite the opposite of "logless" and a VPN is not different.
