### ISSUE TITLE
Option to choose either UDP/TCP, change port number

### ISSUE THREAD

**Issue by slrslr** [Nyr/openvpn-install#226]
Hello,

installer offer me to select port. I would like 443 and TCP (not UDP), it would be good if i can also define whether i want UDP or TCP protocol.
Or please how to change it manually after installer finished?

Thank You, your installer is very helpful

**Comment by Nyr** [comment]
You can edit `proto udp` to `proto tcp` in both `/etc/openvpn/server.conf` and the generated `.ovpn` files.
