### ISSUE TITLE
Feature request: tap mode

### ISSUE THREAD

**Issue by trackrx** [Nyr/openvpn-install#229]
Currently, "tun" (routed) network is assumed by the script. This is fine because it's the most widely used configuration. I'm just asking did you consider supporting also "tap" mode?

Thank you for your work.

**Comment by Nyr** [comment]
TUN is the best choice for the kind of setup which this script makes, so I see no reason tu support TAP, which is only useful for other different use cases.

**Comment by Noiwex** [comment]
TAP is useful when you want to have steam in-home streaming work on remote
