### ISSUE TITLE
Add an option to choose either UDP or TCP and change the port number 

### ISSUE THREAD

**Issue by bharatbee** [Nyr/openvpn-install#231]
> _He cerrado los ojos y, pues, ejem EJEM estoy viendo, un poco de todo. Y esto tendría gracia si fuera un documental de estos en los que van tíos muy colgaos viendo de todo. El problema es que es la vida real. Entonces...pues...es difícil. Ehh...puff..a ver osea..pufpuf...no o sea a ver realmente está muy mal, está fatal de hecho._
> _Aoa...en serio chicos espero que mañana pues...puf...no lo sé..purff....purrffffff....es que es que...se..se me viene el mundo encima. Bueno no el mundo encima no pero...pero sí va a ser muy gracioso explicarle a mis padres la que ha sucedido en casa. De hecho estaba, estaba pensando hace un rato pues como explicarles que me...que había descubierto la droga. Y he descubierto que no es buena idea explicarles como había descubierto la droga...porquee lo mismo se preocupan,...y no quiero que se preocupen...entonces no._
> _También he descubierto que os quiero. A vosotros. A los que estáis tras la pantalla. Es como tras la pantalla pero en la pantalla a la vez._
> _Yyyyyy no sé osea ahí ya se pierden los conceptos porque es todo muy psicodélico. Pero lo que quería deciros es que os quiero, así que deberíais de quererme, espero que me queráis. De hecho, estaría muy bien que me quisiérais._
> _Controlo todos los tiempos verbales sorprendentemente o sea purff es que se está derritiendo tío. Se me está derritiendo del dedo, o sea no el dedo pero...claro...si es que no entendéis. Jiessdffchrrr....PRRJRRRR...ehm...a ver o sea vamos a ponernos serios._
> _Bueno eso sí, no sé, ps...pff...a ver o sea hay un pájaro psicodélico, hay un grafitti psicodélico, hay un gato psicodélico, hay un...un amanecer si casi es que está amaneciendo. Pero si es que...sisque..esto eto eto eto es como Trainspotting tío o sea puff...no sé...tiene que haber un momento en el que digas paro, y paro, y espero que paro y ojalá no haya más que eso. O sea, prrr no eso está sonando un poco mal. Bueno ya me habéis entendido. Tsss..no, de hecho no me he entendido ni yo. Pues ojala, me entendierais._
> _Ero bueno la intención es que me estoy rayando bastante entonces, de hecho esto va a ser bastante gracioso mañana, o no lo estoy seguro o sea sí probablemente sí._
> _Bueno, a saber, no, o sea lo que sí que quiero o sea pff fuff. A ver, el concepto de que os quiero es un concepto que lo tengo muy claro, lo tengo muy claro, y os quiero, os quiero a todos, y os quiero de verdad. De hecho os quiero muy bien porque la gente no sabe querer muy bien pero yo os quiero muy bien._
> _Hombre hay gente que sabe querer muy bien pero es la que menos. Por lo general no sabe querer muy bien. Bueno pero yo os quiero entonces la cuestión es se me está derritiendo esa es la cuesti..pr es que claro sé que es difícil de explicar pero se me está derritiendo el dedo y la uña en el movil o sea...mirar, no lo entendéis._
> **-- Marcus Tullius Cicero, "De re publica" (54 BC)**

![900_692640mmkc_pharmacist-birthday-cake](https://cloud.githubusercontent.com/assets/23725013/20604824/56feba68-b260-11e6-9273-5dc3eded6e44.jpg)

**Comment by Nyr** [comment]
¯\_(ツ)_/¯

**Comment by YassinOufkir** [comment]
Here you forgot your \
