### ISSUE TITLE
 PolarSSL: SSL read error : X509 – Certifcate verification failed, e.g. CRL, CA or signature check failed

### ISSUE THREAD

**Issue by ceyhanmolla** [Nyr/openvpn-install#236]
OpenVPN server certificate verification failed : PolarSSL: SSL read error : X509 – Certifcate verification failed, e.g. CRL, CA or signature check failed

Do you have any idea what the problem is?

Fresh VPS and Fresh Install

**Comment by Nyr** [comment]
What's your client? Android or iOS by any chance?

Whatever it is, this isn't an issue with the script. Try using a proper client if you can.

**Comment by Nyr** [comment]
Just to clarify: OpenVPN Connect (the mobile branch) included a buggy PolarSSL previously, which caused this.

For Android you have some alternatives, for iOS the project has been abandoned for years: they clearly don't care about mobile...

**Comment by nihalf** [comment]
Nyr, what are the android alternatives? Any which are known to work well
with the certificates from your script?

**Comment by Nyr** [comment]
Not an Android user myself so I don't talk from experience, but there seem to be at least 2 unofficial clients in the Play Store which are highly rated and look better maintained than the official one.

Going a bit off topic, but for those interested in the "road warrior" features (secure connection) and not in the VPN (networking) aspect, I always suggest Shadowsocks for mobile. It is stateless and easier on the battery.

I know we are talking about OpenVPN here, but when there are better alternatives for the use case, why ignore them :)

**Comment by TheNomad11** [comment]
Yes, the two other Android clients work well! 

Regarding battery life: If you change the keepalive settings on the server from 10 120 to 90 180, the battery consumption is nearly zero.

**Comment by Nyr** [comment]
There are also other factors like needing to renegotiate the connection when switching networks.

Anyway, happy to know it works!

**Comment by kgojiwong** [comment]
use older version to solve this problem.
