### ISSUE TITLE
info about tls-auth

### ISSUE THREAD

**Issue by artemdudkin** [Nyr/openvpn-install#237]
Please please please add info about client config - i mean the fact that everyone should add 

'tls-auth ta.key 1'

in config. I did not know that and '5-minutes-installation' became '3-hours-installation'.

('ca', 'cert' and 'key' mentioned at every howto, but 'tls-auth' is not so common)

**Comment by Nyr** [comment]
`tls-auth` is being set up correctly by the script, with an inline key and direction set with `key-direction` as it should.

I don't understand why you are confused but I can assure you that the script sets it up correctly and you don't need to edit anything manually.

**Comment by artemdudkin** [comment]
oh. i mean client-config. I installed server in 5 mins and this is great, but then I copied client-common.txt to client, and there was no keys mentioned, and I found info about ca, cert and key very soon, while search info about tls-auth took a lot of time. 

Or I can install client by your script too? Not only server?

**Comment by Nyr** [comment]
> I copied client-common.txt to clien

There's your problem.

The client config files are located in `~/$CLIENT.ovpn` and you are told about this when installation finishes. 

Check your `/root` directory for `.ovpn` files in case you still don't understand what I mean.

**Comment by artemdudkin** [comment]
Shame on me. Thanks!
