### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR,  Chrome browser,  Site can't provide a secure connection

### ISSUE THREAD

**Issue by RudyRipDraw** [Nyr/openvpn-install#239]
Thank you very much for your scripts.  I am able to get my RaspPi to work (I think).  I have my Pi on the lan/Xfinity Router and my Windows Machine running off a separate cell phone hotspot.  Using OpenVPN client on the Win machine, I believe I connect to the VPN.  On my Windows machine, I am now able to see the router on the lan (verifying that I can going thru VPN).  I am also able to browse to some web sites.  But it has problems with some popular web sites like facebook and google.  It gives a ERR_SSL_PROTOCOL_ERROR, This site can't provide a secure connection.  But if I drop the VPN ( visibility to lan/router goes away, as expected) and those web sites show up.

Is this a OPENVPN server configuration issue?

Thanks

![image](https://cloud.githubusercontent.com/assets/13458260/21038636/35ea4d38-bd8c-11e6-9143-8deb380a808a.png)

Just some more information.

ip address of win machine connected to lan/router via wifi, no VPN
![image](https://cloud.githubusercontent.com/assets/13458260/21038780/63e53198-bd8d-11e6-80cf-d59ed00377e6.png)

ip address of win machine connected to hotspot (not using lan/router) and no VPN
![image](https://cloud.githubusercontent.com/assets/13458260/21038801/924ffef0-bd8d-11e6-810d-99f525b5df90.png)

ip address of win machine connected to hotspot WITH VPN connected, which now has the lan/router ip
![image](https://cloud.githubusercontent.com/assets/13458260/21038829/ce6829e4-bd8d-11e6-9570-e2bcebd293ed.png)

**Comment by Nyr** [comment]
No idea what is going on, but it has nothing to do with the script itself.

**Comment by RudyRipDraw** [comment]
thank you for script and time on this!  I will hunt around and if I figure it out, will post it.  Might be my hotspot

thanks !!!

**Comment by RudyRipDraw** [comment]
Problem found!  Windows 7 has some sort of bug in it.  Everything works on my Windows 8 machine.

**Comment by RudyRipDraw** [comment]
After additional planing round, it turns out my DNS configuration on the PI was wrong.  Once I switched over to use the google DNS, all my client systems worked.  The funny thing was before I made this change, it worked on some client systems and not others.  For example, windows 8, iphone worked but not ipad and android phone.  Now it seems fine.

thanks and I hope my posting will help others.
