### ISSUE TITLE
--no-check-certificate kind of defeats the purpose :-)

### ISSUE THREAD

**Issue by yeah** [Nyr/openvpn-install#24]
I really like the idea, but why do you use --no-check-certificate? Downloading something from the Internet and executing it straight away is scary, but not checking the SSL certificates while doing so is really dangerous. Should not be necessary, no?

**Comment by yeah** [comment]
Hm. But wouldn't the better solution be to tell people where to get the proper ca cert bundles, for instance in a troubleshooting section or so? E.g. on Debian, it's as easy as `apt-get install ca-certificates` for instance.

**Comment by Nyr** [comment]
Not really, git.io doesn't even have a valid certificate available and anyway, I don't want to force anyone to comply with the CA mafia.

If you worry about the one-liner, don't use it.
