### ISSUE TITLE
Unable to OpenSSL

### ISSUE THREAD

**Issue by NicolasLoew** [Nyr/openvpn-install#240]
I am getting this error:
```
wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh
--2016-12-09 14:48:59--  https://git.io/vpn
Resolving git.io... 54.243.91.166, 54.243.89.142, 54.225.223.184, ...
Connecting to git.io|54.243.91.166|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.
```

**Comment by Nyr** [comment]
I see nothing wrong with the git.io server so it looks like this problem is in your end.

Try grabbing the long URL instead:
`https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh`

**Comment by NicolasLoew** [comment]
Install worked now. I can connect via ovpn gui but I have no internet connection once connected.
Im using a NAT VPS but Ive been assigned a Public IP with 20 ports aswell and the port I specified during ovpn script setup was within that range so not sure why I wouldnt have internet when connected :/

**Comment by Nyr** [comment]
It's very likely that you did set up the NAT incorrectly.

Your internal IP should be automatically detected in the first step of the installation, don't wrongly change that for the public IP which you don't have available in your container. The script will continue and later the NAT will be detected and you'll be asked for the public IP address.

**Comment by NicolasLoew** [comment]
Aight will retry this :) But I'm only asked once for a port right? So Id need to take a forwarded one eh (one of the 20 public ip ports)?

**Comment by Nyr** [comment]
Yeah, the script assumes that the internal and external port number will be the same.

**Comment by NicolasLoew** [comment]
Oh damn you're a lifesaver :) It all works now! Thanks!
