### ISSUE TITLE
Needs more documentation on client generation

### ISSUE THREAD

**Issue by db666** [Nyr/openvpn-install#241]
Hi there, thanks for this project.

I would like to point out that the usability of this script can be improved a bit more for beginners. Once the OpenVPN install is done and client configuration generated, the script outputs a message:

> Client client added, certs available at ~/client.ovpn

Assuming that the name of the new client is "client", the message implies that (at least for me):

1. Some certs would be available at the location `~/client.ovpn`
2. They would be available in the "home" directory

Given that most folks don't log in as `root` but sudo into it, this results in a bit confusion. I spent a good deal of time searching for the files in `/home/myusername` directory when they were actually created at `/home/root`. Maybe printing out the absolute path would be better in this case?

Also, given that the newly created .ovpn files are standalone, wouldn't it be better to replace the message to say that the client config file is now present at `/home/root/client.ovn`?

**Comment by Nyr** [comment]
Both are very valid points, thank you.
