### ISSUE TITLE
Unattended installation and predefined config files

### ISSUE THREAD

**Issue by timdream** [Nyr/openvpn-install#244]
This project looks prefect and I wish I find it sooner. I do however have a use case that can be considered as a feature request. What I want is to be able to rebuild a server on DigitalOcean with the same CA & cert on the fly whenever I needed. I will set up my own DDNS hostname to the new server every time, but for the rest the script currently generates new certs and asks configs interactively.

What I can think of is to modify the script in two parts:

1. Source a defined configure script (`[[ -f ./openvpn-install.conf ]] && source ./openvpn-install.conf`) and don't `read` for configs if the variable is already non-empty.
2. Create a new `CONFIG_DIR` variable, when specified, copy the files (like `ta.key`, `./easy-rsa/pki` etc.) from the original `/etc/openvpn` directory instead of generate a new one.

Optionally, `openvpn-install.conf` can be also automatically generated when a server is newly installed.

Obviously this can be done outside of this project by saving the generated `/etc/openvpn` directory for the new server, but I don't want to recreate part of what this script do (install packages and set up routing/firewall etc).

Would you accept pull request for this feature? If so I am happy to supply one. My interface design can be changed too if there are better idea (for example, 1 & 2 should be combined).

Again, thanks for the great work!

**Comment by Nyr** [comment]
I have actually considered an unattended option in the past. Not structured like this, but a similar idea.

Since you are going to use DigitalOcean, have you considering saving a server image instead? Just a suggestion, maybe it doesn't work for you.

Ultimately, I decided to keep the script simple and this is a niche option, so among other ideas, it was never implemented.

Anyway, I appreciate that this can be useful to others and I encourage you to implement this as a fork.

Let me know if you end up publishing said fork.

**Comment by timdream** [comment]
@Nyr Thanks for the quick reply. The catch is that they charge (though tiny) for a snapshot too, and I don't want to waste money on it.

Will definitely implement this in a fork and tell you about it.

**Comment by timdream** [comment]
@Nyr Please see [this](https://github.com/Nyr/openvpn-install/compare/c6880407dd...timdream:master) for my patch.

I ended up put the directory path on the first argument, and also allow the client config to be written with a hostname instead of the IP address. The main motivation here is, again, allow the client config to be reusable (it's quite troublesome actually to update a client config on for example iOS).

I couldn't get my DDNS setup work reliably yet so this is tested but not battlefield tested. If you change your mind and would like to merge it I will do more testing and create a pull request.

Thank you.

**Comment by Nyr** [comment]
@timdream I will make sure to direct anyone interested in an unattended install to your fork. Although niche, it is good to have that option, also for those who need to rotate servers.

Thank you!
