### ISSUE TITLE
Feature Request - TCP/443

### ISSUE THREAD

**Issue by wicknet** [Nyr/openvpn-install#245]
Hi Nyr - I’ve been using your script for the last 2 years to spin up multiple VPN servers in minutes that just work. I've also read through (and mostly agree with) your stance re. the ill-advisability of using TCP on OpenVPN. However, as the 40+ issues opened on this topic might suggest to you, this is a common use scenario when the only open ports available in a restrictive workplace are http and https and even UDP port 53 is blocked as DNS is resolved internally. As such, I strongly recommend that you consider (at least consider) offering the option of using either TCP/443 or UDP/1194 (with a disclaimer) in your script for server/client configurations. That would, at one stroke, make your script “universally useful” for the vast majority of use cases, especially for rookie users who can’t figure out how to modify the configs with proto tcp themselves, and are currently being directed by shills to use the forked “advanced” installs pushing laughable options (Antivirus!!!) besides being  remarkably unstable and woefully out of date. Just saying... :-)

**Comment by Nyr** [comment]
The fact is, this has been by far the most requested feature and you are right about one thing: over the past years I didn't really reconsider my position.

Protocol choice has been implemented with 0e4bba792bae9d99bf8f3ad5a5e8e62ce9dc01c4. I hope the "(recommended)" note plus UDP being the default choice are clear enough for those who don't understand the implications.

**Comment by wicknet** [comment]
Wow! That was fast... THANK YOU! 

I'm sure your legion of users (current and future) are going to be thrilled. For my part, I'm just relieved that rookies will no longer have to rely on forked scripts shamelessly piggybacking off your hard work, scripts that were neither robust nor well thought out.
