### ISSUE TITLE
Hardcoded protocol in firewall

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [Nyr/openvpn-install#250]
Hello, Nyr!
I see you modified your script to allow both TCP and UDP. This is a great addition but TCP works only when there is no firewall. The firewall rules allow only UDP connections right now.

Best regards,
Eusebiu

**Comment by Nyr** [comment]
Thanks a lot for the report.

**Comment by EusebiuOprinoiu** [comment]
With pleasure! :)
