### ISSUE TITLE
[Solved] Cannot Ping Win7 Clients from Ubuntu 16.04 Server

### ISSUE THREAD

**Issue by glarcina** [Nyr/openvpn-install#257]
I'm writing this for anyone else who might be struggling with a similar setup as this took me a while to finally find some of the answer here in the 'Issues' section.

Windows 7 clients connect to OpenVPN server and work properly - pinging server is successful.  But, pinging Win7 clients from the server was unsuccessful.

From this [issue](https://github.com/Nyr/openvpn-install/issues/190) I used `iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to my_ipaddress` to allow internal networking.

Pinging still didn't work, so I checked the Windows Firewall to make sure pings were allowed.
`Windows Firewall -> Advanced Settings -> Inbound Rules -> Find rules: File and Printer Sharing (Echo Request - ICMPv4-In) -> Right-click each and Enable Rule`.

Pinging worked after using these two settings.

**Comment by bigyan-kc** [comment]
Thank you so much. It really helped me.
