### ISSUE TITLE
My provider still se my traffic

### ISSUE THREAD

**Issue by giggioman00** [Nyr/openvpn-install#258]
Hello
I bought an OVH VPS and installed openvpn-install to use my VPS as VPN.
I have a limited traffic on my LTE connection so I need a VPN to hide my traffic from my provider's eyes.
I setup openVPN using the port 80 TCP.

Yet my provider still see how many traffic I'm consuming.

Any suggestion?

**Comment by Nyr** [comment]
> Any suggestion?

Use Google, this is not an issue with the script.

**Comment by giggioman00** [comment]
I don't find anything on google. please help

**Comment by Nyr** [comment]
I have no interest in helping you to defraud your ISP.
