### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by giggioman00** [Nyr/openvpn-install#259]
https://github.com/Nyr/openvpn-install/issues/258

Is my ISP that is trying to defraud me. 
Do you think is okay to spend 5 € (5,37 USD) for 1 Gb of traffic? With 1 Gb of traffic I barely see one 1080p video on youtube... That's a thief. If you don't believe you can check the page of this theyr offert: https://www.tim.it/offerte/mobile/voce-e-internet/opzione-1gb-4g

I'm willing to pay for a flat LTE profile but they doesn't offer any flat profile. they're maximum traffic offer is 4 Gb for 20 €. That's a thief too.

I really need to use LTE connection... please it would be a dream for me...it's not my fault if they doesn't offer any decent plan for... 
With my home ADSL connectiom I usually spend 120-150 Gb/month. But I cannot use my home ADSL connection anymore, even if it's flat the maximum speed is 1,5 Mbps and go off every night and time start raining. Please help me... It's a nightmare for me to live in this situation... Any provider is giving me a decent service... please understand my situation

**Comment by Nyr** [comment]
In case this needed clarification: I have no sympathy for your ISP, but I don't appreciate your spam in this issue tracker either.

Both of your accounts had been blocked for this reason (spam after you were told to go elsewhere and your insults in Italian).
