### ISSUE TITLE
wont create a certificate if client name has a "space"

### ISSUE THREAD

**Issue by Eltii** [Nyr/openvpn-install#26]
in linux doing something like "cd Hey You" wont work it wil tell u no such file or directory ,same with files
if you want it to work youl have to use "cd Hey\ You" 
same when a client enters a name that has a space in it lets say "Yaseen Eltii"
it will say Finished but you wont find a .cert file you should add a note there :))

**Comment by Nyr** [comment]
It's already there:

    echo "Tell me a name for the client cert"
    echo "Please, use one word only, no special characters"
    read -p "Client name: " -e -i client CLIENT

A proper approach would be to introduce input validation and error checking everywhere, not just with the client name. But that would take many hours of work and testing, so it will not happen for now.
