### ISSUE TITLE
Unrecognized option or missing parameter(s): block-outside-dns

### ISSUE THREAD

**Issue by 990px** [Nyr/openvpn-install#260]
> Tue Feb  7 14:16:06 2017 Unrecognized option or missing parameter(s) in client.ovpn:14: block-outside-dns (2.3.10)
> Tue Feb  7 14:16:06 2017 OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Feb 2 2016
> Tue Feb  7 14:16:06 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08

**Comment by Nyr** [comment]
That's a warning which is to be expected in non-Windows clients. Nothing wrong with it.

For more details see here: https://github.com/Nyr/openvpn-install/commit/acca10ba1a87b86da3f402ef08e07ad42126913e
