### ISSUE TITLE
Connection to OpenVPN server via HTTP proxy failed

### ISSUE THREAD

**Issue by ssswww0004** [Nyr/openvpn-install#261]
Hello, your script is very easy to use, can be directly connected and used, but when I need to connect through HTTP will fail when the client will add http-proxy will not connect, the client shows tcp port read failed on Recv (): operation now in progress (errno = 115). Really do not know how to solve, I hope you can help me, the reason in what place? How to solve? Thank you.

**Comment by Nyr** [comment]
I do not appreciate spam to my personal email and you simultaneously trying every channel you can think of to get my attention. I'm sorry if you are in a hurry, but I don't work for you.

Anyway, this is not the OpenVPN support forum, so wrong place to ask for assistance on anything completely unrelated to my work.
