### ISSUE TITLE
Suggestion: adding support for Alpine?

### ISSUE THREAD

**Issue by k0nsl** [Nyr/openvpn-install#263]
Hi @Nyr !

Do you think you would be able to add support for Alpine Linux? That would be awesome. I know that it would require a rather impressive overhaul in such a case. Maybe it would be more suitable as a separate project.
At any rate, it was just something I had on my mind and I had to write to you about it.

Have a great day!

**Comment by Nyr** [comment]
> Maybe it would be more suitable as a separate project.

Indeed that's the case. Specially since the differences between Alpine and the currently supported distros are huge.

This isn't something that I plan on doing/supporting, but anyone willing to do so is more than welcome to fork.
