### ISSUE TITLE
The client can not connect

### ISSUE THREAD

**Issue by MrMagloire** [Nyr/openvpn-install#266]
Hello,
Thank you for this script.
But After installation everything went well but when I want to connect with a client I get Time Out and this for two days.
Please Help Me Sir

**Comment by lukebarone** [comment]
Attach the connection log. Where is the server located, at home or a data
centre? What operating systems?

**Comment by MrMagloire** [comment]
Thanks for replying so fast, the problem came from the firewall of my router. Thank You So Much

**Comment by Nyr** [comment]
I guess this was reopened by mistake?
