### ISSUE TITLE
problem with the script

### ISSUE THREAD

**Issue by ben42210** [Nyr/openvpn-install#27]
Hello,
I encounter many problems with your script. I did something wrong this morning, and so I wanted to reinstall the script but I am having errors. At the beginning of the script, I get errors like "
openvpn-install.sh: 9: openvpn-install.sh: [[: not found
openvpn-install.sh: 15: openvpn-install.sh: [[: not found
openvpn-install.sh: 21: openvpn-install.sh: [[: not found
openvpn-install.sh: 48: openvpn-install.sh: [[: not found
openvpn-install.sh: 53: openvpn-install.sh: [[: not found "
or "openvpn-install.sh 154: read: Illegal -e"
Can you help me?
Best Regards

**Comment by Nyr** [comment]
Where are you trying to run this? With what shell?

I assume you are not using bash and that's why it's happening.

**Comment by ben42210** [comment]
Hello,
I try to run the script on a private server leased from a hosting provider. The server runs on Debian.
Do you have any idea how I can solve this problem?

**Comment by Quintenps** [comment]
@ben42210 , could you tell me the output of "echo $0"?

**Comment by ben42210** [comment]
I do not know how to answer you, I'm sorry
