### ISSUE TITLE
client-to-client

### ISSUE THREAD

**Issue by nexus166** [Nyr/openvpn-install#275]
Been using this script for >3 years now, and iirc the setup used to ask for this option to be enabled.
Am I dreaming, or was it removed for some reason?

**Comment by Nyr** [comment]
Your memory is good :)

The option was indeed removed but you can easily enable internal networking manually, with or without internet routing, whatever you need. Take a look at [this](https://github.com/Nyr/openvpn-install/issues/211#issuecomment-258063856).

**Comment by nexus166** [comment]
Thanks :) you're great!
