### ISSUE TITLE
Connecting to SMB share

### ISSUE THREAD

**Issue by scouseman** [Nyr/openvpn-install#276]
I have successfully setup OpenVPN with your script and it works great on my Ubuntu server.
I have also set up samba on the same server and configured a shared samba folder.
My problem is how do I get the samba server to allow openvpn access as currently, I am unable to view my shared folder.
Any help would be most appreciated
Thanks ever so much for all your effort on this script.

**Comment by lukebarone** [comment]
Did you add the new interface to your smb.conf file?

**Comment by scouseman** [comment]
I have added 
interfaces  = 10.66.0.0/24 10.8.0.0/24

But I am not sure it is correct.
From the openvpn client log it says:
Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]

**Comment by lukebarone** [comment]
Have you run "testparm" to ensure the syntax is ok? I am believing you need
a comma, but could be wrong.

Next, what iptables rules do you have set?

On Mar 23, 2017 3:45 AM, "scouseman" <notifications@github.com> wrote:

I have added
interfaces = 10.66.0.0/24 10.8.0.0/24

But I am not sure it is correct.
From the openvpn client log it says:
Set TAP-Windows TUN subnet mode network/local/netmask =
10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Nyr/openvpn-install/issues/276#issuecomment-288681276>,
or mute the thread

**Comment by scouseman** [comment]
Thanks for your help  Luke, it is much appreciated.
I have run testparm and it comes back with no errors.
I have also checked my iptables, I have not made alterations to it though, as I assumed if openvpn  was working correctly iptables would be ok.

ns3043093:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain fail2ban-ssh (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere

**Comment by lukebarone** [comment]
Is the Ubuntu server on your local network? Can you test it without the VPN
connection? Can you paste a (sanitized) version of your smb.conf file, and
the share stanza that you're trying to access?

**Comment by scouseman** [comment]
No its a remote server on the internet.
Is there any way to test my samba share without the vpn, I do believe it should be set up correctly.
Here is a link to my smb.conf file.
http://pastebin.com/a60gRqM5

I am trying to access:

\\10.8.0.1\\share

I thought this was going to be straight forward to setup never realised it was going to cause these many problems. As the OpenVPN connection works perfectly.
Thanks again for your help.

**Comment by Nyr** [comment]
Take a look at #190, I don't remember much about how SMB works but you likely need to change that.

Closing the issue as this is not a problem with the script.

**Comment by scouseman** [comment]
@Nyr, I have had a look at the script, I see there is an option in the script whether to enable local network or not, would I be better uninstalling my current setup and re-running the script?

**Comment by Nyr** [comment]
The versions including a local networking option are very old and outdated, so I'd suggest to avoid them.

You can make the change manually editing the `/etc/rc.local` file in the server (reboot after that).

**Comment by scouseman** [comment]
That's perfect guys, thank you both very much all sorted now.
