### ISSUE TITLE
Question and suggestion

### ISSUE THREAD

**Issue by MichaelJCole** [Nyr/openvpn-install#277]
Hi, cool project.  I found it from a comment link [in this tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04)

I was thinking of using openvpn-install to setup a server on DO.

That tutorial takes extra steps (e.g. ufw) I don't see in openvpn-install.  Is there anything here openvpn-install doesn't do?

Also, they show how to test it with this [site](https://www.dnsleaktest.com/).  Is that a good way to test?  If so, might be cool to add to openvpn-install's readme.

Thanks for this, it's important!

Mike

**Comment by Nyr** [comment]
Hey,

Honestly it looks like the person who wrote that tutorial doesn't understand what's going on and just copied some commands found in the internet. From a technical point of view, I think that the setup done by my script is better (but I'm of course biased).

ufw is just a front-end for iptables. My script natively supports both iptables and firewalld, so you are covered either way. It will set up all for you transparently, even if you don't even notice.

The mentioned website is fine for testing DNS leaks, I guess. A default setup using the configuration generated by my script will not leak, except if there are client-side issues which are out of the scope of my work. The setup described in the DigitalOcean tutorial will leak in Windows 10 clients, by the way.
