### ISSUE TITLE
problem in getting it work

### ISSUE THREAD

**Issue by Respectme** [Nyr/openvpn-install#28]
Hello there sir, I installed your script on my server , and everything seems to be fine 
the only problem is when i open the OpenVPN and connect via my server 
the ip of my computer still the same , not mention that I have another server from another company come with the openvpn installed and it’s work just fine .

**Comment by Nyr** [comment]
Run the following commands in your server and paste the output:
`cat /etc/rc.local`
`ifconfig`

Run again the iptables command present on your `/etc/rc.local` file. Does it throw any error?

Please, also paste the client connection log.

**Comment by Respectme** [comment]
#!/bin/sh -e
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to 195.154.80.198
iptables -t nat -A PREROUTING -p udp -d 195.154.80.198 --dport 53 -j REDIRECT --to-port 1194
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0

ifconfig : 

eth0      Link encap:Ethernet  HWaddr c8:0a:a9:f1:a5:3d
          inet addr:195.154.80.198  Bcast:195.154.80.255  Mask:255.255.255.0
          inet6 addr: fe80::ca0a:a9ff:fef1:a53d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1412058112 errors:27 dropped:0 overruns:0 frame:27
          TX packets:2026578698 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:698811957783 (698.8 GB)  TX bytes:2338529939985 (2.3 TB)
          Interrupt:28 Memory:feae0000-feb00000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:1616407 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1616407 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2835874913 (2.8 GB)  TX bytes:2835874913 (2.8 GB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.0.1  P-t-P:10.8.0.2  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


and no it show no problem sir.

**Comment by Nyr** [comment]
I see you are using the system as a remote desktop on Ubuntu... could you be using some firewall by any chance? Take a look at https://github.com/Nyr/openvpn-install/pull/25, for example.

This looks like a problem with your custom setup and not with the script. As the readme specifies, this script is designed to be used on a clean system and it's impossible to support each custom configuration or firewall out there, I can't help any further.

Just so you know: I am personally using this script on Debian with one of my Online.net servers, so it's not a problem with the provider.

Good luck.

**Comment by Respectme** [comment]
im using the server as seedbox , and ubuntu desktop environment

so what do i have to do , so i can make the script work with mine .

and is it work as http proxy too ?

**Comment by Nyr** [comment]
I don't know what exact your setup is. I can only say it works on a default Ubuntu/Debian install. If you are using a fiewall, you would need to add exceptions, but again I don't know much about your setup.

An HTTP proxy has nothing to do with a VPN. You can tunnel HTTP connections using OpenVPN and this script, if that's what you want.

**Comment by Respectme** [comment]
okay sir, im gonna buy a vps from the company you listed on your post. 
and i will install it , and feed you back on the matter 

thank you sir.
