### ISSUE TITLE
Static IP for clients

### ISSUE THREAD

**Issue by dlazesz** [Nyr/openvpn-install#281]
It would be nice if the script could assign static IP for clients when they are added.
(I assume the server's ip is already static.)
As the scirpt currently maintains the list of allowed clients and it would be easy to implement to have a static IP assigned for them when they are added.

What do you think?

**Comment by Nyr** [comment]
Not sure why you want that, but this is a feature which would be useful to a very small portion of users, so there are no plans to implement it.

You are actually the first person ever to ask for this.

**Comment by dlazesz** [comment]
I accept that.

**Comment by Nyr** [comment]
Out of curiosity, may I ask why did you want this?

**Comment by dlazesz** [comment]
See issue #282 ... ;)

**Comment by amir751020** [comment]
I badly need it too guys. @Nyr 
I have a scenario which I will be connecting multiples clients behind dynamic ips to a vpn server, so that our server can communicate with the clients (they are routers actually) freely, because usually most ips block more than 90% of the ports behind dynamic ips, and we don't want to force our customers to buy a static ip.

**Comment by gregology** [comment]
This is how I achieved static ip addresses

create a file with the same name as your cert in /etc/openvpn/client

`$ sudo nano /etc/openvpn/client/greg`

add this line

```
ifconfig-push 10.8.0.42 255.255.255.0
```

then edit `server.conf` to reference that directory

`$ sudo nano /etc/openvpn/server.conf`

```
...
client-config-dir /etc/openvpn/client
```

**Comment by mmendescortes** [comment]
Only if @gregology was there when I used the script...

@Nyr, static IPs are a must for some cases, like when you must set SSH only for a specific client...
