### ISSUE TITLE
Some more documentation on the script

### ISSUE THREAD

**Issue by dlazesz** [Nyr/openvpn-install#282]
I know this nice script is for road warriors, but as it is a pretty easy way to setup a basic generic VPN there should be some more documentation on the limitations:

- There is no support for `client-to-client` option, therefore the clients 'do not see each other' in the network, which can be easily enabled manually.
- There is a rule set for the server's firewall to forward all traffic (__including the VPN subnet__) to the server's LAN instead of the VPN itself, which means the server also 'can not see' the clinents. This can be worked around, but I think it worth noting that.

**Comment by Nyr** [comment]
I get where you are coming from, but this would add further complexity which honestly, I don't want.

A good part of the installation would have to be reworked: conditional NAT checking, conditional DNS prompt, firewall rules for the different situations (road warrior, road warrior + internal, internal only), sysctl, the uninstaller, etc...

Are those difficult to implement? Not really.
Why I don't want to do it then? To keep the installer simple for the user and the code easier to maintain for me.

In general, I don't consider additional features for the script at this point. TCP support was the latest addition and there were lots of demand for it. Internal networking is requested from time to time, but it adds a greater degree of complexity and diverts a little too much from the initial road warrior design.

**Comment by welkie** [comment]
I think dlazesz's comment may have been misunderstood. I think what they meant was to simply document that those features aren't present (that they are limitations), not to implement them

**Comment by Nyr** [comment]
I see.

Well, the readme explains that the script is intended for a road warrior setup. Internal networking shouldn't be expected for that.

For how to enable it, or any other OpenVPN feature, users should check either this issue tracker (where the internal networking particularities had been addressed) or the OpenVPN documentation itself.

**Comment by dlazesz** [comment]
I accept that you do not want to add a single line of complexity into your code, still I suggest to add the two senetence (or the like) in the opener to your README.md as Wikipedia is not explicit on the two suggested topics:

- In road warior configuration (what is implemented in this script) __you should not expect__ clients to see each other. Otherwise consult the `client-to-client` option in the OpenVPN documentation.
- Beware: There is a firewall rule created by this script, that mess up routing if you expect the server to see clients over the VPN and __this is intended__.

These to sentence has no maintenance cost, and the latter caused me to debug this issue for days and that were added to the _no more than a minute setup time_.

Personally I hate OpenVPN documentation as it is too verbose and not usefull. I do not want to know how the thing works. I just need a quick & dirty solution to set it up in one minute and go back to my stuff.

This script would be perfect with the above to warnings in the documentation. You do not have to implement anything and they have no maintenance cost nor add to the complexity of your code.

So please include them in the documentation as this information will be lost in the sea of closed issues, even though how helpful would it be for other newbies like me.

**Comment by Nyr** [comment]
If I were to add warnings about each issue that users opened because they didn't understand how the script or OpenVPN works, the readme would likely be hundreds of lines long by this time.

The script is not intended as an internal networking solution and as such, users modifying the code for their needs are welcome to do so, but shouldn't expect hand holding in the process.

I think we'll need to agree to disagree on this matter.

**Comment by dlazesz** [comment]
If I were expect you to hold my hand, i would insist on changing the source code and therefore the script into something else, which i have accepted not to do.

I do not want to understand your script or OpenVPN as long as it is working as expected!
I have read and expected the following:

> This script will let you setup your own VPN server in no more than a minute, even if you haven't used OpenVPN before. It has been designed to be as unobtrusive and universal as possible.

This tells it all. **Big fat lie!**

There is not a single line of documentation on the intended behaviour of breaking routes from server to clients. The whole point of the README.md is that the user must not know how the scirpt works but is told what it does.

If I am the only one who has problem with the buzzwords __universal as possible__ and __setup your own VPN server__, leave it, else please clarify it!

Now I understand why there are so many forks of this repository are there...
I do not think I could ever make up your mind on writing a sentence or two on this road warrrior stuff in the practical view of the script.

**Comment by Nyr** [comment]
It is clearly explained that the script is intended for a "road warrior" kind of setup (why would I want to mislead my users?).

I never claim that my assistant is an all-purpose OpenVPN installer. The claims that the script is as universal as possible are referring to the fact that it aims to support a wide variety of system and network configurations (servers behind a NAT, various firewall software, many years of old and new OpenVPN and Debian/Ubuntu/CentOS releases, almost all client software, etc...).

About forks, I'd love to see forks implementing other features out of the scope of my project. I don't see forks as bad, more like the opposite: that's why the script is released with a very permissive license.

Enough.
