### ISSUE TITLE
Suggestion for readme re: VPS

### ISSUE THREAD

**Issue by benoliver999** [Nyr/openvpn-install#284]
I don't know about anyone else but I frequently encounter a situation where you have to enable TUN/TAP in a control panel when you have just got a new VPS.

The script exits with 'TUN is not available'. Dunno if it's worth leaving a note in the README to suggest it may need enabling in the VPS control panel when this happens.

**Comment by Nyr** [comment]
You're right, the previous message wasn't very helpful.

The way of enabling TUN varies depending on the server configuration, control panel and type of virtualization, so I think it's better to just show a clearer message so the user can seek help for his specific situation.

Thanks for the report.
