### ISSUE TITLE
How to connect to the VPN once it's setup

### ISSUE THREAD

**Issue by StevenMasini** [Nyr/openvpn-install#285]
Hello,

Could you give more detail about how to connect to the VPN once it's setup ?
How should I configure my client ?

**Comment by k0nsl** [comment]
What OS are you using, @StevenMasini? Typically you would just issue `openvpn --config your_client_config.ovpn`.

**Comment by StevenMasini** [comment]
I'm using Mac OS X. 
It should be possible to use the VPN client included in the OS to connect to the server. Right ?

**Comment by Nyr** [comment]
The included OS X client doesn't support OpenVPN.

You need to download the .ovpn file from the server and import it into Tunnelblick or Viscosity (popular OpenVPN clients for OS X).
