### ISSUE TITLE
Stopped to work on OVZ hosting after recent update

### ISSUE THREAD

**Issue by lewadik** [Nyr/openvpn-install#286]
Hi,
I am using your script for a long time, thank you so much for your work!
But after the recent code updates it's stopped to work on OpenVZ hosting
where it's was working for half of a year before updates comes.
After some of investigation I figured out the suitable config parameters from another .ovpn file.
Original settings that does not work:
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote MY_SERVER_IP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
comp-lzo
setenv opt block-outside-dns
key-direction 1
verb 3

Changes that was help me to fix this:
client
dev tun
proto udp
sndbuf 393216
rcvbuf 393216
mssfix 1410
tun-mtu 1500
remote MY_SERVER_IP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
comp-lzo
pull
redirect-gateway def1
key-direction 1
verb 3

**Comment by Nyr** [comment]
Invalid bug report.
