### ISSUE TITLE
Use official OpenVPN repos for Debian/Ubuntu

### ISSUE THREAD

**Issue by clreinki** [Nyr/openvpn-install#288]
Official Debian and Ubuntu repositories tend to have fairly old OpenVPN versions available.  Therefore OpenVPN has repos for Debian and Ubuntu that have the latest versions available.  It would be nice the script could add this repo prior to install so the latest version would be downloaded.  Official instructions can be found [here](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos).

**Comment by Nyr** [comment]
Debian and Ubuntu repos have reliable and predictable support policies along with binaries for architectures unavailable in the official OpenVPN repos.

The official OpenVPN repo can still be used if the user wants to, script is compatible.
