### ISSUE TITLE
Padavan as client

### ISSUE THREAD

**Issue by bbbenji** [Nyr/openvpn-install#289]
I am having trouble setting up my Padavan router with OpenVPN. Attached is a screenshot of my settings. Am I missing something or maybe a wrong setting perhaps? Using the .ovpn file in Tunnelblick works just fine.

![screen shot 2017-04-12 at 20 35 25](https://cloud.githubusercontent.com/assets/1678118/24973692/0299e33a-1fc0-11e7-80ae-731f3d0b90e6.png)
![screen shot 2017-04-12 at 20 38 25](https://cloud.githubusercontent.com/assets/1678118/24973693/048ea4c8-1fc0-11e7-94b4-00f56cf088b7.png)

Perhaps unrelated, but Padavan logs state:
`Apr 12 20:38:33 openvpn-cli[468]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
`

**Comment by Nyr** [comment]
From the screenshot I can see that you have not enabled the TLS authentication, which is needed.

See the `<tls-auth>` section in the client configuration file.
