### ISSUE TITLE
Easy-RSA V3 - Possible ?

### ISSUE THREAD

**Issue by Zuendapp** [Nyr/openvpn-install#29]
Hello Nyr,

very nice script, thank you very much!!
Is it possible to change the script to RSA v3 or is there any issue with it?

Thank you very much!

Best regards!

**Comment by Nyr** [comment]
Untested, I don't know if something needs to be changed, but it's very likely.

That said, v3 will be implemented when the final release becomes available. AFAIK, the latest at the moment is v3.0.0-rc2.

Anyway I don't see any hurry to update and the official Debian/Ubuntu repos are still serving the 2.x branch.

**Comment by Zuendapp** [comment]
Ok, thank you!
