### ISSUE TITLE
Road Warrior?

### ISSUE THREAD

**Issue by FelixPQ** [Nyr/openvpn-install#291]
I went back for a second look at the definition of road warrior and I think it is exactly what I want. If like the example, I'm outside my office traveling with whatever device, a tablet, phone, etc. I don't see how I can connect to my server from a client with a profile using a private subnet ip 192.168.0.xxx. This is what I have in my clientX.ovpn files. 

It's probably a mistake on my part and I don't understand how I can fix it. I have a domain name and my router is setup to both update my wan ip automatically and forward all the ports I need to service to my server. 

I went to see your suggestion [https://github.com/Nyr/openvpn-install/issues/190] and my needs are exactly of the road warrior type, no internal network stuff as you call it. Client interact only with the server and not between themselves but these client don't necessarily have physical access to my lan thus the idea of using openvpn over the internet, isn't this the normal use?

Thanks,

**Comment by Nyr** [comment]
Please, do not open multiple issues for the same matter.

I insist: if you need clients to access services on the server, you need to enable internal networking.
