### ISSUE TITLE
RSA key length

### ISSUE THREAD

**Issue by user0007** [Nyr/openvpn-install#294]
What is default RSA key length? 2048 bits? Can I change it during setup?

**Comment by Nyr** [comment]
2048 bits is the default, yeah.

Key length can be changed using environment variables, read the easy-rsa documentation for that.

But there is rarely a good reason to change it.

**Comment by amavarick** [comment]
#update vars file
nano /etc/openvpn/easy-rsa/vars
#Change the "export KEY_SIZE= value to the encryption level you desire.
export KEY_SIZE=4096

**Comment by Nyr** [comment]
@amavarick that's useless and will not even work. You lack a basic understanding of how and when the script is using easy-rsa to generate the DH. But some people just want a false sense of security, so I guess it's fine then...

Oh, and key length doesn't change the "encryption level" either. Please, avoid spreading misinformation.
