### ISSUE TITLE
Connection between users

### ISSUE THREAD

**Issue by podguzovvasily** [Nyr/openvpn-install#298]
Hello! 

Great  configuration, but I can`t connect between 2 clients. Ping from server to client is disable!

Sincerely
Vasily

**Comment by heinzdmx** [comment]
Nyr has previously stated that this script is not intended to support that scenario but rather to provide a road warrior setup, see among others #190

**Comment by podguzovvasily** [comment]
Dear Heinzdmx,
Thank you! It is work for me. 
Sincerely
Vasily
