### ISSUE TITLE
Internal networking

### ISSUE THREAD

**Issue by Nyr** [Nyr/openvpn-install#299]
It has been increasingly obvious that many users expect internal networking to be available for their setups.

I have previously expressed [my opinion](https://github.com/Nyr/openvpn-install/pull/195#issuecomment-245961395) on this matter, but it's clear that others think differently.

I see two ways to approach this:
- Allow internal networking by default: judging by the amount of opened issues, many people expect this to be the case. My fear is that others don't and would unknowingly expose stuff to untrusted clients. Connecting hosts should be secured to start with, but we all know that's not always the case. That's my primary concern.
- Provide internal networking as an option: I would also need to add a second prompt about enabling internet routing, since many users wouldn't want that. I don't like the idea of cluttering the assistant with additional questions.

Either way, I would also need to consider if the user would want the script to mess with their firewall to add further exceptions or not. I guess that asking the question would provide some sort of validation.

I want your input on this matter. At the moment, I am considering the simplest option: making internal networking available by default and of course don't mess with firewalls if they are restricting or dropping traffic for that subnet. From the looks of it, that's what many users expect to be default.

**Comment by TechieCrow** [comment]
I'm one of the many that has no need for internal networking if i'm using OpenVPN on the machine but if others find it useful I see no reason to not add it as an optional feature, I understand you don't want it to be cluttered but in the end you will satisfy more people.

As long as the script clearly stats what will be changed in the firewall I don't see anyone have a problem with it.

**Comment by Nyr** [comment]
I kind of expected more participation on this issue, but thanks @TechieCrow.

For now I've taken the less intrusive approach, I think it'll satisfy most users.

**Comment by lukebarone** [comment]
Sorry for chiming in late, but I think offering the option on the initial
run of the script would be awesome. When I set it up for my clients, I
always have to ask the question, and I'd say it's almost a mix 50/50 of
yeses and nos to allowing access to the LAN and Internet at the same time.
Just my two cents.
