### ISSUE TITLE
Problem with LowEndSpirit Server.

### ISSUE THREAD

**Issue by zkanda** [Nyr/openvpn-install#30]
Hi I'm running this script successfully on linode but I can't get it to work for LES.

I can connect to the server but I can't browse/ping anything on my mac after that.
I can't find anything in my syslog or the openvpn-status.log

I tried this with Debian, Ubuntu12/14 with no success.

**Comment by Nyr** [comment]
What recursors did you select during the install? If this is on any of the Inception Hosting sponsored locations, you probably need to select the local ones (default option) and not Google/OpenDNS/etc...

**Comment by zkanda** [comment]
I have one for NanoVZ, the dns resolver are also from local(default). :(

I'm trying to find the logs with no success.

**Comment by Nyr** [comment]
NanoVZ is known to work correctly on the default templates, so this is most likely a problem in your end and not with the script, sorry :(

**Comment by zkanda** [comment]
No worries, can you at least point me to the right logs or something? Sorry for not enough information.

**Comment by Nyr** [comment]
There was a discussion about it on NanoVZ [here](http://lowendtalk.com/discussion/comment/859737/).

That's why I know it works, I did purchase one just to be sure it wasn't the script not supporting their NATed setup.
