### ISSUE TITLE
Devuan

### ISSUE THREAD

**Issue by qahtani** [Nyr/openvpn-install#301]
I just used the script on a machine running Devuan and needed to modify it to check for /etc/devuan_version. Perhaps this could be integrated into future versions of the script.

**Comment by Nyr** [comment]
Devuan is unsupported. For now the script works there, but will stop doing so when some firewall configuration parts are switched to a systemd service, which is a planned change.

Devuan itself will have serious issues surviving as more and more packages become dependant on systemd, but that's out of the scope of this issue ;)
