### ISSUE TITLE
How to use more than 1 IP

### ISSUE THREAD

**Issue by unstopabl3** [Nyr/openvpn-install#302]
Hi, I've been using your script for a while and firstly I'd like to thank you for your effort and hard work.

Previously I was using your script on a VPS which had only 1 statis IP e.g 192.168.1.5 and that's what would show up when I would go to ipburger.com

Now I have installed the script on a new KVM based VPS which has CentOS 6.5 64 bits and I have a total of 3 IPv4 IPs in my account which I want to use with this script but can't figure out how to use them.

I want to be able to have 3 client/ovpn files each with a different IP address and when I connect using that file I should get that IP. I tried by re-running your script again it doesn't ask for a new IP and uses the same IP for all new users. Whereas I would like to assign different IP for different users. Previously with CentOS 5x and older OpenVPN versions I would make a new config file for each IP alongwith a new matching client file, make a new rule in iptable and run all the config files on the server listening for connections. Then I would just connect with the desired client.ovpn file and get a different IP.

Hope you can provide me with noob friendly answer.

Thanks very much.

**Comment by Nyr** [comment]
The process described of using per-client configurations is exactly what you need to do.

The script doesn't support that and given the global IPv4 exhaustion, that will likely continue to be the case.

**Comment by lukebarone** [comment]
As well, the IP you found "by ipburger" is a private IP address, meaning
you won't be able to access it from outside your network, in order to
connect to the server.

**Comment by unstopabl3** [comment]
Can one of you point me to an updated tutorial on how to install openvpn on centos 6.5 or 7 with the latest builds of openvpn such as 2.4.x as all the tutorials on the internet are outdated and don't work.

**Comment by Nyr** [comment]
EPEL has OpenVPN 2.4 available, so that's what the script will install in CentOS.

This is not the right place to ask for general OpenVPN help, use their forums for that.
