### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by Ammar7347** [Nyr/openvpn-install#303]
Hi,

First of all, I love your script. I just wanted to ask if I can access the Open VPN web interface by going onto yourVPSip:1194. I want to change the settings like the encryption of 256 bit to none but can't do so. Is there any way to disable/change the encryption?

Many thanks

**Comment by Nyr** [comment]
There is no web interface. The web interface you are asking about, is probably OpenVPN Access Server, which is a commercial release unrelated to this script.

You can change `cipher AES-256-CBC` to `cipher none` in the configuration. This needs to be edited in both `/etc/openvpn/server.conf` and the `.ovpn` client configuration files.

For further questions related to OpenVPN configuration, read the manual or ask in their forums. This place is only for issues related to the script.
