### ISSUE TITLE
Routing web traffic away from the VPN?

### ISSUE THREAD

**Issue by scouseman** [Nyr/openvpn-install#304]
I am not sure is this should have been placed in the suggestions thread, but what I have been wondering if it would be possible to route only specific ip addressed through the vpn and have all other web activity routed away from the vpn as sort of split tunnel?

I am looking to achieve this as I find the vpn slows down my web browsing experience, so to circumvent this I only want specific ip address routed through the vpn.

Thanks so much for all your effort on this project it is a great script ;)

**Comment by Nyr** [comment]
https://www.google.com/search?q=openvpn+route+specific+traffic
