### ISSUE TITLE
have problem on Ubuntu 17.04 64bit

### ISSUE THREAD

**Issue by ookangzheng** [Nyr/openvpn-install#305]
<img width="1108" alt="screen shot 2017-05-05 at 18 33 47" src="https://cloud.githubusercontent.com/assets/6301735/25742302/681c2c3c-31c1-11e7-8b2d-a9549e00b48e.png">

**Comment by Nyr** [comment]
Likely the OpenVPN package installation failed. Most commonly this happens because your container was out of memory and the script got killed.

Maybe you got more issues than that, but I can't tell. Not an issue with the script.

**Comment by ookangzheng** [comment]
but I install on clean VM and my RAM is 1GB
How can it happend

**Comment by Nyr** [comment]
I don't know what are you doing wrong but you are doing something wrong.

Try to install without modifying anything, the IP, port, nothing. Just run the script and press enter five times. If it's a clean VM, the installer will work.

**Comment by ookangzheng** [comment]
I now tried with 16.04 ubuntu on Digitalocean and see without modifying
