### ISSUE TITLE
Installed finish on Ubuntu 17.04 Digitalocean IPtables prb

### ISSUE THREAD

**Issue by ookangzheng** [Nyr/openvpn-install#306]
The script doesn't auto-insert IPtables rules to the firewall
<img width="889" alt="screen shot 2017-05-05 at 19 01 35" src="https://cloud.githubusercontent.com/assets/6301735/25743109/4d396656-31c5-11e7-9f8b-36fc39eee9c3.png">

**Comment by Nyr** [comment]
Learn to use iptables:

```
root@ubuntu-512mb-fra1-01:~# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:139.59.212.192
```

Again, not a problem with the script. Please do not open more issues about similar matters.

**Comment by Nyr** [comment]
And by the way, if you're planning to use OpenVPN in China, that's not viable.

If that's the case, I suggest that you take a look at Shadowsocks.

**Comment by ookangzheng** [comment]
No lah, I'm not from china ~~ now shadowsocks also blocked in few places 
IKEv2 works well from now I think
