### ISSUE TITLE
key paths

### ISSUE THREAD

**Issue by wynie** [Nyr/openvpn-install#307]
openvpn does not recognize the key/crt/pem files unless you put the full path in server.conf axample: key /etc/openvpn/server.key.
openvpn.service does not work i dont know if this is to do with the script however running openvpn --config /etc/openvpn/server.conf works fine. i am using ubuntu server 16.04.1

**Comment by Nyr** [comment]
You are doing something wrong, this is not an issue with the script or with the openvpn package.
