### ISSUE TITLE
No internet after connection

### ISSUE THREAD

**Issue by ac130kire** [Nyr/openvpn-install#308]
I can connect to the server successfully (running on godaddy vps), but I cannot connect to or ping any website aside from the vps itself.

I am running Centos 7.  I tried Ubuntu 15.04 before, but it had the same situation.

Here is my server.conf

```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
```
If I need to supply any other information, I'd be glad to.  Thanks

**Comment by Nyr** [comment]
- If on Windows, remember that you need to run the OpenVPN client as an administrator.
- Use the script in a clean VPS, if you hadn't already done so.
- If during install you specified a different IP address than the one auto detected, don't.

**Comment by pooriamo** [comment]
I have the same problem although I did exactly what you said and did WHATEVER advice I got from other websites. No internet connection except vps itself. :(
