### ISSUE TITLE
Fails to start on debian (serverSIOCSIFADDR: No such device)

### ISSUE THREAD

**Issue by SheriefAlaa** [Nyr/openvpn-install#31]
Hi,

Thanks for this script but it seems that every time I attempt to start it on debian 7 kernal 3.2.0-4-amd64 I get the following error:

```
[FAIL] VPN 'server' is not running ... failed!
sherief@PersonalServer:~$ sudo service openvpn start
[....] Starting virtual private network daemon: serverSIOCSIFADDR: No such device
: ERROR while getting interface flags: No such device
SIOCSIFDSTADDR: No such device
: ERROR while getting interface flags: No such device
SIOCSIFMTU: No such device
 failed!
```

**Comment by Nyr** [comment]
Something is probably wrong with your TUN adapter, not a problem with the script. Reboot your server and try again, a kernel update could cause this.

If then is still happening, you'll need to troubleshoot this by yourself.
