### ISSUE TITLE
Could not connect from Turkey

### ISSUE THREAD

**Issue by podguzovvasily** [Nyr/openvpn-install#310]
Dear developers and users. I use Digital Ocean droplet and your open-vpn.sh script. In Russia I have not problem with connection, but in Turkey I can`t connect to vpn server. I tried any different configuration. I reinstall server UDP and TCP. Tried another ports like 585 and 25. But still not work.  Ping to server is ok, but openvpn client give different errors:

Control Channel Authentication: tls-auth using INLINE static key file
Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Socket Buffers: R=[65536->65536] S=[65536->65536]
Attempting to establish TCP connection with [AF_INET]207.154.226.108:25 [nonblock]
MANAGEMENT: >STATE:1495114831,TCP_CONNECT,,,
TCP: connect to [AF_INET]207.154.226.108:25 failed, will try again in 5 seconds: Connection timed out (WSAETIMEDOUT)
MANAGEMENT: >STATE:1495114846,TCP_CONNECT,,,
TCP: connect to [AF_INET]207.154.226.108:25 failed, will try again in 5 seconds: Connection timed out (WSAETIMEDOUT)

**Comment by Nyr** [comment]
It looks like you are aware of the fact that this is not an issue with the script or OpenVPN.

Take a look at Shadowsocks, a better tool to bypass internet censorship in oppressive regimes.
