### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by kodekrendel** [Nyr/openvpn-install#311]
Hi. Tried this script on AWS, Ubuntu 16.04. Choose OpenDNS. But have DNS Leak (my provider is shown).

**Comment by Nyr** [comment]
That's a client-side issue unrelated to this script.

**Comment by kodekrendel** [comment]
@Nyr all VPN that I used before doesn't leak DNS. 

How to prevent this with VPN made by this scriot?

**Comment by Nyr** [comment]
Please, do not spam the issue tracker. Lots of people are notified every time you send a message.

Your client system is leaking, this isn't an issue with the script. Honestly I have no clue about whatever client Ubuntu builds, so am unable to help you.

Seek help in the OpenVPN or Ubuntu forums, this is a tracker for issues with the script, not with your personal computer.
