### ISSUE TITLE
How to change settings without reinstalling?

### ISSUE THREAD

**Issue by nucamoz** [Nyr/openvpn-install#313]
My VPS IP is changed. 

If I continue generating users, script is keep using old IP's to configure files. To fix I need to uninstall Openvpn, and then run script again, to proceed all this initial questions, where I choose my IP. 

How to call this setup without reinstalling?

**Comment by Nyr** [comment]
Edit `/etc/openvpn/client-common.txt`.

But you would also need to change the firewall rules, except if you are using NAT and the internal IP didn't change. How to do that, depends on which distro are you using.
