### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by nucamoz** [Nyr/openvpn-install#314]
After I run .ovpn file I got DNS error

whoer.net’s server DNS address could not be found.
Try:
Checking the proxy, firewall, and DNS configuration
DNS_PROBE_FINISHED_BAD_CONFIG

Both client and server are Ubuntu 16.04

**Comment by Nyr** [comment]
Likely because you didn't update the NAT rules, told you on the last issue.

Since you are using Ubuntu, just edit `/etc/rc.local` and reboot.

And please don't open further issues.

**Comment by nucamoz** [comment]
@Nyr it's NEW instance. So you are wrong.

**Comment by Nyr** [comment]
There is no way I can know if you don't tell me.

Don't change the default IP which is automatically detected by the script. If the issue persists, your problem is client-side.
