### ISSUE TITLE
Xbox One giving MTU Error

### ISSUE THREAD

**Issue by MRizkBV** [Nyr/openvpn-install#318]
Hello

I wanted to setup a VPN server to use on my Xbox One because my ISP is trying to restrict access to the VoIP side of Xbox Live which is affecting the online multiplayer in some games causing issues.

Xbox One keeps reporting MTU error when I try to do a multiplayer connectivity test unfortunately. I am not sure why it happens. I have a VPN Unlimited subscription and I use their ovpn files and the Xbox never reports any MTU errors with them, so they must have something special at the server configs I think. I would appreciate any help you can give. Thanks :)

**Comment by Nyr** [comment]
Well, OpenVPN lets you configure a custom MTU, so you take a look at the working configuration and see what they are using.

Other than that, this isn't an issue with the script so I'm closing it. If needed, you can use the OpenVPN forums for further support.

**Comment by MRizkBV** [comment]
I checked their OVPN file but it has nothing special. 
client
dev tun
reneg-sec 0
persist-tun
persist-key
ping 5
ping-exit 30
nobind
comp-lzo adaptive
remote-random
ns-cert-type server
route-metric 1
block-outside-dns

Here is the config the use in the client file. I understand that this is not an issue with the script, I just asked here hoping you knew maybe a way to fix it :/. Thanks.
