### ISSUE TITLE
Not working well for Windows clients

### ISSUE THREAD

**Issue by mark4co** [Nyr/openvpn-install#319]
I have run the install script on an Ubuntu 16.04 server, and while the vpn works wonderfully and flawlessly for Android clients, sadly it keeps on **stopping after some use when connecting using the OpenVpn GUI on Windows 10.** 

I have tried adding the line

`msfix 1300`

to my server config file, but still, after some use Internet stops coming through. (Though the connection seems to be intact, and nothing shows up in the log.)

**Comment by Nyr** [comment]
This is not an issue with the script, use the OpenVPN forums for technical support.

**Comment by mark4co** [comment]
I believe it could be an issue with the script though, because the same windows client works perfectly fine when connecting to a different OpenVPN server that my friend set up. It seems that the client only has these problems when connecting to servers set up with the script. (I have tried running the script on two different servers)

**Comment by Nyr** [comment]
I can assure you that this is not an issue with the script.

If you are using UDP you can try with TCP, but if you're unable to further troubleshoot please go to the OpenVPN forums.

**Comment by Nyr** [comment]
You can also take a look at my responses in #219, a bit of spam on that issue but some factors which you can consider like trying a shorter keepalive.

**Comment by mark4co** [comment]
Thanks for the help. I messed with the keepalive but it still was having troubles.

I found this fork of your script, re-installed with it and it seems to work perfectly out of the box, with no issues on my windows client.    https://github.com/Angristan/OpenVPN-install

**Comment by Nyr** [comment]
My advice is against using that fork, given how clueless and irresponsive the creator is. The creator is aware of my concerns and has even removed the "forked from Nyr/openvpn-install" part on his GitHub repo.

But that has been discussed more than enough in some previous issues, I just don't want to promote that fork.

You can take a look at the configuration differences between the scripts in case you want to further troubleshoot. I'm using a configuration very close to the suggested defaults by the OpenVPN developers, while the fork is modifying more settings instead. I insist that my script is not causing the issue, anyway.

Another detail you can take into account is that my script uses the distribution repos and the fork is grabbing binaries from the official OpenVPN repos, which are more up to date, so in the unlikely case that this was a bug with OpenVPN, it could've been fixed.

Anyway, good to know that you got a working setup.
