### ISSUE TITLE
Suggestion - non-Debian distros

### ISSUE THREAD

**Issue by erm3nda** [Nyr/openvpn-install#32]
This is not a issue, but a suggestion.

How hard is to make it work with non-Debian distros.

**Comment by Nyr** [comment]
Supporting Red Hat based distros (CentOS) shouldn't be very hard but, it's another branch which needs to be tested in as many scenarios as possible and mantained, so it's basically double the work in the long term.

It's something I thought about in the past and will probably do at some point, but no ETA for now.

**Comment by erm3nda** [comment]
Laziness may be a virtue, but only on a working hands.

I have no bash skill, i have no *nix experience, but i will make it work using your script :D because i don't like to do those things manually. Run OpenVPN may be a pain.

Thx.

**Comment by Nyr** [comment]
"Making it work" is pretty easy, even if you aren't very experienced :)

Just change the apt to yum, some file locations and... not much more.

In fact, I should add official support sooner, to be honest. I currently have a broken hand so using computers is a pain, but will take a look at this in the future.

Thanks for the reminder!

**Comment by erm3nda** [comment]
Forked, modified and working on my CentOS vps. Paths are just the same.
The only thing you need to change, is the apt-get/yum commands.

I will update mine later because i have what i need. I guess that was your thing when stop your developing :)
