### ISSUE TITLE
cannot send request to client !

### ISSUE THREAD

**Issue by Boss1669** [Nyr/openvpn-install#323]
Hi, i was able to install openvpn and make client connect to server with ease !!
i wan be able to ping from server to client as well, also client to server are working fine !!
server => 10.8.0.1
client => 10.8.0.2
but i am wondering that i can send request to specific port on client
i have try to send json data to 10.8.0.2 from server with the following command line it doesnt work

wget -O- --post-data='{
  "Test" : "Test",
}' --header=Content-Type:application/json 
"http://10.8.0.2:9999/Integration/Odoo/Execute"

of course on my client i have a listener to port 9999 , but i cant send a POST request to that client openvpn ip and that port

**Comment by Nyr** [comment]
This isn't a issue related to the script.

Please seek assistance on this matter elsewhere.
