### ISSUE TITLE
no TUN device found

### ISSUE THREAD

**Issue by krisjace** [Nyr/openvpn-install#325]
When just ran the script it halted at the beginning telling me that I had no TUN device enabled.
I am running Ubuntu 16.04, and I had to spend some time to learn that this issue can be resolved by these commands:
```
$ cd /dev
$ sudo MAKEDEV tun
$ sudo openvpn --mktun --dev tun0
$ sudo modprobe tun

```
Would be nice if the script could either take care of that OR print an info about this solution in the error message.

**Comment by Nyr** [comment]
TUN is usually available by default, except for some container-based VPS.

Your "solution" can't be implemented into the script because the way of enabling TUN varies depending on the kind of virtualization.
