### ISSUE TITLE
Connected but no internet

### ISSUE THREAD

**Issue by Amir-soltani** [Nyr/openvpn-install#326]
since last commit there is an issue about openvpn, it connects but there is no internet(routing) to browse web.

Edit: I'm trying it in debian

**Comment by raberto-nowhere** [comment]
I have this issue on a fresh install of fedora and script too

**Comment by Nyr** [comment]
It's impossible that the last commit caused an issue with this, more likely the issue is in your end.

Fedora is unsupported and untested, so no surprise that the script doesn't work there. The exception is, if there is something which can be fixed and is coming to CentOS down the line.
