### ISSUE TITLE
Running script in LXC container failed to create cliente ovpn file

### ISSUE THREAD

**Issue by lpvm** [Nyr/openvpn-install#328]
Hi,

First of all, thanks for the script that promises to save hours of error prone configs.
Tried to run it in a ubuntu LXC container in a ubuntu 16.04 server, but the script tries to write the '.ovpn' file in the home path of the host user (lxc in my case) that starts or stops each container.  The files should be saved inside the container, not outside of it.  Please find the below messages:
```

cp: cannot create regular file '/home/lxc/client1_lp_u.ovpn': No such file or directory
openvpn-install.sh: line 48: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 49: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 50: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 51: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 52: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 53: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 54: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 55: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 56: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 57: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 58: /home/lxc/client1_lp_u.ovpn: No such file or directory
openvpn-install.sh: line 59: /home/lxc/client1_lp_u.ovpn: No such file or directory

Finished!

Your client configuration is available at /home/lxc/client1_lp_u.ovpn
```

**Comment by Nyr** [comment]
Use `lxc-attach` instead of whatever you're using, so you get a shell inside the container and run the script there.

Remember that with LXC you need to do other things like enabling TUN and taking care of the NAT.

**Comment by lpvm** [comment]
What I used was lxc-attach.
I know about tun.

**Comment by Nyr** [comment]
Unable to repro then, `~/` expands to `/root` (inside the container) for me.

**Comment by lpvm** [comment]
The user to deal with lxc containers is `lxc`.
I do a `ssh lxc@localhost`.
Then `lxc-attach -n vpnu`
Inside the container:  
```
root@vpnu:/# echo ~
/home/lxc
```
not root :-(

**Comment by Nyr** [comment]
First of all I'm not very familiar with lxc, so maybe you know more than me and please correct if I'm wrong. From what I see, you seem to be dealing with an unprivileged container, while I was running a privileged one.

Does the script fully work on the unprivileged container other than this issue, at least apparently? I would need to figure where's the proper place to write on an unprivileged container, if that's the only issue causing the script to fail.

**Comment by lpvm** [comment]
You're right, I'm running an unprivileged container.  From a security perspective, I don't see much of a difference running a privileged container from running a service in the host, that's why I'm trying to run OpenVPN in an unprivileged container.

Just know of lxc from a user perspective, though.

Yes, the script seems to work well (apparently) besides this problem.

**Comment by Nyr** [comment]
I understand that if enough, an unprivileged container is very desirable. But when running software in unprivileged environments, it's usually the admin which needs to adapt the environment, not the other way around ;) 

The main issue here is that your container doesn't have an usable /home, which is something to be reasonably expected in a functional system. Sure, the script could write somewhere else, but... where? I can't think of a proper place.

I'm almost sure that you can map a /home for your unprivileged container, right? That's a decent approach. Alternatively you can do something else, dirtier, like modifying the script to write in a different place.

**Comment by lpvm** [comment]
I don't understand why you consider there's not an usable /home.  Maybe an user could be created, or maybe the script could write to /root, as root is an unprivileged user outside of the container.
I'll take a look at the script, but it's big and I'm not an expert of bash.
Thank you anyway for the script and for the support!

**Comment by Nyr** [comment]
> I don't understand why you consider there's not an usable /home

Because there isn't. That's exactly why the script is failing.
