### ISSUE TITLE
No access to Internet after connecting to VPN?

### ISSUE THREAD

**Issue by supercom32** [Nyr/openvpn-install#329]
Hi there,

After using the installer on an instance of Ubuntu to setup the VPN server, it seemed everything was fine and it generated my client.ovpn file. However, when I use this file on a client machine to connect to my VPN server, it looses all internet connectivity. 

I assume there is some configuration that I am missing on the VPN server? I was under the impression this script would handle all of that? Or do I need to make changes on the client?

**Comment by supercom32** [comment]
Ah, seems like my firewall service was disabled which I assume was causing issues. I'll play around a bit more and re-open the issue if it indeed is a problem. Apologies!

**Comment by Soullivaneuh** [comment]
@supercom32 I would like to hear what you did if you found a solution. I have the same issue.

**Comment by supercom32** [comment]
@Soullivaneuh: I already mentioned the solution, but I'll say it again in case it wasn't clear. :-) The solution is to turn on your firewall service. You'd think that leaving it off would let everything run just fine, but I suspect there are some specific entries made to the iptables that openvpn depends on. So if your firewall is disabled, these rules never kick in, and it never works. 

In terms of what exactly was the issue with the iptables, I didn't really dig deep enough to find out. Cheers!
