### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by ItsAdventureTime** [Nyr/openvpn-install#33]
Yo,

I really love your script! Seriously! At last. I won't be using OpenVPN's Access Client that has 2 concurrent connections limit. Really, thanks.

Have an awesome day! Also, I hope your script is compatible with CentOS :)

**Comment by Nyr** [comment]
Thanks.

At the moment, the script is compatible with Debian and Ubuntu.

CentOS support will be added in the future.

**Comment by ItsAdventureTime** [comment]
Your script does not allow me to access the internet.

**Comment by ItsAdventureTime** [comment]
I'm willing to give you access to a special VPS server. Please enter your email address here: http://goo.gl/forms/P9SHSTEqgM

**Comment by Nyr** [comment]
Sorry, I don't provide free personal support. The script does work on clean Debian and Ubuntu setups.

**Comment by ItsAdventureTime** [comment]
Because it does not allow me to access the Internet. I even disabled IPtables. Same thing. I can connect to the vpn thingy but it does not allow me to access any website.

**Comment by Nyr** [comment]
> I even disabled IPtables

So you are not using a clean setup. Again, I can only guarantee it to work on a clean Debian/Ubuntu system, no further support is provided except for NATed networks and some other common configurations.

**Comment by ItsAdventureTime** [comment]
What if I’m under NAT, what will I do?

From:  Nyr <notifications@github.com>
Reply-To:  Nyr/openvpn-install 
<reply+007b41a19c962b93289ade8da76d7c06f597b59b263654a692cf0000000110e3480b
92a169ce03547949@reply.github.com>
Date:  Friday, January 30, 2015 at 9:24 PM
To:  Nyr/openvpn-install <openvpn-install@noreply.github.com>
Cc:  Juan Karlo de Guzman <01karlo@gmail.com>
Subject:  Re: [openvpn-install] Hey! (#33)


I even disabled IPtables

So you are not using a clean setup. Again, I can only guarantee it to work 
on a clean Debian/Ubuntu system, no further support is provided except for 
NATed networks and some other common configurations.

**Comment by Nyr** [comment]
I will repeat one last time: support for custom setups will never be provided and you will need to work your way around issues.

Locking this issue now.
