### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by JacobValdemar** [Nyr/openvpn-install#330]
The installation was completed successfully, but when I run `/root/client.ovpn` it says:
```
/root/client.ovpn: line 1: client: command not found
/root/client.ovpn: line 2: dev: command not found
/root/client.ovpn: line 3: proto: command not found
/root/client.ovpn: line 4: sndbuf: command not found
/root/client.ovpn: line 5: rcvbuf: command not found
/root/client.ovpn: line 6: remote: command not found
/root/client.ovpn: line 7: resolv-retry: command not found
/root/client.ovpn: line 8: nobind: command not found
/root/client.ovpn: line 9: persist-key: command not found
/root/client.ovpn: line 10: persist-tun: command not found
/root/client.ovpn: line 11: remote-cert-tls: command not found
/root/client.ovpn: line 12: auth: command not found
/root/client.ovpn: line 13: cipher: command not found
/root/client.ovpn: line 14: comp-lzo: command not found
/root/client.ovpn: line 15: setenv: command not found
/root/client.ovpn: line 16: key-direction: command not found
/root/client.ovpn: line 17: verb: command not found
/root/client.ovpn: line 18: syntax error near unexpected token `newline'
/root/client.ovpn: line 18: `<ca>'
```
I guess that's not what it is supposed to do... 
Btw I'm using Ubuntu Server 17.04 - but, I'm not sure if that's relevant.

**Comment by Nyr** [comment]
That's not what you're supposed to do because `.ovpn` files aren't executable files.

Try for example: `openvpn client.ovpn`

**Comment by lukebarone** [comment]
No, don't run it from a shell. Download openvpn on your device (mobile
phone, laptop, etc) and copy the .ovpn file there. Tell openvpn to use that
configuration file and connect. Check the documentation for your os to know
exactly how.

**Comment by Nyr** [comment]
Yes, I don't think that I was clear enough. 

You need to copy the configuration file to your client first (using SCP for example), then load it into whatever client software you want to use.
