### ISSUE TITLE
Limited bandwidth

### ISSUE THREAD

**Issue by Soullivaneuh** [Nyr/openvpn-install#331]
Thanks for this saving time script! :wink: 

I setup OpenVPN on a VPS server. It works, but the bandwidth seems to be limited.

If I try to download this file: http://ovh.net/files/10Gio.dat (using wget)

From my server: ~35MB/s
From my home using the VPN of this server: **~1MB/s**
From my home without VPN: ~28.4MB/s

I saw some [articles](https://community.openvpn.net/openvpn/wiki/Gigabit_Networks_Linux) explaining some stuff to fix this bandwidth limit.

Can your script handle that?

Note: I installed OpenVPN with your script using all the default settings.

Regards.

**Comment by Nyr** [comment]
Well, my script is of course not applying any limits to your bandwidth.

There are too many factors which can contribute to this issue, but overall you shouldn't expect to get those 300 mbps over the internet with OpenVPN, except in some very favorable circumstances.

~1MB/s is not great, but so weird either. Just so you get an idea, that's similar what I usually get during the afternoons for a connection going across Europe to my shitty home ISP. Maybe you can do better, but troubleshooting this is out of the scope of this issue tracker (which is only for issues with the script).

**Comment by Soullivaneuh** [comment]
Thanks for the reply @Nyr.

It seems to be related to server CPU capacity too.

I did the same install on a dedicated server, now I have a **~5MB/s** download speed.

Does it make sense to you?

**Comment by Nyr** [comment]
CPU bottlenecks are common in VPS, yeah.

Network congestion is also a recurring issue: for example if you are in France and using Free (just assuming) you'd have relatively low-quality bandwidth to almost everywhere.

Again, this is out of the scope of this issue tracker... too many factors involved. If you tell me what is your home ISP and where you do want a good connection to, I could make some suggestions, but ultimately you'll need to try different providers if you want to get an idea of which one works better for you.

**Comment by Soullivaneuh** [comment]
I'm using Orange ISP and I have a 250Mbps connection.

As I said:

> From my home without VPN: ~28.4MB/s

**Comment by Nyr** [comment]
> I'm using Orange

If you want a French ISP, OVH has direct peering with Orange residential and always spare capacity on that link, maybe that's what you're using already? Anyway 50 mbps is a reasonable speed, you shouldn't expect 250 over the VPN in normal conditions.
