### ISSUE TITLE
Support CSF (Config Server & Firewall)

### ISSUE THREAD

**Issue by MikeRich88** [Nyr/openvpn-install#333]
CSF (Config Server & Firewall) is pretty common, especially on cPanel servers.

It presents a far more user friendly interface to the underlying iptables.

To support CSF, you would need to:
1. Insert the desired port number into the correct lines in /etc/csf/csf.conf, example:
```
# Allow incoming UDP ports
UDP_IN = "20,21,53,5201,1194" # order doesn't matter here
```

2. Other direct iptables rules should go into /etc/csf/csfpre.sh

I could try to hack at it but I'm pretty lousy with bash scripting.

**Comment by Nyr** [comment]
Does CSF flush existing rules when starting up? That would be the only way to break rules configured by the script, I'm not familiar with CSF.

Anyway I don't plan to support CSF/ufw or any other "firewall frontend" as long as they don't come enabled by default in one of the supported distros.

**Comment by MikeRich88** [comment]
CSF does flush the rules, I think.

You would not need to support anything in csf.conf. If the rules are simply placed in csfpre.sh instead of /etc/rc.local, it seems to work fine.

I can't test a whole lot on this server.

This would seem like a fairly trivial thing.

**Comment by MikeRich88** [comment]
OK, so at least if people search for "CSF", this issue will show up. For anyone searching:

Just move the iptables lines from /etc/rc.local to /etc/csf/csfpre.sh

Then: csf -ra

**Comment by Nyr** [comment]
If the user is running a custom firewall (or a user-friendly front end, whatever), I don't want to mess with that. The script supports both of the default firewall daemons and that's it.

User is expected to be able to manage his own firewall.

But it's good that this issue is now searchable if anyone with CSF needs some assistance :)

**Comment by africabloe** [comment]
This post is intended to confirm, supplement and help those who need it.
Plus a huge thank you to the developer Nyr.

For **WireGuard + OpenVPN by Nyr** (I am using both of them)
You can add only the code you need. For WireGuard or OpenVPN. 
For about 2 years I used the 1st code. Lately I've been using the 2nd. 
I think it works better with my Windows 10 client PC. Especially when I'm running one of Virtual Box, VMware or HyperV.

Tested on: Ubuntu Server 22.04.5 | Virtualmin 7.30.2 | CSF 14.22 | <del>Fail2Ban</del> | <del>FirewallD</del>

**Before** on file ➙ /usr/local/csf/bin/csfpre.sh
```
#!/bin/bash
# IPV4 Wireguard
iptables -A INPUT -i wg0 -j ACCEPT
iptables -A OUTPUT -o wg0 -j ACCEPT
iptables -A FORWARD -i wg0 -o eth0 -j ACCEPT
iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.7.0.0/24 -o eth0 -j MASQUERADE
# IPV6 Wireguard
ip6tables -t nat -A POSTROUTING -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to $your_IPV6
ip6tables -I FORWARD -s fddd:2c4:2c4:2c4::/64 -j ACCEPT
ip6tables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
# IPV4 OpenVPN
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A FORWARD -o tun0 -j ACCEPT
iptables -A FORWARD -i tun+ -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
# IPV6 OpenVPN
ip6tables -t nat -A POSTROUTING -s fddd:1194:1194:1194::/64 ! -d fddd:1194:1194:1194::/64 -j SNAT --to $your_IPV6
ip6tables -I FORWARD -s fddd:1194:1194:1194::/64 -j ACCEPT
ip6tables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
```

**Now** on file ➙ /usr/local/csf/bin/csfpre.sh
```
#!/bin/bash
# IPV4 Wireguard
iptables -A INPUT -i wg0 -j ACCEPT
iptables -A OUTPUT -o wg0 -j ACCEPT
iptables -A FORWARD -i wg0 -o eth0 -j ACCEPT
iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.7.0.0/24 -o eth0 -j MASQUERADE
# IPV6 Wireguard
ip6tables -A INPUT -i wg0 -j ACCEPT
ip6tables -A OUTPUT -o wg0 -j ACCEPT
ip6tables -A FORWARD -i wg0 -o eth0 -j ACCEPT
ip6tables -A FORWARD -i eth0 -o wg0 -j ACCEPT
ip6tables -t nat -A POSTROUTING -s fddd:2c4:2c4:2c4::/64 -o eth0 -j MASQUERADE
# IPV4 OpenVPN
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A FORWARD -o tun0 -j ACCEPT
iptables -A FORWARD -i tun+ -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
# IPV6 OpenVPN
ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
ip6tables -A INPUT -i tun+ -j ACCEPT
ip6tables -A FORWARD -i tun+ -j ACCEPT
ip6tables -A FORWARD -o tun0 -j ACCEPT
ip6tables -A FORWARD -i tun+ -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
ip6tables -A FORWARD -i eth0 -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
```
