### ISSUE TITLE
Not working on ubuntu 16.04.2

### ISSUE THREAD

**Issue by lopify** [Nyr/openvpn-install#334]
Hi, 

I'm running your script on my digital ocean server with ubuntu 16.04.2.

Everything seems to work, I can connect to it with my macbook but then I try no use the safari or chrome and it doesn't work. Same from my iPhone.

Can you help me debug the issue?

I'm using OS X 10.12.5; Tunnelblick 3.7.1b (build 4813)

Thanks!

**Comment by Ammar7347** [comment]
I can confirm that it's not working. For me it's not working on any browser. The problem is that in "nload", tun0 doesn't show up even though VPN is running
![image](https://user-images.githubusercontent.com/19525838/27916313-221f8f52-6282-11e7-980f-1c17a042a1a4.png)

**Comment by lopify** [comment]
Issue solved for me, I just had to reboot my Mac 😅

**Comment by Ammar7347** [comment]
Mine is still not working

**Comment by Ammar7347** [comment]
THIS is the right place to ask this question because if I manually configure using https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04 the OpenVPN, it works but when I use this script, VPN doesn't work. So basically, the problem is definitely "Script" related.

**Comment by tim-massey** [comment]
For what its worth, I also had issues with Ubuntu 16.04.2. Running the script worked flawlessly when reinstalling the VPS OS to 14.04.x

**Comment by Nyr** [comment]
@tim-massey the script is compatible with Ubuntu 16.04.2. [This](https://github.com/Nyr/openvpn-install/issues/206) is the only known issue which affects some Ubuntu and Debian users and is not caused by the script.
