### ISSUE TITLE
Issue with selecting additional port 53 during setup

### ISSUE THREAD

**Issue by stefancrain** [Nyr/openvpn-install#34]
First off, loving this tool!

During a recent setup I opted to use port 53 in addition to 1194 : 
```
Do you want OpenVPN to be available at port 53 too?
This can be useful to connect under restrictive networks
Listen at port 53 [y/n]: y
```
When I downloaded the .ovpn profile I wasn't able to connect, so I took a look at open ports on the server
```
root@crain:~# netstat -ltnup
Proto Recv-Q Send-Q Local Address   Foreign Address    State   PID/Program name
shh-ports blah blah blah ...
udp    0   0 0.0.0.0:53    0.0.0.0:*      922/openvpn
```
It looks like port 1194 isn't attached to anything, but I took a look from my computer just to make sure.
```
echo -e "\x38\x01\x00\x00\x00\x00\x00\x00\x00" | nc -w 10 -u server.ip 1194 | cat -v
```
And no response came back, 'pinging' openvpn it should output something like @??e?tg]T^@^@^@^@^@@..... 

I'd love to have both ports working, is there anything else I can do to help debug this issue?

Here's my test system info
```
root@crain:~# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
Thanks again!

**Comment by Nyr** [comment]
You are right, this was a regression introduced with the latest commit which has now been reverted.

Thank you for reporting this.
