### ISSUE TITLE
Terminal Issues After Command

### ISSUE THREAD

**Issue by pianolinux** [Nyr/openvpn-install#342]
Whenever i run the command " openvpn --config script.ovpn " on the client side, my terminal freezes even after the script executes successfully. i even tried to send the output to a file, it still freezes on Centos and Ubuntu terminals.

**Comment by Nyr** [comment]
Are you remotely connected (via SSH for example) while running that? In that case, your connection would drop after establishing the VPN connection, "freezing" your terminal until it times out. That's to be expected.

Anyway please go elsewhere for technical support, this is just a tracker for issues with the script.
