### ISSUE TITLE
No Internet connectivity after installing

### ISSUE THREAD

**Issue by wodim** [Nyr/openvpn-install#346]
Server: VPS on Scaleway. Behind a NAT, but properly configured (I believe). UDP over IPv4.

Client: iPhone 5s. (😉)

I can connect to the VPN but there's no Internet connectivity. I can reach 10.8.0.1 (the default gateway), but nothing else.

Client log: http://sprunge.us/WNTW

**Comment by Nyr** [comment]
Please paste the output of:

`iptables -t nat -L`

**Comment by wodim** [comment]
Chain PREROUTING (policy ACCEPT)
    target     prot opt source               destination

    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination

    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination

    Chain POSTROUTING (policy ACCEPT)
    target     prot opt source               destination
    SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:212.47.x
    SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:0.0.0.0
    SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:10.2.x

(The IP addresses are correct)

**Comment by Nyr** [comment]
Only the latest rule is needed/correct, and it was set up by the script. I assume that you did set up the two others manually.

**Comment by raphaelmerx** [comment]
@Nyr is right, this problem comes from bad rules in your iptables. I fixed the problem by clearing the iptables rules, then adding the one in the script:
```
iptables -t nat -F  # clear the rules in the nat table
IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)  # get your IP address
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP  # add the rule
```
