### ISSUE TITLE
TAP connection

### ISSUE THREAD

**Issue by river100** [Nyr/openvpn-install#347]
Could you please give me the changes in script to make the server install as a TAP connection ?

**Comment by river100** [comment]
BTW works great as TUN as intended, I thank you.

**Comment by Nyr** [comment]
This request is out of the scope of the script, please use the OpenVPN forums for that.

The configuration itself is easy to edit in the script, you just need to find and edit the relevant parameters in the code, they are directly written in the configuration from there.
