### ISSUE TITLE
why it hints "No such file or directory" while the files indeed exist?

### ISSUE THREAD

**Issue by luckypoem** [Nyr/openvpn-install#348]
hi.

root@gcv:~# ls /etc/openvpn
ca.crt		   crl.pem   server.conf  ta.key
ca.key		   dh.pem    server.crt   update-resolv-conf.dpkg-new
client-common.txt  easy-rsa  server.key
root@gcv:~# openvpn --config /etc/openvpn/server.conf
Options error: --dh fails with 'dh.pem': No such file or directory
Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'server.crt': No such file or directory
Options error: --key fails with 'server.key': No such file or directory
Options error: --crl-verify fails with 'crl.pem': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
root@gcv:~#

tks

**Comment by luckypoem** [comment]
NOW I KNOW WHY.just modify server.conf as follows:(write the full path to those files)

port 1278
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh.pem
auth SHA512
tls-auth /etc/openvpn/ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify /etc/openvpn/crl.pem

then the issue is fixed.

**Comment by Nyr** [comment]
This is not an issue with the script. The script uses relative paths and that's fine when using the service, as you should.
