### ISSUE TITLE
Failed to fetch http://swupdate.openvpn.net/ - 404 Not Found [IP: 104.20.194.50 80]

### ISSUE THREAD

**Issue by rhbkweb** [Nyr/openvpn-install#349]
Hi,

Since a few days I'm getting this error message when I try to update my server:

`Err http://swupdate.openvpn.net jessie/main amd64 Packages                             
  404  Not Found [IP: 104.20.194.50 80]
Fetched 4,952 kB in 8s (562 kB/s)                                                      
W: Failed to fetch http://swupdate.openvpn.net/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 104.20.194.50 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

My server is running Debian 8.9 Jessie. Does anyone knows how to fix this issue?

Thanks

**Comment by rhbkweb** [comment]
Found the solution:

Edit file: /etc/apt/sources.list.d/swupdate-openvpn.list and update the rep with:

deb http://build.openvpn.net/debian/openvpn/stable jessie main

**Comment by Nyr** [comment]
You weren't using my script so please don't open issues on my tracker.

Greetings to the maintainer of the "improved" fork which has left his entire user base unable to receive security updates.
