### ISSUE TITLE
Job for openvpn@server.service failed 

### ISSUE THREAD

**Issue by dach384** [Nyr/openvpn-install#354]
Hi there, 

I'm getting `"because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.  
`

From the logs, I see the following:

```
Sep  4 16:54:40 fluffytiger systemd[1]: Stopped openvpn@server.service.
Sep  4 17:16:56 fluffytiger ovpn-server[28000]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf
Sep  4 17:17:35 fluffytiger systemd[1]: openvpn@server.service: Control process exited, code=exited status=1
Sep  4 17:17:35 fluffytiger systemd[1]: openvpn@server.service: Unit entered failed state.
Sep  4 17:17:35 fluffytiger systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
```
let me know if I can assist further. I am happy to help.

**Comment by dach384** [comment]
I got it to work when i commented out `LimitNPROC line in /lib/systemd/system/openvpn@.service`
so no rush on fixing this.

**Comment by Nyr** [comment]
This is a well known issue with the OpenVPN service in containers (#206) and sadly no one able to fix it is interested in doing so.
