### ISSUE TITLE
on reboot cant connect to vpn 

### ISSUE THREAD

**Issue by gaming09** [Nyr/openvpn-install#355]
I am sorry if im a noob at this, When i rebooted my vps, i am no longer able to connect to the open vpn session it just hangs at 

Tue Sep 05 15:46:47 2017 UDP link remote: [AF_INET]PUBLICIP:1194
Tue Sep 05 15:46:47 2017 MANAGEMENT: >STATE:1504651607,WAIT,,,,

**Comment by slrslr** [comment]
as a noob i would try:
cat /var/log/messages|grep openvpn
Click your openvpn client and find log file
ping youropenvpnserverip

**Comment by Nyr** [comment]
Looks like a connectivity related issue.

If you still need help, please go to the OpenVPN forums [here](https://forums.openvpn.net/).
