### ISSUE TITLE
Request: add per-user + password configuration option

### ISSUE THREAD

**Issue by MagicFab** [Nyr/openvpn-install#358]
I noticed client configurations are generated with the NOPASS option. It would be useful to have an option to be able to generate per-user password-protected configurations.
I am not certain which options would result in such a setup but the end result is the user having to enter their password each time the VPN link is established.
For now I removed the NOPASS option in easyrsa client config generation but it results in a permanent password being specified in the configuration (it has to be saved) which doesn't match what I describe above but improves security of the configuration when sending the ovpn generated files.

**Comment by Nyr** [comment]
This is not a planned feature, but I don't see what's wrong with removing `nopass` to use a password for the client private key. If that's not what you want, you could be interested in authentication via `auth-user-pass` instead. Read the OpenVPN manual about that setting.

**Comment by no-replies** [comment]
It would be useful
