### ISSUE TITLE
After Connected to VPN than Internet is not working anymore.

### ISSUE THREAD

**Issue by chantrea999** [Nyr/openvpn-install#359]
![screen shot 2017-09-13 at 10 57 32 am](https://user-images.githubusercontent.com/28737197/30392781-b31874b2-9872-11e7-99a5-46a1a2d6a969.png)

Please watch the step that I did on youtube
https://youtu.be/i1NRVym4vhU

**Comment by Nyr** [comment]
You did set up the NAT incorrectly. Next time, search for similar issues before opening a new one for the same problem.

See [here](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353).
