### ISSUE TITLE
Client password without 'in-line' certificates

### ISSUE THREAD

**Issue by Ali3n0id** [Nyr/openvpn-install#36]
Forgive me if this has already been done but is there a fork that uses a .ovpn file with a client password but without the certificate files required... So I only need to import the .ovpn and enter the password.

Thanks in advance

**Comment by Nyr** [comment]
No idea about the fork.

With inline certificates you can simply import the .ovpn too, no need for a password.

**Comment by Ali3n0id** [comment]
Not sure if you know what I mean.

I want a password that is associated with the .ovpn file, I don't want to transfer all the certificates as well so if I give a user access all they'll need it the .ovpn file and the matching password.

Like how this tutorial has done:

http://readwrite.com/2014/04/10/raspberry-pi-vpn-tutorial-server-secure-web-browsing#awesm=~oDjmBKjSNU6cYr

**Comment by Nyr** [comment]
This script intends to be as barebones and default as possible and OpenVPN by default uses certificate authentication which is usually more convenient and secure, so this will not change in the near future.

You are welcome to fork trough.

**Comment by Ali3n0id** [comment]
Okay thanks for your help. 

That's exactly what I'll do, cheers.
