### ISSUE TITLE
Websites not loading

### ISSUE THREAD

**Issue by lomer3** [Nyr/openvpn-install#360]
I've configured openvpn with your script. But i can not access the internet. VPN connects fine. But ping 8.8.8.8 not work and websites not loading.
I can only access 10.8.0.1.
ping 10.8.0.1 is fine
But all other not fine, can't ping 8.8.8.8 or anything else. Can't access websites.
I have no firewalls before vps and i did not change anything in iptables - just installed script, client machine is on NAT network (but i suppose no open ports required on client machine).
I am using Debian 7 64-bit on server and Ubuntu 16.4 on client.
I have tried to use another protocol and another ports, any port and protocol not work.
Can you please help?

**Comment by lukebarone** [comment]
I guess I should ask...

Are you trying to access the Internet, a distant LAN, or just a server that
has OpenVPN installed?

**Comment by lomer3** [comment]
I am using client with Ubuntu 16.4, and i am trying to do at least two things:

1. ping Google DNS correctly
8.8.8.8
```bash
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
--- 8.8.8.8 ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8065ms
```
2. access https://github.com over VPN using Mozilla Firefox browser.
It returns "Server not found

Firefox can’t find the server at github.com."

**Comment by lukebarone** [comment]
Have you looked at https://github.com/Nyr/openvpn-install/issues/92?

**Comment by Nyr** [comment]
Yes, see #92 or https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353. That's likely your issue.
