### ISSUE TITLE
Iptables Firwall Rules

### ISSUE THREAD

**Issue by fuddel18** [Nyr/openvpn-install#362]
Hello Nyr,

First of all, a praise to your script. Many Thanks.

Is it possible that you can give me the iptables rule separately times.
I have created an iptabels firewall script and would like to add the rules for the OpenVPN.
Input, Forwarding, Output, Nat, Routing

Many Thanks.

**Comment by Nyr** [comment]
We have a little language barrier here. If I understood you, you are asking which rules is the script setting up, right?

It depends:

1. iptables is only used if firewalld is not enabled
2. If iptables is used, only the following rule is applied:
`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP `
3. Except if the script detects `DROP` or `REJECT` rules active. If so, these are added too:
`iptables -I INPUT -p $PROTOCOL --dport $PORT -j ACCEPT`
`iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT`
`iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT`

If the system uses firewalld, the following rules are set up instead:
```
firewall-cmd --zone=public --add-port=$PORT/$PROTOCOL
firewall-cmd --zone=trusted --add-source=10.8.0.0/24
firewall-cmd --permanent --zone=public --add-port=$PORT/$PROTOCOL
firewall-cmd --permanent --zone=trusted --add-source=10.8.0.0/24
firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
```

Please also note that this platform is just a tracker for issues with the script (bugs, improvements, suggestions...), so I'm closing this. If you need further assistance, I'd ask you to please go elsewhere.
