### ISSUE TITLE
LXD Containers

### ISSUE THREAD

**Issue by aaronstuder** [Nyr/openvpn-install#364]
Anyone have a solution for running this inside a LXD container?

**Host:** Ubuntu 17.04
**Container:** Ubuntu 17.04

I am forwarding port 1194 from the host to the container using iptables.

Sadly I still can not connect.

**Comment by aaronstuder** [comment]
sudo systemctl status openvpn@server shows:

Failed to start OpenVPN connection to server.

Commenting out the LimitNPROC line in /lib/systemd/system/openvpn@.service allows the service to run but I still can not connect.

**Comment by Nyr** [comment]
If the service is running, maybe haven't forwarded the port correctly.

Or maybe you did set up the NAT wrongly, check [this](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353).

Difficult to troubleshoot more with the information given, but this does seem like a connectivity issue.
