### ISSUE TITLE
OpenVPN on RPi OMV 2.0.15

### ISSUE THREAD

**Issue by redgallows** [Nyr/openvpn-install#365]
Hi,

I used to be able to setup OpenVPN successfully by using the "openvpn-install.sh" script a year ago.
Recently I reinstalled the OMV 2.0.15 on RPi again and used the latest version of "openvpn-install.sh" but failed.
Please see below the screen shot. Seems like problem is on "OPENSSL_1.0.1s' not found".

Could you please take a look and advice?

Thank you.

########################################################################
Saving to: `/root/EasyRSA-3.0.3.tgz'

100%[==================================================================================================================================================================>] 40,960       211K/s   in 0.2s

2017-09-23 02:45:39 (211 KB/s) - `/root/EasyRSA-3.0.3.tgz' saved [40960/40960]

openssl: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.1s' not found (required by openssl)

Easy-RSA error:

Missing or invalid OpenSSL
Expected to find openssl command at: openssl
openssl: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.1s' not found (required by openssl)

[openvpn-install_error.log](https://github.com/Nyr/openvpn-install/files/1326382/openvpn-install_error.log)

**Comment by Nyr** [comment]
Please note that your distribution is unsupported, even if it's based on Debian. Unsupported doesn't mean that it will necessarily not work, only that it is not actively maintained or tested and there are no guarantees.

That said, a quick search suggests this: https://github.com/alexa/alexa-avs-sample-app/issues/55.

**Comment by redgallows** [comment]
Thanks. It's resolved by manually install "libssl-dev".
