### ISSUE TITLE
changing easyRSA vars

### ISSUE THREAD

**Issue by irghost** [Nyr/openvpn-install#369]
how can i change default vars in esayRSA for this script

**Comment by Nyr** [comment]
https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Advanced.md

**Comment by irghost** [comment]
and how will this works with your bash?

**Comment by Nyr** [comment]
It depends on what you want, search elsewhere if you need help understanding bash, this is not the right place.
