### ISSUE TITLE
Not running dns

### ISSUE THREAD

**Issue by nekulin** [Nyr/openvpn-install#370]
server.conf

	push "redirect-gateway def1 bypass-dhcp"
	push "dhcp-option DNS 8.8.8.8"
	push "dhcp-option DNS 8.8.4.4"

Connect

	sudo openvpn --config client.ovpn

Ping

	ping google.com

no ping

**Comment by Nyr** [comment]
OpenVPN doesn’t “run” DNS.

If your server is behind NAT, check this: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353
