### ISSUE TITLE
How do support ipv6 ?

### ISSUE THREAD

**Issue by liuxyon** [Nyr/openvpn-install#371]
my VPS and my local lan hope add ipv6 , how i do it?  vps has ipv6 and ipv4 ip address.  

by the way, how i chooice GCM cert ?

**Comment by Nyr** [comment]
Use the OpenVPN forum for support.

**Comment by liuxyon** [comment]
my mean is use your shell how do it?

**Comment by billyprice1** [comment]
i need this as well
