### ISSUE TITLE
Server fails to start on 16.04 OpenVZ

### ISSUE THREAD

**Issue by garikaib** [Nyr/openvpn-install#375]
Even on a pristine install the server will fail to start upon reboot using the command:
`systemctl start openvpn@server`
This means upon rebooting the server you will not be able to connect to VPN service.
# Solution
The solution to this is to edit `/lib/systemd/system/openvpn@.service` and commenting out the line with `LimitNPROC` by adding a `#` before the line.
This stems from this[ issue.](https://github.com/systemd/systemd/issues/6011)

**Comment by Nyr** [comment]
Well known issue, see #206.
