### ISSUE TITLE
  First installation problem

### ISSUE THREAD

**Issue by DoLolitingyu** [Nyr/openvpn-install#382]
I'm a beginner, and I guess a lot of people have this problem. After setting up the account password, how to see or set, if it is better, can you send a mobile phone connection OpenVPN tutorial?thank you.
^_^

**Comment by Nyr** [comment]
This is not the right place to ask for tutorials.

Additionally, and maybe because there is a bit of a language barrier, I couldn't understand your request. Anyway please go to the OpenVPN forums for help, that's the right place.
