### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by JeremiSharkboy** [Nyr/openvpn-install#383]
Hi. Using your script, im install server. and success connect to one. But no internet
Any help?

**Comment by Nyr** [comment]
If your server is behind NAT, [this](https://github.com/Nyr/openvpn-install/issues/376#138) is likely the issue.

**Comment by Nyr** [comment]
Likely too late now, but for anyone who finds this in the future, I linked to the wrong issue.

[This](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353) was the right one.
