### ISSUE TITLE
Change EASYRSA_CRL_DAYS to 3650

### ISSUE THREAD

**Issue by episage** [Nyr/openvpn-install#384]
Currenly it's set at 180 and NO client is able to connect after 180 days pass.
You need to change  EASYRSA_CRL_DAYS `/etc/openvpn/easy-rsa/vars` to 3650 and ./easyrsa gen-crl

The error you get in OpenVPN logs:
```
CRL has expired
```

**Comment by Nyr** [comment]
No, this was already fixed with a cleaner approach: https://github.com/Nyr/openvpn-install/commit/9c0579052f149dd46cc59b1b8bee53f3d54dc785
