### ISSUE TITLE
Can't connect to VPN

### ISSUE THREAD

**Issue by thereturn932** [Nyr/openvpn-install#388]
Yesterday, my VPN was working. However, today I upgraded my server from 14.04 to 16.04 now its not working. I tried returning to 14.04 again its not working. OpenVPN says its connecting and stays like tgat. nothing happens. Also to access admin panel I could use 

/usr/local/openvpn_as/bin/ovpn-init --force

However now it returns error 

-bash: /usr/local/openvpn_as/bin/ovpn-init: No such file or directory

**Comment by Nyr** [comment]
Provide the connection log and the installation log at the very least, we can’t magically troubleshoot your issue.

Try running the script on a clean system, still happening? Take a look at #206 too if you are using OpenVZ.

**Comment by Nyr** [comment]
I see that you have edited your message with more information.

OpenVPN Access Server is 100% unrelated to this project, so this is not the right place to ask for help.
