### ISSUE TITLE
bad encapsulated packet length from peer

### ISSUE THREAD

**Issue by bennygeorgiev** [Nyr/openvpn-install#390]
getting this error when trying to connect to server on tcp port 443
didn't found information online

**Comment by Nyr** [comment]
If you are unable to troubleshoot the issue, at the very least paste the full log and explain if you tried to modify the MTU as the full log will likely suggest.

That said, this can be a sign of other issues, like a filtered network or if you are somehow proxying the traffic on that port (for example, to split for different services).

Go to the OpenVPN forums if you need further assistance.
