### ISSUE TITLE
Single or Multi Access

### ISSUE THREAD

**Issue by phyesix** [Nyr/openvpn-install#395]
Hi,
Firstly thank you for your script file. It really makes a lot of sense. I have a question about multi-access. 
Is there any option single or multi-access with a single *.ovpn file?

**Comment by lukebarone** [comment]
What are you asking about?

**Comment by Nyr** [comment]
From the OpenVPN manual:

> **--duplicate-cn**
> Allow multiple clients with the same common name to concurrently connect. In the absence of this option, OpenVPN will disconnect a client instance upon connection of a new client having the same common name.

Most often, it is a bad idea to share the same certificate between multiple clients, just like it would be sharing your password with multiple people. Use one certificate per client.
