### ISSUE TITLE
Client connects but connection drops after few seconds

### ISSUE THREAD

**Issue by fafilipp** [Nyr/openvpn-install#396]
Dear community,

I have just set up a OpenVPN server on an Ubuntu 16.04.3 LTS VPS using the install script here:
https://github.com/Nyr/openvpn-install

Now, I set up 5 clients and the clients are all able to connect successfully to the server. 
But, for all the clients first the connection is established and all connection is routed through VPN (i can also traceroute 8.8.8.8), but after some seconds (connections stays established), the client is not able to reach any host (traceroute 8.8.8.8 gives no result).

Here you can find my configuration

```
port 1194
proto udp
dev tun
sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
```

One exemplary client.ovpn
```
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote SERVER-ADDRESS 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
comp-lzo
setenv opt block-outside-dns
key-direction 1
verb 3
```

traceroute directly after connection is established:
```
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 52 byte packets
 1  10.8.0.1 (10.8.0.1)  32.836 ms  32.139 ms  32.258 ms
 2  XX.XX.XX.XX (XX.XX.XX.XX)  31.958 ms  32.125 ms  32.249 ms
 3  XX.XX.XX.XX (XX.XX.XX.XX)  32.111 ms  35.302 ms  31.870 ms
 4  XX.XX.XX.XX (XX.XX.XX.XX)  32.062 ms  32.382 ms  32.076 ms
 5  google.mix-it.net (217.29.66.96)  32.668 ms  121.038 ms  88.067 ms
 6  * * *
 7  108.170.233.139 (108.170.233.139)  32.903 ms
    108.170.233.143 (108.170.233.143)  101.067 ms
    108.170.235.59 (108.170.235.59)  37.394 ms
```

traceroute after some time (around 30 sec):
```
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 52 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
```
Also no host can be resolved.

Any advice how to resolve this? Is a really strange behavior.

**Comment by zenithteq** [comment]
Hey, I would try changing the sndbuf and rcvbuf and see if that makes any difference.  Also, are you using the same client file for all 5 devices or you generated 5 different client configs?

```
sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
```

to

```
sndbuf 0
rcvbuf 0
```

**Comment by fafilipp** [comment]
Its 5 client configs, the sndbuf and rcvbuf was to 0 before and it didnt work too.

**Comment by Nyr** [comment]
As @zenithteq has noticed, either you aren't using my script but a fork of it, or you have manually modified the configuration.

Whoever wrote those configuration lines doesn't understand what he's doing and I can't provide support for third party experiments. This is not a problem with the script, so if you need help with configuration I suggest to try in the OpenVPN forums instead.
