### ISSUE TITLE
[BUG REPORT] Your code didnt work on bandwagonghost KVM 

### ISSUE THREAD

**Issue by zhneghuaiyu** [Nyr/openvpn-install#397]
[BUG REPORT] Your code didnt work on bandwagonghost KVM 
Couldn't install EasyRSA properly

**Comment by Nyr** [comment]
I’m going to need a log of the installer or something to see what’s going on. The script is platform independent and should work nearly everywhere, specially in KVM.

Please also note that OpenVPN usually doesn’t work in China mainland, in case you’re there.

**Comment by zhneghuaiyu** [comment]
I will give you root access to look whats happened 
IP  65.49.199.131
PASSWORD  fb36fCN7Gy3y  port 29669  root 

Centos 6 x86_64 bbr 


发送自 Windows 10 版邮件应用

发件人: Nyr
发送时间: 2017年12月27日 18:07
收件人: Nyr/openvpn-install
抄送: zhneghuaiyu; Author
主题: Re: [Nyr/openvpn-install] [BUG REPORT] Your code didnt work onbandwagonghost KVM (#397)

I’m going to need a log of the installer or something to see what’s going on. The script is platform independent and should work nearly everywhere, specially in KVM.
Please also note that OpenVPN usually doesn’t work in China mainland, in case you’re there.

**Comment by Nyr** [comment]
I've just edited your message. You should never publish those details on the internet, this issue tracker is public.

Thankfully looks like I was the first to login and I've changed the password. Please let me know your email so I can privately send the new password if you want.

**Comment by zhneghuaiyu** [comment]
Zhenghuaiyu1992@gmail.com

发送自 Windows 10 版邮件应用

发件人: Nyr
发送时间: 2017年12月27日 18:20
收件人: Nyr/openvpn-install
抄送: zhneghuaiyu; Author
主题: Re: [Nyr/openvpn-install] [BUG REPORT] Your code didnt work onbandwagonghost KVM (#397)

I've just edited your message. You should never publish those details on the internet, this issue tracker is public.
Thankfully looks like I was the first to login and I've changed the password. Please let me know your email so I can privately send the new password if you want.

**Comment by Nyr** [comment]
This issue has been resolved privately with the user.

For anyone interested, root cause was that EPEL repo was installed but disabled, so the `openvpn` package wasn't getting installed.

**Comment by tepmnthar** [comment]
This problem seems occurred on bandwagonghost KVM Centos 6 x86_64 bbr for chinese users.
The root cause is just what @Nyr said. Follow the guide in this link [How to enable or disable repositories in CentOS](https://www.unixmen.com/enable-disable-repositories-centos/) will fix the issue.
简单讲，就是搬瓦工的服务器默认EPEL有但没开，按照上面那个链接开开来再跑一遍就对了。
