### ISSUE TITLE
i server is not forwarding

### ISSUE THREAD

**Issue by Benman2785** [Nyr/openvpn-install#399]
hey - i can connect to the server - but i can visit any websites anymore
server is in lan - and has working access to internet (wget works)

**Comment by Nyr** [comment]
https://github.com/Nyr/openvpn-install/issues/376#138

**Comment by Benman2785** [comment]
still not working!

**Comment by Nyr** [comment]
This is very likely a problem with your setup.

Please paste the output of:

`iptables -t nat -L`

**Comment by Nyr** [comment]
Sorry, I linked to the wrong issue in my first message.

Try this instead: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

**Comment by Benman2785** [comment]
![nyr-iptables](https://user-images.githubusercontent.com/21282980/34457663-1e003bee-edb8-11e7-81a0-112ca9a55878.jpg)

and my server has ip 192.168.0.2 behind nat // and i edit the external ip later

**Comment by Nyr** [comment]
Those rules are not what the script did set up, by the way.

Take a look at the linked issue which is very likely your problem, but you need to cleanup your iptables.

**Comment by Benman2785** [comment]
k-i flash my iptables and do reinstall it a 5th time ;)

will answer in 15min

**Comment by Benman2785** [comment]
sry - will take longer - i was tired and used iptables -P INPUT DROP xD

**Comment by Benman2785** [comment]
hehe - found it

my ISP gave me DS-light - so i needed to call him for a upgrade to full dualstack
now its working ;)
