### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by faurest** [Nyr/openvpn-install#40]
The possibility of creating a password would be welcome;)

**Comment by Stsosz** [comment]
OpenVPN uses a certificate system to allow users to authenticate themselves. There is no need for a password.

**Comment by Nyr** [comment]
@Stsosz is right, certificates provide a better grade of security than passwords, too.

**Comment by jugganuts420** [comment]
I agree that passwords are much weaker than certs but I think it would be a nice feature to have the option to set a password with a security warning. The only reason I say this is because many of the people that use my openvpn server are tech illiterate (e.g. grandma)

**Comment by Nyr** [comment]
There are some very valid use cases for this and other settings, I agree.

That said, we limit the number of available options during setup to only the most requested ones so the script is clear and simple even for the less technical users and this hasn't been a very popular request. There are others like cipher or key length selection which were also dismissed to preserve simplicity.

I would suggest a fork if your specific use case needs this.
