### ISSUE TITLE
Not able to connect from client

### ISSUE THREAD

**Issue by Raakh** [Nyr/openvpn-install#401]
Hello,
Your script successfully generated all files and service openvpn is running fine. I have downloaded client file to my windows 10 laptop and tried severally with administrator privilege to connect but in vain. 
Here is the log:
Wed Jan 03 22:27:14 2018 OpenVPN 2.4.2 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on May 11 2017
Wed Jan 03 22:27:14 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Wed Jan 03 22:27:14 2018 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.10
Enter Management Password:
Wed Jan 03 22:27:14 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Wed Jan 03 22:27:14 2018 Need hold release from management interface, waiting...
Wed Jan 03 22:27:14 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Wed Jan 03 22:27:14 2018 MANAGEMENT: CMD 'state on'
Wed Jan 03 22:27:14 2018 MANAGEMENT: CMD 'log all on'
Wed Jan 03 22:27:14 2018 MANAGEMENT: CMD 'echo all on'
Wed Jan 03 22:27:14 2018 MANAGEMENT: CMD 'hold off'
Wed Jan 03 22:27:14 2018 MANAGEMENT: CMD 'hold release'
Wed Jan 03 22:27:15 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 03 22:27:15 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 03 22:27:15 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]62.210.10.20:1194
Wed Jan 03 22:27:15 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed Jan 03 22:27:15 2018 UDP link local: (not bound)
Wed Jan 03 22:27:15 2018 UDP link remote: [AF_INET]62.210.10.20:1194
Wed Jan 03 22:27:15 2018 MANAGEMENT: >STATE:1515005835,WAIT,,,,,,
Wed Jan 03 22:27:34 2018 SIGTERM[hard,] received, process exiting
Wed Jan 03 22:27:34 2018 MANAGEMENT: >STATE:1515005854,EXITING,SIGTERM,,,,,

Here is logwatch:
Ciphers used for Authentication:
    Control Channel:
       Incoming:
          160 bit SHA1 used 4 Time(s)
          512 bit SHA512 used 2 Time(s)
       Outgoing:
          160 bit SHA1 used 4 Time(s)
          512 bit SHA512 used 2 Time(s)

 **Unmatched Entries**
    Could not determine IPv4/IPv6 protocol. Using AF_INET: 6 Time(s)
    ECDH curve secp384r1 added: 6 Time(s)
    ERROR: Linux route delete command failed: external program exited with error status: 2: 5 Time(s)
    Failed to extract curve from certificate (UNDEF), using secp384r1 instead.: 6 Time(s)
    Linux ip addr del failed: external program exited with error status: 2: 6 Time(s)
    ROUTE_GATEWAY 62.210.10.1/255.255.255.0 IFACE=eth0 HWADDR=c8:1f:66:c9:61:58: 4 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:32893: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33177: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33201: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33450: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33676: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33901: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:33947: 5 Time(s)
    TLS Error: cannot locate HMAC in incoming packet from [AF_INET]62.210.10.20:34151: 5 Time(s)
    do_ifconfig, tt->did_ifconfig_ipv6_setup=0: 6 Time(s)
    library versions: OpenSSL 1.0.1e-fips 11 Feb 2013, LZO 2.03: 6 Time(s)

Please advise where I am making mistake?

Best regards

**Comment by Nyr** [comment]
Maybe you are not making a mistake and your network is filtered/censored somewhere. Try connecting from a different network and use Shadowsocks if you are on a censored network.

**Comment by Raakh** [comment]
You are absolutely right. I am on highly censored network. Shadow socks is good suggestion. I shall try to configure it asap

Thanks from the bottom of my heart

**Comment by Nyr** [comment]
@Raakh the email you got is probably related to [this](https://lwn.net/Articles/741878/), which has been making the news recently and certainly unrelated to my work. Please do not spread misinformation and take some time to learn before making such accusations.

In case anyone finds this issue in the future: before editing his comment, @Raakh confirmed that he was indeed connecting from a "highly censored network" and that was very likely the cause of his initial issue.

**Comment by Pofilo** [comment]
> You are absolutely right. I am on highly censored network. Shadow socks is good suggestion. I shall try to configure it asap
> Thanks from the bottom of my heart

Here is the message not edited.

**Comment by Raakh** [comment]
Sorry for inconvenience

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
