### ISSUE TITLE
How to allow client-to-client Communications - Open VPN server install on Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by gaurishpatil** [Nyr/openvpn-install#402]
Installed Open VPN server using  `wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh` on Ubuntu 16.04.03 LTS. Server created in DigitalOcean Cloud.

Created two client,  **Client-1**: 10.8.0.2 and  **Client-2**: 10.8.0.3 

My `/etc/rc.local ` looks like,

```
#!/bin/sh -e
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to [ServerPublicIP]
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
exit 0
```

`/etc/openvpn/server.conf` look like,

```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS [ServerDNS]"
push "dhcp-option DNS [ServerDNS]"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
```

But, **Client-1**: 10.8.0.2 cannot ping **Client-2**: 10.8.0.3 , timed out.

Even my **Server**: 10.0.8.1 not able to ping any client.

Tried adding `client-to-client`  at the bottom of `server.conf` next line to `crl-verify crl.pem` using nano, doesn't work.

**Comment by Nyr** [comment]
This is an issue in your end.

Probably your clients are firewalled.

**Comment by gaurishpatil** [comment]
Thanks @Nyr , yes , eventually find out it's windows firewall issue.  
Followed steps to create firewall, which allowed client to client communication 
https://superuser.com/questions/1106907/windows-firewall-doesnot-allow-to-connect-from-vpn
