### ISSUE TITLE
Connect and works after a minute or two

### ISSUE THREAD

**Issue by rjberm** [Nyr/openvpn-install#403]
I have followed the step by step for the installation. I have Ubuntu 16.04.1 x64 server through Digital ocean. 

The initial installation was flawless. Then, after a few days, it connects fast, but it takes a 1-2 minutes until it starts working. Then, I might disconnect, and reconnect, but this time might work immediately. 

I feel it might have to do with the iptables. Any thoughts?

`iptables -L -t nat`

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:"public ip"
```

I have masked my public ip address for private reasons but I do put the correct public ip address.

**Comment by Nyr** [comment]
iptables are fine.

Double-check that there isn't a conflict with a local DNS server, with IPv6 or even with the default gateway, that's the only explanations I can think of for that.

I know that this is just general advice, but not much more that I can guess from here. If you are still unable to troubleshoot your issue, my suggestion is that you try asking for support in the OpenVPN forums.
