### ISSUE TITLE
Internet not working

### ISSUE THREAD

**Issue by francescodesiderio** [Nyr/openvpn-install#404]
Hi,
congratulations for the script because it's fantastic. 

I have only one problem: after the installation, connecting with a windows client to vpn, I can access the office server, but the clients no longer goes on the internet. How should I proceed? 
Many Thanks

**Comment by lukebarone** [comment]
I just want to point out that this issue is lucky number 404, and it is
quite fitting for the situation

**Comment by Nyr** [comment]
I assume that your server is behind a NAT? Likely you did set up that the wrong way. Take a look at https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353
