### ISSUE TITLE
Connected via tunnel but no packets

### ISSUE THREAD

**Issue by CapsosUk** [Nyr/openvpn-install#405]
After installing on Ubuntu server (Hp Micro Server) I get a connection whilst on and off my local network but if I ping 8.8.8.8 all packets are lost. 

Firewall 
Ports
And router all checked. But still nothing.

**Comment by Nyr** [comment]
You likely did set up the NAT incorrectly: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

**Comment by CapsosUk** [comment]
Ok I will double check that. I'm still learning and want sure if I even had NAT but on install it believes I did.
