### ISSUE TITLE
Include information about IPv6 enabled clients

### ISSUE THREAD

**Issue by InAnimaTe** [Nyr/openvpn-install#407]
If a client has ipv6 enabled, there is the possibility of some traffic utilizing that stack instead of the VPN. Since this (awesome) script doesn't support ipv6 VPN and most VPS' don't have proper ipv6 support for, users should be made aware of this fact and given details on how to fix it.

* Disable IPv6 [entirely](https://askubuntu.com/a/441122) (kinda meh tbh)
* Install a switcher [script](https://askubuntu.com/a/983655) that toggles ipv6 when you connect to the VPN

Just want to propose this fact and suggest info+links are put in the `README` to make people aware.

**Comment by Nyr** [comment]
This is a client-side issue and both of the proposed solutions are bad. Routing matters should be resolved within the routing layer, disabling IPv6 is an overkill which can have unintended consequences.

I can't add a list of tutorials for every operating system and every kind of setup which a user could have. Anyone having this issue should research the best solution for his situation elsewhere.

**Comment by InAnimaTe** [comment]
Ok. Just thought a quick mention in the readme at least would be helpful. nbd.
