### ISSUE TITLE
Fix for OpenVZ

### ISSUE THREAD

**Issue by RobertoD91** [Nyr/openvpn-install#409]
Hi, in an OpenVZ instance (on lavavps) I have to do these extra steps to make openvpn work:

-run the script
-delete "LimitNPROC=10" from /lib/systemd/system/openvpn@.service
-systemctl enable openvpn@server
-systemctl start openvpn@server

I'm not an expert, I do not know if it's a bug but I wanted to report it

PS:this is the error:

> vps ovpn-server[7697]: OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
gen 27 12:49:04 vps-bob ovpn-server[7697]: library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
vps ovpn-server[7697]: daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
vps ovpn-server[7697]: Exiting due to fatal error
vps systemd[1]: openvpn@server.service: Control process exited, code=exited status=1
vps systemd[1]: Failed to start OpenVPN connection to server.

**Comment by Nyr** [comment]
This is a well known problem which has been discussed in length, see #206 for example.

The issue is in the hands of package maintainers but they refuse to address it.
