### ISSUE TITLE
Daemon() failed or unsupported: Resource temporarily unavailable

### ISSUE THREAD

**Issue by SkywalkerFR** [Nyr/openvpn-install#410]
Hi, sorry to ask help but i've a problem with our script, i've tested on seveal server and i've always the same error : 

`Tue Jan 30 01:20:13 2018 OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Tue Jan 30 01:20:13 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Tue Jan 30 01:20:13 2018 daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
Tue Jan 30 01:20:13 2018 Exiting due to fatal error`

What causes it ?
Tanks ;)

**Comment by Nyr** [comment]
Well known issue with the systemd service file, see #206.

And next time try using a search engine.

**Comment by xiltepin** [comment]
Why is it so hard to place the answer here? This page was the first result of my search engine.

commenting out the LimitNPROC line in /lib/systemd/system/openvpn@.service fixes it.
