### ISSUE TITLE
Getting access is denied?

### ISSUE THREAD

**Issue by LewisHolt** [Nyr/openvpn-install#412]
I've ran the script sucessfully, opened the firewall ports and reloaded, made sure that the service is running on the VPS also, but I'm getting an access is denied message when I read the log on the client.

> Wed Jan 31 04:03:36 2018 NOTE: FlushIpNetTable failed on interface [2] {5393BA56-211D-461C-B3A1-4C84F3EBA010} (status=5) : Access is denied.  
Wed Jan 31 04:03:36 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Jan 31 04:03:36 2018 MANAGEMENT: >STATE:1517371416,ASSIGN_IP,,10.8.0.2,,,,
Wed Jan 31 04:03:36 2018 Block_DNS: WFP engine opened
Wed Jan 31 04:03:36 2018 Error in add_block_dns_filters(): add_sublayer: failed to add persistent sublayer : Access is denied.   [status=0x5]
Wed Jan 31 04:03:36 2018 MANAGEMENT: Client disconnected
Wed Jan 31 04:03:36 2018 Blocking DNS failed!
Wed Jan 31 04:03:36 2018 Exiting due to fatal error

It worked in the past, but that was a previous VPS, I have no idea why its not working. :/

**Comment by Nyr** [comment]
- Try running OpenVPN as an administrator.
- Use the official OpenVPN client instead of whatever you are using.

This is a client-side issue, nothing to do with the script.

**Comment by zer0byte** [comment]
This Works! Thanks!

**Comment by ramitpanwar** [comment]
This works, running as admin, thanks :)

**Comment by fquero47** [comment]
I almost had a Heart Attack. this solved the issue thanks
