### ISSUE TITLE
ipv6 support ?

### ISSUE THREAD

**Issue by guakamole** [Nyr/openvpn-install#414]
Hello,

Thanks for `openvpn-install.sh` :+1: 

Everything seems to work out of the box, except for ipv6. I am a Debian user.

    debian stretch
    openvpn 2.4.0
    network-manager-openvpn-gnome 1.2.8-2
    openvpn-install.sh github-3345224 

No matter how I use the the `.ovpn` file generated (right from the CLI or via Network Manager), only the ipv4 traffic seems to be routed through my vpn. When checking https://wtfismyip.com , for instance, the ipv4 is the VPN's one, the ipv6 is my real ipv6 address.

Is there anything that needs to be done in order to support dual stack?

(my server does have an ipv6)

**Comment by Nyr** [comment]
The script does not support IPv6.

See #242 if you want to enable IPv6 manually or just more information on the matter.
