### ISSUE TITLE
TUN?

### ISSUE THREAD

**Issue by oNeUpKid88** [Nyr/openvpn-install#415]
Not sure but when I run the script, I'm getting:

The TUN device is not available
You need to enable TUN before running this script

What am I msising ?

**Comment by Nyr** [comment]
If only you tried writing “enable TUN” into a search engine before opening an issue...

**Comment by oNeUpKid88** [comment]
I have however, I suppose I could have wasted everyone's time and comment block suggesting to create a search.. ..
