### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by pieterdorenbos** [Nyr/openvpn-install#416]
hey does someone knows werhe i can find the user his logs or when he is using the vpn ?

**Comment by Nyr** [comment]
`grep ovpn /var/log/syslog`

**Comment by pieterdorenbos** [comment]
what is the best udp / tcp port to run the vpn special for gaming

**Comment by Nyr** [comment]
For gaming you should use UDP, port number doesn't matter.

But this is not the right place to get support, so please go elsewhere if you have further questions unrelated to the script.

**Comment by pieterdorenbos** [comment]
okay nyr i will do and im using your script thx for the support
