### ISSUE TITLE
More problems

### ISSUE THREAD

**Issue by PwnKitteh** [Nyr/openvpn-install#417]
Hi Nyr, 
It's me again. I'm sorry, but I don't know where else to seek help, and I think it might be this script this time. I ran the script on an AWS EC2 Instance, hoping that it would set up an openvpn server for me. I scp'd the resulting .ovpn file to my machine, and attempted to connect. When I attempted this, I got the following error: 
`Wed Feb 14 19:52:17 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Feb 14 19:52:17 2018 TLS Error: TLS handshake failed
Wed Feb 14 19:52:17 2018 SIGUSR1[soft,tls-error] received, process restarting
Wed Feb 14 19:52:17 2018 Restart pause, 10 second(s)
`
I know for a fact that the network connectivity is fine, because amazon wouldn't let their datacenter's internet go down and my home internet is working fine. I think it has to be a misconfiguration in the firewall rules ( I could be wrong) but I don't know where to start. Is there something the script might have missed when setting up the firewall? I put in the internal and external IP of the server, so I was hoping it would work. This is my 3rd time attempting the install script on this server, after numerous installs, uninstalls, and reinstalls, it's still not working. I haven't even finished part 1 of my project: setting up the open vpn server. 

Anyways, thanks for the help. Sorry for bugging you again, but I don't really have any experience with openvpn and the manuals are rather confusing for the command line.

**Comment by Nyr** [comment]
> I know for a fact that the network connectivity is fine

Don’t be so sure, it looks like a connectivity issue. EC2 has a firewall, so be sure to add exceptions for OpenVPN.
