### ISSUE TITLE
Options error: Bad protocol: '11'.

### ISSUE THREAD

**Issue by Nurlan199206** [Nyr/openvpn-install#418]
subj problem, do you know how to fix this problem?

**Comment by Nyr** [comment]
Easy to fix, see [here](https://github.com/Nyr/openvpn-install/issues/514#issuecomment-419973969).

**Comment by KalleVuorjoki** [comment]
Maybe would benefit from input validation? I ended up using https://github.com/kylemanna/docker-openvpn instead.

**Comment by vahidshirvani** [comment]
I have the script running in docker. Please see https://github.com/vahidshirvani/openvpn-install
