### ISSUE TITLE
Module ip_tables not found. in CentOS 6 (Godaddy VPS)

### ISSUE THREAD

**Issue by sumancvb** [Nyr/openvpn-install#424]
I tried to run the script, but it gives following error. Please help. I also tried to set openvpn in Ubuntu 16.04 VPS. It gives same error. But it works on DigitalOcean VPS. So I think the problem is with GoDaddy VPS iptables.

    FATAL: Module ip_tables not found.
    iptables v1.4.7: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
    Perhaps iptables or your kernel needs to be upgraded.

Thanks in advance.

**Comment by Nyr** [comment]
Contact GoDaddy and ask if they can enable iptables for your VPS, this has nothing to do with my script.

If they refuse to help with this, I would suggest to find a better VPS provider.

**Comment by sumancvb** [comment]
Thanks.
I changed my VPS provider.
