### ISSUE TITLE
Autostart on Debian

### ISSUE THREAD

**Issue by casperstorm** [Nyr/openvpn-install#426]
First of all let me just thank you for this amazing script. This helped me get it all running and working 🥇 

However, each time I restart the container (Debian GNU/Linux 9) OpenVPN needs to be started again.
What I have been doing so far is:

```
vpn@vpn:~$ sudo systemctl enable openvpn@server.service
vpn@vpn:~$ sudo systemctl start openvpn@server.service
```

Could someone help me? 🙏

**Comment by Nyr** [comment]
This must be a problem in your side, maybe related to OpenVZ.

The default script setup will run the service on startup, so if that is not being the case something must be wrong. Additionally, `systemctl enable` should enable the service to run at startup if it was disabled for some reason.

My suggestions:
- Check the logs, likely the service is trying to start the VPN server but is failing for some reason.
- Unlikely that this is the cause of your problem, but still worth checking: https://github.com/Nyr/openvpn-install/issues/206

**Comment by casperstorm** [comment]
Thanks!
I differently think it's on my end. It's however a all clean container with nothing else than the script and the newest Debian version. Where would I find the logs so i can study them?

**Comment by Nyr** [comment]
`systemctl status openvpn@server.service`

If you need longer output:
`grep ovpn /var/log/syslog`

**Comment by casperstorm** [comment]
I solved the issue by looking into the log file: `grep ovpn /var/log/syslog`

```
vpn ovpn-server[96]: ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
vpn ovpn-server[96]: Exiting due to fatal error
```

I am using Proxmox, so i need to open TUN/TAP manually which is a systemctl script on its own, so the problem was that the `openvpn@server.service` was run before TUN/TAP was correctly setup. Solved it with a `Before=`.

Maybe this will help others, in the future.
