### ISSUE TITLE
What if server IP changes?

### ISSUE THREAD

**Issue by ivazin** [Nyr/openvpn-install#427]
Old IP stays hardcoded in:
1) client-common.txt
2) /etc/rc.local (I mean this rule "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 111.111.111.111")

Looks like not the best behavior. May be it's possible to offer automatic server ip-address replacement and update?

**Comment by Nyr** [comment]
A dedicated IP in a server should not change.

If the IP is dynamic, you should use an updated domain name (Dynamic DNS) for client configurations (`client-common.txt`) and masquerade instead of SNAT (`/etc/rc.local)`.

The change is easy if you need to do it, but out of the scope of this script.

**Comment by maxisme** [comment]
@Nyr do you know what the actual params I should be setting in those files?
I am guessing remove the `remote` option with `...` in `/etc/openvpn/client-common.txt`. Also my `/etc/rc.local` is empty so what should I be adding to specify `masquerade` opposed to SNAT?

**Comment by Nyr** [comment]
@maxisme don't remove the `remote` parameter, it is needed. If you have a dynamic IP, my guess is that the server is probably behind NAT. If that's the case, you don't need to change anything in `/etc/openvpn/client-common.txt`.

If your `/etc/rc.local` file is empty, very likely your system is using firewalld and a rule like this was added yo your firewall:
`firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP`

That rule could be removed with the following commands:
`firewall-cmd --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP`
`firewall-cmd --permanent --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP`

Once that's done, you would need to add a MASQUERADE rule according to your needs, something like this:
`firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j MASQUERADE -o eth0`
`firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j MASQUERADE -o eth0`

And of course, edit the client configuration files specifying the new IP address.
