### ISSUE TITLE
Server Migration / Portability Question. Not related to Script

### ISSUE THREAD

**Issue by wicknet** [Nyr/openvpn-install#440]
@Nyr - Now that you’ve helped me create 50+ OpenVPN clients for employees in a jiffy (THANKS!), I want to take our installation one step further and ensure that the need to re-create and more importantly, re-distribute, clients is not faced anytime soon.

Currently our OpenVPN setup works off udp/1194 on a physical server with a static public IP, and it’s in daily use by employees to connect back to the office network to access a secure database. Superb speed, instant access, highly secure, and with no passwords to remember. Everyone loves it.

Ideally, I’d like to setup and keep in reserve a second server with a different IP but identical certs/keys/clients, so that if the physical server was to ever go down (power, bad drive), I could simply bring the virtual server online, change the NAT to point to it, install available updates, and we’re back in business in literally minutes without needing to notify and email a new VPN client again to 50 different folks.

This would be easier if we were running VSphere, so I could simply restore a backup of the primary virtual server to another host via Veeam if disaster struck, but budgets are tight.

Is that even doable without cloning (using Acronis or clonezilla)? Many thanks for any/all advise.

**Comment by Nyr** [comment]
Please, avoid opening further issues seeking general support. I suggest the OpenVPN forums for that, this is not the right place.

That said, in your case it is way easier than you think:
- You can configure clients for failover with multiple server IP addresses. That way you could have zero downtime if required.
- Alternatively, and if the secondary server needs to have a different, unknown at this time, IP address, you should use domain name(s).
- Once you have that done, just backup the server configuration from `/etc/openvpn`. That will include all the needed certificate stuff. When setting up a new server, you can just restore the backed up configuration and certificates.

**Comment by wicknet** [comment]
Understood. Apologies for posting this query under Issues.

Will try out your suggestion on restoring /etc/openvpn on another server.
