### ISSUE TITLE
OpenVPN Doesn't Start Upon VPS/Droplet Reboot

### ISSUE THREAD

**Issue by michaelarida** [Nyr/openvpn-install#441]
This has happened on every droplet I provisioned with this script (I am using CentOS 7.4). It works great however it fails to work once the droplet it is running on is rebooted. Everything works great until you reboot the droplet, then everything goes kaput. 

Looks like the service is never even enabled?
You can enable it with: systemctl enable openvpn-server@server.service
But that doesn't do much good as it actually fails to start even if its enabled.

It looks like the actual OpenVPN service may be starting but it won't allow any connections after the host being rebooted.

**Comment by michaelarida** [comment]
Looks like it might be running but client is unable to connect.

nobody     945  0.0  0.3  74956  3984 ?        Ss   19:01   0:00 /usr/sbin/openvpn --cd /etc/openvpn/ --config server.conf

**Comment by michaelarida** [comment]
Sat Mar 17 15:02:52 2018 MANAGEMENT: >STATE:1521316972,WAIT,,,,,,
Sat Mar 17 15:03:52 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 17 15:03:52 2018 TLS Error: TLS handshake failed
Sat Mar 17 15:03:52 2018 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 17 15:03:52 2018 MANAGEMENT: >STATE:1521317032,RECONNECTING,tls-error,,,,,
Sat Mar 17 15:03:52 2018 Restart pause, 40 second(s)

**Comment by Nyr** [comment]
Problem is in your side. The service is likely running and this is a connectivity issue.

Check your firewalls and check that your network is not censored.

**Comment by michaelarida** [comment]
This was due to faulty entries in sysctl.conf.
