### ISSUE TITLE
Finer-grained params?

### ISSUE THREAD

**Issue by silverdr** [Nyr/openvpn-install#448]
I am in a situation where some (not really old but apparently employing somewhat older config) clients do not allow any fine-grained configuration. For example I have only GUI access and GUI does not allow setting SHA512, SHA256 being the highest. Also, and much more problematic, it seems internally configured with ns-cert-type and therefore authentication always fails. The default setup therefore doesn't work for those clients at all and I end up redoing everything manually. Wouldn't it be good to give somewhat finer-grained control over the setup parameters, while obviously keeping the sensible and recommended defaults? That would on one hand keep the UX smooth, while allowing those in specific needs to still have the setup tremendously simplified.

**Comment by Nyr** [comment]
If your client does not support those options, it must be very outdated. The script is already very conservative, but `ns-cert-type` has been deprecated for years and will be removed soon.

You can of course change whatever you want in the script to make it work, but the right path would be to use an updated client.

**Comment by silverdr** [comment]
I perfectly understand that. Those are embedded devices with recent (2017) firmware. OpenVPN there is also relatively new. It's just that the GUI is not up to date or nobody thought about verifying stuff with modern defaults. I already managed to fix the problems on my side. I was more or less asking if you are interested in having this kind of options. If not, no problem either. It's been a bumpy ride with even the logs being accessed only through the GUI but it seem to work now.
