### ISSUE TITLE
UFW Support

### ISSUE THREAD

**Issue by StudioLE** [Nyr/openvpn-install#45]
It took me a while to figure out that additional configuration is required to get OpenVPN working with UFW enabled. You may want to consider adding an FAQ into the README with the following steps.

[The following steps are borrowed from [How To Set Up an OpenVPN Server on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04)]

This tutorial will use OpenVPN over UDP, so ufw must also allow UDP traffic over port 1194. [Set this to your preferred port]

```
ufw allow 1194/udp
```

The ufw forwarding policy needs to be set as well. We'll do this in ufw's primary configuration file.

```
vim /etc/default/ufw
```

Look for `DEFAULT_FORWARD_POLICY="DROP"`. This must be changed from `DROP` to `ACCEPT`. It should look like this when done:

```
DEFAULT_FORWARD_POLICY="ACCEPT"
```

Next we will add additional ufw rules for network address translation and IP masquerading of connected clients.

```
vim /etc/ufw/before.rules
```

Add the lines between `# START OPENVPN RULES` and `# END OPENVPN RULES` to make the top of your `before.rules` file look like below. 

```
#
# rules.before
#
# Rules that should be run before the ufw command line added rules. Custom
# rules should be added to one of these chains:
#   ufw-before-input
#   ufw-before-output
#   ufw-before-forward
#

# START OPENVPN RULES
# NAT table rules
*nat
:POSTROUTING ACCEPT [0:0] 
# Allow traffic from OpenVPN client to eth0
-A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE
COMMIT
# END OPENVPN RULES

# Don't delete these required lines, otherwise there will be errors
*filter
```

With the changes made to ufw, we can now enable it. Enter into the command prompt:

```
ufw reload
```

**Comment by Nyr** [comment]
First of all, thanks for the guide, I hope it will be useful to someone in your situation.

Second, this script is intended for default Debian/Ubuntu/CentOS images, if the user wants to use a firewall we assume he understands how to add exceptions. Officially supporting all the common firewalls and custom setups would be crazy ;)
