### ISSUE TITLE
Feat request: Add 1.1.1.1 (cloudflare) DNS resolvers as an option ...

### ISSUE THREAD

**Issue by just4t** [Nyr/openvpn-install#450]
Hi, Please consider to add the **1.1.1.1** and **1.0.0.1** (cloudflare) **DNS resolvers** as an option available at installation level.
- More info. about:  https://1.1.1.1/ and [Announcing 1.1.1.1: the fastest, privacy-first consumer DNS service](https://blog.cloudflare.com/announcing-1111/)

**Comment by Nyr** [comment]
This is already available in the latest version of the script.

**Comment by just4t** [comment]
Opps! Thank You! :)
