### ISSUE TITLE
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

### ISSUE THREAD

**Issue by Nixellion** [Nyr/openvpn-install#453]
Hi, I keep getting this error on the client:

```
Apr 23 20:22:11 openvpn[24114]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Apr 23 20:22:11 openvpn[24114]: TLS Error: TLS handshake failed
Apr 23 20:22:11 openvpn[24114]: SIGUSR1[soft,tls-error] received, process restarting
Apr 23 20:22:11 openvpn[24114]: Restart pause, 2 second(s)
Apr 23 20:22:13 openvpn[24114]: Socket Buffers: R=[118784->118784] S=[118784->118784]
Apr 23 20:22:13 openvpn[24114]: UDPv4 link local: [undef]
Apr 23 20:22:13 openvpn[24114]: UDPv4 link remote: [AF_INET]server_ip:6958
Apr 23 20:23:13 openvpn[24114]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Apr 23 20:23:13 openvpn[24114]: TLS Error: TLS handshake failed
Apr 23 20:23:13 openvpn[24114]: SIGUSR1[soft,tls-error] received, process restarting
Apr 23 20:23:13 openvpn[24114]: Restart pause, 2 second(s)
Apr 23 20:23:15 openvpn[24114]: Socket Buffers: R=[118784->118784] S=[118784->118784]
Apr 23 20:23:15 openvpn[24114]: UDPv4 link local: [undef]
Apr 23 20:23:15 openvpn[24114]: UDPv4 link remote: [AF_INET]server_ip:6958
Apr 23 20:24:15 openvpn[24114]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Apr 23 20:24:15 openvpn[24114]: TLS Error: TLS handshake failed
Apr 23 20:24:15 openvpn[24114]: SIGUSR1[soft,tls-error] received, process restarting
Apr 23 20:24:15 openvpn[24114]: Restart pause, 2 second(s)
Apr 23 20:24:17 openvpn[24114]: Socket Buffers: R=[118784->118784] S=[118784->118784]
Apr 23 20:24:17 openvpn[24114]: UDPv4 link local: [undef]
Apr 23 20:24:17 openvpn[24114]: UDPv4 link remote: [AF_INET]server_ip:6958
```

It's the same whether I try to setup client on AsusWRT or Windows. It's the same even if I disable all firewalls on the server and client. Where and what should I look for to fix this issue?

Can it be because of the older kernel that vpscheap.net uses? ( `2.6.32-042stab128.2` )

**Comment by Nyr** [comment]
This problem is unrelated to the issue mentioned by @slrslr.

The logs pasted in this thread suggest that there is a connectivity problem. Firewalls, censored networks or misbehaving NAT are the usual cause of this.

Try switching to TCP instead of UDP, but other than that I suggest the OpenVPN forums if you need further assistance.

**Comment by slrslr** [comment]
@Nixellion hi, have You found the cause of this issue?
I stopped iptables, checked /etc/hosts.deny and i am not aware about other blocking software (did "ps aux").

I tried to connect VPN from my home PC and phone which is using different internet/IP, but can not connect, seeing same status messages as mentioned. What else to try to discover why vpn server is not proceeding?
@Nyr 
Hi, i have new log entries from the server, these are interesting, please can you check it?

> Wed Apr 25 12:00:24 2018 us=309178 myip:44173 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server'
> Wed Apr 25 12:00:24 2018 us=309195 myip:44173 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client'
> RWed Apr 25 12:00:24 2018 us=309288 myip:44173 TLS: Initial packet from [AF_INET]myip:44173, sid=8289a011 23bf96ff
> WRRWWRRWRWed Apr 25 12:00:24 2018 us=513010 myip:44173 **VERIFY ERROR: depth=0, error=CRL has expired: CN=client**
> Wed Apr 25 12:00:24 2018 us=513151 myip:44173 OpenSSL: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:**no certificate returned**
> Wed Apr 25 12:00:24 2018 us=513172 myip:44173 TLS_ERROR: BIO read tls_read_plaintext error
> Wed Apr 25 12:00:24 2018 us=513186 myip:44173 TLS Error: TLS object -> incoming plaintext read error
> Wed Apr 25 12:00:24 2018 us=513198 myip:44173 TLS Error: TLS handshake failed
> Wed Apr 25 12:00:24 2018 us=513312 myip:44173 SIGUSR1[soft,tls-error] received, client-instance restarting

**Comment by Nyr** [comment]
@slrslr in your case, which could be different to @Nixellion's (yes, even if the client logs are very similar), the issue is very clear now that you have provided this log.

Easy solution:
`echo 'EASYRSA_CRL_DAYS=3650' >> /etc/openvpn/easy-rsa/vars`
`/etc/openvpn/easy-rsa/easyrsa  gen-crl`

Looks like your issue was indeed related to #352. I did miss it because the client connection log did not show that, sorry about that.

**Comment by slrslr** [comment]
@Nyr 

Thank you for a previous reply, the result of that command was:

> Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
> WARNING: can't open config file: /root/openssl-1.0.cnf
> 
> Easy-RSA error:
> 
> **The OpenSSL config file cannot be found.**
> Expected location: /root/openssl-1.0.cnf

so i did: cd /etc/openvpn/easy-rsa;/etc/openvpn/easy-rsa/easyrsa gen-crl

result:

> Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
> Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
> 
> **An updated CRL has been created.**
> CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

service openvpn restart

Though nothing changed, can not connect (stuck on: VERIFY OK: depth=0, SN=server). The server log:

> Wed Apr 25 15:27:49 2018 us=501631 myip:43619 Re-using SSL/TLS context
> Wed Apr 25 15:27:49 2018 us=501668 myip:43619 LZO compression initializing
> Wed Apr 25 15:27:49 2018 us=501792 myip:43619 Control Channel MTU parms [ L:1622 D:1184 EF:66 EB:0 ET:0 EL:3 ]
> Wed Apr 25 15:27:49 2018 us=501829 myip:43619 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
> Wed Apr 25 15:27:49 2018 us=501887 myip:43619 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server'
> Wed Apr 25 15:27:49 2018 us=501911 myip:43619 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client'
> RWed Apr 25 15:27:49 2018 us=501978 myip:43619 TLS: Initial packet from [AF_INET]myip:43619, sid=fcef377a f5617903
> WRRWWRRWRWed Apr 25 15:27:49 2018 us=691662 myip:43619 **VERIFY ERROR: depth=0, error=CRL has expired: CN=client**
> Wed Apr 25 15:27:49 2018 us=691856 myip:43619 OpenSSL: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
> Wed Apr 25 15:27:49 2018 us=691952 myip:43619 TLS_ERROR: BIO read tls_read_plaintext error
> Wed Apr 25 15:27:49 2018 us=692037 myip:43619 TLS Error: TLS object -> incoming plaintext read error
> Wed Apr 25 15:27:49 2018 us=692127 myip:43619 TLS Error: TLS handshake failed
> Wed Apr 25 15:27:49 2018 us=692290 myip:43619 SIGUSR1[soft,tls-error] received, client-instance restarting

head /etc/openvpn/server.crt

> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number: 1 (0x1)
>     Signature Algorithm: sha256WithRSAEncryption
>         Issuer: CN=ChangeMe
>         Validity
>             Not Before: Oct 24 19:30:29 2017 GMT
>             Not After : Oct 22 19:30:29 **2027** GMT
>         Subject: CN=server

Do i have to somehow recreate .ovpn file/certificate please?

**Comment by Nixellion** [comment]
Here's my server log. Since I wrote my first post I switched to OpenVPN Access Server (the one with webui), and from Ubuntu to CentOS (because it uses much much less RAM), but client-side error is the same.

Here's server-side log tail: 

```
2018-04-25 09:04:56-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:04:56 2018 213.141.150.28:49179 TLS_ERROR: BIO read tls_read_plaintext error'
2018-04-25 09:04:56-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:04:56 2018 213.141.150.28:49179 TLS Error: TLS object -> incoming plaintext read error'
2018-04-25 09:04:56-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:04:56 2018 213.141.150.28:49179 TLS Error: TLS handshake failed'
2018-04-25 09:04:56-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:04:56 2018 213.141.150.28:49179 SIGUSR1[soft,tls-error] received, client-instance restarting'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 TLS: Initial packet from [AF_INET]213.141.150.28:35450, sid=9b816111 c1ea7231'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 OpenSSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 TLS_ERROR: BIO read tls_read_plaintext error'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 TLS Error: TLS object -> incoming plaintext read error'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 TLS Error: TLS handshake failed'
2018-04-25 09:05:57-0400 [-] OVPN 10 OUT: 'Wed Apr 25 13:05:57 2018 213.141.150.28:35450 SIGUSR1[soft,tls-error] received, client-instance restarting'
```

**Comment by Nyr** [comment]
@slrslr paste the output of this:
`openssl crl -in /etc/openvpn/easy-rsa/pki/crl.pem -text`

@Nixellion yours is not a problem with the script, so please seek help in the OpenVPN forums or elsewhere. Looking at the provided log, your router is very likely running a very old OpenVPN client or TLS library and the server expects better.

**Comment by slrslr** [comment]
@Nyr hi, **[here](https://pastebin.com/YbEEuxNe)** is the output

**Comment by slrslr** [comment]
@Nyr your commands made the client to connect. BUT interesting is that apparently no network traffic go thru (websites not loading...) when i am connected to this particular VPN server. I tried on two devices with different IPs. The server log says:

PID_ERR replay-window backtrack occurred [1] [SSL-0] [0_00000000000000000000000000000000000000000000000000000000000000] 0:140 0:139 t=1524684391[0] r=[-4,64,15,1,1] sl=[52,64,64,528]
...
PID_ERR large diff [85] [SSL-0] [0_______________________________________________________________] 0:16656 0:16571 t=1524684435[0] r=[-3,64,15,108,1] sl=[0,64,64,528]
AEAD Decrypt error: bad packet ID (may be a replay): [ #16571 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

**[Here](https://pastebin.com/nviaZSNi)** i posted more detailed client & server log if you need, i would be grateful if you can take a look and advise how to proceed?

**Comment by Nyr** [comment]
@slrslr try connecting over TCP and see if that works.

Other than that, I suggest the OpenVPN forums if you need further troubleshooting on issues unrelated to the script.

**Comment by slrslr** [comment]
No, TCP not worked, i asked on the forums as suggested, but no reply so far, so i
run Nyr OpenVPN install script and selected to uninstall OpenVPN.
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
Then installed again & i can connect.

**Comment by absispat** [comment]
Change the Protocol on the Pritunl server config to tcp from udp and keep the DNS server blank

Restart the server
