### ISSUE TITLE
VERIFY OK: depth=0, CN=server; TLS Error: TLS key negotiation failed to occur

### ISSUE THREAD

**Issue by slrslr** [Nyr/openvpn-install#454]
Hello, yesterday i seen following status when trying to connect OpenVPN server from my Windows PC:

> Mon Apr 23 21:07:14 2018 VERIFY OK: depth=1, CN=ChangeMe
> Mon Apr 23 21:07:14 2018 VERIFY KU OK
> Mon Apr 23 21:07:14 2018 Validating certificate extended key usage
> Mon Apr 23 21:07:14 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> Mon Apr 23 21:07:14 2018 VERIFY EKU OK
> Mon Apr 23 21:07:14 2018 VERIFY OK: depth=0, CN=server
> Mon Apr 23 21:08:14 2018 **TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)**
> Mon Apr 23 21:08:14 2018 TLS Error: TLS handshake failed
> Mon Apr 23 21:08:14 2018 SIGUSR1[soft,tls-error] received, process restarting
> Mon Apr 23 21:08:14 2018 MANAGEMENT: >STATE:1524510494,RECONNECTING,tls-error,,,,,

It seemed to be similar to the issue that happened to me some time ago, so i tried to execute commands recommended in that issue: https://github.com/Nyr/openvpn-install/issues/352#issuecomment-368208831
but that not helped.

I am using this old version of the script:
$ ls -l openvpn-install.sh

> -rw-r--r-- 1 root root 14165 **Mar  1  2017** openvpn-install.sh

$ head /etc/openvpn/server.crt

> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number: 1 (0x1)
>     Signature Algorithm: sha256WithRSAEncryption
>         Issuer: CN=ChangeMe
>         Validity
>             Not Before: Oct 24 19:30:29 2017 GMT
>             Not After : Oct 22 19:30:29 2027 GMT
>         Subject: CN=server

$ cat /etc/openvpn/server.conf

> port 1194
> proto udp
> dev tun
> sndbuf 0
> rcvbuf 0
> ca ca.crt
> cert server.crt
> key server.key
> dh dh.pem
> tls-auth ta.key 0
> topology subnet
> server 10.8.0.0 255.255.255.0
> ifconfig-pool-persist ipp.txt
> push "redirect-gateway def1 bypass-dhcp"
> push "dhcp-option DNS 108.235.69.142"
> push "dhcp-option DNS 108.235.69.142"
> keepalive 10 120
> cipher AES-256-CBC
> comp-lzo
> user nobody
> group nobody
> persist-key
> persist-tun
> crl-verify crl.pem

**Comment by Nyr** [comment]
I already replied to your issue yesterday, not sure why you are opening a new one.
