### ISSUE TITLE
errors while installing vpn on ubuntun 16.4

### ISSUE THREAD

**Issue by clarkiris1212** [Nyr/openvpn-install#455]
I am seeing following errors. Is it just me or it is global issue?

Okay, that was all I needed. We are ready to set up your OpenVPN server now.
Press any key to continue...
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Reading package lists... Done
FATAL -> Failed to fork.
Reading package lists... Done
Building dependency tree... Done
iptables is already the newest version (1.6.0-2ubuntu3).
The following additional packages will be installed:
  liblzo2-2 libpkcs11-helper1
Suggested packages:
  resolvconf easy-rsa
The following NEW packages will be installed:
  liblzo2-2 libpkcs11-helper1 openvpn
The following packages will be upgraded:
  ca-certificates openssl
2 upgraded, 3 newly installed, 0 to remove and 179 not upgraded.
FATAL -> Failed to fork.
mv: cannot stat '/etc/openvpn/EasyRSA-3.0.4/': No such file or directory
chown: cannot access '/etc/openvpn/easy-rsa/': No such file or directory
openvpn-install.sh: line 235: cd: /etc/openvpn/easy-rsa/: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
openvpn-install.sh: line 238: ./easyrsa: No such file or directory
openvpn-install.sh: line 239: ./easyrsa: No such file or directory
openvpn-install.sh: line 240: ./easyrsa: No such file or directory
openvpn-install.sh: line 241: ./easyrsa: No such file or directory
openvpn-install.sh: line 242: ./easyrsa: No such file or directory
cp: cannot stat 'pki/ca.crt': No such file or directory
cp: cannot stat 'pki/private/ca.key': No such file or directory
cp: cannot stat 'pki/dh.pem': No such file or directory
cp: cannot stat 'pki/issued/server.crt': No such file or directory
cp: cannot stat 'pki/private/server.key': No such file or directory
cp: cannot stat 'pki/crl.pem': No such file or directory
chown: cannot access '/etc/openvpn/crl.pem': No such file or directory
openvpn-install.sh: line 248: openvpn: command not found
55
Failed to restart openvpn@server.service: Unit openvpn@server.service not found.
cat: /etc/openvpn/easy-rsa/pki/ca.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/issued/client.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/private/client.key: No such file or directory
cat: /etc/openvpn/ta.key: No such file or directory

**Comment by clarkiris1212** [comment]
If I run this part manually it will work

EASYRSAURL='https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.4/EasyRSA-3.0.4.
wget -O ~/easyrsa.tgz "$EASYRSAURL" 2>/dev/null || curl -Lo ~/easyrsa.tgz "$EASYRSAURL"
tar xzf ~/easyrsa.tgz -C ~/
mv ~/EasyRSA-3.0.4/ /etc/openvpn/

**Comment by xnobodyx** [comment]
Hi, did you try to install  script on openvz vds? I have no internet connection. 
ip route show - default dev venet0  scope link

**Comment by Nyr** [comment]
@clarkiris1212 looks like maybe you don't have enough memory. Issue is unrelated to the script itself.

@xnobodyx difficult to troubleshoot with the provided information but yes, script works with OpenVZ. If you VPS is behind NAT, you need to leave the detected private address when asked in the first step of the installation. Then you will be questioned about the public IP. If not behind NAT, check the server firewall.
