### ISSUE TITLE
Allow user to use hostname instead of IP-address in OVPN files even when not NATted

### ISSUE THREAD

**Issue by skobkin** [Nyr/openvpn-install#456]
In the current version user can only choose to use hostname instead of IP if server is NAT'ted.

It would be nice to use hostname to connect to the server. It may help in situations when you need to change server IP for example.  Then you will not be needed to replace all issued OVPN files.

**Comment by Nyr** [comment]
Not possible, it works for NAT because we assume that the internal IP doesn't change, but replacing the interface IP requires additional changes in the iptables/firewalld to work.

**Comment by skobkin** [comment]
Yes. But it requires works on the server. Is is simplier than contact all users and change settings on each device.20:27, April 28, 2018, Nyr <notifications@github.com>:Not possible, it works for NAT because we assume that the internal IP doesn't change, but replacing the interface IP requires additional changes in the iptables/firewalld to work.

**Comment by Nyr** [comment]
I insist: edit `/etc/openvpn/client-common.txt` and replace the IP address with your domain. The script in its current form will set up users using whichever domain is specified there.

The only downside of that approach is that the first used generating during initial install can't have that, but .ovpn can easily be edited or the user revoked.

**Comment by skobkin** [comment]
> I insist

No need to insist. It was accident because I replied by email didn't see my answer in the thread and then replied in the browser. And then email reply was added too :)
