### ISSUE TITLE
OpenVPN gets internet from server

### ISSUE THREAD

**Issue by atuxnull** [Nyr/openvpn-install#457]
Hi. AMAZING script. In 2 clicks we have an openvpn server with clients management. I would like to ask if it is possible to have the clients access the internet from the local connection and from the remote server(openvpn). is it possible to have that as an option in the script please? Now every client by default can access the Internet with the IP of the Openvpn server.

**Comment by Nyr** [comment]
Sorry, this is not a planned feature for the script.
