### ISSUE TITLE
OVPN File

### ISSUE THREAD

**Issue by scouseman** [Nyr/openvpn-install#46]
Thanks for the great script Nyr,  it is quite embarrassing to have to ask this question but I can't find the .ovpn file anywhere, I have done a file scan of my whole system but cant find the file anywhere, can you please advise were the script has  copied the .ovpn file too, its definitely not in /etc/openvpn/easy-rsa/2.0/keys.

Cheers

**Comment by Nyr** [comment]
It will be in `~/client.ovpn`, which most likely translates to `/root/client.ovpn`.
