### ISSUE TITLE
Slow performance.

### ISSUE THREAD

**Issue by exaflare** [Nyr/openvpn-install#465]
I'm here in UAE and now the connection while I'm using openvpn is so slow,
I'm using digitalocean and the server is in singapore.

**Comment by Nyr** [comment]
That's to be expected.

If using Etisalat, try the DO Indian datacenter, but don't expect too much and also they have censorship there. Your best bet should probably be an European ISP which peers directly with Etisalat, but not in DE-CIX (Germany) where their ports are almost always busy. I would try with MIX in Italy. I can suggest this Italian ISP which peers there with Etisalat: http://iwstack.com/

If you are using du, you can also try the DO Frankfurt datacenters, but have low expectations.
