### ISSUE TITLE
client share not work.

### ISSUE THREAD

**Issue by chefjuanpi** [Nyr/openvpn-install#47]
Hi, Congrats is a very nice script, very useful.

I have a problem, 

I try to share a directory from server with the clients in a mixed enviroment server cloud linux, remote clients win and mac, i was installed and configured samba.

I use the script to config openvpn, i write y about share clients. i can connect with every client but I can't view the server, don't appears in the network list. and i can't search or connect the samba directory.

can you help me?

**Comment by Nyr** [comment]
Make sure Samba in the server is listening at the right IP, which should be 10.8.0.1.

The script does allow connectivity to the server by default, so this is not an issue with it.
