### ISSUE TITLE
read TCP_CLIENT: Unknown error (code=10060)/TLS Error: TLS key negotiation failed to occur

### ISSUE THREAD

**Issue by ac130kz** [Nyr/openvpn-install#479]
I've been using your script a lot last 5 months maybe, and even made a fork without encryption and compression to fully utilize the potential speed. The problem is that possibly after a corporate firewall update about a week ago I could not connect as usual using my fork, as it turns out even the latest version of your script is not able to connect. Both UDP and TCP do not connect properly. I know that some people have already come across similar stuff, but maybe you could suggest a solution for me. Could it possibly be a certificate issue? Thank you

UDP:
> Sun Jun 10 11:57:11 2018 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
> Sun Jun 10 11:57:11 2018 Windows version 6.2 (Windows 8 or greater) 64bit
> Sun Jun 10 11:57:11 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
> Sun Jun 10 11:57:11 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
> Sun Jun 10 11:57:11 2018 Need hold release from management interface, waiting...
> Sun Jun 10 11:57:11 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'state on'
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'log all on'
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'echo all on'
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'bytecount 5'
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'hold off'
> Sun Jun 10 11:57:11 2018 MANAGEMENT: CMD 'hold release'
> Sun Jun 10 11:57:11 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Sun Jun 10 11:57:11 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Sun Jun 10 11:57:11 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:57:11 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 11:57:11 2018 UDP link local: (not bound)
> Sun Jun 10 11:57:11 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:57:11 2018 MANAGEMENT: >STATE:1528610231,WAIT,,,,,,
> Sun Jun 10 11:58:11 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 11:58:11 2018 TLS Error: TLS handshake failed
> Sun Jun 10 11:58:11 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 11:58:11 2018 MANAGEMENT: >STATE:1528610291,RECONNECTING,tls-error,,,,,
> Sun Jun 10 11:58:11 2018 Restart pause, 5 second(s)
> Sun Jun 10 11:58:16 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:58:16 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 11:58:16 2018 UDP link local: (not bound)
> Sun Jun 10 11:58:16 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:58:16 2018 MANAGEMENT: >STATE:1528610296,WAIT,,,,,,
> Sun Jun 10 11:59:16 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 11:59:16 2018 TLS Error: TLS handshake failed
> Sun Jun 10 11:59:16 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 11:59:16 2018 MANAGEMENT: >STATE:1528610356,RECONNECTING,tls-error,,,,,
> Sun Jun 10 11:59:16 2018 Restart pause, 5 second(s)
> Sun Jun 10 11:59:21 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:59:21 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 11:59:21 2018 UDP link local: (not bound)
> Sun Jun 10 11:59:21 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 11:59:21 2018 MANAGEMENT: >STATE:1528610361,WAIT,,,,,,
> Sun Jun 10 12:00:21 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:00:21 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:00:21 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:00:21 2018 MANAGEMENT: >STATE:1528610421,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:00:21 2018 Restart pause, 5 second(s)
> Sun Jun 10 12:00:26 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:00:26 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 12:00:26 2018 UDP link local: (not bound)
> Sun Jun 10 12:00:26 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:00:26 2018 MANAGEMENT: >STATE:1528610426,WAIT,,,,,,
> Sun Jun 10 12:01:26 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:01:26 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:01:26 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:01:26 2018 MANAGEMENT: >STATE:1528610486,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:01:26 2018 Restart pause, 5 second(s)
> Sun Jun 10 12:01:31 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:01:31 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 12:01:31 2018 UDP link local: (not bound)
> Sun Jun 10 12:01:31 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:01:31 2018 MANAGEMENT: >STATE:1528610491,WAIT,,,,,,
> Sun Jun 10 12:02:32 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:02:32 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:02:32 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:02:32 2018 MANAGEMENT: >STATE:1528610552,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:02:32 2018 Restart pause, 10 second(s)
> Sun Jun 10 12:02:42 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:02:42 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 12:02:42 2018 UDP link local: (not bound)
> Sun Jun 10 12:02:42 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:02:42 2018 MANAGEMENT: >STATE:1528610562,WAIT,,,,,,
> Sun Jun 10 12:03:42 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:03:42 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:03:42 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:03:42 2018 MANAGEMENT: >STATE:1528610622,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:03:42 2018 Restart pause, 20 second(s)
> Sun Jun 10 12:04:02 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:04:02 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 12:04:02 2018 UDP link local: (not bound)
> Sun Jun 10 12:04:02 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:04:02 2018 MANAGEMENT: >STATE:1528610642,WAIT,,,,,,
> Sun Jun 10 12:05:02 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:05:02 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:05:02 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:05:02 2018 MANAGEMENT: >STATE:1528610702,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:05:02 2018 Restart pause, 40 second(s)
> Sun Jun 10 12:05:42 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:05:42 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 12:05:42 2018 UDP link local: (not bound)
> Sun Jun 10 12:05:42 2018 UDP link remote: [AF_INET]165.227.143.71:1194
> Sun Jun 10 12:05:42 2018 MANAGEMENT: >STATE:1528610742,WAIT,,,,,,
> Sun Jun 10 12:06:42 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sun Jun 10 12:06:42 2018 TLS Error: TLS handshake failed
> Sun Jun 10 12:06:42 2018 SIGUSR1[soft,tls-error] received, process restarting
> Sun Jun 10 12:06:42 2018 MANAGEMENT: >STATE:1528610802,RECONNECTING,tls-error,,,,,
> Sun Jun 10 12:06:42 2018 Restart pause, 80 second(s)

UDP config:
> client
> dev tun
> proto udp
> sndbuf 0
> rcvbuf 0
> remote 165.227.143.71 1194
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> remote-cert-tls server
> auth SHA512
> cipher AES-256-CBC
> comp-lzo
> setenv opt block-outside-dns
> key-direction 1
> verb 3

TCP:

> Sun Jun 10 23:16:47 2018 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
> Sun Jun 10 23:16:47 2018 Windows version 6.2 (Windows 8 or greater) 64bit
> Sun Jun 10 23:16:47 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
> Sun Jun 10 23:16:47 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
> Sun Jun 10 23:16:47 2018 Need hold release from management interface, waiting...
> Sun Jun 10 23:16:48 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'state on'
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'log all on'
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'echo all on'
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'bytecount 5'
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'hold off'
> Sun Jun 10 23:16:48 2018 MANAGEMENT: CMD 'hold release'
> Sun Jun 10 23:16:48 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Sun Jun 10 23:16:48 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> Sun Jun 10 23:16:48 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:16:48 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:16:48 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:16:48 2018 MANAGEMENT: >STATE:1528651008,TCP_CONNECT,,,,,,
> Sun Jun 10 23:16:49 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:16:49 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:16:49 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:16:49 2018 MANAGEMENT: >STATE:1528651009,WAIT,,,,,,
> Sun Jun 10 23:17:13 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:17:13 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:17:13 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:17:13 2018 MANAGEMENT: >STATE:1528651033,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:17:13 2018 Restart pause, 5 second(s)
> Sun Jun 10 23:17:18 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:18 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:17:18 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:17:18 2018 MANAGEMENT: >STATE:1528651038,TCP_CONNECT,,,,,,
> Sun Jun 10 23:17:19 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:19 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:17:19 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:19 2018 MANAGEMENT: >STATE:1528651039,WAIT,,,,,,
> Sun Jun 10 23:17:41 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:17:41 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:17:41 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:17:41 2018 MANAGEMENT: >STATE:1528651061,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:17:41 2018 Restart pause, 5 second(s)
> Sun Jun 10 23:17:46 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:46 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:17:46 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:17:46 2018 MANAGEMENT: >STATE:1528651066,TCP_CONNECT,,,,,,
> Sun Jun 10 23:17:47 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:47 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:17:47 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:17:47 2018 MANAGEMENT: >STATE:1528651067,WAIT,,,,,,
> Sun Jun 10 23:18:08 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:18:08 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:18:08 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:18:08 2018 MANAGEMENT: >STATE:1528651088,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:18:08 2018 Restart pause, 5 second(s)
> Sun Jun 10 23:18:13 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:13 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:18:13 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:18:13 2018 MANAGEMENT: >STATE:1528651093,TCP_CONNECT,,,,,,
> Sun Jun 10 23:18:14 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:14 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:18:14 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:14 2018 MANAGEMENT: >STATE:1528651094,WAIT,,,,,,
> Sun Jun 10 23:18:35 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:18:35 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:18:35 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:18:35 2018 MANAGEMENT: >STATE:1528651115,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:18:35 2018 Restart pause, 5 second(s)
> Sun Jun 10 23:18:40 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:40 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:18:40 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:18:40 2018 MANAGEMENT: >STATE:1528651120,TCP_CONNECT,,,,,,
> Sun Jun 10 23:18:41 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:41 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:18:41 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:18:41 2018 MANAGEMENT: >STATE:1528651121,WAIT,,,,,,
> Sun Jun 10 23:19:02 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:19:02 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:19:02 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:19:02 2018 MANAGEMENT: >STATE:1528651142,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:19:02 2018 Restart pause, 10 second(s)
> Sun Jun 10 23:19:12 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:12 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:19:12 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:19:12 2018 MANAGEMENT: >STATE:1528651152,TCP_CONNECT,,,,,,
> Sun Jun 10 23:19:13 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:13 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:19:13 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:13 2018 MANAGEMENT: >STATE:1528651153,WAIT,,,,,,
> Sun Jun 10 23:19:35 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:19:35 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:19:35 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:19:35 2018 MANAGEMENT: >STATE:1528651175,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:19:35 2018 Restart pause, 20 second(s)
> Sun Jun 10 23:19:55 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:55 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:19:55 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:19:55 2018 MANAGEMENT: >STATE:1528651195,TCP_CONNECT,,,,,,
> Sun Jun 10 23:19:56 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:56 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:19:56 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:19:56 2018 MANAGEMENT: >STATE:1528651196,WAIT,,,,,,
> Sun Jun 10 23:20:17 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:20:17 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:20:17 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:20:17 2018 MANAGEMENT: >STATE:1528651217,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:20:17 2018 Restart pause, 40 second(s)
> Sun Jun 10 23:20:57 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:20:57 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:20:57 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:20:57 2018 MANAGEMENT: >STATE:1528651257,TCP_CONNECT,,,,,,
> Sun Jun 10 23:20:58 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:20:58 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:20:58 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:20:58 2018 MANAGEMENT: >STATE:1528651258,WAIT,,,,,,
> Sun Jun 10 23:21:20 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:21:20 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:21:20 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:21:20 2018 MANAGEMENT: >STATE:1528651280,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:21:20 2018 Restart pause, 80 second(s)
> Sun Jun 10 23:22:40 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:22:40 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
> Sun Jun 10 23:22:40 2018 Attempting to establish TCP connection with [AF_INET]46.101.235.206:443 [nonblock]
> Sun Jun 10 23:22:40 2018 MANAGEMENT: >STATE:1528651360,TCP_CONNECT,,,,,,
> Sun Jun 10 23:22:41 2018 TCP connection established with [AF_INET]46.101.235.206:443
> Sun Jun 10 23:22:41 2018 TCP_CLIENT link local: (not bound)
> Sun Jun 10 23:22:41 2018 TCP_CLIENT link remote: [AF_INET]46.101.235.206:443
> Sun Jun 10 23:22:41 2018 MANAGEMENT: >STATE:1528651361,WAIT,,,,,,
> Sun Jun 10 23:23:03 2018 read TCP_CLIENT: Unknown error (code=10060)
> Sun Jun 10 23:23:03 2018 Connection reset, restarting [-1]
> Sun Jun 10 23:23:03 2018 SIGUSR1[soft,connection-reset] received, process restarting
> Sun Jun 10 23:23:03 2018 MANAGEMENT: >STATE:1528651383,RECONNECTING,connection-reset,,,,,
> Sun Jun 10 23:23:03 2018 Restart pause, 160 second(s)

TCP config:

> client
> dev tun
> proto tcp
> sndbuf 0
> rcvbuf 0
> remote 46.101.235.206 443
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> remote-cert-tls server
> auth SHA512
> cipher AES-256-CBC
> comp-lzo
> setenv opt block-outside-dns
> key-direction 1
> verb 3

**Comment by Nyr** [comment]
> after a corporate firewall update about a week ago I could not connect as usual

I'd say you answered your own question, this hasn't much to do with the script...

**Comment by Nyr** [comment]
If you are trying to connect from Kazakhstan I wouldn't have much hopes of port 443 TCP working. Last I heard there was some MITM going on for HTTPS connections, no idea of the current situation, probably you know more than me.

I suggest to try Shadowsocks instead, is better for this kind of situations. Plain OpenVPN can be blocked easily.

**Comment by ac130kz** [comment]
I tried TCP with 443 and it failed. Seems like there is no easy way to get fast UDP traffic going. Shadowsocks is a good thing to pass http traffic, but no good UDP support yet. Btw are there any other open source vpn solutions like SoftEther (which does not work well for me)? Thank you

**Comment by northpoint412** [comment]
When I run into problems like this its good to know if the server or client files have changed or not. I run linux servers so I check for differences in a saved, Known working server.conf file:
diff -r <current config file>  <saved known working config file>

To me this smacks of port 1194 either not open anymore or not being forwarded properly.

**Comment by Nyr** [comment]
@ac130kz if you want something fast + reliable and OpenVPN is blocked or has issues, Shadowsocks and ShadowsocksR are the way to go. You can try other VPN protocols (L2TP/IPsec, Cisco...) which could or couldn't be filtered, but unfortunately there is no magic solution.

@northpoint412 you should read the issue again, in this case the problem is likely out of the hands of the user.
