### ISSUE TITLE
Linux Mint 18.3 client routing issue

### ISSUE THREAD

**Issue by northpoint412** [Nyr/openvpn-install#480]
Hello Nyr,

I have a remote client running linux Mint 18.3 with Mate desktop. My openvpn server is a centos 7.4 server that works just great with windows clients. However, The client.ovpn file when created and installed via Network Manager (GUI, Import ovpn) causes the system to lockup network wise. I think I have the problem narrowed down to the routing on the client.

client.ovpn file contents (minus the cert stuff):
-----------------------------------------------
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote 71.201.xx.xx 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
comp-lzo
setenv opt block-outside-dns
key-direction 1
verb 3
------------------------------------------------
Routing table before vpn active:

-------------------------------------------------
Kernel IP routing table:
-------------------------------------------------
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.254   0.0.0.0         UG    100    0        0 enp4s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp4s0
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp4s0
--------------------------------------------------

Routing table after activating vpn (connects and locks up networking):

--------------------------------------------------
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.8.0.1        0.0.0.0         UG    50     0        0 tun0
0.0.0.0         192.168.1.254   0.0.0.0         UG    100    0        0 enp4s0
10.0.1.0        10.8.0.1        255.255.255.0   UG    50     0        0 tun0
10.8.0.0        0.0.0.0         255.255.255.0   U     50     0        0 tun0
71.201.xx.xx    192.168.1.254   255.255.255.255 UGH   100    0        0 enp4s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp4s0
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp4s0
--------------------------------------------------
Server.config file contents:

--------------------------------------------------
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1"
push "route 10.0.1.0 255.255.255.0"
push "route 10.8.0.0 255.255.255.0"
# Uncommented the push below will make all default routes go thru vpn server-jdegraw
# push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nobody
persist-key
persist-tun
log-append /var/log/openvpn.log
status openvpn-status.log
verb 3
crl-verify crl.pem
-------------------------------------------------
The server.conf file works fine with windows boxes. I have a feeling its possibly a qwerk in Network Manager? Other info is that the /dev/tun0 is created and does have an I.P. Looks fine there. The client linux box connects to a DSL and we have tested a generated config on a windows 7 pro box on same network - runs fine.

Apologize for the font issues here :)
Thoughts?
Northpoint

**Comment by Nyr** [comment]
Next time please fix the format, it's difficult to read like that.

Looks like you have modified the script configuration, and reading the route table, either there are other changes which you haven't mentioned or your client refuses to comply with the OpenVPN protocol.

Your route table looks fine but weird. The script configuration uses `def1`, which adds two /1 routes instead of a /0 route, which is what you have.

Since this is not a problem with the script. I suggest to:
- Install without modifying the default configuration.
- Use a client/wrapper which respects the OpenVPN protocol. I have zero experience with NetworkManager, don't know if that's the case or not.
- Get further support from the OpenVPN forums, which are the proper place to get support with OpenVPN configuration and the likes.
