### ISSUE TITLE
Access Onion Over OpenVPN

### ISSUE THREAD

**Issue by r00tsyst3m** [Nyr/openvpn-install#482]
**What is Onion Over VPN and why it is important?**

Even though no single relay can see the full picture of what you are doing online, your Internet Service Provider will know that you are using the Tor network to access the Internet, which, in fact, is restricted in the most authoritarian countries.

What is more, any node in the Onion network can be set up and run by anyone on the Internet. In theory, any government could deploy thousands of relays to monitor users’ behavior online.

And since your online traffic is unencrypted at the exit node, there is a slight chance for a request to be associated with an individual user connecting with a real IP address. This can be risky for any political and human right activist, journalist, and blogger, who work and live in censorship-heavy countries.

**Comment by Nyr** [comment]
Not sure what do you exactly want, but if you are requesting to integrate Tor with this OpenVPN installer, that will not happen.
