### ISSUE TITLE
Creating a xor patched version (a suggestion to integrate?)

### ISSUE THREAD

**Issue by ac130kz** [Nyr/openvpn-install#483]
After googling about what possibilities do I have against the improved firewall, I saw [a patch for OpenVPN  2.4.4](https://github.com/clayface/openvpn_xorpatch), which xors the traffic. I tried to change the following lines in your script:
> apt-get update
> apt-get install openvpn iptables openssl ca-certificates -y

To this (which installs tools, required OpenVPN version from the archive, applies the patch, builds and installs):
> apt update
> apt install git autoconf build-essential checkinstall libtool liblzo2-dev libpam0g-dev libssl-dev iptables openssl ca-certificates -y
> wget -O ~/openvpn-2.4.4.tar.gz "https://github.com/OpenVPN/openvpn/archive/v2.4.4.tar.gz"
> git clone https://github.com/clayface/openvpn_xorpatch.git
> tar xvf openvpn-2.4.4.tar.gz -C ~/
> patch -p0 < ~/openvpn_xorpatch/openvpn_xor.patch
> cd ~/openvpn-2.4.4/
> autoreconf -vi
> ./configure
> make
> make install
> cd -

I tested and up until EasyRSA it works fine, but I think something is missing, as now the system says that mv cannot find /etc/openvpn/EasyRSA-3.0.4/ folder. Could you please explain why it happens (installing OpenVPN through apt is creating something or I messed up the dirs, I guess)? As a suggestion, I kindly ask you to create a built-in option for xoring the traffic maybe based on the aforementioned patch (although it is not advised by the OpenVPN guys).

**Comment by Nyr** [comment]
Sorry, this will never be implemented into the script.

If you need support with that, you'll need to get help elsewhere.

My suggestion still stands: use Shadowsocks when possible.
