### ISSUE TITLE
Change key size

### ISSUE THREAD

**Issue by Threefish1024** [Nyr/openvpn-install#492]
Can you add the possibility to choose the size of key? 2048 or 4096.

Thank you

**Comment by wanderleihuttel** [comment]
Hello @Threefish1024.

You can change the file "/etc/openvpn/easy-rsa/easyrsa" and modify teh variable below:

set_var EASYRSA_KEY_SIZE        2048

**Comment by Threefish1024** [comment]
Oh perfect, thank you for the notice, good job!

Il Ven 13 Lug 2018, 21:13 Wanderlei <notifications@github.com> ha scritto:

**Comment by stefancrain** [comment]
This has been covered multiple times in these issues #294 #154 
I did some research on this 3 years ago in #38 - That should be worth looking at.

**Comment by Nyr** [comment]
As @stefancrain mentioned, this has been already discussed.

2048 bit RSA keys are still fine, the situation hasn't changed.

Anyone willing can of course change them via variables, but it's useless.
