### ISSUE TITLE
using subdomain.domain.com for IP returns: iptables v1.4.21: Bad IP address "[host]"

### ISSUE THREAD

**Issue by amrazi** [Nyr/openvpn-install#493]
I am attempting to use a subdomain.domain.com instead of a numeric IP address when asked "First, provide the IPv4 address of the network interface you want OpenVPN listening to."

If I provide subdomain.domain.com, I see the `iptables v1.4.21: Bad IP address "[subdomain.domain.com]" right before the "Finished!"` message. Using the connection with the resulting .ovpn file results in pages not loading (chrome: ERR_NAME_NOT_RESOLVED).

**Comment by cezar97** [comment]
The IP is asking is the network card one aka interface.

**Comment by Nyr** [comment]
Exactly as @cezar97 said.

You can use a subdomain later if your server is behind NAT, but first the installer needs to know the IP address of the interface.
