### ISSUE TITLE
I have done a rewrite to use whiptail

### ISSUE THREAD

**Issue by houghi** [Nyr/openvpn-install#494]
Hello,

I have rewritten the script to use whiptail. Tested on Debian. It makes the asking of questions look a bit nicer.
Not much code has been edited, Please feel free to use it or not.
[ovpn.zip](https://github.com/Nyr/openvpn-install/files/2196028/ovpn.zip)

If you do not use it. No hard feelings.

**Comment by Nyr** [comment]
I actually have a very old version implemented with `dialog`, but never implemented it.

Yours looks nice too, but honestly I have no use for it.
