### ISSUE TITLE
auth-nocache problem

### ISSUE THREAD

**Issue by wswind** [Nyr/openvpn-install#495]
I've got this warning on windows openvpn client:

Thu Jul 19 20:54:35 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

The connection is fine ,but I want to fix this so I've seen this page:
https://support.hidemyass.com/hc/en-us/articles/202720436-Auth-nocache-Warning-in-OpenVPN-connection-log

then I add  'auth-nocache ' in  /etc/openvpn/server.conf
but the warning comes again.

what shall i do to make this warning disappear?

**Comment by cezar97** [comment]
Add it in the ovpn instead.

**Comment by wswind** [comment]
:) ,  the warning is gone .thanks

**Comment by imsina20** [comment]
auth-nocache
