### ISSUE TITLE
Slowness on Mac client

### ISSUE THREAD

**Issue by haidixiansheng** [Nyr/openvpn-install#496]
The connection is fine on windows but very very slow( not even usable) on Mac client. I did a search on google and it seems that the setting of MTU to 1400 will solve the situation. 

Could this be added to the script to solve this situation?

**Comment by Nyr** [comment]
If you think that you need to change it, feel free to try in your setup. Read the OpenVPN manual if you need assistance on how to do it.

The default value is good for most cases, so this doesn't need to be set in the script for everyone.
