### ISSUE TITLE
Windows 7 gives a bad base64 error 

### ISSUE THREAD

**Issue by liveforfree** [Nyr/openvpn-install#50]
When using the generated .ovpn file on windows I got the following error windows PEM_read_bio:bad base64 encode

I have googled around alot and it seems to be that some people got this error with problems with line endings not being unix, I have done everything that was suggested and cannot fix the encoding. Really stuck on what to do about this one

**Comment by Nyr** [comment]
Looks like a problem in your end. Can you please try to download the certificate from the server directly to Windows? Alternatively, you can put it in a .zip to ensure it is not modified.

**Comment by liveforfree** [comment]
I fixed it in the end by recreating the whole file by hand, something is
happening with the unix file endings when taking the generated .ovpn file
over to windows 7. I found several posts about this online from other
users, completely unrelated to this. To fix it you just need to make sure
the file is ASCII character encoding, and for windows the inline certs dont
work so you have to make the ca.cert and ca.key files. Then it's all good.
Thanks again for this superb script, I have donated :)

**Comment by dafx** [comment]
I am having to the problem on Win7-64. liveforfree mentioned

"for windows the inline certs dont work so you have to make the ca.cert and ca.key files"

Can you please give the instructions how to do this exactly? or better yet, build this as an option in the script.

**Comment by liveforfree** [comment]
Ok mate, you simply gotta goto the openvpn directroy on your linux box
where you are running this install shell script and copy out the .ca and
.key files to your local machine, then ensure they reside inside of your
locals openvpn/config directory (same directory the .ovpn fille be)

next inside the .ovpn file that is generated you must remove the inline
<ca> <cert> and <key> tags and put it back to the default samples and also
turn on the tap adapter because it is windows not linux - after that it
worked very well. but yeh certainly cost me a hour or so and alot of energy
figuring out wtf is up with shitty windows.

it's the same story again and again, our elders at microsoft decide to
release a unfinished product and cash out on it - so the shame rains on
their heads really because i have no respect for them and i would spit on
them if i saw them in the street for their pathetic abilities with
computers (not to mention internet explorer)

I hope u got it fixed an i hope windows is over soon cos it truely is the
worst operating system i ever encountered in my life

**Comment by Nyr** [comment]
I am not able to reproduce this on Windows 7 with the current version of OpenVPN. In-line certificates are working fine for me.

**Comment by dafx** [comment]
Here is the screenshot of what I see.

http://content.screencast.com/users/miraxlabs/folders/Jing/media/c4ebbc64-06ff-46fa-bae0-5a0af8040f15/2015-07-06_2148.png

**Comment by Nyr** [comment]
Sorry but I still can't reproduce.

**Comment by liveforfree** [comment]
Lucky you :)

**Comment by dafx** [comment]
I really appreciate what you have done here. But my QA would start screaming if I say "sorry, works for me".

**Comment by Nyr** [comment]
I just said I can't reproduce.

From what I know, this could have nothing to do with the script itself: if someone can help in proving the opposite and I can reproduce the problem, I'll reopen the issue and attempt a fix :)
