### ISSUE TITLE
Is all traffic passing through VPN ? 

### ISSUE THREAD

**Issue by jhagege** [Nyr/openvpn-install#502]
Is it possible to configure only part of the traffic to go through VPN ? 
Is it a configuration on the server side or on all the client keys ? 
Thanks !

**Comment by Nyr** [comment]
The server pusses a route telling the client to forward all the IPv6 traffic.

See `/etc/openvpn/server.conf`:
`push "redirect-gateway def1 bypass-dhcp"`

That could be changed to meet your specific needs, take a look at the OpenVPN documentation.

**Comment by encryptblockr** [comment]
@Nyr 

how do i disable all traffic passing through vpn?
i only want  the vpn traffic only
what do i do to achieve this?
