### ISSUE TITLE
Same installer suggestion but for WireGuard [not openvpn-related at all]

### ISSUE THREAD

**Issue by bykidi** [Nyr/openvpn-install#505]
Hello. More and more times i hear about this WireGuard VPN.
Can you please create the installer for this VPN?

**Comment by Nyr** [comment]
I certainly am following the WireGuard project but at this time is still in early stages, there are not user friendly clients for most platforms, etc...

We'll see in the future.

**Comment by sahand12** [comment]
Hi, isn't this question more relavant now? Do you have any plan to maybe create a similar script for WireGuard as well?

Or maybe some suggestion as to how to go about it?

**Comment by Nyr** [comment]
I am seriously considering it.

I need to push some updates for this project first and hopefully a new WireGuard installer will launch during the next few months.

**Comment by sahand12** [comment]
Thanks for all of your efforts man.
