### ISSUE TITLE
Question About Logging

### ISSUE THREAD

**Issue by JackHyland** [Nyr/openvpn-install#506]
First of all, THANK YOU! This script is a life saver, I was about to write the same thing but then found your GitHub. I was curious if you knew how OpenVPN handles logging on the server side and also if your script could give the option to choose the logging preference during setup. 

Thanks again

**Comment by Nyr** [comment]
By default some basic stuff is logged (a little bit of connection establishment information very useful for troubleshooting and client connection times + IP addresses).

I have no intention in making the user believe that his activities wouldn't be logged if server-side logs are disabled, so I have no plans for implementing that.

If you use a VPN, your activity is being logged at the very least by the server's ISP or the upstreams, no way around that.
