### ISSUE TITLE
TLS Negotiation Failed

### ISSUE THREAD

**Issue by boxintense** [Nyr/openvpn-install#51]
I'm installing the OpenVPN server on CentOS 6 64 bit, and then trying to connect via Windows 8.1 OpenVPN client v2.3.7 (latest as of this writing), but it kept failing during TLS negotiation.

I have turned off every firewall (Windows Firewall and iptables) as well as SPI firewall on the router, but still unavailable.

I have another OpenVPN AS server on different server and this same Windows PC can connect to it, so I assume this isn't a problem within the PC at all. Any advise are welcome...

**Comment by Nyr** [comment]
Looks like a connectivity problem which has nothing to do with the script, until proven otherwise.

Try using the script on a clean image with no firewalls.
