### ISSUE TITLE
write to TUN/TAP error while connecting

### ISSUE THREAD

**Issue by zodiacnet** [Nyr/openvpn-install#512]
Hi there
after the deletion of the comp-lzo parameter on the last commit (#509 ) the clients can connect but fails to perform any action with the next error

> write to TUN/TAP : Invalid argument (code=22)

this is happening on a fresh install using the script, the solution was add comp-lzo to the user.ovpn file

**Comment by Nyr** [comment]
Are you sure that `comp-lzo` isn't present in the client or the server configuration?

You could also try with `comp-lzo no` in both the server.conf and client.ovpn.

This is a problem in your side.

**Comment by zodiacnet** [comment]
Yes I'm sure, as I mentioned, that part was removed from server.conf and ovpn files on the last merge, looks like in a first attempt `comp-lzo` was changed to `comp-lzo no` in both client and server files as you can see on thise commit: 
[https://github.com/Nyr/openvpn-install/pull/509/commits/7d303d3ae53aeafc28441c5707f15bda32c0a93d](url)

 but after that commit theres another one where `comp-lzo` is removed as the commit says "Remove deprecated compression flag for same mitigation effect" commit url: 
[https://github.com/Nyr/openvpn-install/pull/509/commits/29e21843fa6871cbe13be37f4df4dffc9c811f13](url)

there you can see the compression was removed, which is causing connection issues on new installs, is not a problem on my side since the compression flag is removed from both, server and client templates, I know that can be easily fixed including `comp-lzo` con the client.ovpn file but my intention with this issue was inform you that is failling due to those commits

**Comment by Nyr** [comment]
To understand the differences:
- Removing `comp-lzo` will disable compression.
- Using `comp-lzo no` will disable compression, but enable the packet framing used for compression, so it can still be enabled if pushed from the server.

What client software are you using? This is not a problem with the script, but of course if one or more common clients are having issues with this, I will look into a solution.

**Comment by zodiacnet** [comment]
client used: OpenVPN 2.4.4

**Comment by zodiacnet** [comment]
Hello @iProdigy sorry the delay, was checking my files to verify if `comp-lzo` was only on the ovpn file, and confirmed that I've added it to server.conf too (sorry for mention that was only on the ovpn file, probably I forget it after multiple attemps to try to solve the connection), so the parameter was added on both files, I can spin up another server to verify if required

**Comment by Nyr** [comment]
Please, try using `comp-lzo no` instead and let us know.

**Comment by zodiacnet** [comment]
@Nyr @iProdigy just tested with the `comp-lzo no` on both server and client and works, but decided to try replicate the error on a new server, and I was not able to, tested everything without  any change and worked, also tested only sending the vpc traffic over the vpn with out including `comp-lzo` and it also worked, since I was not able to replicate the error  I think something went wrong during the install, sorry for bothering you with this
