### ISSUE TITLE
Google Compute Engine Debian Stretch install error

### ISSUE THREAD

**Issue by SerdarARIKAN** [Nyr/openvpn-install#513]
https://github.com/Nyr/openvpn-install/blob/22adb31b2e0df8a8f019d39a0384d4f7fe011105/openvpn-install.sh#L240

```
root@deploy-server:/etc/openvpn/easy-rsa# ./easyrsa build-server-full server nopass
```
**return this;**
```
Generating a 2048 bit RSA private key
...........................................+++
..........................+++

writing new private key to '/etc/openvpn/easy-rsa/pki/private/server.key.lFZziL3mlM'
-----
Using configuration from ./openssl-easyrsa.cnf
```

**```Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory```**

**```140489198712064:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')```**
**```140489198712064:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:```**

```
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Sep  4 17:55:33 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
```
@Nyr

**Comment by Nyr** [comment]
You can safely ignore that, is an issue with easy-rsa, not with my script.
