### ISSUE TITLE
DNS server does not change on DEBIAN

### ISSUE THREAD

**Issue by lorien** [Nyr/openvpn-install#515]
Just used recent version of `git.io/vpn` script to generate server/client config on debian system.
Server config contains `push "dhcp-option DNS ...` but this settings is not processed on client (on Debian) because there is no
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```
line in client.conf
Is there any reason you have not included this lines into client.conf?

**Comment by Nyr** [comment]
> Is there any reason you have not included this lines into client.conf?

Yes, because that's a Linux-specific issue and would break the client configuration elsewhere.
