### ISSUE TITLE
[enhancement] add option to generate separate ca.crt, client.crt, client.key files

### ISSUE THREAD

**Issue by CristianCantoro** [Nyr/openvpn-install#52]
Hi,

this is a feature requests. Given [this bug of NetworkManager](https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/606365) importing the configuration file (e.g. `client.ovpn`) in NetworkManager on Linux does not work.

The idea is to add an option/request in the script to have all the files already separated. 

## A workaround
Hoping that this is useful to otherrs here's a quick manual workaround.
A workaround is to manually copy-paste the certificates from the configuration file to the respective `ca.crt`, `client.crt` and `client.key` files.
In practice (do not copy the tags, only what is inside):
* everything that is inside  `<ca>...</ca>` -> `ca.crt`
* everything that is inside `<cert>...</cert>`  -> `client.crt`
*  everything that is inside `<key>...</key>`   -> `client.key`

Then add to the config file (`client.ovpn`) the fllowing lines after the corresponding commented paragraph:
```
# SSL/TLS parms.
# See the server config file for more
# description.  It's best to use
# a separate .crt/.key file pair
# for each client.  A single ca
# file can be used for all clients.
ca ca.crt
cert wash.crt
key wash.key
```
(and of course one can delete everything between the tags `<ca></ca>`, `<cert></cert>`, `<key></key>` tags in the original `client.ovpn`).

Add this point you can successfully import the configuration in NetworkManager.

**Comment by Nyr** [comment]
In-line certificates had been the default on OpenVPN-AS for years and I implemented them here after many user requests. Adding a choice for this would be confusing for the less experienced users, .ovpn files are generally easier and more convenient.

https://github.com/Nyr/openvpn-install/commit/2174037768868fefdf6e34150e210cb423974794 is the commit which added in-line certificates. Affected users could use this as a workaround while the maintainers fix the bug.

Thanks for reporting this.

**Comment by CristianCantoro** [comment]
@Nyr, yep... I agree that it makes little sense to change a working program/script/software to address a bug in another.
I hope though that people having trouble with NetworkManager will find this useful.
