### ISSUE TITLE
Successfully connects to VPN server, but no internet access

### ISSUE THREAD

**Issue by awcchungster** [Nyr/openvpn-install#521]
I followed the script (pretty easy to do). Server is running on Ubuntu 18.04 on Azure, and the client is tunnelclick. I made sure the ports are open for UDP 1194. I entered the IP address I want my traffic to bind to as "10.0.0.5", and then separately put in my actual public ip.

From the logs, you can see when I connected to the VPN, because the pings stop working.

Any thoughts on what's going on? I'm happy to upload any config settings, though they should just be from the scripts. 

```
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=122 time=20.008 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=122 time=12.823 ms
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
```

**Comment by Nyr** [comment]
> I entered the IP address I want my traffic to bind to as "10.0.0.5", and then separately put in my actual public ip.

Not sure what internal IP address has Azure assigned you, but I kind of doubt that it is 10.0.0.5. It could be, I don't have experience with Azure.

You need to set up the NAT correctly, see here: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353.

As a rule of thumb, you usually don't need to change the IP address detected by the script in the first prompt.

**Comment by awcchungster** [comment]
The fix for me here was to run this on a new VM. Looks like if you run an older machine, or have some settings already changed, the script breaks.

Thanks, Nyr!
