### ISSUE TITLE
problem - server and two clients

### ISSUE THREAD

**Issue by pabloneruda1** [Nyr/openvpn-install#523]
Hellou, i have problem with server (linux) and 2 clients (windows 7):
ping 1. client -> server - OK
ping 2. client -> server - OK
ping server -> 1. client - OK
ping server -> 2. client - BAD
ping 2. client -> 1. client - OK
ping 1. client -> 2. client - BAD
client-to-client directive added in server.conf
2. client firewall is off
I have no idea where is the problem??

**Comment by Nyr** [comment]
Your problem is likely in the second client side.

And `client-to-client` is not needed for the internal networking to work, read the manual.
