### ISSUE TITLE
Access to http pages blocked?

### ISSUE THREAD

**Issue by jesusgascon** [Nyr/openvpn-install#537]
I've configured openvpn with your script. But I cannot access to internet in all the pages.

As I could check, I can surf in a vpn  client connected to the server, in all the pages https://. But when I try to enter to a http:// page the page is not charged.

Is it right? Is it possible to disable, or config for all the pages to be charged?

I've tryed with an Linux and iOS client and in both cases the result was the same.

**Comment by Nyr** [comment]
This is not a problem or a restriction with the script, the issue must be in your end.
