### ISSUE TITLE
No Internet, ping OK

### ISSUE THREAD

**Issue by Sub-7** [Nyr/openvpn-install#538]
Server Ubuntu 18.04 -> Client W10 Ping OK
Client W10 -> Server Ubuntu 18.04 Ping OK
Server ip forwarding is set to 1
W10 connection ok, symbol is green, no error message

No internet connection!
I missed something?

server.conf
`port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 5
crl-verify crl.pem
`

**Comment by Nyr** [comment]
If your server is behind NAT, take a look at this: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

**Comment by Sub-7** [comment]
Solution for router "Speedport Hybrid" (bundles DSL + LTE)

add in client.ovpn (udp ->1356, tcp -> 1344)

mssfix 1356
or
mssfix 1344
