### ISSUE TITLE
Google Compute Engine Debian Stretch Connection problem

### ISSUE THREAD

**Issue by SerdarARIKAN** [Nyr/openvpn-install#547]
It's not actually a bug with your script. The error is caused by the Google Compute Engine.

I can install OpenVPN seamlessly with your script and connect seamlessly from the client machine to the server. However, the client machine is not connected to the Internet in any way.

I think the problem may be caused by IPTABLES. However, I did not find the right configuration despite the various attempts.

I also found an explanation in the GCE documents (https://cloud.google.com/vpc/docs/advanced-vpc#detailedconnectionwalkthrough) that I think might be relevant.

"The VPC networking rewrites the IP header to declare the instance's external IP address as the source. If the instance has no external IP address, the call is not allowed, and the VPC network drops the packet without informing the sender."

What do you think I can do? Can you help me?

**Comment by Nyr** [comment]
Probably you aren't setting up the NAT correctly. See [here](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353).
