### ISSUE TITLE
Doesn't recognize Amazon version of CentOS.

### ISSUE THREAD

**Issue by mgb1980** [Nyr/openvpn-install#548]
2018-11-27 17:19:12 (20.1 MB/s) - ‘openvpn-install.sh’ saved [14739/14739]

Looks like you aren't running this installer on Debian, Ubuntu or CentOS

  GNU nano 2.9.8                      os-release

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

  GNU nano 2.9.8                    system-release

Amazon Linux release 2 (Karoo)

**Comment by Nyr** [comment]
The script doesn't support Amazon Linux.

Feel free to remove the check and see if it works, maybe it does or maybe it doesn't, but it's not supported and will not be supported.

**Comment by mgb1980** [comment]
Hi, i changed the check here:
elif [[ -e /etc/os-release || -e /etc/redhat-release ]]; then

it looks for **os-release** instead of **centos-release** and then script ran fine.
