### ISSUE TITLE
Set Sane Default Security Settings

### ISSUE THREAD

**Issue by jmstacey** [Nyr/openvpn-install#55]
This is a neat little script. It would be great if it setup some hardened security defaults out of the box. For example:
* limit accepted encryption ciphers to say AES 128 CBC [or 256]
* Limit and order TLS cipher preferences
* Set a TLS auth shared key

There are probably other hardening things that should be done out fo the box as well, but I'm not a security expert. These turned up as acceptable starts from my searching around:

**ciphers:** AES-128-CBC:AES-192-CBC:AES-256-CBC
**auth:** SHA256:SHA1
**tls-ciphers:** DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-RSA-AES128-SHA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA

**Comment by Nyr** [comment]
> Set Sane Default Security Settings

The default settings are sane for the year 2015. They also provide a good compromise between performance and security, while AES-256 certainly doesn't in many CPUs.

> There are probably other hardening things that should be done out fo the box as well, but I'm not a security expert.

No offense, but if you aren't a security expert, you shouldn't be giving security advice. The cyphers discussion has already been had multiple times and is not getting changed. Anyone unhappy, can fork and create a "secure" version of the script with AES-256 and 4096 bit keys or whatever.

**Comment by jmstacey** [comment]
Your script your call of course
