### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by Biologist89** [Nyr/openvpn-install#550]
Hello. Thanks for this great project. I've used your script on multiple servers without any problems but recently I've purchased an Ubuntu 16.04 VPS from Virmach but installation process stucks in below section. I have performed `sudo apt-get upgarde` and `sudo apt-get update` before running the script but still no successful installation.
`Okay, that was all I needed. We are ready to set up your OpenVPN server now.
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:3 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]
Hit:4 http://archive.canonical.com/ubuntu xenial InRelease
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Ign:3 https://download.docker.com/linux/ubuntu xenial InRelease
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [884 k                                                                                                                     B]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [7                                                                                                                     10 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [2                                                                                                                     90 kB]
Fetched 2166 kB in 3s (720 kB/s)
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu xenial InRelease: The fol                                                                                                                     lowing signatures couldn't be verified because the public key is not available:                                                                                                                      NO_PUBKEY 7EA0A9C3F273FCD8
W: The repository 'https://download.docker.com/linux/ubuntu xenial InRelease' is                                                                                                                      not signed.
N: Data from such a repository can't be authenticated and is therefore potential                                                                                                                     ly dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                                                                                                     ils.
Reading package lists... Done
Building dependency tree
Reading state information... Done
iptables is already the newest version (1.6.0-2ubuntu3).
ca-certificates is already the newest version (20170717~16.04.1).
openssl is already the newest version (1.0.2g-1ubuntu4.13).
openvpn is already the newest version (2.3.10-1ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
`

**Comment by Nyr** [comment]
Hard to say what could be happening, but this problem is specific to your system.

Maybe it is going out of memory (unlikely because the process should be killed and apt-get would fail) or probably something else is somehow broken.

I also see that you already have OpenVPN installed. If you are unable to resolve it on your own, I suggest to try in a clean image and there it will work.
