### ISSUE TITLE
Not able to find config certificate

### ISSUE THREAD

**Issue by jtodom04** [Nyr/openvpn-install#554]
Looked it the file in root, wasn't there. Also, (now finding this), I got a 144 as follows. Any help? Thanks. `Job for openvpn@server.service failed. See 'systemctl status openvpn@server.service' and 'journalctl -xn' for details.`

**Comment by Nyr** [comment]
No need to open a new issue.

If you are using OpenVZ or other container technology, see https://github.com/Nyr/openvpn-install/issues/206.

About your client configuration file, it should always be in the user home folder if setup did finish correctly.
