### ISSUE TITLE
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr

### ISSUE THREAD

**Issue by diveyez** [Nyr/openvpn-install#556]
Using configuration from ./safessl-easyrsa.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
140334784730496:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
140334784730496:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:

**Comment by Nyr** [comment]
Duplicate, next time use the search engine.

https://github.com/Nyr/openvpn-install/issues?utf8=%E2%9C%93&q=index.txt.attr
