### ISSUE TITLE
Warn when /usr/share/doc/openvpn missing

### ISSUE THREAD

**Issue by phiresky** [Nyr/openvpn-install#56]
My server had the file `/etc/dpkg/dpkg.cfg.d/01_nodoc` which contained ignore rules for the /usr/share/doc directory. Seems like digitalocean added that file.

This script failed with
```
./vpn: line 239: cd: /usr/share/doc/openvpn*/*ample*/sample-config-files: No such file or directory
gzip: server.conf.gz: No such file or directory
cp: cannot stat ‘server.conf’: No such file or directory
sed: can't read server.conf: No such file or directory
sed: can't read server.conf: No such file or directory
sed: can't read server.conf: No such file or directory
sed: can't read server.conf: No such file or directory
sed: can't read server.conf: No such file or directory
sed: can't read server.conf: No such file or directory```

I think a check if that folder exists with a message about the possible cause would be helpful

Also, it might make sense to add `set -e` to the beginning of the script.

**Comment by Nyr** [comment]
You sure this was done by DigitalOcean? It would be dumb.

I just checked with their following images, none of them had this file:
- Ubuntu 14.04 x64
- Debian 8.1 x64
- CentOS 7 x64

**Comment by phiresky** [comment]
I had Debian 7, and upgraded to Debian 8 yesterday. Might also have been the upgrade process.. And I can't find any information about it either.. weird. It was called `01_nodoc` and looked kind of like this: https://unix.stackexchange.com/questions/128884/can-i-disable-all-man-pages

**Comment by Nyr** [comment]
So it was not a clean image. If someone can reproduce this after dist-upgrading a clean image, let me know and I will reopen the issue.
