### ISSUE TITLE
2 problem on openvz nat vps

### ISSUE THREAD

**Issue by BobZombiE69** [Nyr/openvpn-install#560]
Today i tried this on a fresh NAT openvz VPS ubuntu 16.04
But for me it needs 2 modifications
1-
comment out the LimitNPROC line in /lib/systemd/system/openvpn@.service

2- error: no tun/tap.  even after enabling it in control panel
fix:

cd /dev
mkdir net
cd net
mknod tun c 10 200
chmod 666 tun

**Comment by Nyr** [comment]
1. Known issue, see #551
2. Problem in your side, probably solved by restarting the container after enabling TUN.

Thanks anyway!
