### ISSUE TITLE
win 10 Client route-nopull not working 

### ISSUE THREAD

**Issue by salamander-mh** [Nyr/openvpn-install#561]
I add `route-nopull` to the client config file. However, All the access will use VPN. There are some errors in the log:
```
Thu Dec 27 10:15:14 2018 Options error: option 'dhcp-option' cannot be used in this context ([PUSH-OPTIONS])
Thu Dec 27 10:15:14 2018 Options error: option 'dhcp-option' cannot be used in this context ([PUSH-OPTIONS])
Thu Dec 27 10:15:14 2018 OPTIONS IMPORT: timers and/or timeouts modified
Thu Dec 27 10:15:14 2018 OPTIONS IMPORT: --ifconfig/up options modified
```
any way to fix it?

**Comment by Nyr** [comment]
Try to do it server side:

Remove the following lines from `/etc/openvpn/server.conf`:
```
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS x.x.x.x"
push "dhcp-option DNS y.y.y.y"
```

And restart OpenVPN.

Optionally, also remove the firewall rules from `/etc/rc.local` or firewalld (take a look at the script).
