### ISSUE TITLE
openvpn_xorpatch

### ISSUE THREAD

**Issue by shploos** [Nyr/openvpn-install#562]
hello
i don't know how work with this site but your .sh is perfect, i want suggect you add another option for it
so plese check the link, that version not work but your work perfect the problem is after one day use the server become block in china, we have many chinese friend ready to donate and you update your shell code and add one option for china to support xor
https://github.com/clayface/openvpn_xorpatch

thanks

**Comment by Nyr** [comment]
The script uses precompiled OpenVPN packages, so using this patch is not impossible.
