### ISSUE TITLE
Support More than 254 users?

### ISSUE THREAD

**Issue by DonZheng** [Nyr/openvpn-install#571]
Hi Nyr,

Thanks a million for this wonderful work! It helped greatly for my fellows to get over government censorship.

In the script it has been set by default to use /24 subnet which supports 254? users. Can I support more users by simply changing them to /22 and 255.255.252.0 mask? Is there anything else I should do?

One more query is whether you have any plan to add obfuscation so we can hide from ever-growing censorship better?

Thanks and Best Regards

**Comment by Nyr** [comment]
>  I support more users by simply changing them to /22 and 255.255.252.0 mask?

Yes, that should work.

> add obfuscation

Unlikely. Censorship evasion varies from country to country and requires a lot of changes (maintaineance) over time. Thus, it is unlikely that it will be integrated into the project. Still you can setup Obfsproxy (for example) manually and use the script to do the hard work with OpenVPN.
