### ISSUE TITLE
I can't start openvpn

### ISSUE THREAD

**Issue by Valadius02** [Nyr/openvpn-install#574]

**Comment by Nyr** [comment]
Too bad.

**Comment by Valadius02** [comment]
Hello! I need help with openvpn bc when i run this command: sudo systemctl start openvpn@server
Then is the problem here:

Job for openvpn@server.service failed because the control process exited with error code.
See "systemctl status openvpn@server.service" and "journalctl -xe" for details.

I run this command: systemctl status openvpn@server.service

Then: 
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-01-21 17:25:46 CET; 2min 44s ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 22667 ExecStart=/usr/sbin/openvpn --daemon --writepid /var/run/openvpn-server/server.pid --cd /etc/

Jan 21 17:25:46 88.198.16.210 systemd[1]: Starting OpenVPN connection to server...
Jan 21 17:25:46 88.198.16.210 systemd[1]: openvpn@server.service: Control process exited, code=exited status=2
Jan 21 17:25:46 88.198.16.210 systemd[1]: Failed to start OpenVPN connection to server.
Jan 21 17:25:46 88.198.16.210 systemd[1]: openvpn@server.service: Unit entered failed state.
Jan 21 17:25:46 88.198.16.210 systemd[1]: openvpn@server.service: Failed with result 'exit-code'.


PLS Help me..

**Comment by Nyr** [comment]
See #206, that's likely your problem.

**Comment by Valadius02** [comment]
Okey @Nyr 

You must help me i don't understand this okey?
I m not good in this things...

**Comment by Valadius02** [comment]
Okay. Do what you want i think you will not help me

**Comment by Valadius02** [comment]
@Nyr HELLO!!!!

Help me men....

Nothing doesn't work bc its too long 
I can't understand and i will get good support....

**Comment by Nyr** [comment]
Since you seem to be unable to follow my suggested solution and report back with the results, I can't help you any longer.
