### ISSUE TITLE
Setting up OpenVPN for both TCP and UDP

### ISSUE THREAD

**Issue by xrisk** [Nyr/openvpn-install#576]
I need to set up OpenVPN such that I can connect to it both through TCP and UDP. This would require me to bind to two ports I believe.

Is there some way of accomplishing this through the script or do I have to mess about with OpenVPN config files myself?

**Comment by Nyr** [comment]
This does require two independent OpenVPN processes and is not supported by the script.

You can of course use the script to setup OpenVPN, but you then need to modify the configuration for dual protocol.

**Comment by xrisk** [comment]
Thank you very much.
