### ISSUE TITLE
rc.local iptables rule IP address changes

### ISSUE THREAD

**Issue by freibuis** [Nyr/openvpn-install#581]
I would suggest changing the `rc.local` file not to use an hard code IP address but do a lookup instead
```bash
#!/bin/sh -e
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to x.x.x.x
exit 0
```
to something like
```bash
#!/bin/sh -e
IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
exit 0
```

this would be better for machines that change ip addresses dynamically on reboot. for example. booting fresh AWS-AMI image with openvpn-install baked in.

**Comment by Nyr** [comment]
It is a bad idea to implement this and not viable.

For example, the installer would then behave differently depending on if you use CentOS or Debian. Also, IP autodetection is reliable but not perfect or valid everywhere.

Additionally, rc.local has its days numbered and will be retired from the script sooner than later.

If your specific use case needs this, go ahead and do it yourself, but I can't adapt the project for each of your needs.
