### ISSUE TITLE
IPv6 Leaks

### ISSUE THREAD

**Issue by NickTheLim** [Nyr/openvpn-install#583]
IPv6 is leaking.... Is it possible to disable IPv6 at the client.conf or server.conf level? Or better yet just route it through the VPN server?

**Comment by Nyr** [comment]
You can tell your client to disable the IPv6 routes while connected, many clients include this option (I use Viscosity, for example).

You can also route IPv6 through the server but that's not currently supported by the script.  See here to enable manually: https://github.com/Nyr/openvpn-install/issues/242#issuecomment-273330878
