### ISSUE TITLE
Lots of love

### ISSUE THREAD

**Issue by vinyll** [Nyr/openvpn-install#587]
I was following the OpenVPN tutorial at https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04 and gave up mid-way.

That was until I arrived here and installed in less than 2 minutes.

Thanks so much for this smooth-easy-simple-actuallyworking solution for basic setup ❤️

**Comment by Nyr** [comment]
Glad to be of help :)
