### ISSUE TITLE
Problems with certificates due to the lack of hostname

### ISSUE THREAD

**Issue by dudeisbrendan03** [Nyr/openvpn-install#588]
the FQDN on the certs is ChangeMe, during set up could we have the option to set one instead?

**Comment by Nyr** [comment]
What specific problem does this cause to you? It shouldn't matter.

**Comment by dudeisbrendan03** [comment]
For implementing into an enterprise environment it does.

**Comment by Nyr** [comment]
I will ask again: what is specifically the problem caused by this?

99,99% of the script users don't need this, so if your use case really needs it, I want to understand why.

**Comment by dudeisbrendan03** [comment]
I don't want staff having to remember an IP between devices, and Chromebooks just refuse to connect to OpenVPN at all.

Ended up just setting it up myself, made a couple scripts to generate users and packs that can be downloaded by the user so I don't really need it anymore.

**Comment by Nyr** [comment]
> I don't want staff having to remember an IP between devices

So a FQDN would be needed for the client configuration, not for the certificate as you requested. That's why I was confused.

> Chromebooks just refuse to connect to OpenVPN at all.

And there is nothing wrong with the script, AFAIK Chromebooks only have limited OpenVPN support.

**Comment by dudeisbrendan03** [comment]
After I got the certificates we have the Chromebooks working
