### ISSUE TITLE
[Question] - regarding renewals

### ISSUE THREAD

**Issue by kyle95wm** [Nyr/openvpn-install#589]
So I realize that realistically, I'm not going to hit the 10-year mark on these certs, but let's say I need to renew these for whatever reason. Would uninstalling and re-installing OpenVPN effectively renew/re-create certs for clients? Obviously everyone involved will need a new OVPN profile. Will this work?

**Comment by Nyr** [comment]
In 10 years, there are other issues which would need to be addressed, for example the configuration would likely be outdated or even insecure and the setup itself almost certainly be broken if you kept updating your system for so long.

The script doesn't implement renewals, so removing and creating individual clients would work, a full reinstall wouldn't be needed.
