### ISSUE TITLE
Interface name instead of local IP address

### ISSUE THREAD

**Issue by sunsetsystems** [Nyr/openvpn-install#590]
Some users of this script will want to configure a VPN server before the local IP address of the interface is known. It would be nice to have the option to specify the interface name (e.g. eth0) instead of its IP address. At run time the IP address can be obtained with a command such as:

    IP=`ifconfig eth0 | perl -nle 's/ inet (\S+)/print $1/e'`

... though something else may be more universal.

**Comment by Nyr** [comment]
If you need to do that, using `MASQUERADE` is a better approach.

There are no plans to implement that into the script, `MASQUERADE` should only be implemented if the user really needs it.
