### ISSUE TITLE
No password for user

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/openvpn-install#594]
Hello, Your script is great and save my day after many failtures of installing openvpn on debian and centOS servers. But I have one doubt - is it safe to connect to my VPN without password?

Regards,
Przemek

**Comment by Nyr** [comment]
Authentication is certificate based, which speaking generally, can be considered safer than a password.

This is a very common and secure choice for OpenVPN (and other VPN software, too).

**Comment by raditya69** [comment]
yeah i guess so,,
please giving optional about "user key password" while create a client openVPN.
i'm so insecure about that
