### ISSUE TITLE
Possible to Add 2nd Instance

### ISSUE THREAD

**Issue by kyle95wm** [Nyr/openvpn-install#597]
Is it possible to add a 2nd server config (different port, address pool, etc) and still use the same DNS server (which in my case is 10.8.0.1 - Pi-Hole)?

Basically, I'm looking to have one instance route DNS ONLY, and then have another route everything including DNS. I tried duplicating what the installer did, but for some reason the new iptables rules made DNS stop working alltogether. What am I doing wrong?

**Comment by Nyr** [comment]
Well, this is not officially supported by the script.

But what you want is possible, you need to use a different config file with a different network and everything and then route as you desire. That is out of the scope of this issue tracker. Alternatively, you could route specific clients selectively, so their DNS traffic goes over the VPN while the other is routed directly.

Take a look at how routing works, you can do this with OpenVPN or just using iptables directly.
