### ISSUE TITLE
Iphone can not connect to the vpn

### ISSUE THREAD

**Issue by LinYKen** [Nyr/openvpn-install#599]
Iphone 8 ios 12.2
I download the client application, and import the ovpn file. But when I click the button, it shows that "network is unavailable. Please try to connect later with active network. "
I open the setting -> vpn, and click the connect button there, after I release the button, it toggles back to close position and fail to connect the vpn.
How can I solve this problem?

**Comment by Nyr** [comment]
That's a problem with your client, this issue tracker is not the right place to get support for that.
