### ISSUE TITLE
ошибка openvpn

### ISSUE THREAD

**Issue by Aleks1911** [Nyr/openvpn-install#600]
народ помогите купил vps и не могу настроить когда делаю скрипт wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh выдаёт
An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

502
Error: INVALID_PROTOCOL: '11' not in {'tcp'|'udp'|'sctp'|'dccp'}
success
Error: INVALID_PROTOCOL: '11' not in {'tcp'|'udp'|'sctp'|'dccp'}
ну и соотвецтвенно конфиг не работает ( как поднять vpn ?
у меня сейчас CentOS 5.9 32 бит Тип виртуализации (КВМ)

**Comment by Nyr** [comment]
Take a look at #514.
