### ISSUE TITLE
Problem with DDNS

### ISSUE THREAD

**Issue by cipster86** [Nyr/openvpn-install#607]
Hello,
i have a problem with dinamc Dns.
I have this error:
********************
Write out database with 1 new entries
Data Base Updated

Using SSL: openssl OpenSSL 1.1.0j  20 Nov 2018
Using configuration from ./safessl-easyrsa.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

iptables v1.6.0: Bad IP address "domain.net"

Try `iptables -h' or 'iptables --help' for more information.
91

Finished!
********************

Have you a idea how resolve it??

**Comment by Nyr** [comment]
I will assume that your machine is behind NAT. If so, you are setting up the NAT incorrectly, see here: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

If your machine has a dynamic public IP directly assigned (which is very rare), the script doesn't support this and you would need to manually set up rules using MASQUERADE.
