### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by TheDoctorsLife** [Nyr/openvpn-install#61]
First a complement, thanks for this amazing script, it just makes my life so much easier.

So I'm running. Digital ocean Vps, with IPv6. After doing some looking online, I've realized this is pretty difficult to do. How I propose this can be added since not everyone has IPv6, is to add it to the list of things to do after installing openvpn. It could also be done just if the machine openvpn is being installed on has IPv6 during installation.

**Comment by Nyr** [comment]
See #42. The crappy IPv6 deployment from DigitalOcean wouldn't even work with OpenVPN anyway.

**Comment by TheDoctorsLife** [comment]
According to that one, DO only assigned one ip per droplet, howerver I've had my current droplet since January. ![/64](http://i.doctors.us.to/PWBz5SJj.png) as you can see, I have more than that assigned. At some point I did have ipv6 working, however I broke the openvpn conf and haven't been able to find the article that allowed me to do so without any scripts.

**Comment by Nyr** [comment]
Look at the "configurable address range". Looks like they are still usen a broken IPv6 implementation, although one a little less broken.

That's why we can't have IPv6 support, because everyone is doing stupid things like that.

**Comment by TheDoctorsLife** [comment]
Ahh, just got finished snapshoting, destroying then recreating my droplet from the snapshot without IPv6 support. Got a nice /48 range from HE and did that. Pretty sure I have been working on getting everything working with IPv6 and openvpn for weeks. The lack of good tutorials out there and broken IPv6 implantations made this take forever
