### ISSUE TITLE
Can not Connect to VPN

### ISSUE THREAD

**Issue by EqualOwl** [Nyr/openvpn-install#610]
I installed using the script but when i try to connect to server using profile it says 
 Sat May 11 15:26:19 2019 read UDP: Unknown error (code=10054)
Is their a way to fix. I am using the VirMarch Host that was linked in the readme

**Comment by sbondo1234** [comment]
Have you tried turning it off and then on?

**Comment by EqualOwl** [comment]
yea thanks worked like a charm

**Comment by Nyr** [comment]
I guess you were ironic in your response?

This is a connectivity issue, either you have a firewall configured in the server which is blocking the connections from the client, or your client is on a restricted network (or has a very restrictive firewall).
