### ISSUE TITLE
Only one connection by certificate

### ISSUE THREAD

**Issue by enanotg** [Nyr/openvpn-install#612]
Hi!

Everything works amazingly good! 
But I want just one connection to each certificated, is possible to do that?

Thanks!

**Comment by NextGenerationcloud** [comment]
Hello!
Do the script again ;)

**Comment by enanotg** [comment]
Hi!

I uninstall everything (option 4) and run it again? Or just run it again?

Thanks!

**Comment by NextGenerationcloud** [comment]
Or just run it again?
YES
https://github.com/NextGenerationcloud/openvpn-install/blob/master/multi-openvpn-install.sh
command server 1:
bash multi-openvpn-install.sh 1

command server 2:
bash multi-openvpn-install.sh 2

command server 3:
bash multi-openvpn-install.sh 3

Edit position Nr: 218-224 

clone this to 225-232 
and EDIT this
if [ $servermodell -eq "1" ]; then
to
if [ $servermodell -eq "2" ]; then
and you have 2 vpn single server with internet ^^

**Comment by enanotg** [comment]
Hi!

I got confused, I just need One Connection for Certification.

For what I got, you give me the way to have 2 VPN's running on the same server.

**Comment by NextGenerationcloud** [comment]
Oh, right

Clone file / etc / openvpn / * .conf to / etc / openvpn / server2.conf
then edit it ;) 
then start it command: sudo systemctl start openvpn@server2

**Comment by NextGenerationcloud** [comment]
second certification
start the schript again

**Comment by Nyr** [comment]
> I want just one connection to each certificated, is possible to do that?

That's the default, you don't need to change anything :)

**Comment by enanotg** [comment]
I don't understand why but i can connect with the same certificate from my phone an my laptop.

But thanks!
