### ISSUE TITLE
TLS certificate failed handcheck

### ISSUE THREAD

**Issue by MagnusDot** [Nyr/openvpn-install#613]
when i'am triing to connect to the vpn the return are :
`Wed May 15 12:38:42 2019 MANAGEMENT: >STATE:1557916722,WAIT,,,,,,
Wed May 15 12:39:42 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed May 15 12:39:42 2019 TLS Error: TLS handshake failed
Wed May 15 12:39:42 2019 SIGUSR1[soft,tls-error] received, process restarting
Wed May 15 12:39:42 2019 MANAGEMENT: >STATE:1557916782,RECONNECTING,tls-error,,,,,
Wed May 15 12:39:42 2019 Restart pause, 5 second(s)`

**Comment by NextGenerationcloud** [comment]
firewall deaktivieren and port forwarding ;)

**Comment by Nyr** [comment]
Indeed, this is a connectivity issue.

Maybe a firewall, maybe you are trying to connect from a restricted network.

If you are using UDP, try TCP protocol and port 443 instead. Or UDP protocol in port 53 if you were using TCP.
