### ISSUE TITLE
enable client-to-client

### ISSUE THREAD

**Issue by limitall** [Nyr/openvpn-install#615]
Thanks for such a helpful  script, it save my time.
everything works fine after installation, my question is just how i can enable client-to-client.

e.g: 
server ::  local : 192.168.205.115 vpn : 10.8.0.1
client1 :: local : 192.168.1.3(office network) vpn : 10.8.0.2
client2 :: local : 192.168.1.113(home network) vpn : 10.8.0.3

issue 1 : after connect vpn on client1 lost connection of (office network) i can't ping on 192.168.1.4 on office network

issue 2 : I can't ping to 192.168.1.113(home network) from 192.168.1.3(office network)

please help to solve this

**Comment by kichsp** [comment]
issue 1: 192.168.1.(4)??

**Comment by limitall** [comment]
> issue 1: 192.168.1.(4)??

yes 192.168.1.4 another machine on office network

**Comment by Nyr** [comment]
This issue tracker is to report problems with the script, not a technical support forum.

That said, the script sets up the internal 10.8.0.0/24 network and that's what you should use for communication between hosts connected to the VPN (so ping 10.8.0.x addresses, not 192.168.1.x). If it doesn't work, most likely a firewall is blocking that.

**Comment by javanoclaw** [comment]
I also have such needs
