### ISSUE TITLE
CLI Usage

### ISSUE THREAD

**Issue by miguel456** [Nyr/openvpn-install#617]
Hi,

Does the script have a way to be used with CLI options? Like --my-option-here
Not sure if this already exists

**Comment by Nyr** [comment]
No, and no plans to implement that since some of the script features need to be interactive (for example, NAT detection, but probably more in the future).

If you really need unattended usage, it should be relatively easy to modify the script for your specific needs.

**Comment by x-yuri** [comment]
> no plans to implement that since some of the script features need to be interactive (for example, NAT detection

Yet, somehow I detect NAT [non-interactively][a]. What am I doing wrong?

I might be missing something, but the mantra you repeat across the issues (some parts need interactivity) sounds like an excuse. I can understand that you don't have time, but no way to make it non-interactive?.. o.O

[a]: https://gist.github.com/x-yuri/113cda3fac50dc2032984995a474d2c8
