### ISSUE TITLE
how to get .ovpn file

### ISSUE THREAD

**Issue by kerenbir** [Nyr/openvpn-install#618]
hi im in troble to get .ovpn file i know this file in root folder but i cant download with winscp.
thank you.

**Comment by stevemccann** [comment]
You need to copy/move it to your home directory and change the permissions/owner to yourself so you can download it. 

Example:
sudo cp *.ovpn ~
sudo chown <your username> *.ovpn

Or you could run cat and copy and paste the contents if you're stuck.

**Comment by kerenbir** [comment]
found my own trouble im using aws ec2 and aws not allowing root login so i enable it and succes.
thank you

**Comment by Offirmo** [comment]
For googlers: no need to allow root login, the install script gives you the path of the .ovpn, ex.

> The client configuration is available in: /root/iphone14.ovpn

then it's as simple as `sudo cat /root/iphone14.ovpn`
