### ISSUE TITLE
Adding port 53 to default client.conf?

### ISSUE THREAD

**Issue by zenithteq** [Nyr/openvpn-install#62]
Hello Nyr, firstly thank you for a great script.

When I run the script and select that the alternate port 53 to be configured, it appears that there is no command to add the entry into the default client.conf file. So when the client profile is created the IP and port 53 are missing from the file.

Are you able to replicate this?

My server is:
CentOS Linux release 7.1.1503 (Core)
Linux C7-OVPN.localdomain 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18

Thank you,

ZT

**Comment by Nyr** [comment]
Yeah, it was intended like that but arguably isn't the best UX.

Should we...
- Change the port to 53 only (server side) when the user selects this option?
- Change the port to 53 in the client.conf but still have 1194 available?
- Keep it like it has been for now?

I would appreciate input from other users, although I think maybe the first option is the less confusing one?

**Comment by TheDoctorsLife** [comment]
I think option 2 is the best, that way if user x decides he wants to change the port back to 1194 later, he can

**Comment by zenithteq** [comment]
2nd option would be useful, though my query was more to do with the action being intentional or not, which you have answered.

Thanks Nyr.
