### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by alexkentov** [Nyr/openvpn-install#624]
mv: cannot stat ‘/etc/openvpn/server/EasyRSA-3.0.5/’: No such file or directory
chown: cannot access ‘/etc/openvpn/server/easy-rsa/’: No such file or directory
openvpn-install.sh: line 231: cd: /etc/openvpn/server/easy-rsa/: No such file or directory
openvpn-install.sh: line 233: ./easyrsa: No such file or directory
openvpn-install.sh: line 234: ./easyrsa: No such file or directory
openvpn-install.sh: line 235: ./easyrsa: No such file or directory
openvpn-install.sh: line 236: ./easyrsa: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
cp: cannot stat ‘pki/ca.crt’: No such file or directory
cp: cannot stat ‘pki/private/ca.key’: No such file or directory
cp: cannot stat ‘pki/issued/server.crt’: No such file or directory
cp: cannot stat ‘pki/private/server.key’: No such file or directory
cp: cannot stat ‘pki/crl.pem’: No such file or directory
chown: cannot access ‘/etc/openvpn/server/crl.pem’: No such file or directory
systemctl: unrecognized option '--now'
systemctl: unrecognized option '--now'
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/client18.crt: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/client18.key: No such file or directory

Previous worked. Why was the obviously non-working script upload

**Comment by Yakashimoto** [comment]
same here!

**Comment by Nyr** [comment]
Were you using CentOS 6 or Debian 8? Support for those distributions was deprecated recently.

You can use an older version of the script if you really want to install there, but both distributions have reached their end of life and are getting security updates only.

**Comment by suricloud** [comment]
where to find the older version

**Comment by Nyr** [comment]
@suricloud for a version compatible with Ubuntu 16.04, this is the latest: https://git.io/vpn1604

**Comment by suricloud** [comment]
Looking for ubuntu 14.04 .
Its not working on this version.

**Comment by Nyr** [comment]
@suricloud Ubuntu 14.04 reached its end of life on April 30 and is unsupported.

There are old versions of the script which would work on it, but you should really upgrade to a newer distribution.

**Comment by pruss** [comment]
There is a an error in the script when folders are moved

`
	mv ~/EasyRSA-3.0.5/ /etc/openvpn/server/
	mv /etc/openvpn/server/EasyRSA-3.0.5/ /etc/openvpn/server/easy-rsa/
`

It seems that the folder /etc/openvpn/server does not exists and so the mv does not work correctly.

Fix:
`
        if [[ ! -e /etc/openvpn/server ]]; then
                mkdir -p /etc/openvpn/server
        fi
        mv ~/EasyRSA-3.0.5/ /etc/openvpn/server/easy-rsa/
        mv /etc/openvpn/server/EasyRSA-3.0.5/ /etc/openvpn/server/easy-rsa/
`

This fixed it for me.

**Comment by Nyr** [comment]
@pruss two possible causes for your issue:

- You are using an old, unsupported distribution.
- OpenVPN vas installed previously in the system and not fully removed.

Can it be one of them? If not please specify which environment is this happening in.

**Comment by pruss** [comment]
1) you can from Canonical an support extension.
2) Ubuntu 14.04.6 LTS
3) It's just a small fix

**Comment by Nyr** [comment]
@pruss there are more problems with Ubuntu 14.04, but the main issue remains: it is an unsupported distribution since it reached its end of life.

Yes, you can buy a subscription for some extended support but that only covers the kernel and is not relevant to this. If you want to set up a secure OpenVPN system, you really need to upgrade, no way around it.

**Comment by pruss** [comment]
@Nyr Upgrade is already running.
Thank you for your support!
