### ISSUE TITLE
Problem with script - CentOS 6.4,6.7, 7.0 

### ISSUE THREAD

**Issue by mleyvas** [Nyr/openvpn-install#625]
mv: cannot move `/root/EasyRSA-3.0.5/' to `/etc/openvpn/server/': No such file or directory
mv: cannot stat `/etc/openvpn/server/EasyRSA-3.0.5/': No such file or directory
chown: cannot access `/etc/openvpn/server/easy-rsa/': No such file or directory
openvpn-install.sh: line 231: cd: /etc/openvpn/server/easy-rsa/: No such file or directory
openvpn-install.sh: line 233: ./easyrsa: No such file or directory
openvpn-install.sh: line 234: ./easyrsa: No such file or directory
openvpn-install.sh: line 235: ./easyrsa: No such file or directory
openvpn-install.sh: line 236: ./easyrsa: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
cp: target `/etc/openvpn/server' is not a directory
chown: cannot access `/etc/openvpn/server/crl.pem': No such file or directory
openvpn-install.sh: line 243: openvpn: command not found
openvpn-install.sh: line 252: /etc/openvpn/server/dh.pem: No such file or directory
openvpn-install.sh: line 267: /etc/openvpn/server/server.conf: No such file or directory
openvpn-install.sh: line 268: /etc/openvpn/server/server.conf: No such file or directory
openvpn-install.sh: line 281: /etc/openvpn/server/server.conf: No such file or directory
openvpn-install.sh: line 281: /etc/openvpn/server/server.conf: No such file or directory
openvpn-install.sh: line 309: /etc/openvpn/server/server.conf: No such file or directory
openvpn-install.sh: line 342: /etc/systemd/system/openvpn-iptables.service: No such file or directory
openvpn-install.sh: line 343: systemctl: command not found
openvpn-install.sh: line 358: systemctl: command not found
openvpn-install.sh: line 379: /etc/openvpn/server/client-common.txt: No such file or directory
cp: cannot stat `/etc/openvpn/server/client-common.txt': No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/client.crt: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/client.key: No such file or directory
sed: can't read /etc/openvpn/server/ta.key: No such file or directory

This error happens after trying both wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh
with raised privileges or not.

**Comment by Nyr** [comment]
CentOS 6 is too old and not supported.

I doubt that this same error can happen in CentOS 7, since the `openvpn` package creates the `/etc/openvpn/server/` directory.

It could only happen if OpenVPN was previously installed and there where leftovers.

**Comment by Yakashimoto** [comment]
It could only happen if OpenVPN was previously installed and there where leftovers.

No! Fresh installed VPS with Centos 6 and same issue!
