### ISSUE TITLE
Office365 and default gateway

### ISSUE THREAD

**Issue by acs-ferreira** [Nyr/openvpn-install#627]
I've started using Office365 under Windows 10 and it seems i can't connect when OpenVPN is running.

I searched for the fix and found this (it works): https://www.macwheeler.com/windows-10-office-365-cannot-connect-over-openvpn-fixed/

So i don't know if this can or should be fixed here, so FYI.

Thanks.

**Comment by Nyr** [comment]
This is an issue with the way Office 365 detects an internet connection. For anyone interested, [here](https://forums.openvpn.net/viewtopic.php?t=27321) is some discussion/explanation of the issue.

You should try adding the following lines to your client config:
```
allow-pull-fqdn
route www.msftncsi.com net_gateway
```

If that can fix the issue, it would be a much better fix, but I am not sure that it will work.

Ultimately this is something which is wrong with software external to OpenVPN and we are limited in what we can do to fix it in our side.

Thanks anyway for the report, very interesting issue and something I wasn't aware of.
