### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by ayton** [Nyr/openvpn-install#628]
One and the same error after installing your script on Debian 8 and centos 7
-------------------------------
Installed:
  openvpn.x86_64 0:2.4.7-1.el6

Dependency Installed:
  lz4.x86_64 0:r131-1.el6           pkcs11-helper.x86_64 0:1.11-3.el6

Complete!
mv: cannot stat `/etc/openvpn/server/EasyRSA-3.0.5/': No such file or directory
chown: cannot access `/etc/openvpn/server/easy-rsa/': No such file or directory
openvpn-install.sh: line 231: cd: /etc/openvpn/server/easy-rsa/: No such file or directory
openvpn-install.sh: line 233: ./easyrsa: No such file or directory
openvpn-install.sh: line 234: ./easyrsa: No such file or directory
openvpn-install.sh: line 235: ./easyrsa: No such file or directory
openvpn-install.sh: line 236: ./easyrsa: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
cp: cannot stat `pki/ca.crt': No such file or directory
cp: cannot stat `pki/private/ca.key': No such file or directory
cp: cannot stat `pki/issued/server.crt': No such file or directory
cp: cannot stat `pki/private/server.key': No such file or directory
cp: cannot stat `pki/crl.pem': No such file or directory
chown: cannot access `/etc/openvpn/server/crl.pem': No such file or directory
openvpn-install.sh: line 342: /etc/systemd/system/openvpn-iptables.service: No such file or directory
openvpn-install.sh: line 343: systemctl: command not found
openvpn-install.sh: line 358: systemctl: command not found
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/aydoqdy.crt: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/aydoqdy.key: No such file or directory

Finished!

**Comment by ayton** [comment]
I noticed that the problem is ignored and there is no solution, thanks and sorry for the duplicate.

**Comment by Nyr** [comment]
Of course there is a solution and issues are not ignored at all.

Did those systems had OpenVPN installed previously?

If not, can you provide steps to reproduce the problem? What is your server provider, are you on a clean image?

Does running `mkdir -p /etc/openvpn/server/` previous to the script fix the problem?

**Comment by TinCanTech** [comment]
Because there are some issues with Easy-rsa-305/306 I tested this myself.
I had no issue at all but the directory `/etc/openvpn/server` was already present.

**Comment by Nyr** [comment]
I don't think that this issue has much to do with Easy-RSA. The problem seems to be that for whatever reason, `/etc/openvpn/server` is not created when the OpenVPN package is installed.

**Comment by TinCanTech** [comment]
I believe that is something todo with how debian package openvpn.

**Comment by Yakashimoto** [comment]
same issue here..on Centos 6

**Comment by Nyr** [comment]
Both Debian 8 and CentOS 6 are too old and unsupported by the script.
