### ISSUE TITLE
Can connect but no internet on Amazon AWS

### ISSUE THREAD

**Issue by skipik** [Nyr/openvpn-install#629]
Hello, I have a problem that I can connect to my server but it looks like no internet at all (I cant open any web site when using openvpn application).
When it (the script) ask me for an IP, I choose my internal one, then it says I'm behind NAT and I write my external IP, so everything should be correct on those steps. I also opened 1194 UDP on amazon AWS web site.
Could you help me?
P.S. my OS is Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1041-aws x86_64)

**Comment by Nyr** [comment]
You probably have internet, just not DNS.

AWS EC2 sets an internal IP address for the DNS, so if you selected `1) Current system resolvers` during setup, your client will be assigned a DNS which is unusable from its side.

Just select any other option for the DNS during setup.
