### ISSUE TITLE
If default port 1194 is changed, OpenVPN Server does not listen - CentOS

### ISSUE THREAD

**Issue by zenithteq** [Nyr/openvpn-install#63]
Hi Nyr,  On CentOS 6 and 7 I am unable to get a connection to the server if the default port of 1194 is changed to another port during install.  Can you verify this?  Script works fine on Ubuntu when default port is changed.

Thank you,

ZT

**Comment by Nyr** [comment]
Hello and thank you for reporting this.

I did just check with three CentOS 7 templates at different cloud providers and can't reproduce, but I'm not a CentOS guy and am not sure about any circumstances where FirewallD could maybe be enabled by default.

Are you using a clean image? Is it a template from some provider or the official ISO? On CentOS 7, could you please run the following commands and let me know the output?
`firewall-cmd --state`
`netstat -nlup`

Thanks in advance.

**Comment by zenithteq** [comment]
Hi Nyr, thank you for the reply.  I have just tested the script on Bandwagon Host and it works perfectly fine.

Need to look at my setup more closely.  Will do some more testing and revert if needed.

Thanks again for your time.
