### ISSUE TITLE
OpenVPN management interface does not work 

### ISSUE THREAD

**Issue by 13bscsaamjad** [Nyr/openvpn-install#630]
the management interface does not work by adding ```management 127.0.0.1 port``` in the /etc/openvpn/server/server.conf file.

**Comment by TinCanTech** [comment]
This script does not enable `--managment` port.
Please see your openvpn log file for **other** errors.

**Comment by bosen365** [comment]
> This script does not enable `--managment` port. Please see your openvpn log file for **other** errors.

Hi, can you help me ? I want to know How to enable the --managment  in this script?
