### ISSUE TITLE
The script can remove needed dependencys

### ISSUE THREAD

**Issue by ChillerDragon** [Nyr/openvpn-install#633]
From the uninstall code:

```
if [[ "$OS" = 'debian' ]]; then
	apt-get remove --purge -y openvpn
else
	yum remove openvpn -y
fi
```

And this happens no matter if openvpn was installed before using ``openvpn-install.sh``. And thus could possible be a dependency of any other vpn provider or similar.

**Comment by Nyr** [comment]
If user selects the option `Remove OpenVPN`, then the script will assume that the user really wants to remove OpenVPN. I don't think that is unexpected.
