### ISSUE TITLE
Raspberry, no tun interface

### ISSUE THREAD

**Issue by atuxnull** [Nyr/openvpn-install#634]
I am trying to install to 2 raspberrys the script but it does not create the tun interface. as a consequence the vpn does not work. i have tried in stretch and in buster as well. both failed. any ideas on how to bypass this issue please?

**Comment by Nyr** [comment]
The script doesn't need to "create" the TUN interface. OpenVPN will bring it up on startup.

If you are still having issues, please provide the OpenVPN server log.
