### ISSUE TITLE
dont work with CentOS 6 and Debian 8

### ISSUE THREAD

**Issue by Yakashimoto** [Nyr/openvpn-install#636]
Fresh installed VPS with CentOS 6

mv: cannot stat `/etc/openvpn/server/EasyRSA-3.0.5/': No such file or directory
chown: cannot access `/etc/openvpn/server/easy-rsa/': No such file or directory
openvpn-install.sh: line 231: cd: /etc/openvpn/server/easy-rsa/: No such file or                                        directory
openvpn-install.sh: line 233: ./easyrsa: No such file or directory
openvpn-install.sh: line 234: ./easyrsa: No such file or directory
openvpn-install.sh: line 235: ./easyrsa: No such file or directory
openvpn-install.sh: line 236: ./easyrsa: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
cp: cannot stat `pki/ca.crt': No such file or directory
cp: cannot stat `pki/private/ca.key': No such file or directory
cp: cannot stat `pki/issued/server.crt': No such file or directory
cp: cannot stat `pki/private/server.key': No such file or directory
cp: cannot stat `pki/crl.pem': No such file or directory
chown: cannot access `/etc/openvpn/server/crl.pem': No such file or directory
openvpn-install.sh: line 342: /etc/systemd/system/openvpn-iptables.service: No s                                       uch file or directory
openvpn-install.sh: line 343: systemctl: command not found
openvpn-install.sh: line 358: systemctl: command not found
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/client.crt: No such file                                        or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/client.key: No such file or direct                                       ory

i found several closed issues here, but not solution! Whats going wrong?

**Comment by lukebarone** [comment]
As @Nyr mentioned, CentOS 6 is too old, and is not supported.

**Comment by Yakashimoto** [comment]
but it work without any issue a couple of weeks ago.!

**Comment by Nyr** [comment]
There is no issue with the script on this, no need to spam the issue tracker with multiple messages.

CentOS 6 and Debian 8 support was deprecated recently from the script.

Of course you can use an older version on the script to install there, but you should seriously consider upgrading since both on them are no longer receiving mainline support (CentOS 6 since more than 2 years ago, Debian 8 for a year already).

I will consider adding a dialog for users running those old distributions, but support for them will not return.

**Comment by slrslr** [comment]
> consider adding a dialog for users running those old distributions

yes.

> you can use an older version on the script

thanks for mention this. This worked on CentOS 6:

`wget https://raw.githubusercontent.com/Nyr/openvpn-install/d4efae3b1081867ffce420267f8c20a7c7336047/openvpn-install.sh && bash openvpn-install.sh`
