### ISSUE TITLE
Debian10 service never gets started...

### ISSUE THREAD

**Issue by thejohnha** [Nyr/openvpn-install#637]
Long time user. Always was able to get Debian9 or Ubuntu 16 or 18 to work in the past. Recently tried with Debian10. Service doesn't seem to want to start.

Just thought I'd report my findings. I skimmed through the script but I'm not familiar enough with it to be able figure it out. Thank you for all your hard and diligent work to maintain this over the years! :-)

**Comment by Nyr** [comment]
Hello,

I assume that this is a clean install with the latest version of the script and you didn't upgrade your existing setup from Debian 9 to Debian 10?

Debian 10 is supported and it should work, so please provide the output of the following commands after installation:
``systemctl status openvpn@server.service``
``journalctl -xe``

May I also ask where are you using the installer? Is this a cloud provider like DigitalOcean? An OpenVZ VPS? Your own server installed from the ISO?

Thanks

**Comment by thejohnha** [comment]
Yes correct thanks for checking the basics, it's a fresh install. I am using Proxmox as the hypervisor, and running plain debian10 in an LXC container. This setup still works with debian9, but not with 10...

I found the error message `Cannot set tx queue length on tun0: Operation not permitted` and saw references to unprivileged vs privileged LXC containers... normally I use the default `unprivileged` container, but I tried on a privileged container and still did not work (although with different error messages).

This is from the `unprivileged` container:
![Screen Shot 2019-07-16 at 11 46 55](https://user-images.githubusercontent.com/6325833/61310088-944b4b80-a7c1-11e9-8a8e-3af34037a83a.jpg)


And this is from the `privileged` container:
![Screen Shot 2019-07-16 at 11 58 15](https://user-images.githubusercontent.com/6325833/61310114-9f9e7700-a7c1-11e9-848c-c6cf0f765066.jpg)

**Comment by Nyr** [comment]
AppArmor is restricting the LXC container, this was added in Debian 10 and can't/shouldn't be "fixed" from the script.

I'm not an expert, but the easiest solution would be to edit the LXC container configuration file and disable AppArmor:
`lxc.apparmor.profile = unconfined`

There is probably a better solution which doesn't imply entirely disabling AppArmor for the container, so don't quote me on this advice.

**Comment by thejohnha** [comment]
@Nyr Thank you so much for helping read the tea leaves. I'll report back if I run into any issues - thanks for pointing it out as an apparmor issue.

**Comment by thejohnha** [comment]
Dang, no joy after disabling apparmor:

```
root@vpn3:/etc/openvpn/server# systemctl status openvpn@server.service
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
```

```
root@vpn3:/etc/openvpn/server# journalctl -xe
-- The job identifier is 906.
Jul 18 14:49:57 vpn3 openvpn[1554]: OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Jul 18 14:49:57 vpn3 openvpn[1554]: library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Jul 18 14:49:57 vpn3 openvpn[1554]: NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as
Jul 18 14:49:57 vpn3 openvpn[1554]: Diffie-Hellman initialized with 2048 bit key
Jul 18 14:49:57 vpn3 systemd[1]: Started OpenVPN service for server.
-- Subject: A start job for unit openvpn-server@server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit openvpn-server@server.service has finished successfully.
--
-- The job identifier is 906.
Jul 18 14:49:57 vpn3 openvpn[1554]: Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Jul 18 14:49:57 vpn3 openvpn[1554]: Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Jul 18 14:49:57 vpn3 openvpn[1554]: TUN/TAP device tun0 opened
Jul 18 14:49:57 vpn3 openvpn[1554]: Note: Cannot set tx queue length on tun0: Operation not permitted (errno=1)
Jul 18 14:49:57 vpn3 openvpn[1554]: /sbin/ip link set dev tun0 up mtu 1500
Jul 18 14:49:57 vpn3 openvpn[1554]: openvpn_execve: unable to fork: Resource temporarily unavailable (errno=11)
Jul 18 14:49:57 vpn3 openvpn[1554]: Exiting due to fatal error
Jul 18 14:49:57 vpn3 systemd[1]: openvpn-server@server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit openvpn-server@server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jul 18 14:49:57 vpn3 systemd[1]: openvpn-server@server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit openvpn-server@server.service has entered the 'failed' state with result 'exit-code'.
```
