### ISSUE TITLE
[asking] build vpn server using openvpn, and build proxy server in centos

### ISSUE THREAD

**Issue by zulhiyatiuwi** [Nyr/openvpn-install#64]
hello... sorry for disturbing. i want to ask something about build vpn server using openvpn and centos as operating system.
in my school have 6 laboratory. and i want to build one vpn server for every laboratory with different ip address. so the main server know which computer from laboratory do a connection. can it be? i plan to build proxy server too. my lecture give me this for my end task. thank you for your attention...

**Comment by Nyr** [comment]
Not an issue with the script.
