### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by robinbd87** [Nyr/openvpn-install#645]
mv: cannot stat `/etc/openvpn/server/EasyRSA-3.0.5/': No such file or directory
chown: cannot access `/etc/openvpn/server/easy-rsa/': No such file or directory
openvpn-install.sh: line 231: cd: /etc/openvpn/server/easy-rsa/: No such file or directory
openvpn-install.sh: line 233: ./easyrsa: No such file or directory
openvpn-install.sh: line 234: ./easyrsa: No such file or directory
openvpn-install.sh: line 235: ./easyrsa: No such file or directory
openvpn-install.sh: line 236: ./easyrsa: No such file or directory
openvpn-install.sh: line 237: ./easyrsa: No such file or directory
cp: cannot stat `pki/ca.crt': No such file or directory
cp: cannot stat `pki/private/ca.key': No such file or directory
cp: cannot stat `pki/issued/server.crt': No such file or directory
cp: cannot stat `pki/private/server.key': No such file or directory
cp: cannot stat `pki/crl.pem': No such file or directory
chown: cannot access `/etc/openvpn/server/crl.pem': No such file or directory
openvpn-install.sh: line 342: /etc/systemd/system/openvpn-iptables.service: No such file or directory
openvpn-install.sh: line 343: systemctl: command not found
openvpn-install.sh: line 358: systemctl: command not found
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/client.crt: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/client.key: No such file or directory

**Comment by BobZombiE69** [comment]
same problem here on ubuntu 14

**Comment by robinbd87** [comment]
https://github.com/angristan/openvpn-install

**Comment by Nyr** [comment]
@robinbd87 what distribution are you using?

@BobZombiE69 Ubuntu 14.04 reached its end of life and isn't supported. You need to upgrade your system.
