### ISSUE TITLE
Error stopping Openvpn Service (Ubuntu 18.04)

### ISSUE THREAD

**Issue by DonZheng** [Nyr/openvpn-install#648]
Hi Nyr,

Firstly I would like to thank you for maintaining such a great script. All my fellow users benefit from your wonderful work.

The script has run flawlessly until recently. Below is how I reproduce the error:

1. Create a new Ubuntu 18.04 Server from Hetzner
2. Run your script (an older version which has been running perfectly) to install the openvpn service.
3. Verify service status is ok. (I use telnet localhost 7505, as I added management option in the server.conf)
4. Then run /etc/init.d/openvpn stop.

Then I got below error message:
`Sun Sep  1 12:31:28 2019 event_wait : Interrupted system call (code=4)`
`Sun Sep  1 12:31:28 2019 Closing TUN/TAP interface`
`Sun Sep  1 12:31:28 2019 /sbin/ip addr del dev tun0 10.8.0.1/22`
`RTNETLINK answers: Operation not permitted`
`Sun Sep  1 12:31:28 2019 Linux ip addr del failed: external program exited with error status: 2`
`Sun Sep  1 12:31:28 2019 SIGTERM[hard,] received, process exiting`

Could you please share some expertise on this issue? Please advise if you need any more details.

P.S. The above environment does not have any firewall set up.

EDIT: After above operations, if I run /etc/init.d/openvpn start, the service still wont be up.
EDIT: Every commands mentioned above is run with root account

**Comment by Nyr** [comment]
You are using an old version of the script which has been modified by yourself and I don't know how. Additionally, but this will not make much difference for your issue, you should use `systemctl` commands for managing the service, sysvinit was deprecated years ago.

I'm sorry but I can only provide support for the latest version of the script unmodified by the end user, this is very likely an issue in your setup and I am not in a possition to see what did go wrong.
