### ISSUE TITLE
Future feature suggestion - Auto Install two instances one for UDP other for TCP

### ISSUE THREAD

**Issue by DonZheng** [Nyr/openvpn-install#649]
Dear Nyr,

At the moment, user is prompted to select UDP or TCP. User selects one option. As a result, one openvpn instance is built with the selected proto option. 

In many real world scenarios, One OpenVPN server needs to cater for users using either protocols. At the moment, the script does not support creating more than one instances.

I would like to humbly suggest this script gives user an proto option (Both TCP and UDP). When selected, the script automatically creates two OpenVPN instances: one for UDP, one for TCP.

Benefits: This enhancement dramatically simplifies real world VPN server deployment, making the script one of the most comprehensive in the industry.

Sincerely wish you can consider the idea.

Kind Regards,

**Comment by Nyr** [comment]
The biggest issue for this is that OpenVPN natively doesn't support simultaneous listening in both TCP and UDP. This means that we need to run two instances of the daemon, one for each protocol and there are a few issues with that (we basically need to duplicate the setup for everything).

To be honest with you, this would've been done ages ago if it was cleaner/easier, but given the low demand for this feature and the lack of native support from OpenVPN, I realistically don't think that this will be implemented in the near future.
