### ISSUE TITLE
I have some errors

### ISSUE THREAD

**Issue by cuipu** [Nyr/openvpn-install#650]
Hi Nyr

I have some errors

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
281473718089344:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd

How can I solve these problems

thanks!

**Comment by Nyr** [comment]
You can safely ignore this.
