### ISSUE TITLE
I keep getting udp dropped packet errors on tun0 interface

### ISSUE THREAD

**Issue by xperator** [Nyr/openvpn-install#651]
Hi,

I'm new to openvpn and I used this script to install openvpn on my server. It was very convenient and easy, so thanks for that!

I'm not sure if the issue I'm about to describe is related to this script or just openvpn in general. But I thought it's better to ask it here so maybe someone with experience can help. 

Before coming here, I asked my question on [serverfault](https://serverfault.com/questions/982166/tun0-errors-when-running-a-vpn-server) but no one replied.

It's been only few days since I started my vpn server, and I have netdata monitoring installed. The openvpn was and is working fine but the problem is netdata keeps reporting these 3 types of errors constantly:
```
"server needs attention, ipv4.udperrors (udp), 1m ipv4 udp receive buffer errors = 12 errors"
"server needs attention, net_drops.tun0 (tun0), outbound packets dropped = 34 packets"
"server needs attention, net_packets.tun0 (tun0), outbound packets dropped ratio = 0.33%"
```
I didn't pay attention to these and yesterday my server froze and went unreachable. I had to force a reboot to cover it. I have full details on the [serverfault](https://serverfault.com/questions/982166/tun0-errors-when-running-a-vpn-server) post I mentioned earlier.

I checked my server logs ( `/var/log/syslog/` & `kern.log` ) and didn't find anything specific to this problem. they were only a bunch of `[UFW BLOCK]` reports blocking random ip's on different ports.

Can anyone help me with this?

**Comment by Nyr** [comment]
Your problem doesn't have anything to do with this script.

If your server lost connectivity, that almost surely had nothing to do with OpenVPN. If you are in China, the server IP could've been temporally banned. Or it can be any other issue, but that is not a problem with this installer.
