### ISSUE TITLE
How to configure user password authentication login?

### ISSUE THREAD

**Issue by wateras** [Nyr/openvpn-install#652]
How to configure user password authentication login? At present, I have tried all the methods according to the online method, such as adding in server.conf.
Auth-user-pass-verify /usr/local/open***/etc/checkpsw.sh via-env
Client-cert-not-required
Username-as-common-name
Both checkpsw.sh and psw-file have been added.
Add in ovpn file
Auth-user-pass

**Comment by Nyr** [comment]
This is not an issue with the script.

I'd suggest to read the OpenVPN manual and understand what you are doing instead of copy-pasting information from unreliable sources.
