### ISSUE TITLE
iptables rule for AWS lightsail VPS

### ISSUE THREAD

**Issue by DonZheng** [Nyr/openvpn-install#653]
Hi Nyr,

I happened to try your masterpiece script on aws lightsail and experienced an interesting issue.

Environment: AWS Lightsail VPS (Ubuntu 18.04); No firewall (all ports open)

The script runs successfully. Openvpn client can successfully connects to server. After connecting to the VPN server, client cannot access Internet.

I have googled it and make following manual changes to make it work:
1. nano /etc/sysctl.conf; Then uncomment option to get "net.ipv4.ip_forward=1"
2. Flush iptables nat rules (created as part of script) then add below rule:
iptables -t nat -A POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE

Then issue fixed.

I am no expert in iptables. Wondering if the 'iptables -t nat -A POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE' shall replace equivalent command(s) in the script to make it run unattendedly on AWS lightsail (and probably ec2) machines?

Appreciate it very much if you can share your expertise on the subject.

Kind Regards,

Don

**Comment by Nyr** [comment]
It is very likely that you did set up the installer incorrectly. I'm not familiar with Lightsail, but I guess that they are using NAT internally to do networking.

See here for how to set up NAT correctly: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353
