### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by edw71** [Nyr/openvpn-install#655]
First, thanks for making this script available!

I have tried, so far unsuccessfully, to add 2 factor authentication.
Have you planned to do that?
Or can you provide a hint how you would go about to add that?

Thanks
Wolfgang

**Comment by Nyr** [comment]
No plans to add support for that.

For general OpenVPN questions this is not the right place to ask, but how to implement it would vary depending on the 2FA method you want to use.
