### ISSUE TITLE
/etc/openvpn/server/EasyRSA-3.0.5/  not found

### ISSUE THREAD

**Issue by yidane1981** [Nyr/openvpn-install#656]
Thank you for you shell.
Some directory and file not found.I need help.

mv: 无法获取"/etc/openvpn/server/EasyRSA-3.0.5/" 的文件状态(stat): 没有那个文件>或目录
chown: 无法访问"/etc/openvpn/server/easy-rsa/": 没有那个文件或目录
./openvpn-install.sh: line 238: cd: /etc/openvpn/server/easy-rsa/: 没有那个文件>或目录
./openvpn-install.sh: line 240: ./easyrsa: 没有那个文件或目录
./openvpn-install.sh: line 241: ./easyrsa: 没有那个文件或目录
./openvpn-install.sh: line 242: ./easyrsa: 没有那个文件或目录
./openvpn-install.sh: line 243: ./easyrsa: 没有那个文件或目录
./openvpn-install.sh: line 244: ./easyrsa: 没有那个文件或目录
cp: 无法获取"pki/ca.crt" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"pki/private/ca.key" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"pki/issued/server.crt" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"pki/private/server.key" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"pki/crl.pem" 的文件状态(stat): 没有那个文件或目录
chown: 无法访问"/etc/openvpn/server/crl.pem": 没有那个文件或目录
./openvpn-install.sh: line 349: /etc/systemd/system/openvpn-iptables.service: 没
有那个文件或目录
./openvpn-install.sh: line 350: systemctl: command not found
./openvpn-install.sh: line 365: systemctl: command not found
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: 没有那个文件或目录

**Comment by Nyr** [comment]
What distribution and version are you using?

**Comment by yidane1981** [comment]
vps in hostwinds.
Linux version 4.18.20-1.el6.elrepo.x86_64 (mockbuild@Build64F28) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)) #1 SMP Wed Nov 21 18:11:58 EST 2018
And lastest shell.

**Comment by Nyr** [comment]
CentOS 6 is too old and unsupported by the installer.

You should consider upgrading to CentOS 7, which was released 5 years ago already.
