### ISSUE TITLE
server.conf path is not right after upgrading system

### ISSUE THREAD

**Issue by KiritoStudio** [Nyr/openvpn-install#657]
Hi, 
I have upgrade my OS from Ubuntu 16.04 to 18.04. But the server.conf path not changed and the new script will always ask me to install new openvpn.
new script config path: /etc/openvpn/server/server.conf
my script config path: /etc/openvpn/server.conf

**Comment by Nyr** [comment]
The older version should always be used until you decide to reinstall. If you no longer have that version, it can be downloaded again from GitHub, check the commit history of this repository.
