### ISSUE TITLE
Whitelist support?

### ISSUE THREAD

**Issue by aadrian** [Nyr/openvpn-install#659]
Hi,

Any chance adding support for "whitelist"?
E.g. if there's a `whitelist.txt` with content like:
```
...
route-nopull
route 1.2.3.4
route 1.2.3.5
route 1.2.3.6
route 1.2.3.7
...
```
to include it in the generated `*.ovpn` files?

This would allow to avoid post-processing the generated `*.ovpn` files and ensure that the VPN is routing only to those IP addresses.

Thank you.

**Comment by Nyr** [comment]
Nah, this is very niche sorry.

If needed, you must do it yourself.
