### ISSUE TITLE
Reconfigure setting

### ISSUE THREAD

**Issue by hadan** [Nyr/openvpn-install#661]
Is it possible to reconfigure openvpn setting without uninstalling the openvpn server

**Comment by Nyr** [comment]
Can you be more specific in what you want to reconfigure?

If you want to upgrade to the latest client and server configuration files then no, they need to be redeployed and there is no way around that.

**Comment by hadan** [comment]
like setting different port, protocol(tcp/udp),etc.

**Comment by Nyr** [comment]
You could change the port and/or protocol manually in the client and server configuration files.
