### ISSUE TITLE
Network feature

### ISSUE THREAD

**Issue by Patatone** [Nyr/openvpn-install#662]
In the main menu can you add a "Configure network again" option?
Two days ago i flushed all the iptables rules and would have been useful set all the rules with a simple script.
Thanks for reading :)

**Comment by Nyr** [comment]
You can do that already! The rules will be applied again when rebooting the server.

If you don't want to reboot and are running a recent version of the script, apply them by running:
`systemctl start openvpn-iptables.service`

If running an older version, iptables rules are saved in:
`/etc/rc.local`

That is for Debian/Ubuntu, CentIOS uses firewalld which is a different matter.
