### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by buzz3rs** [Nyr/openvpn-install#663]
i tired installing OpenVPN and followed the instructions you gave but after successfully connecting to the vpn i cant access google.com or any google platform for some reason although i have your l2tp vpn setup and working just fine

**Comment by Nyr** [comment]
You can't access the internet or you can't access the Google network in particular?

Can you ping an IP address while connected? (Is this a DNS problem or a connectivity problem?)

**Comment by andre-paulo98** [comment]
This is also happening to me. I had a fully working OpenVPN server yesterday or 2 days ago, and today when I'm connected to the VPN I can't ping anything, I can't open websites. `grep ovpn /var/log/syslog` returned empty.
I haven't changed anything in this server for a month.

**Comment by Nyr** [comment]
@andre-paulo98 that must be a problem in your side.

- What distribution are you running in the server?
- Provide the client connection log
- Provide the output of `systemctl status openvpn-server@server.service`
- Does your server have a dynamic IP address? (for example. Google Compute Engine)

**Comment by andre-paulo98** [comment]
- _What distribution are you running in the server?_ Debian 7
- _Provide the client connection log_ [here](https://gist.github.com/andre-paulo98/a72aaabb0d8e6aae637ae083946a0c63)
- _Provide the output of `systemctl status openvpn-server@server.service`_ not found on Debian
- _Does your server have a dynamic IP address? (for example. Google Compute Engine)_ No, it's on LES

**Comment by Nyr** [comment]
> Debian 7

Woah. That is a **very** old version, worst I've seen in a long time to be honest. Debian 7 itself became unsupported more than 3 years ago, so you can't expect to run anything there, much less a secure OpenVPN installation.

I suggest that you upgrade to Debian 10 and use the latest version of the script. An upgrade is really needed.

If your LES provider doesn't offer a modern version of Debian, that's likely because they are running OpenVZ 6, which is very old itself and will become unsupported next month. If that's the case, Ubuntu 16.04 or CentOS 7 are probably your best possible choices right now, but your provider should be planning an upgrade very soon.

But if you have a choice, I suggest one of the following:
- Debian 10 (or 9 if you can't do better)
- Ubuntu 18.04
- CentOS 8 (or 7 if you can't do better)

**Comment by andre-paulo98** [comment]
Yeah, I'll try to do that then. Thank you.

**Comment by andre-paulo98** [comment]
Getting the exact same issue.

What distribution are you running in the server?
Ubuntu 18

Provide the client connection log: [here](https://gist.github.com/andre-paulo98/e1037512d62233cc4d1f2befdf7df686#file-new-client-log)

Provide the output of systemctl status openvpn-server@server.service: [here](https://gist.github.com/andre-paulo98/e1037512d62233cc4d1f2befdf7df686#file-systemctl-log)

**Comment by Nyr** [comment]
Did you configure the NAT correctly? Some LES hosts use one IP address for inbound and a different one for outbound.

If the server networking is configured correctly, this could be a client side issue, try with a different client device if you can.

**Comment by andre-paulo98** [comment]
> Did you configure the NAT correctly? Some LES hosts use one IP address for inbound and a different one for outbound.

I'm using Inception Hosting. I wasn't aware of different IPs for inbound and outbound, but this has been working for 9 months or so now. I will try confirm it.

> If the server networking is configured correctly, this could be a client side issue, try with a different client device if you can.

I've tried with my phone (Huawei P Smart 2018) and got the same issue.

**Comment by buzz3rs** [comment]
> You can't access the internet or you can't access the Google network in particular?
> 
> Can you ping an IP address while connected? (Is this a DNS problem or a connectivity problem?)

i'm positive its a DNS problem because i can access the internet, just not google.
i tried all the DNS options during the installation (1-5) with no avail

**Comment by buzz3rs** [comment]
i can share the ovpn file if you want

**Comment by buzz3rs** [comment]
I have just confirmed that i can ping google.com but i cant access it so its a dns problem
i can access FaceBook.com , Telegram.org etc, but not google

**Comment by buzz3rs** [comment]
Fixed.
changed protocol from UDP to TCP and everything worked just fine Thanks
