### ISSUE TITLE
tls-crypt unwrap error: packet too short

### ISSUE THREAD

**Issue by luutruong** [Nyr/openvpn-install#666]
I have faced this error. Setup all defaults.

server.conf contents:
```
local XXX.XXX.XXX.XXX
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nobody
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
explicit-exit-notify
```

Also if I run this command `service openvpn@server restart` that cause the file `/etc/openvpn/server.conf` does not exists.

And for this comment `service openvpn restart` that cause error: `Failed to restart openvpn.service: Unit not found.`

**Comment by Nyr** [comment]
> tls-crypt unwrap error: packet too short

Two options:

- Your client is old/non standard and has issues with `tls-crypt`
- Some kind connectivity issue, try over TCP if you are actually running UDP.

This is 100% a problem in your side, probably one of those options.

> Also if I run this command service openvpn@server restart that cause the file /etc/openvpn/server.conf does not exists.

Use this:
`systemctl restart openvpn-server@server.service`
