### ISSUE TITLE
Unable to Start OpenVPN on Ubuntu 18.04

### ISSUE THREAD

**Issue by ACA30** [Nyr/openvpn-install#669]
On a brand new Ubuntu 18.04 system, I ran the script on the root user, selecting `UDP`, port `443` (restrictive network I'm trying to run this on, but no webservices on the VPS so it shouldn't conflict with anything), `1.1.1.1` DNS, and default `client` name.

Throughout the script, there are a few RNG errors like
```
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140255124357568:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
```
However it seems to finish just fine, and still gives `Finished!` message.

I then type `systemctl status openvpn@server`, and it gives the following output:
```
systemctl status openvpn@server
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset
   Active: inactive (dead)
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
```
Even trying to systemctl stop it, then start it, and also restarting it, it doesn't work. I've also tried rebooting the VPS. Any ideas what could be going on and how to fix?

Thanks! :)

**Comment by Nyr** [comment]
> Throughout the script, there are a few RNG errors

This message is not from the script but from one of the external dependencies it uses. It can be ignored.

> I then type systemctl status openvpn@server, and it gives the following output:

The service has a different name, try this instead:

`systemctl status openvpn-server@server.service`
