### ISSUE TITLE
I have a problem on Centos 7

### ISSUE THREAD

**Issue by wipau** [Nyr/openvpn-install#670]
At first install, i can connect server well and surf websites. But after server restart it connect to vpn server but cant reach any website what can i do ? is it a firewall problem or gateway ? i dont know exactly what can i do ?
Each server restart I reinstall openvpn to work with it.

additional
im using TCP port
Server VMware VDS

**Comment by Nyr** [comment]
Ater restarting the server, run the following commands:

```
firewall-cmd --add-port=$port/$protocol
firewall-cmd --zone=trusted --add-source=10.8.0.0/24
firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $ip
```
Replace the following variables:
`$port` = the port you selected during setup
`$protocol` = tcp
`$ip` = IP address of the server

Does it start working again after that? If so, you have a firewall conflict which is removing or superseding the rules set by the installer.

**Comment by wipau** [comment]
When I try run the command shell gives me this message
`
FirewallD is not running
`
Also in my VDS Centos Webpanel installed too. Problem is the CWP ?

**Comment by Nyr** [comment]
Your server has FirewallD disabled, which is usually enabled by default in CentOS.

You can try running:
`systemctl start openvpn-iptables.service`

Other than that, you are running a custom configuration so you are on your own.
