### ISSUE TITLE
Password and Certificate for Client

### ISSUE THREAD

**Issue by SoloTalent** [Nyr/openvpn-install#675]
Hello,

it is possible to add a password Question for each Client that is generated by this code? The Client have to connect to the Server and have to enter a password for the connection. For example a new topic at the selection menu (2.) Add a new User with password.

In the OpenVPN tutorial (https://openvpn.net/community-resources/how-to/) this function is used:
"If you would like to password-protect your client keys, substitute the build-key-pass script."

I hope you can help me.

**Comment by Nyr** [comment]
There are two lines in the script like this:

`EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-client-full "$client" nopass`

Remove the `nopass` part and you will be prompted for a password every time you add a new user.
