### ISSUE TITLE
EasyRSA no such file error

### ISSUE THREAD

**Issue by BustedSec** [Nyr/openvpn-install#676]
The following output should be useful:

mv: cannot stat '/etc/openvpn/server/EasyRSA-3.0.5/': No such file or directory
chown: cannot access '/etc/openvpn/server/easy-rsa/': No such file or directory
openvpn-install.sh: line 305: cd: /etc/openvpn/server/easy-rsa/: No such file or directory
openvpn-install.sh: line 307: ./easyrsa: No such file or directory
openvpn-install.sh: line 308: ./easyrsa: No such file or directory
openvpn-install.sh: line 309: ./easyrsa: No such file or directory
openvpn-install.sh: line 310: ./easyrsa: No such file or directory
openvpn-install.sh: line 311: ./easyrsa: No such file or directory
cp: cannot stat 'pki/ca.crt': No such file or directory
cp: cannot stat 'pki/private/ca.key': No such file or directory
cp: cannot stat 'pki/issued/server.crt': No such file or directory
cp: cannot stat 'pki/private/server.key': No such file or directory
cp: cannot stat 'pki/crl.pem': No such file or directory
chown: cannot access '/etc/openvpn/server/crl.pem': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-iptables.service → /etc/systemd/system/openvpn-iptables.service.
Failed to enable unit: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/ca.crt: No such file or directory
sed: can't read /etc/openvpn/server/easy-rsa/pki/issued/Havok.crt: No such file or directory
cat: /etc/openvpn/server/easy-rsa/pki/private/Havok.key: No such file or directory

running on:
Linux vps 2.6.32-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Nyr** [comment]
I guess that you are running this on OpenVZ and a very old distribution, right?

You need to run a newer distribution, not only for this script but for security/compatibility reasons.
