### ISSUE TITLE
Add wget and tar as installs for Centos 8 minimal install.

### ISSUE THREAD

**Issue by joshuagordondba** [Nyr/openvpn-install#679]
I have been testing this on centos 8 minimal installs.
The minimal install of Centos 8 does not have tar or wget. I would suggest adding this to the install on the epel-release line. like the following.
Change this line
yum install epel-release -y
to this line
yum install epel-release wget tar -y
I have other suggestions for how to harden this by default if you would like.

**Comment by Nyr** [comment]
I'm pretty sure that CentOS 8 netinst carries curl, so wget wouln't be needed. tar is also available.

If your provider is supplying a CentOS 8 "minimal" custom image which lacks those packages, that's a different matter. Where are you seeing this? Name the provider, please.
