### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by nleo** [Nyr/openvpn-install#68]
I was always scared about setup openvpn server. It was seems to me very complicated and overheading.  With this script setup and managing vpn very simple. Thanks!

**Comment by Nyr** [comment]
Happy to help :)

**Comment by Shawak** [comment]
Indeed, this script is close to being perfect.

**Comment by laapsaap** [comment]
+1

**Comment by Nyr** [comment]
Thanks for your words.
