### ISSUE TITLE
 • 'comp-lzo' was deprecated in OpenVPN 2.4 and has been or will be removed in a later version

### ISSUE THREAD

**Issue by pianolinux** [Nyr/openvpn-install#682]
Hi i get this pop up when i try to connect to the vpn.. 

Warning: This VPN may not connect in the future.

The OpenVPN configuration file for 'mac' contains these OpenVPN options:

 • 'comp-lzo' was deprecated in OpenVPN 2.4 and has been or will be removed in a later version

You should update the configuration so it can be used with modern versions of OpenVPN.

Tunnelblick will use OpenVPN 2.4.7 - OpenSSL v1.0.2t to connect this configuration.

However, you will not be able to connect to this VPN with future versions of Tunnelblick that do not include a version of OpenVPN that accepts the options.

THIS pops up when i connect with the VPN client "TunnelBlick"
I've been using this client and the VPN script for a long time now, this just happened.

**Comment by TinCanTech** [comment]
@Nyr Please see: https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--comp-lzo

Looks like Tunnelblick is jumping the gun a touch.

**Comment by Nyr** [comment]
> I've been using this client and the VPN script for a long time now, this just happened.

I'm sure, because the script hasn't enabled compression for a long time already :)

Tunnelblick is trying to be helpful but indeed, they jumped the gun on this. This is a non-issue and has already been reported multiple times here. I'll open an issue with Tunnelblick.

**Comment by Nyr** [comment]
From the [original issue](https://github.com/Nyr/openvpn-install/issues/430#issuecomment-371153523):

> you can avoid that warning switching from `comp-lzo` to `compress lzo` in your client.
