### ISSUE TITLE
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

### ISSUE THREAD

**Issue by zemelax** [Nyr/openvpn-install#683]
good day. I am a beginner, and I can’t understand why on the client side(ubuntu) I can’t join the server(ubuntu). 3 days of torment, can someone help me?

Sun Nov 24 16:22:00 2019 Unrecognized option or missing or extra parameter(s) in /etc/openvpn/user.conf:17: block-outside-dns (2.4.4)
Sun Nov 24 16:22:00 2019 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Sun Nov 24 16:22:00 2019 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Sun Nov 24 16:22:00 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sun Nov 24 16:22:00 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Nov 24 16:22:00 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sun Nov 24 16:22:00 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Nov 24 16:22:00 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]18.195.117.16:1194
Sun Nov 24 16:22:00 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Nov 24 16:22:00 2019 UDP link local: (not bound)
Sun Nov 24 16:22:00 2019 UDP link remote: [AF_INET]18.195.117.16:1194
Sun Nov 24 16:23:00 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Nov 24 16:23:00 2019 TLS Error: TLS handshake failed
Sun Nov 24 16:23:00 2019 SIGUSR1[soft,tls-error] received, process restarting
Sun Nov 24 16:23:00 2019 Restart pause, 5 second(s)
Sun Nov 24 16:23:05 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]18.195.117.16:1194
Sun Nov 24 16:23:05 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Nov 24 16:23:05 2019 UDP link local: (not bound)
Sun Nov 24 16:23:05 2019 UDP link remote: [AF_INET]18.195.117.16:1194

**Comment by zemelax** [comment]
client
proto udp
remote 18.195.117.16 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_OJpfwodPYe1k0EmR name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3

**Comment by zemelax** [comment]
it seems there was a problem with the port

**Comment by Nyr** [comment]
Glad you solved it, please do not open issues in this issue tracker if you aren't using this project.

**Comment by cjrutherford** [comment]
@zemelax can you detail your fix?

**Comment by zemelax** [comment]
> @zemelax can you detail your fix?


I have already forgotten. perhaps it was necessary to open port 1194. on client or server

**Comment by Nyr** [comment]
This error is usually a sign of some kind of connectivity issue.
