### ISSUE TITLE
TLS Handshake Failed

### ISSUE THREAD

**Issue by parsanoori** [Nyr/openvpn-install#684]
I completely reseted IPTables and installed OpenVPN but still get TLS Handshake Failed.
Here's my logs on Tunnelblick client.
[Tunnelblick Logs](https://dl.dropboxusercontent.com/s/cr198xvv6j5wzup/Tunnelblick%20Logs.rtf?dl=0)

**Comment by Nyr** [comment]
You are trying to connect to a server in Iran so the most plausible explanation would be network censorship. I would suggest to try Shadowsocks if you want to evade network filtering.

**Comment by parsanoori** [comment]
It's my own VPS in the country I can use SSH on it and have configured SSH on it successfully.
So I definitely have access to it.

**Comment by Nyr** [comment]
Yes, but OpenVPN is a different protocol. which is filtered in Iran, along with lots of other content.

Not idea why would you need a VPS there (maybe accessing some Persian content?), but I would suggest considering a VPS in a country with reliable and uncensored internet connections instead, if that's possible.
