### ISSUE TITLE
client have not internet access after reboot

### ISSUE THREAD

**Issue by A2116** [Nyr/openvpn-install#685]
Dear sir
I installed OpenVPN server on centos by your script and default configuration
and i tested it with default account that produced in setup procedure and it worked without a problem
but after server reboot connection performed but I have no internet behind it
in same time I have internet access and DNS on my server but I have not access on my client and on ping it prompt me request time out, what should i do?

**Comment by A2116** [comment]
problem is for openvpn-iptables services
I added these lines on the end of rc.local

sleep 120
service openvpn-iptables restart
service openvpn-server@server restart

**Comment by A2116** [comment]
the problem is occurred because of failure of openvpn-iptables.service
the error is:

Process: 1579 ExecStop=/sbin/iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 198.143.178.85 (code=exited, status=1/FAILURE)

**Comment by rbrondgeest** [comment]
Check your system logs

**Comment by Nyr** [comment]
CentOS usually has firewalld enabled, but it wasn't in your system because the service got installed apparently.

Anyway, script would also work using the iptables service if firewalld is not available but yeah, you would need to see why iptables is failing.

**Comment by A2116** [comment]
Dear sir
thank you for your answer
I solved the problem by restarting service multiple times in rc.local with
60-second interval
but I think it's because of iptables not work properly because one or more
services not started on time of starting your services

with best regards

**Comment by Nyr** [comment]
Well, the service is started `Before=network.target` which is where it should be started in my opinion. Maybe your system is starting something after that which is overriding the rules set by the service, but as far as I know, we're doing it right.

**Comment by A2116** [comment]
Thank you for your reply
another problem that i have is if i want to reset my server os or move to
another server, how can i backup user accounts and how can i restore them
on the target?

**Comment by Nyr** [comment]
That would imply using a domain so users don't have to reconfigure the IP address, backing up the contents of `/etc/openvpn/server` and restoring the iptables/firewalld configuration.
