### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by joebass85** [Nyr/openvpn-install#686]
Hi @Nyr 

I love your script and the fact that you have made setting up OpenVPN so easy. I am new to VPNs and I am struggling to connect my client machine to the VPN server I created. Maybe you could include this in the README or point me to a place that will have an answer?

Thanks! 
- Joe

**Comment by Nyr** [comment]
The steps would be:

- Grab the .ovpn file from the server (this would require SCP or SFTP and how to do it depends on your client system but you can easily search Google to find instructions).
- Install a OpenVPN client (which again, depends on your client operating system) and use it with the .ovpn file to establish the VPN connection.

I hope this helps.

**Comment by joebass85** [comment]
@Nyr 

Awesome! I'll be sure to try that later. Thanks!
