### ISSUE TITLE
Installation dont work

### ISSUE THREAD

**Issue by Niore** [Nyr/openvpn-install#688]
Got the following after executing the script

Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease                                                                                                                                        
Hit:2 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease                                                                                                          
0% [Connecting to archive.raspberrypi.org (2a00:1098:0:82:1000:13:0:6)]                                                 

Does not continue after this. Trying to install on a rasperry pi

**Comment by rbrondgeest** [comment]
What package is it trying to download? Try to confirm that your raspberry pi can access this package. It might be that your internet provider, home network, or your Pi is somehow blocking that request.

**Comment by Nyr** [comment]
This is not a problem with the script, looks like a connectivity problem with the repository.

Solutions:
- Switch to a different mirror
- Is your IPv6 connectivity working correctly? If not, disable it.
