### ISSUE TITLE
i got an error in the script

### ISSUE THREAD

**Issue by Goddard** [Nyr/openvpn-install#689]
I know pretty much nothing about openvpn, but wanted to use your script to ease my life.  Got an error though.

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140502919942592:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd

**Comment by Goddard** [comment]
Looks like everything still works though.  Client and Server are Ubuntu.

**Comment by Nyr** [comment]
This issue is with an external library which I can't resolve from my side, but can be safely ignored.

Next time use the search engine, this has been reported multiple times.
