### ISSUE TITLE
Use easy-rsa 3.0.0 instead of 2.2.2

### ISSUE THREAD

**Issue by iceTwy** [Nyr/openvpn-install#69]
[easy-rsa 3.0.0](https://github.com/OpenVPN/easy-rsa/releases) was released a week ago, it would be great if we could migrate to this version over time instead of the current one.

The main change for openvpn-install is that the PKI creation, DH parameters generation, and some other binaries have been merged into a single easy-rsa binary. I'll try to make a PR over the weekend.

**Comment by Nyr** [comment]
Don't waste your time, I'm already on it and have spent most of my time today on this and other tasks related to the script.

A new, big commit will be published soon™ which will include at least easy-rsa 3.0 and multiple important fixes for some bugs. Probably other improvements I have in mind too :)

**Comment by Nyr** [comment]
Check https://github.com/Nyr/openvpn-install/commit/eb8d8257a01d0247535f848c3ac370b992e0d4a3 :)
