### ISSUE TITLE
Can't start on ubuntu 18.04

### ISSUE THREAD

**Issue by tidusvn05** [Nyr/openvpn-install#693]
i install complete but service not start.

this is log

------
-- Unit openvpn-server@server.service.service has begun starting up.
Dec 12 19:16:53 ip-10-20-31-31 openvpn[14851]: Options error: In [CMD-LINE]:1: Error opening configuration file: server.service.conf
Dec 12 19:16:53 ip-10-20-31-31 openvpn[14851]: Use --help for more information.
Dec 12 19:16:53 ip-10-20-31-31 systemd[1]: openvpn-server@server.service.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 19:16:53 ip-10-20-31-31 systemd[1]: openvpn-server@server.service.service: Failed with result 'exit-code'.
Dec 12 19:16:53 ip-10-20-31-31 systemd[1]: Failed to start OpenVPN service for server.service.
-- Subject: Unit openvpn-server@server.service.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit openvpn-server@server.service.service has failed.
-------

problem about config path, i not known why.

anyone can help me?

thanks

**Comment by Nyr** [comment]
That's very weird...

Try to run this:
`systemctl enable --now openvpn-server@server`

And maybe also this:
`systemctl enable --now openvpn-iptables`

I can see what is going on, but not why is this happening in your system. Someone else has a clue?

**Comment by lukebarone** [comment]
Why is it trying on openvpn-server@server.service.service? Should there
only be one "service" at the end?
