### ISSUE TITLE
server.conf

### ISSUE THREAD

**Issue by fwt-dot-fr** [Nyr/openvpn-install#695]
After running the very good script openvpn-install.sh i want in the server configuration file /etc/openvpn/server/server.conf to have the choice in the option server an other IP range.
The fixed script choise is on line 339: 
server 10.8.0.0 255.255.255.0

How to change ?
Re-install all ?

Server option could be a variable.

I want to setup to:
server 172.18.0.0 255.255.0.0

**Comment by timdream** [comment]
@fwt-dot-fr I am pretty sure it would work if you do string replacement from `10.8.0.0` to `172.18.0.0` *before* the running script. If you have already run the script, consider running it again before changing and choose the uninstall option to remove existing configurations.

**Comment by Nyr** [comment]
Exactly as @timdream said.

You could of course modify your existing installation if you wish, search the installer for the `10.8.0` string to see what needs to be changed.

**Comment by fwt-dot-fr** [comment]
It seems working well.
I have writen a patch on debian 10.
Problem to test it on line 172:
ip=$(firewall-cmd --direct --get-rules ipv4 nat POSTROUTING | grep '\-s 10.8.0.0/24 '"'"'!'"'"' -d 10.8.0.0/24 -j SNAT --to ' | cut -d " " -f 10)
Who can verify and test it on Ubuntu and CentOS ?

**Comment by Nyr** [comment]
You just need to change the numbers, all the coincidences and it will work.

**Comment by fwt-dot-fr** [comment]
I start the patch by :
MyServerHostIpRange="172.18.0.0"
MyServeSubnetMask="255.255.0.0"
MyServerCidr="16"
MyServerHostIpRangeCidr="${MyServerHostIpRange}/${MyServerCidr}"

to have the possibilité the have variables.
