### ISSUE TITLE
OpenVPN weird messages

### ISSUE THREAD

**Issue by orgitnized** [Nyr/openvpn-install#697]
I guess there are just things I don't understand, and I'm going to plead ignorant.
Installing on Ubuntu 18.04.3
While I can see that overall the installation works, it seems like things aren't in place the way I'd suspect them to be.
So here's a portion of my install log:

```
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140300302754240:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
```
/edit - read this: https://github.com/Nyr/openvpn-install/issues/689
Ok, got it.

Then I'll go through wanting to make a change to the server config, which is here `/etc/openvpn/server/server.conf` and I've never seen it there before, nor can I find any supporting documentation that states it should be placed there.  My understanding is that it goes here `/etc/openvpn/server.conf` instead.

I have a monitoring app that watched the logfile for `/etc/openvpn/openvpn-status.log` but yours is `/etc/openvpn/server/openvpn-status.log` - and when I restart the service after making the changes in server.conf to point there after moving the file, it will not write to the file.

Performing restarts on OpenVPN via `systemctl restart openvpn.service` constantly show logs like:

```
Dec 24 13:06:26 vpnsrv1 systemd[1]: Stopped OpenVPN connection to server.
Dec 24 13:06:26 vpnsrv1 systemd[1]: Starting OpenVPN connection to server...
Dec 24 13:06:26 vpnsrv1 systemd[1]: Stopped OpenVPN connection to service.
Dec 24 13:06:26 vpnsrv1 systemd[1]: Starting OpenVPN connection to service...
Dec 24 13:06:26 vpnsrv1 ovpn-service[18187]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/service.conf
Dec 24 13:06:26 vpnsrv1 ovpn-server[18186]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf
Dec 24 13:06:26 vpnsrv1 ovpn-server[18186]: Use --help for more information.
Dec 24 13:06:26 vpnsrv1 ovpn-service[18187]: Use --help for more information.
Dec 24 13:06:26 vpnsrv1 systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:26 vpnsrv1 systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
Dec 24 13:06:26 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to server.
Dec 24 13:06:26 vpnsrv1 systemd[1]: openvpn@service.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:26 vpnsrv1 systemd[1]: openvpn@service.service: Failed with result 'exit-code'.
Dec 24 13:06:26 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to service.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@server.service: Service hold-off time over, scheduling restart.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@server.service: Scheduled restart job, restart counter is at 188.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@service.service: Service hold-off time over, scheduling restart.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@service.service: Scheduled restart job, restart counter is at 186.
Dec 24 13:06:31 vpnsrv1 systemd[1]: Stopped OpenVPN connection to service.
Dec 24 13:06:31 vpnsrv1 systemd[1]: Starting OpenVPN connection to service...
Dec 24 13:06:31 vpnsrv1 systemd[1]: Stopped OpenVPN connection to server.
Dec 24 13:06:31 vpnsrv1 systemd[1]: Starting OpenVPN connection to server...
Dec 24 13:06:31 vpnsrv1 ovpn-service[18192]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/service.conf
Dec 24 13:06:31 vpnsrv1 ovpn-service[18192]: Use --help for more information.
Dec 24 13:06:31 vpnsrv1 ovpn-server[18193]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf
Dec 24 13:06:31 vpnsrv1 ovpn-server[18193]: Use --help for more information.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@service.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@service.service: Failed with result 'exit-code'.
Dec 24 13:06:31 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to service.
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:31 vpnsrv1 systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
Dec 24 13:06:31 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to server.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@service.service: Service hold-off time over, scheduling restart.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@service.service: Scheduled restart job, restart counter is at 187.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@server.service: Service hold-off time over, scheduling restart.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@server.service: Scheduled restart job, restart counter is at 189.
Dec 24 13:06:36 vpnsrv1 systemd[1]: Stopped OpenVPN connection to server.
Dec 24 13:06:36 vpnsrv1 systemd[1]: Starting OpenVPN connection to server...
Dec 24 13:06:36 vpnsrv1 systemd[1]: Stopped OpenVPN connection to service.
Dec 24 13:06:36 vpnsrv1 systemd[1]: Starting OpenVPN connection to service...
Dec 24 13:06:36 vpnsrv1 ovpn-service[18199]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/service.conf
Dec 24 13:06:36 vpnsrv1 ovpn-service[18199]: Use --help for more information.
Dec 24 13:06:36 vpnsrv1 ovpn-server[18198]: Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/server.conf
Dec 24 13:06:36 vpnsrv1 ovpn-server[18198]: Use --help for more information.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
Dec 24 13:06:36 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to server.
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@service.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:06:36 vpnsrv1 systemd[1]: openvpn@service.service: Failed with result 'exit-code'.
Dec 24 13:06:36 vpnsrv1 systemd[1]: Failed to start OpenVPN connection to service.
support@vpnsrv1:/etc/openvpn/server$ sudo systemctl status openvpn.service
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2019-12-24 13:05:00 CST; 2min 26s ago
  Process: 18006 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 18006 (code=exited, status=0/SUCCESS)

```

Yet...it shows the service is started, despite the errors...and it still looks like it's trying to open the conf files in the location that I'm used to.

So for a quick and dirty way to get OpenVPN operational, it works, but it also looks like it operates in a way that conflicts with the usual way I'm used to it working if I were to set it up from scratch.

Maybe none of this matters to anyone and doesn't need to be fixed - it's just weird to me that I see messages I wouldn't expect to see.

**Comment by Nyr** [comment]
> Then I'll go through wanting to make a change to the server config, which is here /etc/openvpn/server/server.conf and I've never seen it there before, nor can I find any supporting documentation that states it should be placed there. My understanding is that it goes here /etc/openvpn/server.conf instead.

Your understanding is wrong and I already told you in an email. That's the new place used by the new systemd service file and shouldn't be changed.

> I have a monitoring app that watched the logfile for /etc/openvpn/openvpn-status.log but yours is /etc/openvpn/server/openvpn-status.log

Fix your monitoring.

> Performing restarts on OpenVPN via systemctl restart openvpn.service constantly show logs like:

You should be using`systemctl restart openvpn-server@server.service`

> and it still looks like it's trying to open the conf files in the location that I'm used to.

Because that's the old service file, kept for compatibility purposes.

> So for a quick and dirty way to get OpenVPN operational, it works, but it also looks like it operates in a way that conflicts with the usual way I'm used to it working if I were to set it up from scratch.

The script sets it up the right and modern way, so I suggest that you get used to that.

> Maybe none of this matters to anyone and doesn't need to be fixed

That's indeed the case. I already told you by email. I am replying again publicly for anyone else wondering. My time is limited, so please don't keep contacting me if you don't find a real issue with the script. Try to use other OpenVPN support channels if you need help for your specific setup or expectations, please.

**Comment by TinCanTech** [comment]
>  it's just weird to me that I see messages I wouldn't expect to see.

We feel the same way .. _learn to code_.
