### ISSUE TITLE
OpenVPN Version

### ISSUE THREAD

**Issue by taskinsabah** [Nyr/openvpn-install#699]
May I kindly ask you that when I install openvpn and check it's version is OpenVPN 2.4.4 x86_64-pc-linux-gnu.  There is a new release on openvpn official webpage which is OpenVPN 2.4.8 — released on 2019.10.31. Why we are using 2.44 instead of 2.4.8? Thank you for your helps..

**Comment by Nyr** [comment]
Because that's the version carried by your distribution's repositories.

You can configure the official OpenVPN repository if you wish and the script will install from it but generally speaking, I would suggest to use your distro's, except if you have a reason to do otherwise.
