### ISSUE TITLE
Traffic do not change IP

### ISSUE THREAD

**Issue by zdarin** [Nyr/openvpn-install#700]
Hi, it is possible to do that not all traffic will be transmitted i need IP stay same where i connecting
Example i go to work ip 1.1.1.1 connect to home vpn server and my ip stay same 1.1.1.1 but can access my home apps. Home ip 2.2.2.2

**Comment by Nyr** [comment]
You mean a VPN without redirecting internet traffic over the tunnel?

Yes, remove the `push "redirect-gateway def1 bypass-dhcp"` line in `/etc/openvpn/server/server.conf` and restart OpenVPN.
