### ISSUE TITLE
vpn can't connect another device

### ISSUE THREAD

**Issue by strongpapazola** [Nyr/openvpn-install#704]
vpn can't connect another device...how to solve this?

**Comment by Nyr** [comment]
If you are trying to say that a single certificate can't be used in two devices simultaneously, that is working as intended. Create a new certificate for each device.

**Comment by strongpapazola** [comment]
my ubuntu client can ping to server vpn

And my server vpn cant ping to my ubuntu client
Why with this? 
Thank you for your answer

**Comment by Nyr** [comment]
Probably because your Ubuntu client restricts inbound connections.

This has nothing to do with an issue with the script, so please seek further help elsewhere.
