### ISSUE TITLE
Profiles are not saved

### ISSUE THREAD

**Issue by psyguy** [Nyr/openvpn-install#705]
Hi,

I have installed OpenVPN using the script on centos 7. I can make profiles but cannot find the corresponding `.ovpn` files in my (root) directory. Yet, they show up among profiles if I choose 2 (`Revoke an existing user`) on the menu.

Why is this happening, and what can I do about it?

**Comment by Nyr** [comment]
`cd ~/`

They must be there.

**Comment by psyguy** [comment]
I'm afraid there's nothing there but `openvpn-install.sh`.

**Comment by Nyr** [comment]
Try this:
`find / -type f -name "*.ovpn"`

If you still are unable to find anything, provide the full installation log.

**Comment by psyguy** [comment]
Thanks, I noticed what was wrong: I was `sudo`ing with another user while running the installation, and the profiles were saved on root!
Cheers!
