### ISSUE TITLE
Install not working on Ubuntu  18.04

### ISSUE THREAD

**Issue by conligwx** [Nyr/openvpn-install#708]
when I use the commandline as stated to download and install I get the following error at the end.

> 
> Saving to: 'openvpn-install.sh'
> 
> openvpn-install.sh              100%[====================================================>]  17.21K  --.-KB/s    in 0.01s
> 
> 2020-01-17 15:42:11 (1.29 MB/s) - 'openvpn-install.sh' saved [17619/17619]
> 
> Unable to initialize the iptables/netfilter NAT table, setup can't continue.
> Make sure that your system has iptables/netfilter available.
> If using OpenVZ, ask your provider to enable full netfilter support.
> 

I have now installed https://github.com/angristan/openvpn-install package without any issue or additional packages to be added, but your own script wont install.  

I am not sure whats missing since its a new minimal build from yesterday.  I've used your script previously with Debian without any issues.

**Comment by Nyr** [comment]
Sorry for the late (too late) response but I completely missed this issue.

Who is your server provider? What virtualization are they using?

Would be useful if you can provide the output of the following command in your system:
`iptables -t nat -nL`

This error message is shown by the script as a safeguard and can be removed, but it's there for good reason because if the NAT table can't be initialized, routing problems will arise.

**Comment by zettend** [comment]
> Who is your server provider?

MCS Mail.ru



> What virtualization are they using?

KVM

**Comment by Nyr** [comment]
@zettend try running `sudo openvpn-install.sh` even if you are already root and report the results, please.

**Comment by zettend** [comment]
@Nyr 
`sudo: unable to resolve host debian-basic-1-2-10gb: Name or service not known
Unable to initialize the iptables/netfilter NAT table, setup can't continue.
Make sure that your system has iptables/netfilter available.
If using OpenVZ, ask your provider to enable full netfilter support.`

**Comment by Nyr** [comment]
@zettend the message is self explanatory:

> Make sure that your system has iptables/netfilter available

Run `apt-get install iptables` and it will work. The Mail.ru image doesn't have the iptables package installed by default.
