### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Dreadarm** [Nyr/openvpn-install#71]
So I have used this script from you today on 12 new vps from digital ocean. I tried various versions of Ubuntu and Debian. The install goes fast and sets things up well, however, every single time I cannot connect to the internet through the VPN although the VPN itself connects without issue. I can not ping anything either, internal or external.

I do not have any firewalls active and I checked all the configs. I cant seem to locate the issue.

**Comment by Dreadarm** [comment]
I just noticed that the gateway is not showing under the client ipconfig readout for the vpn I manually set the gateway and dns servers and that did not seam to get me anywhere either.

**Comment by Dreadarm** [comment]
Ok so after a lot of toying around and reading about 30 guides on vpn networking... I finally found out that my carrier is t-mobile, and my APN only supports  ipv6 on my phone. So... that  is the  reason the VPN is not working. I had another phone that supports ipv4 and it works fine. so there is nothing wrong with your script as I am sure you knew! however, this does lead me to ask if you can add ipv6 support to your setup script per this article.

https://community.openvpn.net/openvpn/wiki/IPv6

**Comment by Nyr** [comment]
Hello and happy to know you managed to troubleshoot it.

To enable IPv6 transport you just need to change one line in both the client and server config:

`proto udp` to `proto udp6`

Once this is done, restart the server.

Then you just need to edit the client.ovpn and change the remote IPv4 address to one of your server's IPv6.

PS: this will only work with OpenVPN 2.3+

**Comment by Dreadarm** [comment]
Wow so simple! I thought it would be much harder!
Thanks a bunch!
