### ISSUE TITLE
AES128 by default

### ISSUE THREAD

**Issue by bolinocroustibat** [Nyr/openvpn-install#712]
AES256 is slowing throughput and AES128 will remain uncrackable until at least 2030. Could we use AES128 by default?

**Comment by Nyr** [comment]
It's very unlikely that the cipher is slowing your throughput. The installer uses OpenVPN defaults which are sane and will not be changed.

And in case you were wondering, AES-256-CBC is probably not the cipher which your connection is using.

**Comment by bolinocroustibat** [comment]
OK!
