### ISSUE TITLE
How to install this connection using a Mikrotik Router?

### ISSUE THREAD

**Issue by brightways021** [Nyr/openvpn-install#713]
How to install this connection using a Mikrotik Router? Are there some best practices

**Comment by Nyr** [comment]
Best practice would be not to do it, since the MikroTik implementation of OpenVPN is very limited/outdated AFAIK. Read their documentation and try to make it work.

Other than that, I have no clue as I don't have a MikroTik device myself and don't plan on getting one.

**Comment by brightways021** [comment]
I got it. I really appreciate it.
