### ISSUE TITLE
Files in wrong places?

### ISSUE THREAD

**Issue by jkcoxson** [Nyr/openvpn-install#715]
Starting the openvpn@server creates errors that it can't find files. They are inside a server folder. Does this have to do with my situation in particular?

`-- Unit openvpn@server.service has begun starting up.
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --dh fails with 'dh.pem': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --ca fails with 'ca.crt': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --cert fails with 'server.crt': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: WARNING: cannot stat file 'server.key': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --key fails with 'server.key': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --crl-verify fails with 'crl.pem': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: WARNING: cannot stat file 'tc.key': No such file or directory (errno=2)
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: --tls-crypt fails with 'tc.key': No such file or directory (errno=2)
Jan 25 22:52:02 open-server systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 22:52:02 open-server ovpn-server[10172]: Options error: Please correct these errors.
Jan 25 22:52:02 open-server systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
Jan 25 22:52:02 open-server ovpn-server[10172]: Use --help for more information.
Jan 25 22:52:02 open-server systemd[1]: Failed to start OpenVPN connection to server.
-- Subject: Unit openvpn@server.service has failed`

**Comment by Nyr** [comment]
The correct systemd unit name is: `openvpn-server@server.service`.

So you'd need to use `systemctl start openvpn-server@server.service`.
