### ISSUE TITLE
IPV6 setup

### ISSUE THREAD

**Issue by mercadeoshop** [Nyr/openvpn-install#719]
Hello, i want to know if its possible setup on ipv6 ip or how can i add a ipv6 option for connect to both (ipv4 and ipv6)

**Comment by Nyr** [comment]
This will be implemented into the script soon, I just need some free time to get it done.

**Comment by liho98** [comment]
> This will be implemented into the script soon, I just need some free time to get it done.

Hi, great work, may i know is this feature done, how to setup for ipv6?
