### ISSUE TITLE
Change for increase speed

### ISSUE THREAD

**Issue by Pahom-ka** [Nyr/openvpn-install#721]
Hello! I noticed that openvpn with these settings gives a low speed vpn. I propose to add to /etc/openvpn/server/server.conf that settings:
```
sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
```

**Comment by Nyr** [comment]
`sndbuf` and `recvbuf`are set to sane values by default since OpenVPN 2.3.9.

That's why they got removed with 6a29a6babdb6e2d813c6c585800debc1558ead2d.

If you are using an OpenVPN version older than that, I'd suggest an upgrade.
