### ISSUE TITLE
Issue about random number in script

### ISSUE THREAD

**Issue by tanja84dk** [Nyr/openvpn-install#723]
Hi first of all thanks a lot for your great work maintaining the script.

I have just installed it on my home server ( Ubuntu 18.04 ) and noticed that I’m getting this error

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
139889989353920:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Generating a RSA private key
........................+++++
.............+++++

**Comment by Nyr** [comment]
You can safely ignore this. See previous duplicate issues on this matter if you want more information.
