### ISSUE TITLE
Random Number Generator Error

### ISSUE THREAD

**Issue by algunes** [Nyr/openvpn-install#724]
It gives an error like below, I'am running on Ubuntu 18.04.3 (LTS) x64 server as root. I could not fix this issue. FYI.
```
Tell me a name for the client certificate.
Client name: deskttop

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140138507424192:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Generating a RSA private key
..........................................................+++++
.........................+++++
writing new private key to '/etc/openvpn/server/easy-rsa/pki/private/deskttop.key.9GwCFmCDIZ'
-----
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140307148579264:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Check that the request matches the signature
Signature ok
```

**Comment by Nyr** [comment]
This is not a problem and can be safely ignored. For more information, check other duplicate issues on the matter.

**Comment by algunes** [comment]
Thanx for your reply, but at the end of the installation client connect to server but can not able to fetch any data from the internet.

**Comment by Nyr** [comment]
That's separate from the initial issue.

Is your server behind NAT? Can you ``ping 1.1.1.1``  while connected to the VPN?

**Comment by algunes** [comment]
Yes, it is behind the NAT. How can I specify my private network IP to this Bash Script?

**Comment by Nyr** [comment]
You don't need to do any of that. Just run the script in a clean system.

Your local network IP address will be detected automatically by the script and then you will be asked about the external IP address (which will usually be auto detected too).
