### ISSUE TITLE
Where can I find logging?

### ISSUE THREAD

**Issue by sicarii-13** [Nyr/openvpn-install#725]
Hi thx for the work, it made my tasks a bunch easier. 

For troubleshooting and security I would like to access the log. However I cannot find this in the standard location.

**Comment by Nyr** [comment]
``grep ovpn-server /var/log/syslog``

``cat /etc/openvpn/server/openvpn-status.log``

**Comment by sicarii-13** [comment]
Is there a way that I can make this a bit more verbose in a seperate log? Like in a normal situation where /var/log/openvpn/openvpn.log on loglevel 4 or 5?

**Comment by Nyr** [comment]
Edit `/etc/openvpn/server/server.conf`:

- Set `verb` to whatever level you want between ``0`` and ``11``
- Add the following line: `log /var/log/openvpn/openvpn.log`. And of course, create the `/var/log/openvpn/` directory.
