### ISSUE TITLE
It doesn't work on my Ubuntu Server 18.04.3 (LTS) x64

### ISSUE THREAD

**Issue by algunes** [Nyr/openvpn-install#726]
Thank you for your time. Your script install the openvpn on my preconfigured [(setp 6)](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04l) NAT behind Ubuntu server but after this, client have no access to internet or can not connect to the server. I tried to run this script at 2 case, one for only public IP address and the other one for private network (NAT). At the public IP address case, client can connect to my server but at the private case it couldn't even connect to the server.

**Here my server's List of iptables postrouting rules:**
(666.666.666.66 is my public IP)

Chain POSTROUTING (policy ACCEPT 7 packets, 564 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1       52 12315 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0
2        0     0 SNAT       all  --  *      *       10.8.0.0/24         !10.8.0.0/24          to:666.666.666.66

**Here is my server.conf file:**

local 666.666.66.66
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 208.67.222.222"
push "dhcp-option DNS 208.67.220.220"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup                                                                                                           
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
explicit-exit-notify

**Comment by Nyr** [comment]
Please, don't open further issues in the tracker.

I already told you in the other issue, there is no need to follow any external guide. Specifically, you don't need to configure any kind of masquerading.

It is the third time which you ask for help without following my previous troubleshooting instructions and reporting the results. I understand that there is probably a language barrier, but sorry, I'm done with this.
