### ISSUE TITLE
CentOS 8 minimal install need to install tar

### ISSUE THREAD

**Issue by pvanthony** [Nyr/openvpn-install#727]
Just leaving a note for others who may had an issue when installing in CentOS 8.
If using CentOS 8 minimal install, please install tar.
The openvpn-install needs tar.

**Comment by Nyr** [comment]
The official CentOS 8 installation has tar available.

Can you please share which provider are you seeing this on? It must be providing a custom template without tar.

**Comment by pvanthony** [comment]
I used this iso, CentOS-8-x86_64-1905-dvd1.iso and did the install using minimal setting.
There was no tar after the install.

**Comment by Nyr** [comment]
Thanks a lot for the report, this has been addressed.
