### ISSUE TITLE
occur error when generate client key

### ISSUE THREAD

**Issue by ckxt** [Nyr/openvpn-install#731]
Dear Sir

I'me the new beginner and start to learn ubuntu
I got error when use this script, same error as post here https://github.com/OpenVPN/easy-rsa/issues/261
"Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG"
not sure how to solve this error due to my poor english, could you please help check that?
Thanks

System: ubuntu 18.04

`root@ubuntu:~# wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh
--2020-03-22 22:53:29--  https://git.io/vpn
Resolving git.io (git.io)... 52.72.182.203, 34.225.254.242, 52.87.62.207, ...
Connecting to git.io (git.io)|52.72.182.203|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh [following]
--2020-03-22 22:53:31--  https://raw.github.com/Nyr/openvpn-install/master/openvpn-install.sh
Resolving raw.github.com (raw.github.com)... 151.101.64.133, 151.101.0.133, 151.101.192.133, ...
Connecting to raw.github.com (raw.github.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh [following]
--2020-03-22 22:53:33--  https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.192.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17623 (17K) [text/plain]
Saving to: ‘openvpn-install.sh’

openvpn-install.sh                          100%[===========================================================================================>]  17.21K  --.-KB/s    in 0.04s

Welcome to this OpenVPN road warrior installer!

I need to ask you a few questions before starting setup.
You can use the default options and just press enter if you are ok with them.

This server is behind NAT. What is the public IPv4 address or hostname?
Public IPv4 address / hostname [18.176.220.38]: 18.176.220.38

Which protocol do you want for OpenVPN connections?
   1) UDP (recommended)
   2) TCP
Protocol [1]: 1

What port do you want OpenVPN listening to?
Port [1194]: 11194

Which DNS do you want to use with the VPN?
   1) Current system resolvers
   2) 1.1.1.1
   3) Google
   4) OpenDNS
   5) Verisign
DNS [1]: 1

Finally, tell me a name for the client certificate.
Client name [client]: jian

Okay, that was all I needed. We are ready to set up your OpenVPN server now.
Press any key to continue...
Hit:1 http://mirrors.aliyun.com/ubuntu bionic InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease
Hit:3 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease
Hit:4 http://mirrors.aliyun.com/ubuntu bionic-security InRelease
Hit:5 http://ppa.launchpad.net/hollywood/ppa/ubuntu bionic InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20180409).
iptables is already the newest version (1.6.1-2ubuntu2).
openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.5).
Suggested packages:
  easy-rsa resolvconf
The following NEW packages will be installed:
  openvpn
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/470 kB of archives.
After this operation, 1,136 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package openvpn.
(Reading database ... 157401 files and directories currently installed.)
Preparing to unpack .../openvpn_2.4.4-2ubuntu1.3_amd64.deb ...
Unpacking openvpn (2.4.4-2ubuntu1.3) ...
Setting up openvpn (2.4.4-2ubuntu1.3) ...
 * Restarting virtual private network daemon.                                                                                                                            [ OK ]
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn.service → /lib/systemd/system/openvpn.service.
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.39) ...

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /etc/openvpn/server/easy-rsa/pki

Generating RSA private key, 2048 bit long modulus (2 primes)
....................................+++++
............+++++
e is 65537 (0x010001)
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140105300844992:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140700857864640:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Generating a RSA private key
............+++++
............................................................................................+++++
writing new private key to '/etc/openvpn/server/easy-rsa/pki/private/server.key.czoY25m7Sf'
-----
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140238996201920:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Can't open /etc/openvpn/server/easy-rsa/pki/index.txt.attr for reading, No such file or directory
140238996201920:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('/etc/openvpn/server/easy-rsa/pki/index.txt.attr','r')
140238996201920:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Mar 20 14:35:46 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
139700686315968:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Generating a RSA private key
..........................+++++
..........+++++
writing new private key to '/etc/openvpn/server/easy-rsa/pki/private/jian.key.h5szVJ44C6'
-----
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140429172212160:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'jian'
Certificate is to be certified until Mar 20 14:35:46 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
140606435611072:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/server/easy-rsa/pki/.rnd

An updated CRL has been created.
CRL file: /etc/openvpn/server/easy-rsa/pki/crl.pem

Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-iptables.service → /etc/systemd/system/openvpn-iptables.service.
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-server@server.service → /lib/systemd/system/openvpn-server@.service.

Finished!

Your client configuration is available at: /root/jian.ovpn
If you want to add more clients, just run this script again!
`

**Comment by Nyr** [comment]
You can safely ignore that message.
