### ISSUE TITLE
connecting to XXX has for failed

### ISSUE THREAD

**Issue by mgiftdc** [Nyr/openvpn-install#738]
I used this script to build on Google's GCP server, it can't connect normally, the firewall is turned on, ubuntu 18.04

Tue Apr 07 01:11:48 2020 OpenVPN 2.4.0 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Dec 27 2016
Tue Apr 07 01:11:48 2020 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Apr 07 01:11:48 2020 library versions: OpenSSL 1.0.2i  22 Sep 2016, LZO 2.09
Enter Management Password:
Tue Apr 07 01:11:48 2020 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25342
Tue Apr 07 01:11:48 2020 Need hold release from management interface, waiting...
Tue Apr 07 01:11:49 2020 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25342
Tue Apr 07 01:11:49 2020 MANAGEMENT: CMD 'state on'
Tue Apr 07 01:11:49 2020 MANAGEMENT: CMD 'log all on'
Tue Apr 07 01:11:49 2020 MANAGEMENT: CMD 'hold off'
Tue Apr 07 01:11:49 2020 MANAGEMENT: CMD 'hold release'
Tue Apr 07 01:11:49 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Apr 07 01:11:49 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Apr 07 01:11:49 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Apr 07 01:11:49 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Apr 07 01:11:49 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]35.xx.xx.87:1194
Tue Apr 07 01:11:49 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Tue Apr 07 01:11:49 2020 Attempting to establish TCP connection with [AF_INET]35.xx.xx.87:1194 [nonblock]
Tue Apr 07 01:11:49 2020 MANAGEMENT: >STATE:1586193109,TCP_CONNECT,,,,,,
Tue Apr 07 01:11:50 2020 TCP connection established with [AF_INET]35.xx.xx.87:1194
Tue Apr 07 01:11:50 2020 TCP_CLIENT link local: (not bound)
Tue Apr 07 01:11:50 2020 TCP_CLIENT link remote: [AF_INET]35.xx.xx.87:1194
Tue Apr 07 01:11:50 2020 MANAGEMENT: >STATE:1586193110,WAIT,,,,,,
Tue Apr 07 01:11:50 2020 MANAGEMENT: >STATE:1586193110,AUTH,,,,,,
Tue Apr 07 01:11:50 2020 TLS: Initial packet from [AF_INET]35.xx.xx.87:1194, sid=63f09074 426c6b99
Tue Apr 07 01:11:52 2020 VERIFY OK: depth=1, CN=ChangeMe
Tue Apr 07 01:11:52 2020 Validating certificate key usage
Tue Apr 07 01:11:52 2020 ++ Certificate has key usage  00a0, expects 00a0
Tue Apr 07 01:11:52 2020 VERIFY KU OK
Tue Apr 07 01:11:52 2020 Validating certificate extended key usage
Tue Apr 07 01:11:52 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Apr 07 01:11:52 2020 VERIFY EKU OK
Tue Apr 07 01:11:52 2020 VERIFY OK: depth=0, CN=server
Tue Apr 07 01:11:52 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Tue Apr 07 01:11:52 2020 [server] Peer Connection Initiated with [AF_INET]35.xx.xx.87:1194
Tue Apr 07 01:11:54 2020 MANAGEMENT: >STATE:1586193114,GET_CONFIG,,,,,,
Tue Apr 07 01:11:54 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Tue Apr 07 01:11:54 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: timers and/or timeouts modified
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: --ifconfig/up options modified
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: route options modified
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: route-related options modified
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: peer-id set
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: adjusting link_mtu to 1626
Tue Apr 07 01:11:54 2020 OPTIONS IMPORT: data channel crypto options modified
Tue Apr 07 01:11:54 2020 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Apr 07 01:11:54 2020 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Apr 07 01:11:54 2020 interactive service msg_channel=880
Tue Apr 07 01:11:54 2020 ROUTE_GATEWAY 192.168.50.1/255.255.255.0 I=2 HWADDR=34:e1:2d:98:xx:e6
Tue Apr 07 01:11:54 2020 open_tun
Tue Apr 07 01:11:54 2020 MANAGEMENT: Client disconnected
Tue Apr 07 01:11:54 2020 There are no TAP-Windows adapters on this system.  You should be able to create a TAP-Windows adapter by going to Start -> All Programs -> TAP-Windows -> Utilities -> Add a new TAP-Windows virtual ethernet adapter.
Tue Apr 07 01:11:54 2020 Exiting due to fatal error

**Comment by Nyr** [comment]
This doesn't seem to be firewall related, the issue is in your client.

Remove your existing client software and install the [latest client](https://openvpn.net/community-downloads/) from the OpenVPN website.
