### ISSUE TITLE
Change Certificate Lifetime

### ISSUE THREAD

**Issue by Zuendapp** [Nyr/openvpn-install#74]
Hi,

very nice script, thank You!!!
How can I change the lifetime from the certificates? When I change the values in "/etc/openvpn/easy-rsa/vars.example" it don't works. 

Thank you!!

Best regards

**Comment by Nyr** [comment]
Read the easy-rsa documentation:
https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Advanced.md

You need to rename `vars.example` to `vars` if you want to do it that way.

**Comment by Zuendapp** [comment]
Thank you very much!
