### ISSUE TITLE
Unable to receive google mail anymore

### ISSUE THREAD

**Issue by MichaelA2014** [Nyr/openvpn-install#740]
Hello Nyr. I installed the VPN using your script and now it is using IPv6 instead of ipv4? 
My email program stopped working . The gmail account gives me error "SEND  - TLS handshake failure. Invalid server certificate. The certificate cannot be used for this purpose"

Is there a way to switch back to IPv4? 
How do I update a certificate for the VPN connection? Apparently google refuses the connection

**Comment by Nyr** [comment]
> Is there a way to switch back to IPv4?

Yes, if you want to do it server side, edit `/etc/openvpn/server/server.conf`:

Remove the following line:
`server-ipv6 fddd:1194:1194:1194::/64`

And change the following line:
`push "redirect-gateway def1 ipv6 bypass-dhcp"`
to:
`push "redirect-gateway def1 bypass-dhcp"`

**Comment by Nyr** [comment]
About your specific issue, the tunnels are now dual stack, that means they support both IPv4 and IPv6 if the server has it. Not sure what your issue is, but Google definitively doesn't have issues with this.
