### ISSUE TITLE
Change the Dns Server

### ISSUE THREAD

**Issue by MrWaste** [Nyr/openvpn-install#742]
Could you allow a custom dns server because I have my own custom dns resolver already that's different then the IP Address of the machine/server.

**Comment by mighty9245** [comment]
there is an option to use system dns resolvers (`/etc/resolv.conf` for example)

or you can manually change pushed dns server in /etc/openvpn/server/server.conf (afaik it's the only place where they're used)

**Comment by Nyr** [comment]
> or you can manually change pushed dns server in the generated /etc/openvpn/server/server.conf (afaik it's the only place where they're used)

Correct.

About the original request, I'll maybe implement that in the future.
