### ISSUE TITLE
How to change to TLS-Auth?

### ISSUE THREAD

**Issue by Stefan-CPlanet** [Nyr/openvpn-install#743]
Hello, For older clients (like synology) that need TLS-Auth instead of Crypt, what is the procedure to change?
I tried changing server.conf file from tls-crypt to tls-auth 0 and adding tls direction 1 on client, and also changing key tags on client to <tls-auth> but it doesn't work. Can you help me change it? Thanks

**Comment by TinCanTech** [comment]
https://forums.openvpn.net/viewtopic.php?f=6&t=30147
