### ISSUE TITLE
Check that this script is compliant with OpenVPN security preconisation

### ISSUE THREAD

**Issue by PoloKltz** [Nyr/openvpn-install#745]
Hi @Nyr, 

Thank you very much for sharing your work. 

I was looking into it as I hoped to find an easier way to set up an OpenVPN server but I there is one question I wanted to ask about the certificate generation. 

The OpenVPN documentation recommends that the root certificate is never stored on the same server than the OpenVPN one: https://community.openvpn.net/openvpn/wiki/GettingStartedwithOVPN

> BEWARE: One common mistake when setting up a new CA is to place all the CA files on the OpenVPN server. DO NOT DO THAT! A CA requires a private key which is used for signing the certificates your clients and servers will use. If you loose control of your CA private key, you can no longer trust any certificates from this CA. Anyone with access to this CA private key can sign new certificates without your knowledge, which then can connect to your OpenVPN server without needing to modify anything on the VPN server. Place your CA files on a storage which can be offline as much as possible, only to be activated when you need to get a new certificate for a client or server.

**Correct me if I am wrong but your script create autogenerate certificates on the same server running the OpenVPN and keep it there ?**

**Comment by Nyr** [comment]
> Correct me if I am wrong but your script create autogenerate certificates on the same server running the OpenVPN and keep it there ?

That's right.

This project uses a very reasonable threat model for a road warrior setup. An air gaped CA is impractical and never will be implemented. Users will have to live with the fact that if an attacker is able to gain the root access which is required to read the private CA key, it is game over for them.

Would you feel much safer if someone fully compromises your VPN gateway but is unable to access to the CA signing key? I certainly wouldn't.

**Comment by PoloKltz** [comment]
I agree that an air gaped CA is impractical but if the use case implies several VPN gateways I still think it would be better to have one compromised without allowing access to the others.
