### ISSUE TITLE
How to support both udp and tcp

### ISSUE THREAD

**Issue by gittmy** [Nyr/openvpn-install#746]

**Comment by Nyr** [comment]
With two daemons and two separate networks, OpenVPN natively doesn't and the script doesn't either.

Anyway you should reconsider if you really need a VPN over TCP. It is usually a very bad idea.

**Comment by gittmy** [comment]
Thank you for your reply, I would like to ask what should I do if I really need udp and tcp?

**Comment by gittmy** [comment]
I am a novice, sorry for taking your time

**Comment by Nyr** [comment]
Not a problem, but you should seek help elsewhere, as this issue tracker is only for matters directly related to the openvpn-install script and no support for unrelated configurations is usually provided

**Comment by gittmy** [comment]
Ok，thanks
