### ISSUE TITLE
Restrict user

### ISSUE THREAD

**Issue by relft** [Nyr/openvpn-install#747]
Hi,

I have a question, It is possible to restrict only one user to apply some restriction with iptalbes, I'm thinking to configure a new ip range for this user, but not sure if I can do this, Is possible?

If not any other options to apply some ip restriction to only one user, other are right with actual default config with default network /24

Thanks

**Comment by Nyr** [comment]
This can be achieved but is unsupported by the script.

I suggest you to read the OpenVPN documentation.
