### ISSUE TITLE
Cannot connect to VPN server from client. TLS handshake error

### ISSUE THREAD

**Issue by Fufe1ok** [Nyr/openvpn-install#749]
Hello, i am tring to configure VPN connection to remote server which is hosted on Hetzner hosting. 
It is a Ubuntu 18.04 server. But when i am trying to connect to server i get this error log 

`Mon Apr 27 17:23:06 2020 OpenVPN 2.4.4 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Sep 26 2017

Mon Apr 27 17:23:06 2020 Windows version 6.2 (Windows 8 or greater) 64bit

Mon Apr 27 17:23:06 2020 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10

Enter Management Password:

Mon Apr 27 17:23:06 2020 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25342
Mon Apr 27 17:23:06 2020 Need hold release from management interface, waiting...
Mon Apr 27 17:23:07 2020 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25342
Mon Apr 27 17:23:07 2020 MANAGEMENT: CMD 'state on'
Mon Apr 27 17:23:07 2020 MANAGEMENT: CMD 'log all on'
Mon Apr 27 17:23:07 2020 MANAGEMENT: CMD 'echo all on'
Mon Apr 27 17:23:07 2020 MANAGEMENT: CMD 'hold off'
Mon Apr 27 17:23:07 2020 MANAGEMENT: CMD 'hold release'
Mon Apr 27 17:23:07 2020 WARNING: Your certificate is not yet valid!
Mon Apr 27 17:23:07 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Mon Apr 27 17:23:07 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Apr 27 17:23:07 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Mon Apr 27 17:23:07 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Apr 27 17:23:07 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]95.216.118.20:1194
Mon Apr 27 17:23:07 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Mon Apr 27 17:23:07 2020 UDP link local: (not bound)
Mon Apr 27 17:23:07 2020 UDP link remote: [AF_INET]xx.xx.xx.xx:1194
Mon Apr 27 17:23:07 2020 MANAGEMENT: >STATE:1587997387,WAIT,,,,,,
Mon Apr 27 17:24:08 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Apr 27 17:24:08 2020 TLS Error: TLS handshake failed
Mon Apr 27 17:24:08 2020 SIGUSR1[soft,tls-error] received, process restarting
Mon Apr 27 17:24:08 2020 MANAGEMENT: >STATE:1587997448,RECONNECTING,tls-error,,,,,
Mon Apr 27 17:24:08 2020 Restart pause, 5 second(s)`

Port is open, because i am tried to use OpenVPN Access Server and it worked fine, but i need to have possibility to connect more than 2 users.

I am think that problem is here
`Mon Apr 27 17:23:07 2020 WARNING: Your certificate is not yet valid!`
But i dont understand where is my problem

**Comment by Nyr** [comment]
> Mon Apr 27 17:23:07 2020 WARNING: Your certificate is not yet valid!

Your time is wrong Just set the correct time and date in both the client and server systems.

**Comment by Nyr** [comment]
Also if the time in the server was significantly wrong during installation, it's possible that you'll have to generate the certificates again (uninstall using the script and reinstall).

**Comment by Fufe1ok** [comment]
> 
> 
> Also if the time in the server was significantly wrong during installation, it's possible that you'll have to generate the certificates again (uninstall using the script and reinstall).

Yees, thx, it work, my pc connect to vpn server, but now i haven't access to internet, so maybe you have some advice?

**Comment by Nyr** [comment]
Maybe you are using the same certificate in more than one client, maybe you have a firewall in your PC, maybe you have conflicting TUN drivers causing issues, maybe it has to do with the fact that you are using a client which was released in the year 2017.

- Remove VPN software installed in your computer and reboot
- Install the latest [OpenVPN Community installer](https://openvpn.net/community-downloads/).
- Hope for the best.

If you need further assistance, you'll need to seek get support elsewhere, this is a tracker for issues with the openvpn-install project only.
