### ISSUE TITLE
generating empty config files

### ISSUE THREAD

**Issue by rajnetgen** [Nyr/openvpn-install#75]
Hi,
thanks for the great script. i had used it one of my server and it was working great. i had initially added 3 users and they worked fine.
Now when i run the script it generates empty config file for openpn with no content for certificate or keys.
can you help with this.

thank you
![screen shot 2015-10-06 at 11 23 47 pm](https://cloud.githubusercontent.com/assets/4663869/10317304/584dc358-6c81-11e5-9f8e-d91755323d49.png)

**Comment by Nyr** [comment]
Looks like you broke something and this isn't related to the script.

On an unrelated note: I wouldn't help anyway if you want to use my work for whatever "SEO" crap you are doing.

**Comment by Nyr** [comment]
And this is how low life scum reacts to being called out...

https://i.nyr.es/IMG_6272-9nRQfCyTxs.png
https://i.nyr.es/IMG_6273-SIXJ92zU4m.png
