### ISSUE TITLE
Which commit hash supports Ubuntu 16?

### ISSUE THREAD

**Issue by vyorkin** [Nyr/openvpn-install#750]
Hi, thanks for this script! Could you please tell which commit works with which OS version? For example, I need to install it on Ubuntu 16, which commit should I checkout? I think it would be helpful to have a list of supported operating systems and their versions in README.

Thanks

**Comment by Nyr** [comment]
This is the latest commit providing Ubuntu 16.04 support: https://git.io/vpn1604

All of the other distributions are supported in all of their currently maintained versions, with the exception of CentOS 6. Ubuntu 16.04 ships with an OpenVPN version which was released more than 4 years ago and as such I'd suggest against using it.

This installer is very conservative and usually legacy support is provided for very long, but Ubuntu 16.04 was just too problematic and old to be worth it, so ended up being discarded.

**Comment by vyorkin** [comment]
Thank you!
