### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by taskinsabah** [Nyr/openvpn-install#752]
I installed Openvpn with success from your repository. First of all, thank you very much for this opportunity you have given to us. May I kindly ask you that, is there any possibility to upgrade OpenVPN 2.4.7 x86_64 to V2.4.9 or at least V2.4.8.

**Comment by Nyr** [comment]
Sorry for the very late response, I forgot about this issue.

The script uses your distribution's repositories. You can use the official OpenVPN repositories instead if you want to have the latest version, but please consider that important security fixes are always backported by the distribution maintainers, even if there isn't a version change.
