### ISSUE TITLE
Ask user for internal/tunnel network during installation

### ISSUE THREAD

**Issue by eBeagle** [Nyr/openvpn-install#753]
Hi Nyr,

Thank you for the great work on developing and consistently maintaining this tool over so many years.

I'd like to suggest an improvement. Instead of using 10.8.0.0 as the internal network would it be possible to ask the user for this information?

The use case I have in mind is installing the script in multiple servers but connecting to these servers from a single client (pfSense) which would be routing traffic to different servers based on policies.

I'm aware I can modify the installation script for each server, but asking the user would be a much cleaner solution.

Cheers

**Comment by lukebarone** [comment]
Personally, I would like to see this as well. Maybe a menu choice like:

```
Choose your VPN IP range:
1) 10.8.0.0/16
2) 172.16.0.0/16
3) 192.168.8.0/24
```

I recently moved to a 10./8 network at home, and that matches another VPN
network I connect to, causing issues sometimes when working from home.

**Comment by Nyr** [comment]
@eBeagle I don't think that this option will be supported, I understand your particular use case but as with any other non-standard configuration, I just can't support everything.

@lukebarone of course you can configure your home network as you wish, but there is a reason why home networks don't use 10.0.0.0/8 and you've just seen that. You'll never need 16 millions of hosts, while there is other software like commercial VPN software which does.

Sorry for the late response guys, but I wanted to think about it before adopting a definitive decision.
