### ISSUE TITLE
Only Lan

### ISSUE THREAD

**Issue by TechNafo** [Nyr/openvpn-install#757]
Hi,

I am using this script for a while and i have great vpn connection, thanks.
But i want use vpn for just connect machine together, not for internet connection.
Is it possible with openvpn ? I made many researches but cant find any solutions.

Thanks for helping :D

**Comment by Nyr** [comment]
Edit `/etc/openvpn/server/server.conf` and remove the line containing the `redirect-gateway` parameter.

And restart:
`systemctl restart openvpn-server@server.service`

**Comment by lhmiranda** [comment]
This does not works for me. I have removed the line containing "redirect-gateway" but the internet traffic is still being redirected to the VPN.
I can ignore it on my side, but I would like to be able to disable it for everyone.

Also, having it as a choice during installation would be lovely.
