### ISSUE TITLE
IDEA: option to not allow clients to reach local network

### ISSUE THREAD

**Issue by boelle** [Nyr/openvpn-install#759]
i have a special use case where i dont want the clients to be able to access the local network behind the VPN, but the vpn server should be able to reach the cleints

think it as  kind of closed off hotel lobby where the clients can meet and exchange info with the reception desk

**Comment by Nyr** [comment]
This is not going to be implemented into the script but can be achieved with iptables or firewalld rules, you can drop traffic with origin + destination within the `10.8.0.0/24` network and allow it only to `10.0.8.1`.

**Comment by boelle** [comment]
no problemo, it was just a thought

noob Q on the way out, where in the script is the re-keying interval set? i tried to find it but no luck
i want to extend the time interval

**Comment by Nyr** [comment]
Use the `reneg-sec` parameter. Read the OpenVPN manual for more information.
