### ISSUE TITLE
'./openvpn-install.sh: line 248: openvpn: command not found' on centos8.1

### ISSUE THREAD

**Issue by AlexanderJi** [Nyr/openvpn-install#762]
OpenVPN installation is ready to begin.
Press any key to continue...
Last metadata expiration check: 2:43:50 ago on Mon 25 May 2020 04:22:51 PM CST.
Package epel-release-8-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 2:43:51 ago on Mon 25 May 2020 04:22:51 PM CST.
Package openssl-1:1.1.1c-2.el8_1.1.x86_64 is already installed.
Package ca-certificates-2019.2.32-80.0.el8_1.noarch is already installed.
Package tar-2:1.30-4.el8.x86_64 is already installed.
No match for argument: 
Error: Unable to find a match

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /etc/openvpn/server/easy-rsa/pki

Using SSL: openssl OpenSSL 1.1.1c FIPS  28 May 2019
Generating RSA private key, 2048 bit long modulus (2 primes)
...............+++++
.......................................................................+++++
e is 65537 (0x010001)

Using SSL: openssl OpenSSL 1.1.1c FIPS  28 May 2019
Generating a RSA private key
....................+++++
........................................................+++++
writing new private key to '/etc/openvpn/server/easy-rsa/pki/easy-rsa-4637.Ag3jek/tmp.doPW7J'
-----
Using configuration from /etc/openvpn/server/easy-rsa/pki/easy-rsa-4637.Ag3jek/tmp.w8gdtz
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until May 23 11:06:45 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Using SSL: openssl OpenSSL 1.1.1c FIPS  28 May 2019
Generating a RSA private key
....+++++
...........................+++++
writing new private key to '/etc/openvpn/server/easy-rsa/pki/easy-rsa-4758.FLOXFl/tmp.d20Jtz'
-----
Using configuration from /etc/openvpn/server/easy-rsa/pki/easy-rsa-4758.FLOXFl/tmp.rgc6QC
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test'
Certificate is to be certified until May 23 11:06:45 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Using SSL: openssl OpenSSL 1.1.1c FIPS  28 May 2019
Using configuration from /etc/openvpn/server/easy-rsa/pki/easy-rsa-4854.f7n76C/tmp.M2UeH6

An updated CRL has been created.
CRL file: /etc/openvpn/server/easy-rsa/pki/crl.pem

./openvpn-install.sh: line 248: openvpn: command not found
success
success
success
success
success
success
Failed to enable unit: Unit file openvpn-server@server.service does not exist.
sed: can't read /etc/openvpn/server/tc.key: No such file or directory

Finished!

The client configuration is available in: /root/test.ovpn
New clients can be added by running this script again.

**Comment by Nyr** [comment]
Weird, looks like the OpenVPN package is not getting installed.

What is your hosting provider?

**Comment by AlexanderJi** [comment]
> Weird, looks like the OpenVPN package is not getting installed.
> 
> What is your hosting provider?
The the OpenVPN package is actually not getting installed, I tried to run 'yum install -y openvpn' first and reexecute script,it works now. Thks!

**Comment by Nyr** [comment]
I still would like to know who is the hosting provider is, where is this server hosted.

**Comment by Nyr** [comment]
This was a recently introduced bug. A small change meant that we were passing empty arguments to `dnf` and it refused to install anything.

This has now been fixed.
