### ISSUE TITLE
Question : How to migrate existing user / cerfiticate

### ISSUE THREAD

**Issue by todiadiyatmo** [Nyr/openvpn-install#767]
Hello,

I have your script installed on very old machine, and we need to migrate the service to other provider. Is there any guide how to migrate the user (and cert to new provider) ? 

thank you

**Comment by Nyr** [comment]
Generally speaking, that would involve copying the /etc/openvpn directory to the new server, installing OpenVPN and setting up the firewall rules in the new server. Also, client configurations would need to be updated if they point to an IP address which has changed.
