### ISSUE TITLE
TLS blank on Debian 10

### ISSUE THREAD

**Issue by tjcomserv** [Nyr/openvpn-install#769]
When using the script on Debian 10 the client file created lacks content in the <tls-crypt> section causing the following error:

Insufficient key material or header text not found in file '[[INLINE]]' (0/128/256 bytes found/min/max)

I believe this to be (current line 250)...
	openvpn --genkey --secret /etc/openvpn/server/tc.key

When running on Debian, I get "unrecognized option" error.

All works perfectly on Ubuntu server 20.04

**Comment by Nyr** [comment]
Unable to reproduce. Please provide the full installation log.
