### ISSUE TITLE
Local network dynamic IP. How to update?

### ISSUE THREAD

**Issue by unphased** [Nyr/openvpn-install#770]
I have a typical home setup with a Netgear router. I noticed that all my port forwards stopped working today, so I have updated my port forwarding to the new LAN IP addresses that were assigned. 

I have also applied address reservation, so there will be no more DHCP dynamism. 

Now my other services work again, but openvpn is still broken, and the service fails to restart. I need to know which files I have to change, because I don't want to redeploy ovpn client files and have to deal with potential fallout from running the script again. Could I get some pointers? what are the config files to change the local IP address?

**Comment by unphased** [comment]
Looks like it works after updating `/etc/openvpn/server/server.conf`, though I am still confirming the iptables rules. But Tunnelblick has already reported a successful connection.

**Comment by unphased** [comment]
3 things need be done, the old nat firewall rule on the old ip needs to be removed, the new up specified in the server configuration, and the new nat firewall rule specified. I can confirm this works without requiring a reboot.

**Comment by crabkilla** [comment]
@unphased Do you know where these rules would be configured on a centos install? I'm not seeing them in firewalld, and iptables isn't installed on the server. I am looking to modify the NAT rules as well.

**Comment by unphased** [comment]
Ah sorry I haven't tried this on centos, and its been a while since I've tinkered with centos 7. I had started to standardize on centos for my "stable" server environments but 7 got really annoying with ancient packages for certain things. And the stability of debian based distros has been on the rise enough that since i started playing with raspberry pi's, I've been just staying in debian land for now.

But you should be able to find the answer easily by googling your centos major version.

**Comment by Nyr** [comment]
@crabkilla firewalld is used for CentOS, see here:
https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh#L339
