### ISSUE TITLE
Script broken in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by darksylinc** [Nyr/openvpn-install#771]
Commit https://github.com/Nyr/openvpn-install/commit/a46a23d84a4b007dc8f6e964219331f876a21602 claims

> OpenVPN 2.4 packages provide a new systemd service unit which uses a different
directory structure. This commit drops support for Ubuntu 16.04 which has v2.3
packages.

However I just tried the script on a **fresh** installation of Ubuntu 18.04.4 LTS on a local VM; and it is using the 'old' directory structure; systemd complains it cannot open `/etc/openvpn/server.conf` because the script is writing to `/etc/openvpn/server/server.conf`

Either the script should bail out on Ubuntu 18.04 like it does on 16.04, or it should still support the older directory structure

**Comment by Nyr** [comment]
The script is 100% compatible with Ubuntu 18.04 and will enable the service automatically, user doesn't need to do anything or follow any external tutorial.
