### ISSUE TITLE
Job for openvpn@server.service failed

### ISSUE THREAD

**Issue by bopnrgi** [Nyr/openvpn-install#773]
Hi,

I'm unable to setup openvpn on a server which running openvpn for a while. (With Nyr script)
With a fresh reset Ubuntu16.04, nothing works

**Install command**
`wget https://git.io/vpn1604 -O openvpn-install.sh && bash openvpn-install.sh`

**First Error**
`Job for openvpn@server.service failed because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.`

**Comment by Nyr** [comment]
Ubuntu 16.04 is no longer supported.

Still, maybe we can help if you provide the output of the mentioned commands, but you should consider an upgrade to a modern Ubuntu release.
