### ISSUE TITLE
DNS issue on ubuntu 18.04 using google cloud VM

### ISSUE THREAD

**Issue by yelanjri** [Nyr/openvpn-install#778]
So I have set up 5 servers that I want to use openvpn on, but when I installed then and got a script I noticed that I couldn't connect to the internet (Got a local Ip so that was fine) So I got to reinstalling and deleting it and I noticed that it worked once I used 1.1.1.1 dns service. Found that weid that the google dns didn't work and the local one didn;t work aswell. I am fine with using 1.1.1.1 but maybe this can be fixed in a future update.

**Comment by Nyr** [comment]
This can't be a problem with the script. Check the firewall.

**Comment by yelanjri** [comment]
Thanks for your response, I checked and everything outbound is open. the vpn port that I use is also set up correctly. I will look further into it and post once I found a solution 
![image](https://user-images.githubusercontent.com/66680137/85708435-7336ee80-b6e4-11ea-9f60-82c320af6c31.png)

**Comment by VChernomYA** [comment]
👍
