### ISSUE TITLE
Log rotation?

### ISSUE THREAD

**Issue by unphased** [Nyr/openvpn-install#779]
First I have to say this script has totally saved my bacon. I live in the US and left to visit family across the world at the end of February, and due to human malware timing will not return until August... It turned into a 5 month excursion!

For so many uses, booking flights using voip, accessing online banking, transferring photos and files that I have no local storage space for... this VPN setup direct to my personal machine at home has been truly indispensable. I was even able to reconfigure it (had to edit the iptables and config file, that's it) when my router back at home re-assigned the local ip of my server. 

I just noticed that the log file /var/log/openvpn/openvpn.log file is now 16GB in size. It brought vim to its knees, no easy task.

So I was wondering if it would make sense to implement log rotation by default with the script? What do you think @Nyr ?

**Comment by unphased** [comment]
Actually. This might be my mistake. I went and looked at the undo history on the config file. I think maybe the openvpn setup by default does not set a log file. I had also changed verb 3 to verb 6, no doubt that could account for the enormous log volume. Maybe this is a non-issue, then.

**Comment by Nyr** [comment]
> Maybe this is a non-issue, then.

That's right.
