### ISSUE TITLE
Can I use this script on AWS EC2 Instance?

### ISSUE THREAD

**Issue by nielsonsantana** [Nyr/openvpn-install#78]
I would link know how I can use this script on a instance on amazon. 
Does EC2 support TUN/TAE connections like VPS?

**Comment by Nyr** [comment]
As long as you use a supported distro (Debian/Ubuntu/CentOS), it's fine.

**Comment by kizomanizo** [comment]
I have a Linode instance where this script works pretty well even for many devices. On EC2 free-tier, I have failed to connect to the server. It gets stuck on: MANAGEMENT: >STATE:1615045703,RECONNECTING,tls-error,,,,,

**Comment by Nyr** [comment]
@kizomanizo check the firewall, this installer is provider agnostic and works in EC2 without issue.
