### ISSUE TITLE
How to use Script with automation?

### ISSUE THREAD

**Issue by Rayv1** [Nyr/openvpn-install#780]
Hi,

we use your script to automate the creation of the ovpn profiles. Unfortunately we're facing now the issue that our "one-liner" is not working anymore.

We execute:

$ printf '1\nmaxMustermann\n' | /opt/openvpn-install.sh 

but the stdin is deactivated by one of the first lines of your script.

Could you please provide us a way how to automate your script?

**Comment by Nyr** [comment]
You can safely remove the conflicting line in this case.
