### ISSUE TITLE
improvements 

### ISSUE THREAD

**Issue by aminmazi** [Nyr/openvpn-install#782]
Hi 
I think there are some improvement for this useful shell script.

1. when configuring the server, you can remove the local line and let the ovpn to listen to all network interfaces. (IPV4 and IPV6 simultaneously)

2. when creating the ovpn client config file, you can ask for a domain name, and put the domain name instead of using the ipv4 address.

**Comment by com2** [comment]
Alternatively use some configuration file for the script that allows to set the domain name at installation. This would allow to save configuration parameters for other features too.

**Comment by Nyr** [comment]
> when configuring the server, you can remove the local line and let the ovpn to listen to all network interfaces. (IPV4 and IPV6 simultaneously)

That was the case previously, but caused an important issue. See #603 if you are curious.

> when creating the ovpn client config file, you can ask for a domain name, and put the domain name instead of using the ipv4 address.

Yes, we could, but what would we gain doing that? The routing installed by the script doesn't support dynamic IP assignments.
