### ISSUE TITLE
User revoked, but still can log in.

### ISSUE THREAD

**Issue by qurikuduo** [Nyr/openvpn-install#785]
Even I revoke a user by using openvpn-install.sh, and it says "Certificate for client xxx revoked!" the user still can  logged in successfully. Did I need restart the open vpn process?

**Comment by qurikuduo** [comment]
The user's cert info in /etc/openvpn/server/easy-rsa/pki/index.txt is:
R	xxxx	200708122011Z	someStr	unknown	/CN=xxxx

**Comment by qurikuduo** [comment]
When I restart the  open vpn  process, the user TLS handshake was failure. thx.

**Comment by Nyr** [comment]
This was fixed with 221319aa54db9bb5e6ae45facad03b6dacbaba47, sorry about that.

If you want to fix it in your existing installation, just do the following:
`chmod o+x /etc/openvpn/server/`

**Comment by qurikuduo** [comment]
Got it, thx a lot!
