### ISSUE TITLE
Debian 10 no internet after restart system

### ISSUE THREAD

**Issue by xMefistofelx** [Nyr/openvpn-install#787]
Hello, No internet (on client) after reboot system. Connecting to server is fine but no internet. Using script for remove and install openvpn fix problem. Thanks.

**Comment by h3ct0rjs** [comment]
@xMefistofelx I have checked the script and read all the options. This happened to me during a quick install, after checking,  I just  disable the following lines from the client machine: 
```
ignore-unknown-option block-outside-dns
block-outside-dns
```
and if you want to specify the dns solvers of the client machine, try to add this to your ovpn file : 

`   pull-filter ignore "dhcp-option DNS"`

This will avoid the dns overwrite,  it also will ignore all pushed config lines that we remove previously.

**Comment by kevin01523** [comment]
Hmm or just add a new line to set a new dns without removing the block outside dns line since it protects you from dns links

**Comment by kixanity** [comment]
if this returns 0
`sudo sysctl net.ipv4.ip_forward`
`sudo cat /etc/sysctl.d/30-openvpn-forward.conf`

do this
`sudo sysctl -w net.ipv4.ip_forward=1`
`sudo sysctl -p -f /etc/sysctl.d/30-openvpn-forward.conf`

**Comment by Nyr** [comment]
Closing this since the original reporting doesn't seem to be responding anymore.

This can happen for example in cloud servers which are behind NAT and the internal IP changes after rebooting them.
