### ISSUE TITLE
Shows only 'user' successful authentication in logs

### ISSUE THREAD

**Issue by potatonc** [Nyr/openvpn-install#791]
I have run the command :
```
cat openvpn.log | grep -i "Username/Password authentication succeeded for username"
```
and this is the result :
```
Fri Aug  7 05:28:00 2020 zagar/127.0.0.1:34276 TLS: Username/Password authentication succeeded for username 'zagar' [CN SET]
Fri Aug  7 05:31:28 2020 127.0.0.1:37616 TLS: Username/Password authentication succeeded for username 'agungcendol' [CN SET]
Fri Aug  7 05:31:54 2020 ulum/127.0.0.1:34408 TLS: Username/Password authentication succeeded for username 'ulum' [CN SET]
Fri Aug  7 05:35:36 2020 127.0.0.1:37928 TLS: Username/Password authentication succeeded for username 'vidia' [CN SET]
Fri Aug  7 05:38:06 2020 127.0.0.1:38092 TLS: Username/Password authentication succeeded for username 'erji' [CN SET]
Fri Aug  7 05:38:49 2020 127.0.0.1:38156 TLS: Username/Password authentication succeeded for username 'hadijah' [CN SET]
```
how can i get only the 'user_name' result in the bash command?

**Comment by andreweymard** [comment]
I'm not sure what you mean but you could try 
cat openvpn.log | grep -i "Username/Password authentication succeeded for username 'erji'"
Instead of 'erji' give the username you want

**Comment by potatonc** [comment]
> I'm not sure what you mean but you could try 
> cat openvpn.log | grep -i "Username/Password authentication succeeded for username 'erji'"
> Instead of 'erji' give the username you want

I want to create a bash script to find out who has successfully logged on to the openvpn server

**Comment by andreweymard** [comment]
Does this solve your issue?
cat openvpn.log | grep -i "succeeded" | cut -d "'" -f 2

**Comment by potatonc** [comment]
> Does this solve your issue?
> cat openvpn.log | grep -i "succeeded" | cut -d "'" -f 2

thanks this worked, then I added tail -f so only the last 10 logins show up.

and now I want to try displaying 'time' with 'user'
```
cat openvpn.log | grep -i "Wed Aug" | grep -i "authentication succeeded" | cut -d "'" -f 2 | tail -f
```
Output:
```
hasdal
Santi
asma
kasmawati
amelia
revan
nilatri
Ineszahra
vira
mamaandi
```

can you help me one more time?

**Comment by andreweymard** [comment]
How about this? 
cat openvpn.log | grep -i " succeeded" | cut -d " " -f 1-6,14

**Comment by potatonc** [comment]
> How about this? 
> cat openvpn.log | grep -i " succeeded" | cut -d " " -f 1-6,14

Thanks, I have tried this:
```
cat openvpn.log | grep -i "succeeded" | cut -d " " -f 1-6,14 | tail -f
```
Output:
```
Wed Aug 12 15:17:08 2020 arni/127.0.0.1:36712 [CN
Wed Aug 12 15:18:27 2020 Socket
Wed Aug 12 15:18:27 2020 127.0.0.1:33262 [CN
Wed Aug 12 15:18:47 2020 vidia/127.0.0.1:56436 [CN
Wed Aug 12 15:19:00 2020 Socket
Wed Aug 12 15:19:00 2020 127.0.0.1:33290 [CN
Wed Aug 12 15:19:07 2020 Socket
Wed Aug 12 15:19:07 2020 127.0.0.1:33304 [CN
Wed Aug 12 15:19:08 2020 Socket
Wed Aug 12 15:19:10 2020 127.0.0.1:33308 [CN
```
i will try to develop it.

**Comment by andreweymard** [comment]
Judging from the output adjust the values like this
cut -d " " -f 1-5,13

**Comment by potatonc** [comment]
> Judging from the output adjust the values like this
> cut -d " " -f 1-5,13

Big thanks, this is better :D
```
cat openvpn.log | grep -i "succeeded" | cut -d " " -f 1-5,13 | tail -f

Wed Aug 12 15:24:03 2020 'lemon'
Wed Aug 12 15:24:45 2020
Wed Aug 12 15:24:45 2020 'asma'
Wed Aug 12 15:24:46 2020
Wed Aug 12 15:24:46 2020 'ais'
Wed Aug 12 15:24:46 2020
Wed Aug 12 15:24:46 2020 'hadijah'
Wed Aug 12 15:25:42 2020 'todingho'
Wed Aug 12 15:26:41 2020
Wed Aug 12 15:26:44 2020 'lemon'
```
How does the 'cat' command work to make this simple, I don't understand the formula 'cut -d " " -f 1-5,13'

can you help me to explain?

sorry for trouble you again

**Comment by andreweymard** [comment]
Did you mean 'cat' or 'cut'? I gonna assume cut
Cut is used to select specific parts in a string. 
'-d' is the delimiter, here we specify how we want to 'cut' our strings. I chose space but you can choose whatever you want. 
'-f' is fields, this is used to select the strings we 'cut'. For instance 1-5 selects the first 5 'cuts' of the string.
Hope this solved your question. I'm sorry my explanation skills are a not that good.

**Comment by potatonc** [comment]
> Did you mean 'cat' or 'cut'? I gonna assume cut
> Cut is used to select specific parts in a string. 
> '-d' is the delimiter, here we specify how we want to 'cut' our strings. I chose space but you can choose whatever you want. 
> '-f' is fields, this is used to select the strings we 'cut'. For instance 1-5 selects the first 5 'cuts' of the string.
> Hope this solved your question. I'm sorry my explanation skills are a not that good.
> 
yes I mean 'cut', sorry for confusing you.

it seems about '-f 1-5' I'm starting to understand, then what about the numbers ',13' and (-d " "), why is there no content in " "?

I am very grateful that you could take the time to answer my questions and I got knowledge from you, thank you very much.

**Comment by andreweymard** [comment]
In -d " " there is something, it's a space. e.g. it could also be -d "," or -d"/". This would tell the cut command to 'cut' the string by the "," or "/" present in the string. Since we chose " " (space) it cuts each line by the spaces it contains. So at every space we create a cut. 
"This is a line" <- in this line we cut it like 
"This" "is" "a" "line"
So by selecting -f 1 I select the first cut which is "This"
Just like so in your case I chose the cuts 1 through 5 and 15. The 15th cut contains the username.

No worries. Just glad to be of help.

**Comment by potatonc** [comment]
> In -d " " there is something, it's a space. e.g. it could also be -d "," or -d"/". This would tell the cut command to 'cut' the string by the "," or "/" present in the string. Since we chose " " (space) it cuts each line by the spaces it contains. So at every space we create a cut. 
> "This is a line" <- in this line we cut it like 
> "This" "is" "a" "line"
> So by selecting -f 1 I select the first cut which is "This"
> Just like so in your case I chose the cuts 1 through 5 and 15. The 15th cut contains the username.
> 
> No worries. Just glad to be of help.

Sorry to respond late, I was busy yesterday.

Now I understand, thank you very much for sharing this very useful knowledge with me. you are so great.
