### ISSUE TITLE
TLS Handshake Failed

### ISSUE THREAD

**Issue by RealMimsical** [Nyr/openvpn-install#792]
Mon Aug 17 19:02:12 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Aug 17 19:02:12 2020 TLS Error: TLS handshake failed
Mon Aug 17 19:02:12 2020 SIGUSR1[soft,tls-error] received, process restarting
Mon Aug 17 19:02:12 2020 MANAGEMENT: >STATE:1597705332,RECONNECTING,tls-error,,,,,
Mon Aug 17 19:02:12 2020 Restart pause, 5 second(s)
Mon Aug 17 19:02:17 2020 MANAGEMENT: CMD 'proxy NONE  '
Mon Aug 17 19:02:18 2020 MANAGEMENT: >STATE:1597705338,RESOLVE,,,,,,
Mon Aug 17 19:02:18 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]XX.XX.XX.XXX:42513
Mon Aug 17 19:02:18 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Mon Aug 17 19:02:18 2020 UDP link local: (not bound)
Mon Aug 17 19:02:18 2020 UDP link remote: [AF_INET]XX.XX.XX.XXX:42513
Mon Aug 17 19:02:18 2020 MANAGEMENT: >STATE:1597705338,WAIT,,,,,,

I keep getting this error when trying to connect to an ovh.  It was working a couple of days ago, but ever since i reset my computer, it just wont work

**Comment by bilalkhann16** [comment]
You need to configure the networking inbound security rules of your VPS. Are you using Azure vm? 
https://medium.com/@evgenijrenke/configure-openvpn-access-server-on-azure-6e6120bacddf

**Comment by Nyr** [comment]
This is a connectivity issue and not a problem with the script. Check your network or your firewall.
