### ISSUE TITLE
Connecting but not working

### ISSUE THREAD

**Issue by sajjadalis** [Nyr/openvpn-install#794]
Hi,

I installed this about 2 years ago on 3 of my servers running Ubuntu 16.04 and it was working fine at that time. I remember using it quite often on both windows and android.

I just tried to use those old profiles again. All of them are connecting fine on windows 10 client but internet stop working as soon as it connects.

So i installed this latest version on Ubuntu 18 but again same issue. Its connecting but not working. I tried to disable AVG firewall, diagnose if there is an issue with network settings. Also disabled ufw firewall on my server. Still same problem.

Any help please.

**Comment by Nyr** [comment]
Try from a different device, like your smartphone. Does it work? Then it is a client-side problem.

It you are still having issues from a different device, the problem will likely be with the server NAT or firewall.
