### ISSUE TITLE
How do I want to listen to multiple ports on the same server at the same time

### ISSUE THREAD

**Issue by nine-city** [Nyr/openvpn-install#796]
How do I want to listen to multiple ports on the same server at the same time
My phone needs to use UDP 53 port
My computer needs a UDP 3100 port
However, the generated ovpn file is port 1194
I tried to forward UDP 53 port and 3100 port using CentOS 7 firewall
Can connect successfully
But my mobile phone and computer can't open the web page and so on
Here are my firewall rules
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 1194
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 1194
Thank you for your help

**Comment by Nyr** [comment]
In CentOS 7, the default firewall frontend is firewalld, not plain iptables.

So except if you intentionally switched to iptables, make sure to open the port with firewall-cmd and then set up the redirect.
