### ISSUE TITLE
How do i configure the configuration for 2 NICs?

### ISSUE THREAD

**Issue by atuxnull** [Nyr/openvpn-install#797]
i have the script working in a system in my LAN (Debian) and it works fine.  In that system i added a second NIC card that attaches to the 2nd LAN, so it is:
-NIC_A 192.168.1.45/24 with gw 192.168.1.1
-NIC_B 192.168.2.45/24 without gw 
Once someone connects to the OpenVPN it can see the network from NIC_A (192.168.1.0/24), but it can not see the network from NIC_B (192.168.2.0/24)
I would like to ask how i could alter the configuration and make this possible, please?

**Comment by Nyr** [comment]
This configuration is out of the scope of a road warrior setup, so the issue tracker for this project is not the right place to ask for help, sorry.
