### ISSUE TITLE
openVPN with static ip

### ISSUE THREAD

**Issue by shrw** [Nyr/openvpn-install#799]
Using openvpn-install to create a VPN

Here is my current scenario :

server A has static ip : 66.64.64.58 and openVPN server is installed and running.
- server B has static ip : 55.64.64.77 and openVPN client is installed.
- server A is a web server
- server B is also a web server running bounded by static ip 55.64.64.77
- Whenever the OPENVPN client starts on server B, webserver/server B ip address is lost, and all the web-sites goes down.

Is there a way to start a openVPN server span across multiple host with static IPs.

**Comment by Nyr** [comment]
This happens because "server B" is instructed to use a default route via the "server A" gateway.

If you don't want this to happen, don't use a road-warrior setup where the default route is replaced in the client machine (server B).
