### ISSUE TITLE
After the script is deployed, the network card cannot get the IPV6 global address

### ISSUE THREAD

**Issue by lee928** [Nyr/openvpn-install#800]
After the script is deployed, the network card cannot get the IPV6 global address. Therefore, the IPv6 address cannot be bound in the openvpn configuration. Does this support IPv6 network? It works normally under IPv4.
Test at armbian7 of debian core

**Comment by lee928** [comment]
use script remove openvpn, the network card can get the IPV6 global address.

**Comment by Nyr** [comment]
There is a language barrier here and we can't understand what the issue which you are trying to report is.

**Comment by lee928** [comment]
install script , the network adapter (eth0) cannot obtain the IPv6 global address. After uninstall script, the network adapter can obtain the IPv6 address normally.
