### ISSUE TITLE
Can i host a [insert game] server when using openvpn?

### ISSUE THREAD

**Issue by Oyplap** [Nyr/openvpn-install#808]
Hello,

I am currently trying to host a game server, for example Rust. And i want to port forward the rust port i need to open (28015).

My scenario is that i have a pc in germany that runs the rust server but i want the internet traffic to go to the vpn server that is located in Amsterdam to let it look like that my Rust server is coming from amsterdam. Right now i have set up openvpn on my ubuntu server in amsterdam, made a connection in germany, i tried opening port 28015 but the server isn't appearing on the server list. I also can't connect it with the ip and port. Is what i am trying to achieve possible?

Kind regards,
Oyplap

**Comment by kreug** [comment]
Hello, I have a very similar setup (game server in Germany, VPN server in Amsterdam).
You need to port forward on your VPN server (not on your game server) to reroute all traffic on that port to your game server. I did it on Linux with this command:

`iptables -t nat -A PREROUTING -p udp --dport PORT1:PORT2 -j DNAT --to-destination 10.8.0.2:PORT1-PORT2`

Replace PORT1 and PORT2 with your port range and replace 10.8.0.2 with your game server's local IP in respect to the VPN. If your game also needs TCP, run the same command but replace **udp** with **tcp**.

You can also check the currently existing iptables rules with this command:
`iptables -t nat -L`

**Comment by Oyplap** [comment]
Thanks! I'll try this today.

**Comment by Oyplap** [comment]
hello,
I have tried the iptables method. It didn't worked for me. I'm currently hosting ubuntu 18.04 in Amsterdam on the provider Microsoft Azure.

![Schermafbeelding 2020-10-27 102934](https://user-images.githubusercontent.com/45702131/97282939-919e2980-183f-11eb-8571-d523be10573c.png)
![Schermafbeelding 2020-10-27 103015](https://user-images.githubusercontent.com/45702131/97282943-9236c000-183f-11eb-9ac2-439512c4ca23.png)

I tried port 7781 because also host a less heavier server than Rust that requires this port.

**Comment by Oyplap** [comment]
I don't know what i am doing wrong. Port 7781 doesn't open but port 22 is open (pretty logical because how else can i connect to my ubuntu server).
![Schermafbeelding 2020-10-27 103407](https://user-images.githubusercontent.com/45702131/97283409-1ab56080-1840-11eb-8d48-f622dd66c4b5.png)
![Schermafbeelding 2020-10-27 103424](https://user-images.githubusercontent.com/45702131/97283416-1be68d80-1840-11eb-81ba-fc9bddeb7aa7.png)

**Comment by kreug** [comment]
Are you absolutely sure that 192.168.1.50 is your game server's local IP in the VPN? Because you have two private IPs, so to speak - one which is for your VPN, and one which is for your local network. If your game server is running Windows and the official OpenVPN client, check this:
![openvpn-private-ip](https://user-images.githubusercontent.com/33865403/97285349-65d07300-1842-11eb-81b5-25d6c96fce71.png)

Or simply run `ipconfig` in the command shell:
![vpn-private-ip](https://user-images.githubusercontent.com/33865403/97285513-987a6b80-1842-11eb-96c1-5352d480a835.png)
In this case, the upper IPv4 address is my VPN private address.

**Comment by Oyplap** [comment]
Oh wow, how could i have missed that. Im on it!

Thanks!

**Comment by Oyplap** [comment]
Ah i see an issue. When i add an port to the iptables it won't save. I did however tried iptables-save command but after a restart it didn't worked.

**Comment by Oyplap** [comment]
Iptables ports are now persistent but the port is still for some reason closed.

**Comment by kreug** [comment]
Hmm I'm honestly out of ideas, maybe check if you have any firewalls or if Azure servers have security policies of their own (in the dashboard maybe? I know that Amazon servers have a similar thing and you need to open the ports through their dashboard first before doing anything). Can you also post your new iptables rules?

**Comment by Oyplap** [comment]
Hello,
You are right, i have a dashboard to open ports. That was also the first thing i did while port forwarding.

here are some pictures where one was requested
![Schermafbeelding 2020-10-28 105349](https://user-images.githubusercontent.com/45702131/97420737-fcb53200-190b-11eb-86d3-53d6f0f921c0.png)
![Schermafbeelding 2020-10-28 105324](https://user-images.githubusercontent.com/45702131/97420741-fd4dc880-190b-11eb-95dd-e49e2f5099cd.png)

Also, thanks for helping me out! I do have the feeling that i am getting close on fixing this thing.

**Comment by Oyplap** [comment]
Correction: I have added the 7781 rule because i forgot it. port is still not open :/
![Schermafbeelding 2020-10-28 110028](https://user-images.githubusercontent.com/45702131/97421485-dd6ad480-190c-11eb-9531-f3a941da9df1.png)

**Comment by Oyplap** [comment]
Holy shit it actually worked! The port is open! You are a life saver!

**Comment by kreug** [comment]
My pleasure, dude. Glad to see it worked out! :)

**Comment by Oyplap** [comment]
Thank you for helping!
