### ISSUE TITLE
Generated .ovpn file is not working in OpenWrt OpenVPN

### ISSUE THREAD

**Issue by abhishekluv** [Nyr/openvpn-install#809]
Thanks for this awesome script. 

I am trying to use my .ovpn file on OpenWrt OpenVPN and it doesn't work. 

Can you please guide me how to make it work?

Cheers
Abhishek

**Comment by Nyr** [comment]
This would be an issue for the OpenWrt tracker.

Probably has something to do with `tls-crypt` option (just my guess).
