### ISSUE TITLE
Support for Cloudlinux OS

### ISSUE THREAD

**Issue by virtualos** [Nyr/openvpn-install#811]
Hello Nyr,

I've installed OpenVPN on my centos some weeks ago and everything working like a charm. Some days ago I converted my OS from centos to cloudlinux os (I'm also using my vps for hosting purpose) and I got that I can't add/remove OpenVPN's users anymore!!

You know, script does not work anymore for adding/removing users; but OpenVPN still working for current users like a charm.

May you please add a patch to support cloudlinux OS?

Thank you.

**Comment by Nyr** [comment]
CloudLinux OS is not supported.

No idea where it breaks the script, but it is difficult to consider a fix because I am not able to easily get an installation of this commercial distribution to test.
