### ISSUE TITLE
OpenVPN 2.5.0

### ISSUE THREAD

**Issue by Neustradamus** [Nyr/openvpn-install#814]
@Nyr: An update is needed:

OpenVPN 2.5.0 (2020-10-27):
- https://openvpn.net/
- https://github.com/OpenVPN/openvpn/releases

Announcement:
- https://sourceforge.net/p/openvpn/mailman/message/37138737/

OpenVPN 2.5 is a new major release with many new features:
- Client-specific tls-crypt keys (–tls-crypt-v2)
- Added support for using the ChaCha20-Poly1305 cipher in the OpenVPN data channel
- Improved Data channel cipher negotiation
- Removal of BF-CBC support in default configuration
- Asynchronous (deferred) authentication support for auth-pam plugin
- Deferred client-connect
- Faster connection setup
- Netlink support
- Wintun support
- IPv6-only operation
- Improved Windows 10 detection
- Linux VRF support
- TLS 1.3 support
- Support setting DHCP search domain
- Handle setting of tun/tap interface MTU on Windows
- HMAC based auth-token support
- VLAN support
- Support building of .msi installers for Windows
- Allow unicode search string in –cryptoapicert option (Windows)
- Support IPv4 configs with /31 netmasks now
- New option –block-ipv6 to reject all IPv6 packets (ICMPv6)
- MSI installer (Windows)
- The MSI installer now bundles EasyRSA 3, a modern take on OpenVPN CA management

Overview of changes in OpenVPN v2.5:
- https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn25

Overview of changes in OpenVPN v2.4:
- https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn24

**Comment by luutruong** [comment]
In CentOS you can following this guide to install the latest version

```bash
yum copr enable dsommers/openvpn-release
yum install openvpn
```

https://copr.fedorainfracloud.org/coprs/dsommers/openvpn-release/

**Comment by Neustradamus** [comment]
After OpenVPN 2.5.8, 2.6 Beta 1 is here!
- https://openvpn.net/community-downloads/

**Comment by Nyr** [comment]
I am well aware of OpenVPN releases. But this installer obtains OpenVPN from the respective repositories from each distro, so there is nothing to upgrade.
