### ISSUE TITLE
Error opening configuration file: server.service.conf

### ISSUE THREAD

**Issue by wpyung** [Nyr/openvpn-install#818]
I ran the script on Ubuntu 18.04.4 LTS
The VPN server works well except that I get error messages every 5 seconds:

Nov 11 16:11:28 vm8 openvpn[11582]: Options error: In [CMD-LINE]:1: Error opening configuration file: server.service.conf

see [https://community.openvpn.net/openvpn/ticket/1353](url)

I don't understand where all these services are coming from - I did not manually set them up.

root@vm8:/var/log# sudo systemctl|grep openvpn
  openvpn-iptables.service                                                                  loaded active     exited       openvpn-iptables.service      
  openvpn-server@server.service                                                             loaded active     running      OpenVPN service for server    
  openvpn-server@server.service.service                                                     loaded activating auto-restart OpenVPN service for server.service
  openvpn.service                                                                           loaded active     exited       OpenVPN service               
  system-openvpn\x2dserver.slice                                                            loaded active     active       system-openvpn\x2dserver.slice

Can you suggest a fix as we are using this for all our remote user to connect in from our company, and its hard to troubleshoot connection problems with all these errors in the log.

Thanks

Peter

**Comment by Nyr** [comment]
I do not see an issue with the installer, `openvpn-server@server.service.service` is not referenced at all in my script.
