### ISSUE TITLE
time to connect and slow speed on DigitalOcean

### ISSUE THREAD

**Issue by vahidx4r4x** [Nyr/openvpn-install#819]
Hi
I created a VPN server using your script but im facing some issues
it takes too much time to connect to server on mobile phones using wifi network and waste so much time on `VERIFY OK: depth=0, /CN=server` 
and if it connects its so slow!

------------------------------------------------------------

13:23:00.556 -- ----- OpenVPN Start -----

13:23:00.556 -- EVENT: CORE_THREAD_ACTIVE

13:23:00.559 -- OpenVPN core 3.git:released:662eae9a:Release android arm64 64-bit PT_PROXY

13:23:00.559 -- Frame=512/2048/512 mssfix-ctrl=1250

13:23:00.561 -- UNUSED OPTIONS
4 [resolv-retry] [infinite] 
5 [nobind] 
6 [persist-key] 
7 [persist-tun] 
11 [ignore-unknown-option] [block-outside-dns] 
12 [block-outside-dns] 
13 [verb] [3] 

13:23:00.561 -- EVENT: RESOLVE

13:23:00.571 -- Contacting xxx.xxx.xxx.xxx:1194 via UDP

13:23:00.571 -- EVENT: WAIT

13:23:00.578 -- Connecting to [xxx.xxx.xxx.xxx]:1194 (xxx.xxx.xxx.xxx) via UDPv4

13:23:00.916 -- EVENT: CONNECTING

13:23:00.925 -- Tunnel Options:V4,dev-type tun,link-mtu 1521,tun-mtu 1500,proto UDPv4,cipher AES-256-GCM,auth [null-digest],keysize 256,key-method 2,tls-client

13:23:00.927 -- Creds: UsernameEmpty/PasswordEmpty

13:23:00.929 -- Peer Info:
IV_VER=3.git:released:662eae9a:Release
IV_PLAT=android
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_AUTO_SESS=1
IV_GUI_VER=net.openvpn.connect.android_3.2.4-5891
IV_SSO=openurl

**13:23:03.791** -- VERIFY OK: depth=0, /CN=server

**13:23:44.104** -- Session invalidated: KEEPALIVE_TIMEOUT

13:23:44.106 -- Client terminated, restarting in 2000 ms...

13:23:46.105 -- EVENT: RECONNECTING

13:23:46.111 -- EVENT: RESOLVE

13:23:46.116 -- Contacting xxx.xxx.xxx.xxx:1194 via UDP

13:23:46.117 -- EVENT: WAIT

13:23:46.128 -- Connecting to [xxx.xxx.xxx.xxx]:1194 (xxx.xxx.xxx.xxx) via UDPv4

13:23:46.480 -- EVENT: CONNECTING

13:23:46.487 -- Tunnel Options:V4,dev-type tun,link-mtu 1521,tun-mtu 1500,proto UDPv4,cipher AES-256-GCM,auth [null-digest],keysize 256,key-method 2,tls-client

13:23:46.489 -- Creds: UsernameEmpty/PasswordEmpty

13:23:46.489 -- Peer Info:
IV_VER=3.git:released:662eae9a:Release
IV_PLAT=android
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_AUTO_SESS=1
IV_GUI_VER=net.openvpn.connect.android_3.2.4-5891
IV_SSO=openurl

13:23:46.794 -- VERIFY OK: depth=0, /CN=server

13:24:00.562 -- EVENT: CONNECTION_TIMEOUT

13:24:00.576 -- EVENT: DISCONNECTED

13:24:00.577 -- Tunnel bytes per CPU second: 0

13:24:00.578 -- ----- OpenVPN Stop -----

------------------------------------------------------------
**server config:**

local xxx.xxx.xxx.xxx
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
server-ipv6 fddd:1194:1194:1194::/64
push "redirect-gateway def1 ipv6 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 67.207.67.2"
push "dhcp-option DNS 67.207.67.3"
keepalive 10 120
cipher AES-256-GCM
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
explicit-exit-notify

**client config:**

client
dev tun
proto udp
remote xxx.xxx.xxx.xxx 1194
tun-mtu 1500
mssfix 1400
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-GCM
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3

my server is hosted on DigitalOcean.
i have another VPN server built by the same script hosted on Hetzner  and its awesome! never faced a problem with it.

**Comment by arnefromsa** [comment]
@vahidx4r4x  - What are the locations of the droplets in DigitalOcean and similarly Hetzner (are they in the same region)? Are they similar specifications ?

**Comment by Nyr** [comment]
I am closing this as it is not an issue with the installer. This is likely a connectivity issue.
