### ISSUE TITLE
Where is `sacli`?

### ISSUE THREAD

**Issue by mariuszklinger** [Nyr/openvpn-install#820]
Hello!
I am pretty new in the OpenVPN, all looks great after the installation, except  I can't localize the "sacli" script anywhere... 
`root@localhost:~/tmp# find / -type f -iname "sacli"`
any help please? My aim is to add new user. 

Thanks

**Comment by trochdewei** [comment]
@mariuszklinger you can run openvpn-install.sh script and add user.
