### ISSUE TITLE
How can i connect to a vpn with Ubuntu 18.04 without a ubuntu desktop gui

### ISSUE THREAD

**Issue by Oyplap** [Nyr/openvpn-install#821]
I want to connect to a vpn with ubuntu 18.04 without using a desktop gui. Is that possible with openvpn? I did create my own vpn.

**Comment by Oyplap** [comment]
I have found out how to do it with the command:
sudo openvpn /home/MYNAME/client.ovpn

this happens:

Mon Dec 14 19:10:32 2020 Unrecognized option or missing or extra parameter(s) in                                                                                                                                                              /home/frikanadmin/frikanclient.ovpn:13: block-outside-dns (2.4.7)
Mon Dec 14 19:10:32 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO]                                                                                                                                                              [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Mon Dec 14 19:10:32 2020 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Mon Dec 14 19:10:32 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CT                                                                                                                                                             R' initialized with 256 bit key
Mon Dec 14 19:10:32 2020 Outgoing Control Channel Encryption: Using 256 bit mess                                                                                                                                                             age hash 'SHA256' for HMAC authentication
Mon Dec 14 19:10:32 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CT                                                                                                                                                             R' initialized with 256 bit key
Mon Dec 14 19:10:32 2020 Incoming Control Channel Encryption: Using 256 bit mess                                                                                                                                                             age hash 'SHA256' for HMAC authentication
Mon Dec 14 19:10:32 2020 TCP/UDP: Preserving recently used remote address: [AF_I                                                                                                                                                             NET]20.71.181.157:1194
Mon Dec 14 19:10:32 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Dec 14 19:10:32 2020 UDP link local: (not bound)
Mon Dec 14 19:10:32 2020 UDP link remote: [AF_INET]20.71.181.157:1194
Mon Dec 14 19:10:32 2020 TLS: Initial packet from [AF_INET]20.71.181.157:1194, s                                                                                                                                                             id=b3ac3f10 81e1f604
Mon Dec 14 19:10:32 2020 VERIFY OK: depth=1, CN=ChangeMe
Mon Dec 14 19:10:32 2020 VERIFY KU OK
Mon Dec 14 19:10:32 2020 Validating certificate extended key usage
Mon Dec 14 19:10:32 2020 ++ Certificate has EKU (str) TLS Web Server Authenticat                                                                                                                                                             ion, expects TLS Web Server Authentication
Mon Dec 14 19:10:32 2020 VERIFY EKU OK
Mon Dec 14 19:10:32 2020 VERIFY OK: depth=0, CN=server
Mon Dec 14 19:10:32 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GC                                                                                                                                                             M_SHA384, 2048 bit RSA
Mon Dec 14 19:10:32 2020 [server] Peer Connection Initiated with [AF_INET]20.71.                                                                                                                                                             181.157:1194
Mon Dec 14 19:10:33 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Mon Dec 14 19:10:33 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-ga                                                                                                                                                             teway def1 bypass-dhcp,dhcp-option DNS 168.63.129.16,route-gateway 10.8.0.1,topo                                                                                                                                                             logy subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,c                                                                                                                                                             ipher AES-256-GCM'
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: timers and/or timeouts modified
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: --ifconfig/up options modified
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: route options modified
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: route-related options modified
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options                                                                                                                                                              modified
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: peer-id set
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
Mon Dec 14 19:10:33 2020 OPTIONS IMPORT: data channel crypto options modified
Mon Dec 14 19:10:33 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
Mon Dec 14 19:10:33 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized                                                                                                                                                              with 256 bit key
Mon Dec 14 19:10:33 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized                                                                                                                                                              with 256 bit key
Mon Dec 14 19:10:33 2020 ROUTE_GATEWAY 10.0.0.1/255.255.255.0 IFACE=eth0 HWADDR=                                                                                                                                                             00:22:48:0c:87:1b
Mon Dec 14 19:10:33 2020 TUN/TAP device tun0 opened
Mon Dec 14 19:10:33 2020 TUN/TAP TX queue length set to 100
Mon Dec 14 19:10:33 2020 /sbin/ip link set dev tun0 up mtu 1500
Mon Dec 14 19:10:33 2020 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0                                                                                                                                                             .255
Mon Dec 14 19:10:33 2020 /sbin/ip route add 20.71.181.157/32 via 10.0.0.1
Mon Dec 14 19:10:33 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1



My system freezes and i can only connect to the ubuntu server if im also on the same vpn network, i try the same command and this happens:

Mon Dec 14 19:12:46 2020 Unrecognized option or missing or extra parameter(s) in                                                                                                                                                              /home/frikanadmin/frikanclient.ovpn:13: block-outside-dns (2.4.7)
Mon Dec 14 19:12:46 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO]                                                                                                                                                              [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Mon Dec 14 19:12:46 2020 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Mon Dec 14 19:12:46 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CT                                                                                                                                                             R' initialized with 256 bit key
Mon Dec 14 19:12:46 2020 Outgoing Control Channel Encryption: Using 256 bit mess                                                                                                                                                             age hash 'SHA256' for HMAC authentication
Mon Dec 14 19:12:46 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CT                                                                                                                                                             R' initialized with 256 bit key
Mon Dec 14 19:12:46 2020 Incoming Control Channel Encryption: Using 256 bit mess                                                                                                                                                             age hash 'SHA256' for HMAC authentication
Mon Dec 14 19:12:46 2020 TCP/UDP: Preserving recently used remote address: [AF_I                                                                                                                                                             NET]20.71.181.157:1194
Mon Dec 14 19:12:46 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Dec 14 19:12:46 2020 UDP link local: (not bound)
Mon Dec 14 19:12:46 2020 UDP link remote: [AF_INET]20.71.181.157:1194
Mon Dec 14 19:12:46 2020 TLS: Initial packet from [AF_INET]20.71.181.157:1194, s                                                                                                                                                             id=bfc2f7f0 e8a55786
Mon Dec 14 19:12:46 2020 VERIFY OK: depth=1, CN=ChangeMe
Mon Dec 14 19:12:46 2020 VERIFY KU OK
Mon Dec 14 19:12:46 2020 Validating certificate extended key usage
Mon Dec 14 19:12:46 2020 ++ Certificate has EKU (str) TLS Web Server Authenticat                                                                                                                                                             ion, expects TLS Web Server Authentication
Mon Dec 14 19:12:46 2020 VERIFY EKU OK
Mon Dec 14 19:12:46 2020 VERIFY OK: depth=0, CN=server



What should i do?

**Comment by PrzemekSkw** [comment]
Hi, I connect to my server on Dietpi with command:
`sudo openvpn --config /path to file/dietpi.ovpn`.

**Comment by Nyr** [comment]
> My system freezes and i can only connect to the ubuntu server if im also on the same vpn network, i try the same command and this happens:

Your SSH session will die if you route all traffic through the VPN, this is normal and expected in a road warrior setup.
