### ISSUE TITLE
Adding opt-in DoH support

### ISSUE THREAD

**Issue by Vheecha** [Nyr/openvpn-install#822]
If I'm not mistaken, openvpn server is making plain text DNS queries which leaves the data vulnerable to eavesdropping and tampering.

Now I know it can be circumvented in several ways from the server or client side but it would be nice to have DNS-over-HTTPS included in the script if possible as it would be more convenient for people during the setup.

Thanks for your work everyone.

**Comment by tkmw1985** [comment]
> If I'm not mistaken, openvpn server is making plain text DNS queries which leaves the data vulnerable to eavesdropping and tampering.
> 
> Now I know it can be circumvented in several ways from the server or client side but it would be nice to have DNS-over-HTTPS included in the script if possible as it would be more convenient for people during the setup.
> 
> Thanks for your work everyone

  openvpn can't do it itself  for example u can set adguard home or pihole for that !

**Comment by Nyr** [comment]
Duplicate: https://github.com/Nyr/openvpn-install/issues/906
