### ISSUE TITLE
editing openvpn-iptables.service for firewall in iptables

### ISSUE THREAD

**Issue by magesticmage** [Nyr/openvpn-install#825]
openvpn-iptables.service adds an entry to iptables and opens up any WAN (0.0.0.0/0) to be able to connect to the port 1194
I would like to edit the service but don't know how. I need to only allow a single incoming IP address to the firewall not just 0.0.0.0/0
is this possible?

i can see the entry by the command:
sudo iptables -L
And then remove the entry manually but every time openvpn-iptables.service adds it back again on restart.

**Comment by av-gantimurov** [comment]
You can change iptables options in `/etc/systemd/system/openvpn-iptables.service`
