### ISSUE TITLE
Cannot connect with my old ovpn files

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/openvpn-install#826]
Hi, I try to add new user and use command: `wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh`. I reboot my VPS server and now cannot connect to openvpn with my other devices and to my OpenVPN Status Monitor. I use new generated ovpn file on my laptop and it works. Do I have to generate new files to all my devices?

Regards,
Przemek

**Comment by disketkakg** [comment]
Hi, I have the same problem @Nyr

**Comment by Nyr** [comment]
> Do I have to generate new files to all my devices?

Yes, that is how it should be done.

An exception is if you configure the `duplicate-cn` directive in `/etc/openvpn/server/server.conf` but that is discouraged.
