### ISSUE TITLE
OpenVPN Access Server don't show connected clients

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/openvpn-install#827]
Hello, I install openvpn-as on my debian VPS and after login to admin panel I don't see my clients. I use different port that default 1194. Is it possible to make it work with openvpn-install script?

Regards,
Przemek

**Comment by hellresistor** [comment]
check on directories other diretories..

**Comment by PrzemekSkw** [comment]
@hellresistor Hi, thanks for answer but I cannot find anything useful. I delete openvpn-as and I will try Vesta Control Panel.
Regards.
