### ISSUE TITLE
--data-ciphers-fallback

### ISSUE THREAD

**Issue by vahidx4r4x** [Nyr/openvpn-install#829]
hi
i created a vpn server and i sat cipher to `CAMELLIA-128-CBC`, my pc doesnt have any problem connecting to server and i just added `--data-ciphers-fallback CAMELLIA-128-CBC` for better security and ignoring warnings.
my problem is i cant connect with my android phone it keep saying `crypto_alg CAMELLIA-128-CBC not found`. I deleted `cipher CAMELLIA-128-CBC` from `.ovpn` file but kept `--data-ciphers-fallback CAMELLIA-128-CBC` and connection was successful 

my question is "Is it secure to only have `--data-ciphers-fallback` option? does my data being encrypted?"

**Comment by TinCanTech** [comment]
`--data-ciphers-fallback` should not be used with this script.

**Comment by vahidx4r4x** [comment]
> 
> 
> `--data-ciphers-fallback` should not be used with this script.

what should i use? and how to do it?

**Comment by Nyr** [comment]
Just leave the default cipher configuration if you do not have a good reason to use otherwise. The script has reasonable default choices.

```
--data-ciphers-fallback alg

    Configure a cipher that is used to fall back to if we could not determine which cipher the peer is willing to use.
    This option should only be needed to connect to peers that are running OpenVPN 2.3 and older version, and have been configured with --enable-small (typically used on routers or other embedded devices).
```
