### ISSUE TITLE
Limit access to one connection only per certificate created

### ISSUE THREAD

**Issue by fabioganga** [Nyr/openvpn-install#834]
Hello,

Thanks for your hard work and for sharing this great script with the Github community!

It works great, but I would like to limit the connection to one connection per cerificate/user only, so that I can prevent abuse and unauthoized sharing of the .opvn files to other people.

Is this possible in any way?

Many thanks.

**Comment by TinCanTech** [comment]
Generally, this is not possible with OpenVPN.

With default settings, when a client uses the same credentials to connect a second time then the first connection is dropped.  If you use `--duplicate-cn` then a client can connect an unlimited number of different instances.

However, https://github.com/TinCanTech/easy-tls adds a new level of connection management to OpenVPN.  You can discuss this idea on Easy-TLS if you wish to.
