### ISSUE TITLE
Login with username and password

### ISSUE THREAD

**Issue by sviluppowebapp** [Nyr/openvpn-install#837]
Hi, when I run the script, everything works fine. I would like to be able to create users with username and password, so that when they try to authenticate they have to enter credentials. It would be possible ? Thanks

**Comment by dkksrong** [comment]
I need this, too

**Comment by marcoaluigi** [comment]
I need this, too

**Comment by marcoaluigi** [comment]
> Hi, when I run the script, everything works fine. I would like to be able to create users with username and password, so that when they try to authenticate they have to enter credentials. It would be possible ? Thanks

I solved it by removing 'nopass' in these lines from the script:

 ./easyrsa --batch build-ca nopass

   EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-server-full server nopass

   EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-client-full "$client" nopass

   EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-client-full "$client" nopass
