### ISSUE TITLE
255+ Clents to one server

### ISSUE THREAD

**Issue by grzegorzjj** [Nyr/openvpn-install#839]
In server.conf is line
server 10.8.0.0 255.255.255.0
meaning only 1 C class for clients.

What if I would like 500+ clients?
I can change of course netmask to 255.255.0.0 , but will it do? What with automatic client configuration creation? 

Thanks for advice.
Grzegorz.

**Comment by Nyr** [comment]
You would need to change the netmask and the iptables/firewalld routing configuration to SNAT the `10.8.0.0/16` subnet.
