### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 9964250741** [Nyr/openvpn-install#840]
Hi Sir,
Thank you for the software you had uploaded on GitHub.
I have some query regarding the usage of the OpenVPN.Is the software is Completely Open Source ?
Can we create unlimited clients on the server, If it is not possible what is the maximum number of clients can be created?
and How many concurrent clients can be connected at a time?
I am looking forward for your reply.

**Comment by Nyr** [comment]
Here is the [license](https://github.com/Nyr/openvpn-install/blob/master/LICENSE.txt).

With the default configuration of this script, the limit is 252 clients.

**Comment by 9964250741** [comment]
Thank you for your response

**Comment by 9964250741** [comment]
Hi sir,
Can we create multiple server instances to increase the number of clients?

**Comment by Nyr** [comment]
Sorry for the very late response.

For anyone else wondering, the subnet used for OpenVPN would need to be adjusted, no need to create multiple server instances.

**Comment by 9964250741** [comment]
Thanks for your response
