### ISSUE TITLE
AEAD Decrypt error: bad packet error only in one client

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/openvpn-install#841]
Hello,
I see in openvpn logs that multiple messeges only when connected to my server from my archlinux laptop. My other clients don't generate that issue. VPN tunnel works on that laptop fine. 

```
openvpn[613]: Dell/83.242.122.30:31880 AEAD Decrypt error: bad packet ID (may be a replay): [ #29262 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```
Regards,
Przemek

**Comment by Nyr** [comment]
This can be a MTU issue or other kind of network related issue.

You can try configuring the `mssfix﻿` directive (read some documentation online) if this message is appearing very frequently.

If it is infrequent, you can ignore it.
