### ISSUE TITLE
works once, not after reboot

### ISSUE THREAD

**Issue by yik77** [Nyr/openvpn-install#845]
This is rather weird, but the script works fine, on fully updated (3/2021) remote debian 9.2 server.
I got my username.opvn file back, and I can connect. When I reboot remote server, it no longer works. I was able to reproduce this behavior, by running option 3, removing openvpn, restarting, running the script again, running openvpn and connecting, but not after restart... 

```
me@debian:~$ sudo systemctl status openvpn@*
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-03-08 23:10:07 EST; 14min ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 280 ExecStart=/usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --config /etc/openvpn/server.conf --writepid /r
 Main PID: 350 (code=exited, status=1/FAILURE)

Mar 08 23:10:07 debian ovpn-server[350]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Mar 08 23:10:07 debian ovpn-server[350]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Mar 08 23:10:07 debian ovpn-server[350]: Socket Buffers: R=[212992->212992] S=[212992->212992]
Mar 08 23:10:07 debian ovpn-server[350]: TCP/UDP: Socket bind failed on local address [AF_INET]xxx.yyy.zzz.132:1194: Cannot assign requested address
Mar 08 23:10:07 debian ovpn-server[350]: Exiting due to fatal error
Mar 08 23:10:07 debian ovpn-server[350]: Closing TUN/TAP interface
Mar 08 23:10:07 debian ovpn-server[350]: /sbin/ip addr del dev tun0 10.8.0.1/24
Mar 08 23:10:07 debian systemd[1]: openvpn@server.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 23:10:07 debian systemd[1]: openvpn@server.service: Unit entered failed state.
Mar 08 23:10:07 debian systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
```

this may be related to the 
`systemctl status openvpn@*` vs 
`systemctl status openvpn-server@*` 
issue, maybe...I am not expert...

**Comment by AdrianDSW** [comment]
I also encountered the same problem, but I still have no solution...
exit-code 1

**Comment by Nyr** [comment]
Please, provide the output of the following commands when it is failing:

`systemctl status openvpn-server@server.service`
`systemctl status openvpn-iptables.service`

Also, let me know which hosting provider are you using.

**Comment by Nyr** [comment]
I will reopen this issue if anyone is able to provide the requested information.

**Comment by TinCanTech** [comment]
> TCP/UDP: Socket bind failed on local address [AF_INET]xxx.yyy.zzz.132:1194: Cannot assign requested address

The most likely fault here is that openvpn is already running and so the port 1194 is taken.

**Comment by yik77** [comment]
I dont think it is running twice, or "already running" as someone suggested...

here is the requested info: 
```
janus@debian:~$ sudo systemctl status openvpn@server
[sudo] password for janus: 
● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/lib/systemd/system/openvpn@.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
janus@debian:~$ 
```
and 

```
janus@debian:~$ systemctl status openvpn-server@server.service
● openvpn-server@server.service - OpenVPN service for server
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-04-06 14:15:51 EDT; 9min ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
  Process: 359 ExecStart=/usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf (code=exited, status=1/FAI
 Main PID: 359 (code=exited, status=1/FAILURE)
lines 1-8/8 (END)
```

and

```
janus@debian:~$ systemctl status openvpn-iptables.service
● openvpn-iptables.service
   Loaded: loaded (/etc/systemd/system/openvpn-iptables.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2021-04-06 14:15:51 EDT; 10min ago
  Process: 355 ExecStart=/sbin/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 353 ExecStart=/sbin/iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 337 ExecStart=/sbin/iptables -I INPUT -p udp --dport 1199 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 262 ExecStart=/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 185.183.96.132 (code=exited, status=0/SUCCESS)
 Main PID: 355 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/openvpn-iptables.service
janus@debian:~$ 
```

**Comment by Nyr** [comment]
You need to forget about `openvpn@*`. The correct service unit name is `openvpn-server@server.service` and it is the only one which you should deal with.

Since you also have the `openvpn@server.service` unit enabled, there is some kind of mixup in your system, and I suggest you to use the script in a new, clean system if you are unable to resolve it by yourself.

**Comment by TinCanTech** [comment]
Unfortunately, many Linux distros still ship systemd unit files such as `openvpn.service` and `opevpn@.service` because they fear their users will complain otherwise.  This leads to exactly the problem of an old service file, having already started openvpn, causing conflicts with modern service files.  This leads to the error reported here: `Cannot assign requested address`

**Comment by Nyr** [comment]
Yes, very commonly users do not even know that the new unit file exists, they see the legacy unit file disabled and try to enable it.

That, or a variation of that is very likely what happened here.

**Comment by yik77** [comment]
should the script check for that, and remove/disable unused units? 
I installed it on clean fresh install of debian, and I can hardly think of more "pristine" environment

**Comment by Nyr** [comment]
If your server has a `openvpn@server.service` unit configured like it seems to be the case, there are two options:
- You used an old version of the installer
- You configured that unit manually or using a different installer

In a clean install of Debian, the installer will setup the proper unit file and work just fine.

I hope this clarifies it.
