### ISSUE TITLE
Use server port for client

### ISSUE THREAD

**Issue by daeeros** [Nyr/openvpn-install#846]
Hi, i cant open port in my pc (blocked from provider), but i have a question, i have installed openvpn in my ubuntu server, there is opened all ports, so can i use server port in my pc (windows) i wont to open rust server with udp 28015 port, host in my pc but use port in ubuntu server, it is possible?(

**Comment by Nyr** [comment]
Yes, you can do that but it is out of the scope of this issue tracker.
