### ISSUE TITLE
DEPRECATED OPTION: --cipher set to 'AES-256-CBC'

### ISSUE THREAD

**Issue by abhishekluv** [Nyr/openvpn-install#847]
How do I fix this so that this error doesn't show up in the OpenVOP 

DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.

**Comment by Nyr** [comment]
No need to "fix" anything, it is just a warning which will disappear in future versions of the script.
