### ISSUE TITLE
GCP disables ip_forward=1 in 99-gce.conf

### ISSUE THREAD

**Issue by trivvz** [Nyr/openvpn-install#848]
I tried to set up this script on Google Cloud Platform, and it seems that Ubuntu image I have chosen comes with `/etc/sysctl.d/99-gce.conf` that sets `net.ipv4.ip_forward = 0` consequently overwriting setting it to `1` in `30-openvpn-forward.conf`.

The issue was solved after I renamed `30-openvpn-forward.conf` to `99-openvpn-forward.conf` (if the numbers are the same the later alphabetical order takes precedence).

I found a solution in [another similar script](https://github.com/angristan/openvpn-install/issues/744), and there the priority was updated to 99 to avoid similar issues.

If you don't see any possible negative implications I think that it can be updated here as well.

**Comment by Nyr** [comment]
Thanks a lot for the report, and sorry for not merging the pull request sooner.
