### ISSUE TITLE
Ovpn Config location located

### ISSUE THREAD

**Issue by Zovpn** [Nyr/openvpn-install#85]
Hi there I'm installed Openvpn using auto scripts below by using Connectbot apk.
May i know where the Ovpn Config location located in Android Phone?

Search over in root/A.Ovpn & scan whole device but not found.

Many thanks.

wget git.io/vpn --no-check-certificate -O openvpn-install.sh && bash openvpn-install.sh

**Comment by TheDoctorsLife** [comment]
you have to copy over the .ovpn file onto your phone. I'd recommend something like the downloads folder.(on the phone)

**Comment by ZaaraHannah** [comment]
How to copy/download please thx

**Comment by ZaaraHannah** [comment]
Or got anyway donate custom help from you?

I need this type of Ovpn (below) 

eg:


client
proto tcp
remote 128.199.156.58 443
route 0.0.0.0 255.255.255.255 vpn_gateway
route 202.75.133.49 255.255.255.255 net_gateway
http-proxy 127.0.0.1 8989
dev tun
dev-type tun
reneg-sec 604800
remote-cert-tls server
sndbuf 0
rcvbuf 0
cipher BF-CBC
auth-user-pass
tun-mtu 1500
comp-lzo no
verb 3


<ca>
-----BEGIN CERTIFICATE-----
MIIFajCCA1KgAwIBAgIBATANBgkqhkiG9w0BAQsFADBGMSEwHwYDVQQKDBg1NjI1
YzIxYzNjZmUxNjJhYmE2NjJkZDMxITAfBgNVBAMMGDU2MjVjMjFjM2NmZTE2MmFi
YTY2MmRlMzAeFw0xNTEwMjAwNDI1MDNaFw0yNTEwMTkwNDI1MDNaMEYxITAfBgNV
BAoMGDU2MjVjMjFjM2NmZTE2MmFiYTY2MmRkMzEhMB8GA1UEAwwYNTYyNWMyMWMz
Y2ZlMTYyYWJhNjYyZGUzMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
yhAkXC6vH8IRlo55UOrEhderKjJtu39hgbho8czNo2CTu5Y4/VwOYLojjrSX7ZVQ
yaYkLBzhI0DQNAJwHpXnkbC8nnEZ/1UqLQo/hVuA493ajeBAaYNl3XW8xoxEFrzy
9hDJPxPKcRoOAQPiC0oO8h3wIVrGquMw4KQi4gn2nh5WEaVNW/X07v0ZIKbJDC6H
JO+dbz3qtxDDgdTRwQRGJkjgA2hE7tn4f+4HE/RDl1m/3IA378wUKkG/AjXdgyqj
xBQKXKlVwG+3IFFuyv5X98FXg65Q+3oO6aQPAhET57MjH5g3Y8GirNlW4bUuHs1m
jsN02+ZitBOgQZ7Wpqqc31JEgUO7nQ2c7UD/knC0L3S2kez3N/QeSXLqwIIjUIgv
ctVy086x8HCgSqiOPWlwJx2M4dLpT/MJ5I3VIkAkqKjUx7jAq3EjaKqv03KGbMVF
//A8S8Y11orZ5aGwK+tmbMNbp68SM8M6QCa1/rhsXXn8kgdYFSJmazN5wZR6Xx9g
EfJ6iDNQiijVOur7EoLk2Iy90moNmaaJhTrmv58pR/wKxtPyqCfTVLErcoDCHF7g
HMXBlXNs4o5M8atFc3VS8qChFslFnjNTcPF9fjV5gEX0VagjafY98tXB3b/YvVkl
jlcwFgNMvFAyWIdk8U/5lxCalEihjY2i4ZXUhRodF5sCAwEAAaNjMGEwDgYDVR0P
AQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHWzsQD8bgVBKr4v
gGaGsbabNsBNMB8GA1UdIwQYMBaAFHWzsQD8bgVBKr4vgGaGsbabNsBNMA0GCSqG
SIb3DQEBCwUAA4ICAQCFtTaujMo11PtVMgn4AYVh2vtF5WpDZE1+qNnLqnP6V9k4
m3K8TzaRhBeGYpxJiecQ7rp8yBnphZowzf1yTfu86dFMdsiw2caw/bWZazEWxZmb
/0fOwJYgOLOZyHrD75jDoTIMUPYP3a4bqtIPF1Xp/ysPXdrWMhEtpsyoaMzDi73Z
mAdnKbnYvCiWZVn+ipKo8bisWsz3XtpM/Pw1EzkVPS0Yrg/ERk7PXsdt4rS6CzmG
3PO/EyNhc86sus7vDCAcyH4IZILhCjKcfjj9N+9Zjrr+qwUHYcLjd9uf1Eke8Lw6
+RO7adSt3U7cp0uiSbaho501O/utpEF4+0r26clc5CBw9kxjUFU1VDZUb2e017QK
Qxgj3kVWfkGy7bsjOzUqBhieeIXG+yhAWZY4KL9vfCVOuURF5/uVe5hja9RU29Xh
eEwu10IY6AP+uK7iEfHoXsEj5cbIDk7/bIIQ88xjJPitu6ZHgsudGAi6REQULISo
orvL44OF0WQZFTGNKuNf2yQZznFW4ihlU5e025Zf6wNP6NkoKF/BH3SkWSjHXn8Y
7b58bTvV1iKEy1HAANBmZcTmH6rGSmWv8Pe/yL0KOjQFKEbKU57saOdAKhanNmkv
6jvR/XMZBSGFG+4Z16jbYaYvm73/tnVE1oo8TzCd/OnwaBqSQXm+Pd3radOhKg==
-----END CERTIFICATE-----




</ca>


Many thanks :)

**Comment by Nyr** [comment]
There is clearly a language barrier here, maybe a technical one too.

- The latest config you posted isn't generated with the script, so I don't understand why you did it.
- Did you connect via SSH to your server using an Android phone? If so, you need to use some SFTP client and download the .ovpn file from the server. This file is not saved in your phone, it is in your remote server.

Closing this as it isn't an issue with the script.

**Comment by Zovpn** [comment]
Reason coz only this way we can bypass our ISP.

No. I connect via Ovpn.

Yes android fon with ovpn 

Please need you help.

Many thanks

**Comment by Nyr** [comment]
> Please need you help.

Difficult if you don't improve your English, sorry.

Anyway if you need to use port 443 TCP, a barebones install with this script wouldn't work.

**Comment by Zovpn** [comment]
Thanks. And sorry for using our local short form english.

**Comment by Zovpn** [comment]
Any idea how to get those Ovpn Config installed? Thanks

**Comment by Nyr** [comment]
Maybe this will help you: https://www.youtube.com/watch?v=S9ZP08Y2PvQ

**Comment by Zovpn** [comment]
Thanks. :)
