### ISSUE TITLE
Love the simplicity... but can we get even more. 

### ISSUE THREAD

**Issue by jacksnodgrass** [Nyr/openvpn-install#854]
Maybe some command line arguments.... 

bash ./openvpn-install.sh iface=eth0  client=client1

and the script does all of the defaults and uses these options.  No prompting from the user for anything at all.

**Comment by Nyr** [comment]
Yes, an unattended mode is requested from time to time and is something which I have in mind, but there are currently other priorities like preparing for the new RHEL-based distros and OpenVPN v2.5.
