### ISSUE TITLE
Script overwrites easy-rsa CN value

### ISSUE THREAD

**Issue by OpalSec** [Nyr/openvpn-install#858]
Creating a client certificate manually using easy-rsa with  `root@raspberrypi:/etc/openvpn/server/easy-rsa# ./easyrsa build-client-full test nopass` generates a .crt with the correct CN value of "test": 
```
root@raspberrypi:/etc/openvpn/server/easy-rsa/pki/issued# openssl x509 -subject -noout -in test.crt 
subject=CN = test
```

However if I do the same by using this script's Create new client option, it overwrites that .crt's CN value and sets it to "ChangeMe":
```
root@raspberrypi:/home/pi/Downloads# openssl x509 -subject -noout -in test.ovpn 
subject=CN = ChangeMe
```

I need to use the CN value to configure OpenVPN to assign a static IP per client, but can't do it with ovpn configs generate with this script as the CN's are all set to "ChangeMe".

How is this happening?

**Comment by Nyr** [comment]
The `.ovpn` file contains multiple certificates, and OpenSSL is reading the CA because it is the first one, not the client certificate.

The CA CN is irrelevant, and the client CN is set correctly by the script.
