### ISSUE TITLE
find a way to avoid blocking

### ISSUE THREAD

**Issue by Zo0oX** [Nyr/openvpn-install#859]
hello

openvpn worked good, thanks a lot, but my country blocked vpn, and maybe 1 day or 2 day worked and after blocked by internet providers, how can i avoid from blocking ?

thanks

**Comment by TinCanTech** [comment]
I have had some _minor_ success defeating DPI firewalls using [Easy-TLS](https://github.com/TinCanTech/easy-tls) to create TLS-Crypt-V2 keys for OpenVPN.

If you care to try it then I will try to help .. but no promises, it _may or may not_ work ..

**Comment by Zo0oX** [comment]
this is very good, im very happy if you help me

**Comment by Zo0oX** [comment]
how can i learn it ? please send email

**Comment by Nyr** [comment]
Generally speaking, OpenVPN is not the right tool for the job. Shadowsocks is usually a better tool (it is not a VPN) to evade blockrades.

You could also run OpenVPN over some other protocol, but that is out of the scope of this script. The solution proposed above would be a good approach, if it works for you (I am not very hopeful, it will depend on the country/equipment used).
