### ISSUE TITLE
no discussion page

### ISSUE THREAD

**Issue by yozdas** [Nyr/openvpn-install#863]
Can you open discussion page, so we can ask questions which are not issue?

I want to ask questions about splitting DNS, and auth with username and password etc.

thanks for this great script. Saved a lot of time.

**Comment by Nyr** [comment]
I have a limited amount of time, so opening a dedicated forum is unattainable for me at this point.

You can take a look at the official OpenVPN documentation, or ask in the LowEndTalk forum, where this script [originated](https://www.lowendtalk.com/discussion/10587/openvpn-automated-installer).

**Comment by yozdas** [comment]
may be other volunteers could help, you may not have to constantly spend time.
