### ISSUE TITLE
Mikrotik Config

### ISSUE THREAD

**Issue by mercenaruss** [Nyr/openvpn-install#865]
Hello, script is working like charm,is just perfect. Thank you for your great work.
I want to connect all my entire home network using Mikrotik but unable because of tls-crypt,better said i think this is the cause.
My connection to server is always terminated,but from laptop i dont have any issue.
It's possible to adjust script to be able to disable next parameters:
UDP mode
LZO compression
TLS authentication
authentication without username/password

**Comment by sanhuoO** [comment]
https://forum.mikrotik.com/viewtopic.php?t=92546#p486996
