### ISSUE TITLE
cant have multiple servers

### ISSUE THREAD

**Issue by shacalaca** [Nyr/openvpn-install#866]
Creating a second server.conf does not makes another service start. Somehow the service scripts does not look for multiple conf files.

**Comment by asiral** [comment]
I would like to understand this better, too.  I cannot figure out how OpenVPN looks in the subdirectories instead of /etc/openvpn/.  It ignores other directories like /etc/openvpn/server2 and journalctl throws errors with configuration files in /etc/openvpn/
