### ISSUE TITLE
Add user, without losing current connections

### ISSUE THREAD

**Issue by tautapps** [Nyr/openvpn-install#869]
If 100 users connect with their own keys and you create a new key for the new user, will all connections be lost?
I'm looking for a strategy to keep connections alive

![image](https://user-images.githubusercontent.com/78632774/117560482-7be9a680-b0a3-11eb-885f-7277e10d9451.png)

**Comment by Nyr** [comment]
Clients can be added or revoked freely without breaking active connections, do not worry about it.
