### ISSUE TITLE
DEPRECATED OPTION

### ISSUE THREAD

**Issue by ghost** [Nyr/openvpn-install#870]
Upon connecting with a new fresh OpenVPN server I am greeted by the following warning:

DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning

**Comment by Nyr** [comment]
Duplicate #847
