### ISSUE TITLE
RockyLinux and AlmaLinux

### ISSUE THREAD

**Issue by tl5k5** [Nyr/openvpn-install#871]
Can you add support for CentOS replacements RockyLinux and AlmaLinux?

`# ./openvpn-install.sh 
This installer seems to be running on an unsupported distribution.
Supported distributions are Ubuntu, Debian, CentOS, and Fedora.
`

**Comment by Nyr** [comment]
Yes, this will be added soon.

**Comment by cWashington91** [comment]
Hello. I'd like to take a look at implementing this, if you don't mind.

**Comment by Docop2** [comment]
Great future addition. But also, please don't remove centos7, as it's a long time running. many thanks

**Comment by Nyr** [comment]
This has been implemented with the latest commit.
