### ISSUE TITLE
Change server IP

### ISSUE THREAD

**Issue by pouyaw** [Nyr/openvpn-install#878]
Hi, I changed my server ip, Now how can i change server ip in openvpnn config.
I try server.conf but it’s not effective

**Comment by pehden** [comment]
The server requires a static ip.

**Comment by GoudronViande24** [comment]
You will also have to edit all the client .ovpn files to make them connect to the new IP. You should make a domain or subdomain for your openvpn server so in case it changes again, you just have to edit the DNS record of the domain and everything works again.

**Comment by KG7QIN** [comment]
Also check if you have a  /etc/systemd/system/openvpn-iptables.service file.  

If it exists then it will be the one that does the firewall setup that has the IP address of your old system in it.

It looks simliar to:

ExecStart=/usr/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to <server ip>
ExecStart=/usr/sbin/iptables -I INPUT -p udp --dport 1194 -j ACCEPT
ExecStart=/usr/sbin/iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStart=/usr/sbin/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=/usr/sbin/iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to <server ip>
ExecStop=/usr/sbin/iptables -D INPUT -p udp --dport 1194 -j ACCEPT
ExecStop=/usr/sbin/iptables -D FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStop=/usr/sbin/iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

Change the <server ip> part to match the new IP of your server.

Then do a systemctl daemon-reload followed by a systemctl restart openvpn-iptables.

That will reset your iptables firewall and traffic should then start flowing from the VPN client via the server again.

**Comment by Nyr** [comment]
For anyone wondering, the best way to deal with a dynamic public IP address would be to use `MASQUERADE` rules instead of `POSTROUTING`, and to use a dynamic DNS service for the clients to connect to.

But this functionality is not implemented into the installer.
