### ISSUE TITLE
Welcome/Landing Page

### ISSUE THREAD

**Issue by Stefan-CPlanet** [Nyr/openvpn-install#880]
Hello,
I have 1 quick question about this project.

Is it possible to edit the client/server configuration file in a way that when you connect to OpenVPN it automatically opens a Landing page?

I need it so that clients that connect with OpenVPN to a network can have an easy intranet page from where they can have links to all the services in the network?

Thank you

**Comment by Nyr** [comment]
Check the documentation for `--up` parameter, you can run a command when connecting with it.
