### ISSUE TITLE
Username and Password.

### ISSUE THREAD

**Issue by vahidx4r4x** [Nyr/openvpn-install#885]
Hi tnx for your great project.
Is there anyway to connect to server with username and password ?

**Comment by bugrevealingbme** [comment]
any solution?

**Comment by Nyr** [comment]
This is not a planned feature. Certificates are more secure, can be included within the config file and are the "standard way" to do authentication in OpenVPN.

**Comment by WillemWever** [comment]
Hi @Nyr,

Using both a certificate and will be even more secure. Maybe you could reconsider this feature?

**Comment by MotazHakim** [comment]
> Hi @Nyr,
> 
> Using both a certificate and an username with password will be even more secure. Maybe you could reconsider this feature?

+1
