### ISSUE TITLE
Always being discconected, wondering why?

### ISSUE THREAD

**Issue by ItsAdventureTime** [Nyr/openvpn-install#89]
Hello,

My iPhone keeps on randomly being disconnected from and I don't know why. Is it because my computer is connected to the VPN through the same username? How many concurrent users are allowed to connect to the same username? I am using Viscosity for OS X when I am connected to the VPN service and as for my iPhone, I am using the OpenVPN client (imported the .ovpn file).

Thanks.

**Comment by Nyr** [comment]
The script doesn't allow 'duplicate-CN', so a different certificate is needed per device.

Anyway this is not a problem with the script.

**Comment by ItsAdventureTime** [comment]
Well, you said "The script doesn't allow 'duplicate-CN'" > which means a different certificate is needed per device. Then you said it isn't a problem with the script? Who which is which? Btw, I am not blaming your script. It was awesome. It works on my end, all of them. The moment that I switched to a different host (not using DigitalOcean and Vultr) anymore, your scripts works great! Or, is it because I am using CentOS 7?

**Comment by Nyr** [comment]
> Well, you said "The script doesn't allow 'duplicate-CN'" > which means a different certificate is needed per device. Then you said it isn't a problem with the script?

Both statements are compatible, yes.
