### ISSUE TITLE
Hard to connect over OpenVpn Connect(android) by OpenVPN

### ISSUE THREAD

**Issue by egosha17** [Nyr/openvpn-install#890]
Hi,
It is very hard to connect over official Openvpn App..
I have to try 5 6 times to connect... 
Openvpn gui and VPN client pro apps connect just one click only...
I have Linode servers...
Trying to connect from Turkmenistan

**Comment by Wutze** [comment]
Recently, there was the same problem here. Also from Turkmenistan. Changing the encryption obviously helped here.

tls-auth ta.key 0
to
tls-crypt ta.key 0

Described in detail here:

https://github.com/Wutze/OpenVPN-WebAdmin/issues/42

**Comment by egosha17** [comment]
Thanks for spending time to answer my issue but my issue is not same as on the link. My scripts connect with official app very hard and after connection work well. On Official app sometimes it is hard to connect.

With VPN Client PRO.apk it connects with just one click  but same .ovpn script connects very hard over official app.
 
I am interested the reason of connectivity problem of official app of the Openvpn

**Comment by Wutze** [comment]
Ahh Ok, but I guess we won't be able to solve that problem here then. You should probably ask the developers themselves. Because I don't know this "PRO.apk", which is obviously from a download that has nothing to do with OpenVPN.
