### ISSUE TITLE
Have an issue with scaleway

### ISSUE THREAD

**Issue by Behnamjef** [Nyr/openvpn-install#899]
Hi, first of all, thanks for your script it's very helpful.

I used your script on a VPS and it worked. I switch my VPS to scaleway and do the same, but when I try to connect on the client-side it doesn't connect. The server is behind the NAT so I used the public IPv4 that exists in the scaleway dashboard.
Also, I read other threads and have no clue!
Is there anything that should be changed about the firewall or something like this?

**Comment by Nyr** [comment]
Just tested and the installer is still working fine on Scaleway.
