### ISSUE TITLE
DoH and DoT

### ISSUE THREAD

**Issue by vahidx4r4x** [Nyr/openvpn-install#906]
Hi,

Is there anyway to push DoH or DoT to client instead of DNS IP address?

**Comment by Nyr** [comment]
Not really at this time, it is something which needs to be dealt with within your client.

Or... one option would be if you want to set up the server to act as a secure recursor and proxy requests for the clients, then you can provide clients with the recursor's local IP.

**Comment by Fix3dll** [comment]
I find `--dns` argument inside the [2.6 document](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/). Is it possible to do with this? @Nyr

**Comment by Nyr** [comment]
> I find `--dns` argument inside the [2.6 document](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/). Is it possible to do with this? @Nyr

When 2.6 is available in the distro repos, yes.
