### ISSUE TITLE
Is there any way that i can use all my IP's available on server to act as VPN connection

### ISSUE THREAD

**Issue by Codelixr** [Nyr/openvpn-install#91]
In my server i have 6 IP addresses, while configuring the openvpn using your script i put the default ip it was showing and everything is working properly

but i want to do the same with my other IP's too.

**Comment by Nyr** [comment]
Not an issue with the script and not supported by the script.

**Comment by Codelixr** [comment]
can you please suggest me a way so that i can do it my self ?

**Comment by Nyr** [comment]
Yes, try using a search engine or reading the OpenVPN manual.

**Comment by Codelixr** [comment]
wow, Thanks for this great suggesting. You are awesome

Thanks
