### ISSUE TITLE
How to allow for more than 254 clients?

### ISSUE THREAD

**Issue by ardraeger** [Nyr/openvpn-install#913]
Hi all,

I'm trying to connect more than 254 clients at ones to my setup. I have not had any problems connecting up to 120 clients at the same time.
However, I noticed that the ip addresses awarded to new clients does not exceed the range of 10.8.0.XXX. So I'm afraid that when the 255 client at the same time will try to connect that it will fail.
I have done some research on how to increase the max number of allowed clients. 
[Allowing more than 254 connections](https://github.com/kylemanna/docker-openvpn/issues/444) 

Does anybody know how to allow more than 254 clients at the same time and what steps to take!? 
Also is there any known issue to connect lets say up to 2000 clients except for memory and cpu requirements?

Thanks for the help guys!

**Comment by velychkov** [comment]
I guess you can look for a paid version if you have big organizations.

**Comment by Nyr** [comment]
You can increase the default subnet to anything larger than a /24, this implies slightly modifying the original script to deal with larger subnets. 2000 clients could connect that way without trouble.
