### ISSUE TITLE
No tc.key File

### ISSUE THREAD

**Issue by WAleemS** [Nyr/openvpn-install#915]
After trying to add a User to the VPN Server i get this message:

`sed: can't read /etc/openvpn/server/tc.key: No such file or directory
`
The Script still generates the .ovpn file but this file cannot be read by an openvpn client.
What can i do to fix this?

**Comment by velychkov** [comment]
you need add more info about your system, I use ubuntu and for me everything is ok

**Comment by Nyr** [comment]
Did you install using an older version of `openvpn-install.sh` and then used a newer version to add the user?

It is by far the most likely explanation. If that is not the case, please let me know and we can troubleshoot further.
