### ISSUE TITLE
Ubuntu  20 04 lts After instalation the service cannot find the config or any of the keys

### ISSUE THREAD

**Issue by dustin-auby** [Nyr/openvpn-install#924]
Hi,

I get the following error when starting openvpn service starts Error opening `configuratio                                                                                                                             n file: /etc/openvpn/myserver.conf` i have tried moving all the files from server into the openvpn folder and renaming server.conf to myconf.conf and this worked but then hits another error which is the port is already in use. i have double checked nothing else is using the port

**Comment by richliu** [comment]
Probably it caused by script didn't put file name right on directory /lib/systemd/system

please check /lib/systemd/system/openvpn*

and start your service with the service name with your configure.

**Comment by Nyr** [comment]
You are using the wrong systemctl unit name. This is the right one:
`systemctl start openvpn-server@server.service`
