### ISSUE TITLE
Static IP address for clients

### ISSUE THREAD

**Issue by b16rdp** [Nyr/openvpn-install#930]
BTW, Great tutorial, indeed up and running with clients in a little over 5 mins.
However, I am totally stuck on how to get static IP addresses working.  I need my clients to come into static IP addresses as a reverse proxy.

I have gone through all I can think of but I cannot get the CN to update from anything by ChangeMe.  I have changed the ChangeMe in multiple files but with no Joy.  I have tied altering the script with --req-cn but that also did not work.

Most grateful for any help before I rip all my hair out.

**Comment by Nyr** [comment]
That is outside of the scope of this issue tracker.

If you want to assign static internal IP addresses to clients, you indeed need to use the `client-config-dir` option, but I did not write any tutorial, so it is probably better to ask elsewhere for support.

**Comment by b16rdp** [comment]
Thank you for your reply. I actually working out how to do the static IP addresses and it's working well. I will make a document in a few days for anyone that would like to do the same when generating single opvn files.  It's actually really easy :-)

**Comment by emreakcadag** [comment]
> Thank you for your reply. I actually working out how to do the static IP addresses and it's working well. I will make a document in a few days for anyone that would like to do the same when generating single opvn files. It's actually really easy :-)

Hello, 

I am trying to do same development but I have not succeed :) Can you explain how you did please?

Thanks.
