### ISSUE TITLE
Please add email Module so once the VPN done and account Created with get the file via email.

### ISSUE THREAD

**Issue by tahasaifeee** [Nyr/openvpn-install#932]
Please add email Module so once the VPN done and account Created with get the file via email.

**Comment by Nyr** [comment]
This is not feasible as we can not assume that the server will have a working MTA available.

I considered other approaches like setting up a temporary HTTPS server for the user to download the certificate, but none of them are fully viable to be honest.

I am still open to creative approaches on this matter, if someone has ideas.
