### ISSUE TITLE
Zombie users

### ISSUE THREAD

**Issue by whoisspy1** [Nyr/openvpn-install#934]
After deleting users they still connected to the server Ubuntu 2.0.04 how can I fix it ?

**Comment by ja4ert** [comment]
open openvpn-install.sh
"bash openvpn-install.sh"
select 2 and select usr

**Comment by Nyr** [comment]
The certificate revocation list is read during the connection phase, so if the user is already connected you would need to restart the OpenVPN service:

`systemctl restart openvpn-server@server.service`
