### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by sacredd** [Nyr/openvpn-install#938]
Good afternoon, thanks for the script, but could you tell me, I have ipv6 and the server also supports ipv6, how can I use it?

**Comment by GitHubBARBARR** [comment]
ipv6 > ipv4 , u know ?

**Comment by Nyr** [comment]
IPv6 inside the tunnel should be configured automatically during setup if the server has IPv6 available. Still, the client will connect to the server over IPv4.
