### ISSUE TITLE
auth SHA1

### ISSUE THREAD

**Issue by igorwhite** [Nyr/openvpn-install#939]
Hello.

How can I change auth from SHA512 to SHA1 - mikrotik can't SHA512

Best Regards, Igor.

**Comment by igorwhite** [comment]
Updated firmware Mikrotik appeared auth SHA512
Now swears at TLS

**Comment by Nyr** [comment]
For anyone arriving here and wondering about this or something related.

It is not only SHA512, they also do not support TLS Crypt and some other stuff.

The MikroTik implementation of OpenVPN sucks and should be avoided. If you are REALLY desperate you can try using a (very) old version of this script, but of course that is a bad idea.
