### ISSUE TITLE
Support macos?

### ISSUE THREAD

**Issue by ryanhz** [Nyr/openvpn-install#941]
Any plan to support MacOS?

**Comment by Nyr** [comment]
Sorry but the truth is, there is no chance for it to happen.

**Comment by ryanhz** [comment]
You hate macos or it is just purely impossible?

**Comment by Nyr** [comment]
I do not hate macOS, in fact I used it as my daily driver for many years. But macOS is not a server oriented operating system.

Client configuration files can always be used with Tunnelblick, Viscosity or any other OpenVPN compatible client, in macOS or elsewhere.

**Comment by ryanhz** [comment]
I have an old macbook, on which I want to run vpn server

**Comment by TinCanTech** [comment]
@ryanhz **_MacOS as an OpenVPN Server_ Howto**:
- Download [OpenVPN Server config example](https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf)
- Download [EasyRSA](https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa)
- Read [OpenVPN Howto](https://community.openvpn.net/openvpn/wiki/HOWTO)
- Try it.
- Almost certainly fail.

And understand **why** this script does **not** support MacOS as a server.
