### ISSUE TITLE
Error opening configuration file: /etc/openvpn/server.conf

### ISSUE THREAD

**Issue by alixxila** [Nyr/openvpn-install#945]
Hello, 

First thanks for the hard work.

I do not have an error while starting openvpn.service but i have this error message while starting openvpn@server.service on a fresh VPS : 

- Debian 10 (buster) from Azure

![image](https://user-images.githubusercontent.com/73705891/166310127-e36b86ab-7553-48b0-97b6-7aefdc0b4f05.png)

This is what i see from the client side, but i'm sure that the problem come from de server : 

![image](https://user-images.githubusercontent.com/73705891/166310282-7ab10b15-1187-420d-bba1-5c9ae86966e5.png)

I also have this error from the service openvpn@server-server.service, it's very strange because the server-server.conf do not exist : 

![image](https://user-images.githubusercontent.com/73705891/166310560-4859a5e3-4737-4fde-9942-485e0dcfc954.png)

So i tried to change the config of openvpn@server-server.service to change the server-server.conf with the server.conf that we can find in /etc/openvpn/server/ but i have much more errors than before, usually i try to fix problem by myself but this time i need help.

Thanks

**Comment by Nyr** [comment]
The correct name is: `openvpn-server@server.service`.

You do not need to change anything.
