### ISSUE TITLE
Changing public ip

### ISSUE THREAD

**Issue by hafizhmakmur** [Nyr/openvpn-install#948]
If for some reason the server where I installed openvpn have changed public IP, how do I change the openvpn server configuration accordingly? I have tried changing the `remote IP` in the .ovpn file but it's sometimes working sometimes not.

**Comment by Nyr** [comment]
It depends on the distro. For Debian/Ubuntu you would also need to edit `/etc/systemd/system/openvpn-iptables.service` and reboot.

For RHEL-based distros, you need to edit the firewalld rules.

**Comment by hafizhmakmur** [comment]
@Nyr i don't see anything related to public ip there, only internal IP.

**Comment by hafizhmakmur** [comment]
[Unit]
Before=network.target
[Service]
Type=oneshot
ExecStart=/usr/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 10.184.0.2
ExecStart=/usr/sbin/iptables -I INPUT -p tcp --dport 1194 -j ACCEPT
ExecStart=/usr/sbin/iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStart=/usr/sbin/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=/usr/sbin/iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 10.184.0.2
ExecStop=/usr/sbin/iptables -D INPUT -p tcp --dport 1194 -j ACCEPT
ExecStop=/usr/sbin/iptables -D FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStop=/usr/sbin/iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target

**Comment by Nyr** [comment]
Is your server behind NAT?

Please provide the output of `ip addr`

**Comment by hafizhmakmur** [comment]
Yes it is.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:b8:00:02 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    inet 10.184.0.2/32 brd 10.184.0.2 scope global dynamic ens4
       valid_lft 2695sec preferred_lft 2695sec
    inet6 fe80::4001:aff:feb8:2/64 scope link
       valid_lft forever preferred_lft forever
9: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 10.8.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::d52d:9e0a:b155:1aa1/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

**Comment by Nyr** [comment]
Nothing wrong with the config you posted, the problem must be elsewhere.

But, I misunderstood your first message, for anyone else encountering this situation in the future, you also need to edit the `local` parameter in `/etc/openvpn/server/server.conf`. In your case this does not apply as it will have the local IP configured which has not changed.

**Comment by hafizhmakmur** [comment]
Yeah I'm currently installing openvpn on another server and after I'm installing grafana and Prometheus, for some reason the VPN no longer works eventhough the IP has not changed at all. I guess it's really sufficient to just change the remote on the ovpn.

**Comment by hafizhmakmur** [comment]
@Nyr  Yeah it turns out removing and reinstalling openvpn using the script makes it work. I dont know why but installing grafana and prometheus really do ruin the server, maybe it can be a concern for you. For future readers, be sure to install grafana and prometheus BEFORE installing this script, or just reinstall it if you already install it.
