### ISSUE TITLE
Client can connects but no internet access

### ISSUE THREAD

**Issue by Zeus64** [Nyr/openvpn-install#949]
I just installed OpenVPN on my server via this script: https://github.com/Nyr/openvpn-install. Everything was fine, openvpn server run well. Now when I try from my client (windows 10, openvpn client) to connect to the server, the connection is well established but I have no internet on the client desktop. Note that from the client If I connect to another vpn server like surfshark VPN then everything work fine, I have internet access.

client config :

client
dev tun
proto udp
remote xx.xx.xx.xx 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3
<ca>

server config :

local xx.xx.xx.xx
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
explicit-exit-notify

Thank you very much in advance for your help.

**Comment by Nyr** [comment]
This usually means one of the following things:
- Something in your server is causing a conflict with the firewall rules used by the script. Install the script on a clean system and try again
- Something in your client is preventing the route from being set up. Try from a different client like your smartphone, and see if it works there
- Your network is filtering OpenVPN traffic
- Your server is behind NAT and something was configured incorrectly
