### ISSUE TITLE
peer review declined

### ISSUE THREAD

**Issue by lmorg** [Nyr/openvpn-install#95]
This project is in dire need of a peer review. I was trying to offer the owner constructive and friendly recommendations based on my own expertise in this industry, but I've been met with hostility. Nyt seems more keen on closing down discussions before users can discuss their issues, than he does on improving his code to keep it in line with security best practices.

This has the potential to be a very highly recommended product, but the no security software should be above peer review. That alone makes this project dangerous for it's users.

I didn't want to get into an argument with Nyr as that wouldn't be fair to either of us. But unfortunately the opportunity for constructive discourse seems to have broken down. So I raise this issue as a warning to anyone else thinking of reviewing and offering their expertise; tread carefully.

**Comment by Nyr** [comment]
You say I'm not open to discussion, but I had been talking to you for more than a week, both here and at Hacker News. We've exchanged tens of messages.

I've replied to ALL of your concerns and argued about them, even when you were very insistent and just repeating yourself multiple times. I've quoted recommendations from others, including the OpenVPN developers which argued against some of your suggestions. I've always explained my motivations when you questioned my decisions. I always appreciate useful feedback to improve my work and I've merged commits from other contributors in the past.

But you are right: I'm not interested in hearing from you any longer. You just keep spamming me and don't ever listen to my words or reasoning. You make me waste my time, which is the most valuable asset I have. Sorry if I'm not amused about it.

**Comment by lmorg** [comment]
It's always everyone else who's to blame and clearly just a coincident that every issue other people have raised with you has turned out the same. It must be difficult having your patience when there's so many idiots who constantly question your perfect code :P

**Comment by Nyr** [comment]
Leave me alone.
