### ISSUE TITLE
How many user can connect to vpn server at the same time?

### ISSUE THREAD

**Issue by alptolga** [Nyr/openvpn-install#950]
Hi Everyone,
 I am sorry, I couldn't find an answer to my question. That's why I had to ask here. How many users can connect at the same time to vpn server?

**Comment by Nyr** [comment]
253 users with the subnet size used by the default setup.

**Comment by alptolga** [comment]
> 253 users with the subnet size used by the default setup.

Thank you for your reply. I want to use vpn for 15 users with different config files. so that I can use without any problem.
