### ISSUE TITLE
TLS Error: local/remote TLS keys are out of sync

### ISSUE THREAD

**Issue by Lamsio** [Nyr/openvpn-install#953]
When my friends connected to the server, their devices were disconnected from time to time. I found the problem after checking the logs. Since I have no experience in this, I hope you can help me solve this problem. Thank you

**Comment by Lamsio** [comment]
and, I noticed what you said in the installation section (Once it ends, you can run it again to add more users), Does this mean that one OVPN file can only be used by one user? I shared the same file with my friends, and I'm not sure if that's why.

**Comment by TinCanTech** [comment]
> I shared the same file with my friends, and I'm not sure if that's why.

That is **exactly _why_** ..

You should use the script correctly, as documented.

However, you may be able to use `--duplicate-cn` in your server config .. but then you are operating **outside the bounds** of the script.

**Comment by Lamsio** [comment]
Thanks for your reply~
This problem is fixed, but when I selected UDP, the log reported many of the same errors.
`tls-crypt unwrap error: packet authentication failed`. So far, I have not change any configuration in the server.conf

**Comment by TinCanTech** [comment]
If your clients can connect successfully then you can ignore that error.

**Comment by Lamsio** [comment]
My friend told me that sometimes the connection would be automatically disconnected. I checked the log and found an error.
`tls-crypt unwrap error: bad packet ID (may be a replay)` and `tls-crypt unwrap error: packet replay`

**Comment by Lamsio** [comment]
Is this a flaw in the UDP protocol? I know that TCP protocol has higher stability. Does this mean that I should set the protocol to TCP?

**Comment by TinCanTech** [comment]
You have shared your client files with multiple clients, so you are bound to see some errors like the ones you see.  The right way for you to fix it, is to make separate client files for each of your clients, as instructed by the script.

If you start randomly changing things, which you do not understand, then expect it to all go wrong.

Simple answer: Do as the script instructs you.
