### ISSUE TITLE
The client cannot access the internet after connecting

### ISSUE THREAD

**Issue by ZhenyuTsai** [Nyr/openvpn-install#954]
openvpn client cannot access internet，Please, how to solve this problem?

**Comment by ManuelMartinC** [comment]
Mee too

**Comment by oscarsmx** [comment]
Same problem did you guys fix it?

**Comment by vijeta1** [comment]
If you are using google as a dns server during vpn setup then add 8.8.8.8 and 8.8.4.4 in DNS/IP in wifi settings. This may work.

**Comment by hilliao** [comment]
even if you choose the default DNS resolver during  the installation, the issue still happens. The client can Google search `what's my ip` to see the IP change during the VPN session. But accessing websites like Amazon or using Netflix, Speedtest app to stream would result in no connection timeout. This is a deal breaker.

**Comment by Nyr** [comment]
There are usually a few reasons why this does happen, and none of them is an issue with the installer itself:
- Selecting `Current system resolvers` as the DNS server, if the DNS server is unreachable from the VPN subnet.
- A firewall in the server or client needs to be configured to allow the VPN traffic
- Other client-side issues, sometimes the OpenVPN DNS server is not configured correctly on connection.
