### ISSUE TITLE
Add support for Oracle Linux

### ISSUE THREAD

**Issue by joaopedroalbernaz** [Nyr/openvpn-install#957]
It would be awesome if you could add support for Oracle Linux, specially to be run on the Oracle Cloud Infrastructure.

**Comment by slavid** [comment]
Hi @joaopedroalbernaz ,

I have downloaded and edited the script and it is very simple to make it work for Oracle Linux 8 (EPEL Repository enabled). Just change two lines at the "Detect OS" zone where it detects CentOS like this:

```
elif [[ -e /etc/almalinux-release || -e /etc/rocky-release || -e /etc/centos-release || -e /etc/redhat-release ]]; then
        os="centos"
        os_version=$(grep -shoE '[0-9]+' /etc/almalinux-release /etc/rocky-release /etc/centos-release /etc/redhat-release | head -1)
```

In the first line I added `|| -e /etc/redhat-release` and in the second line `/etc/redhat-release` and after that it just worked! Just like in this PR: https://github.com/Nyr/openvpn-install/pull/956

**Comment by Nyr** [comment]
Given the uncertainty surrounding RHEL clones, I do not want to commit support for any which is not already supported.
