### ISSUE TITLE
Ability to Connect with multiple IP on One Server

### ISSUE THREAD

**Issue by mpod4g** [Nyr/openvpn-install#966]
Hello

We want to connect to vpn server using this repository to install on one server.

But with multiple IP addresses.

I mean we want to define for example 5 IP for our server and connection can be able to connect with those 5 IPs.

Also we want to make server route data through each specific IP.

For example we have below IPs : 

Main : 111.111.111.111

Second : 222.222.222.222
Third : 333.333.333.333

and when i connect to for example third IP , IP websites show me the third ip , not main the main server IP.

Anybody did it before or has any experience???

Thanks

**Comment by Nyr** [comment]
The described functionality is not supported by the installer.
