### ISSUE TITLE
debian unstable is unsupported

### ISSUE THREAD

**Issue by absunth** [Nyr/openvpn-install#970]
@Nyr 
![github-issue](https://user-images.githubusercontent.com/111267332/185072199-e7314638-5582-46d1-929d-98cbfcb4c829.png)

**Comment by misterG13** [comment]
Consider updating your system OS to a version that still receives updates. Out dated systems hold insecure packages.

**Comment by misterG13** [comment]
That is a question to ask yourself.

"bookworm" is not in release state. Author will likely wait. Or look for someone to patch it in.

**Comment by Darkluna999** [comment]
Please Use Stable

**Comment by misterG13** [comment]
It will work but can you guarantee all packages are secure?

This is why we wait for release, there are testing procedures programmers follow to keep production versions secure.

**Comment by misterG13** [comment]
So you found problem, fixed it and instead of helping the community, you came to complain.

This is not Facebook

**Comment by thejohnha** [comment]
I agree, would be nice to run this script on Debian Testing.

**Comment by Nyr** [comment]
I do not want to commit support for testing or unstable, or to rewrite the version check and deal with issues from unsupported versions.

So while anyone is free and even encouraged to override the version check if they wish, this is a project with limited resources and no plans to officially support unstable/testing distros.

That said, I am fixing the version check to be more specific.
