### ISSUE TITLE
Logging current client connections?

### ISSUE THREAD

**Issue by wicknet** [Nyr/openvpn-install#971]
After 3 years, replaced an old Ubuntu 18 server running OpenVPN with a new VM running Ubuntu 22.0.4.1. 

As promised, Nyr's wonderful script delivered a fully configured VPN server in less than 2 minutes, and using his bulk-client-add script, created over 50 user profiles as well in a few minutes to send out to clients.

The only thing missing is that the following command run under ~/.bashrc  used to return all currently connected clients

cat /etc/openvpn/server/openvpn-status.log

In the current version (2.5.5) installed by the script, there doesn't appear to be any connection logs created under /var/log/openvpn or in /etc/openvpn/server.

Is there an easy fix to get that working again?

Thanks!

**Comment by Nyr** [comment]
This changed with commit cb8730b6213c579bf015ceadd2a1b18b887fc9a5.

The new location is:
`/run/openvpn-server/status-server.log`
