### ISSUE TITLE
Script not working with Ubuntu 22 LTS

### ISSUE THREAD

**Issue by NaXal** [Nyr/openvpn-install#974]
Hello,

I have used this script flawlessly with Ubuntu 20 LTS images deployed in AWS / Linode / DigitalOcean. It still works flawlessly but with Ubuntu 22 LTS images deployed at those cloud locations, this script is not starting the OpenVPN after installation

Server is not showing OpenVPN NIC or the OVPN server IP address

Further, status of OpenVPN is showing "active (exited)"

![02](https://user-images.githubusercontent.com/91847371/185988972-59e99e0b-a3a1-407c-8497-6816d8f7af8c.jpg)

How do I fix this? 

Please help troubleshooting it.

Thanks.

**Comment by Nyr** [comment]
That is not the correct service name.

Try this instead:
`systemctl status openvpn-server@server.service`

**Comment by NaXal** [comment]
Thank you for the quickest reply.

I am getting following output 

![02](https://user-images.githubusercontent.com/91847371/185990448-9e35050c-76f4-44e7-9143-9670d1b0a452.jpg)

server is not showing the OpenVPN IP address and clients are unable to connect

**Comment by Nyr** [comment]
Try running this and see what happens.
`openvpn --config /etc/openvpn/server/server.conf`

But something is wrong in your system, use the installer on a clean Ubuntu 22.04 image, it will work, this is not a problem with the installer.
