### ISSUE TITLE
Script to create new Connection Profile

### ISSUE THREAD

**Issue by luckyAkbar** [Nyr/openvpn-install#975]
I tried to use this script to install OpenVPN, and it works. But the problem is, this script produce client.ovpn file which is used to estabilish a VPN connection.

The problem is, this profile only can be used by a single machine in the same time. I can't use this profile on my phone when my PC is already connected to. Do we have some way to create new connection profile from the same server we installed?

**Comment by Nyr** [comment]
You can run the script again after install is finished and add or remove as many users as you want.
