### ISSUE TITLE
Suggestion for changing the interactive message of the bash script.

### ISSUE THREAD

**Issue by colourfulspring** [Nyr/openvpn-install#976]
Hi Nyr, 

Sorry for disturbing you abruptly. However I hope you can spend some free time read this issue.

Last week, I planned to try build an self-hosted OpenVPN on my Raspberry Pi. At beginning, I was lost in OpenVPN's verbose official documents and many pieces of configuration blogs on the Internet. After learing a lot of docker knowledge for about a week(according to others' blog, I must install docker on my Raspberry Pi if I want to use it as a OpenVPN server), I found a blog which suggested me running your bash script. I tried only once and it succeeded on ipv4! Thanks you a lot for your work on this script!

Despite that, one interactive message in your script made me confused. On line 130:
`echo "This server is behind NAT. What is the public IPv4 address or hostname?"`
I want to run OpenVPN on ipv6 without hostname, but looking at this message, I mistakenly thought your script only support ipv4. So I input the public ipv4 address of my Raspberry Pi. After that, your script generated a server config file with a line as:
`local <public ipv4 addr of my Raspberry Pi>`

At that moment I don't know how to edit the server config file so it can support ipv6, so I found [Reference Manual](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) of OpenVPN. After reading Manual for nearly one day, checking almost every line of config files (server's and client's) and doing many experiments, I finally found that I just need to change the server config file to: 
`local <public ipv6 addr of my Raspberry Pi>`
Then I could run OpenVPN on ipv6. I was very confused. I didn't know whether it was possible that I input some parameters while running the script at beginning and it generated a server config file with
`local <public ipv6 addr of my Raspberry Pi>`
automatically. If there existed a way, I suggested you changing the message 'This server is behind NAT. What is the public IPv4 address or hostname?' for a little. The old message would mislead those who wanted use OpenVPN on ipv6 (for example me😂).

Sincerely hope your reply. 

Colourfulspring.

**Comment by Nyr** [comment]
I do not fully get your point.

The installer asks about the public IPv4 address because it is required to establish the connection (over IPv4).

VPN over IPv6 is not officially supported by the script but of course one can change the configuration to achieve this.

What the script will do, and is what most people care about, is set up IPv6 inside the tunnel, if the server has a working IPv6 connection. This is configured 100% unattended without bothering the user, some will not even notice that they have working IPv6.

**Comment by colourfulspring** [comment]
Sorry for late reply. Maybe my last issue is too verbose to understand.

The network at my living place is partly broken. It only supports IPv6 protocol physically at network layer and I am unable to fix it temprorarily, so I try to establish an OpenVPN connection between my laptop and a VPS with IPv6. Through this connection I can visit those sites that only support IPv4.

Wireshark says OpenVPN is based on IPv6 protocol.
![捕获1](https://user-images.githubusercontent.com/44148390/189465035-4d75d760-8d6b-4c61-8365-28ba4dadbada.PNG)

I know after establishing an OpenVPN connection, everything works just 100% unattended without bothering the user. But during establishing process, I must use IPv6, too.

Now that you said VPN over IPv6 is not officially supported by the script but of course one can change the configuration to achieve this, I just change the IP manually after running "add a client" part of your script.
