### ISSUE TITLE
Not working after reboot

### ISSUE THREAD

**Issue by MBillhardt** [Nyr/openvpn-install#977]
First: Great Job! I ran the script and it worked like a charme on my Ubuntu 18.04 Server ...
But after rebooting the systrem i can connetct to the VPN-Server, connect for eyample via ssh to 10.8.0.1 but not to any other domains.

systemctl status openvpn give's me:
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2022-09-03 20:43:43 CEST; 17min ago
  Process: 1910 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 1910 (code=exited, status=0/SUCCESS)
... systemd[1]: Started OpenVPN service.

Can anyone please help me?

Thank you!
Michael

**Comment by Nyr** [comment]
Does your server have a dynamic IP address? Provide details of your environment, is this a cloud provider - which? Or are you running the installer at home behind NAT and with a dynamic public IP address.

Anyway you are checking the status of the wrong service file. The correct one is: `openvpn-server@server.service`

What is the output of this?
`systemctl status openvpn-iptables.service`

**Comment by MBillhardt** [comment]
Thank you for your quick reply.
It's a virtual Server with Plesk hostet at Strato, fixed IP, no NAT.

Outputs:
root@XXX:~# systemctl status openvpn-server@server.service
● openvpn-server@server.service - OpenVPN service for server
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; indirect; vendor preset: enabled)
  Drop-In: /etc/systemd/system/openvpn-server@server.service.d
           └─disable-limitnproc.conf
   Active: active (running) since Sun 2022-09-04 08:38:31 CEST; 3s ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 20478 (openvpn)
   Status: "Initialization Sequence Completed"
    Tasks: 1 (limit: 165)
   CGroup: /system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service
           └─20478 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf

Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: UDPv4 link remote: [AF_UNSPEC]
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: GID set to nogroup
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: UID set to nobody
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: MULTI: multi_init called, r=256 v=256
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: ifconfig_pool_read(), in='cerberus,10.8.0.2', TODO: IPv6
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: succeeded -> ifconfig_pool_set()
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: IFCONFIG POOL LIST
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: cerberus,10.8.0.2
Sep 04 08:38:31 XXX.stratoserver.net openvpn[20478]: Initialization Sequence Completed


root@XXX:~# systemctl status openvpn-iptables.service
● openvpn-iptables.service
   Loaded: loaded (/etc/systemd/system/openvpn-iptables.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2022-09-03 20:38:32 CEST; 12h ago
  Process: 210 ExecStart=/sbin/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 205 ExecStart=/sbin/iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 194 ExecStart=/sbin/iptables -I INPUT -p udp --dport 1194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 161 ExecStart=/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to XXX.XXX.XXX.XXX (code=exited, status=0/SUCCESS)
 Main PID: 210 (code=exited, status=0/SUCCESS)

Sep 03 20:30:36 XXX.stratoserver.net systemd[1]: Stopped openvpn-iptables.service.
Sep 03 20:31:23 XXX.stratoserver.net systemd[1]: Starting openvpn-iptables.service...
Sep 03 20:31:23 XXX.stratoserver.net systemd[1]: Started openvpn-iptables.service.
Sep 03 20:36:45 XXX.stratoserver.net systemd[1]: Stopping openvpn-iptables.service...
Sep 03 20:36:45 XXX.stratoserver.net iptables[4450]: iptables: Bad rule (does a matching rule exist in that chain?).
Sep 03 20:36:45 XXX.stratoserver.net systemd[1]: openvpn-iptables.service: Control process exited, code=exited status=1
Sep 03 20:36:45 XXX.stratoserver.net systemd[1]: openvpn-iptables.service: Failed with result 'exit-code'.
Sep 03 20:36:45 XXX.stratoserver.net systemd[1]: Stopped openvpn-iptables.service.
Sep 03 20:38:30 XXX.stratoserver.net systemd[1]: Starting openvpn-iptables.service...
Sep 03 20:38:32 XXX.stratoserver.net systemd[1]: Started openvpn-iptables.service.

There seems to be a problem with the Plesk firewall rules.  Restarting the iptables-service manually after reboot corrects the fw-settings ... until reboot ...

Any ideas?

Thank you fpr your help!
Michael

**Comment by Nyr** [comment]
> There seems to be a problem with the Plesk firewall rules. Restarting the iptables-service manually after reboot corrects the fw-settings ... until reboot ...

What is likely happening when you boot the server is:
- First, OpenVPN rules get applied
- Plesk starts shortly after, applying restrictive rules with higher priority, or maybe flushing existing rules

You could work around this by making the `openvpn-iptables.service` start after Plex, but that is not the right way to approach this. The proper solution is to correctly configure the Plex firewall. I have no experience with Plex, so I suggest to do your own research or ask whoever is giving you support for Plesk.

**Comment by MBillhardt** [comment]
Maybe you tell me, wich ports have to be open for openvpn? 1194 incoming/outgoing/forwarding alone does not solve the problem …

**Comment by Nyr** [comment]
Since your OpenVPN client is able to connect to the server, it is not a matter of opening a port within Plesk, if the port was not open you would be unable to establish a connection.

You need to set forwarding and NAT rules, and I have no clue if Plesk has an advanced mode or something to add them.

You can look at the required rules by running this:
`systemctl cat openvpn-iptables.service | grep ExecStart`

It is possible that you can not configure this within the Plesk web panel.

**Comment by zxiaozhou** [comment]
@MBillhardt run and try
```
sysctl -w net.ipv4.ip_forward=1
```
