### ISSUE TITLE
Chain 2 OpenVPN servers

### ISSUE THREAD

**Issue by sahand12** [Nyr/openvpn-install#983]
first, I must say I don't know if here is the right place or not to raise this issue, but I don't know any other way. so here we go:
I live in a place where outside access is restricted and only a handful of data centers have heavily censored access to the outside world and normal users only have access to the local network. So I need to have 2 servers to enable my friends and family to use internet. One in a local data center and another one in the outside world. 
Is it possible for you to guide me how to do this, or at least push me in the right direction? I have the 2 servers in place, both running the OpenVPN using your script, but I don't know how I can forward all the traffic from the local server to the other server.
thanks for everything you have done.

Iranian users ---> local OpenVPN server in a data center in Iran ---> OpenVPN server in Germany (for example) ---> outside world

**Comment by Nyr** [comment]
Is the domestic internet so filtered nowadays in Iran that you are unable to use [V2Fly](https://www.v2fly.org/en_US/) to connect directly to the outside? I understand this is not possible with OpenVPN traffic, but you should have better luck with V2Fly, which is a proper tool for the job.

An alternative to this would be to use my OpenVPN installer normally to set up your IR VPN server. You connect to your IR server over OpenVPN, and from the client use V2Fly to a server outside.

V2Fly also has the advantage of letting you do split routing for domestic traffic using lists like [this](https://github.com/SamadiPour/iran-hosted-domains).
