### ISSUE TITLE
No open port

### ISSUE THREAD

**Issue by parsanoori** [Nyr/openvpn-install#984]
I used the shell and set the port to be 1194 but I get the following on running `ss -tonlp`:
```
State           Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port         Process
LISTEN          0               4096                           0.0.0.0:443                         0.0.0.0:*
LISTEN          0               4096                           0.0.0.0:80                          0.0.0.0:*
LISTEN          0               4096                     127.0.0.53%lo:53                          0.0.0.0:*
LISTEN          0               4096                           0.0.0.0:9174                        0.0.0.0:*
LISTEN          0               128                            0.0.0.0:22                          0.0.0.0:*
LISTEN          0               4096                              [::]:443                            [::]:*
LISTEN          0               4096                              [::]:80                             [::]:*
LISTEN          0               4096                              [::]:9174                           [::]:*
LISTEN          0               128                               [::]:22                             [::]:*
```
On running `sudo systemctl status openvpn-server@server.service` I get:
```
● openvpn-server@server.service - OpenVPN service for server
     Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-09-22 23:44:12 CEST; 2min 38s ago
       Docs: man:openvpn(8)
             https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
             https://community.openvpn.net/openvpn/wiki/HOWTO
   Main PID: 13053 (openvpn)
     Status: "Initialization Sequence Completed"
      Tasks: 1 (limit: 2282)
     Memory: 2.0M
        CPU: 39ms
     CGroup: /system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service
             └─13053 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config>

Sep 22 23:44:12 localhost openvpn[13053]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Sep 22 23:44:12 localhost openvpn[13053]: Socket Buffers: R=[212992->212992] S=[212992->212992]
Sep 22 23:44:12 localhost openvpn[13053]: UDPv4 link local (bound): [AF_INET]46.23.109.251:1194
Sep 22 23:44:12 localhost openvpn[13053]: UDPv4 link remote: [AF_UNSPEC]
Sep 22 23:44:12 localhost openvpn[13053]: GID set to nogroup
Sep 22 23:44:12 localhost openvpn[13053]: UID set to nobody
Sep 22 23:44:12 localhost openvpn[13053]: MULTI: multi_init called, r=256 v=256
Sep 22 23:44:12 localhost openvpn[13053]: IFCONFIG POOL IPv4: base=10.8.0.2 size=253
Sep 22 23:44:12 localhost openvpn[13053]: IFCONFIG POOL LIST
Sep 22 23:44:12 localhost openvpn[13053]: Initialization Sequence Completed
```
What's the problem?

**Comment by Nyr** [comment]
`ss -tonlpu`

**Comment by parsanoori** [comment]
I changed the port to 443 due to being behind firewall (not sure if it is really helpful).
`ss -tolnpu` gives the port 443 has state `UNCONN`.
When I run `telnet localhost 443` on the server I get:
```
Trying ::1...
Trying 127.0.0.1...
Trying [my public ip address]...
telnet: Unable to connect to remote host: Connection refused
```
When I run `telnet` on the client it's the same.  
Obviously can't connect from openvpn client too.
Here's the log from `/run/openvpn-server/status-server.log`:
```
TITLE,OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
TIME,2022-09-23 00:36:33,1663886193
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID,Data Channel Cipher
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
GLOBAL_STATS,Max bcast/mcast queue length,0
END
```

**Comment by Nyr** [comment]
> I changed the port to 443 due to being behind firewall (not sure if it is really helpful).

HTTPS is port 443 TCP. telnet also works over TCP.

OpenVPN by default uses UDP, so if you are trying to bypass a firewall you would want to select the TCP option in the installer along with port 443.

With that said, you will be only able to bypass very basic filtering systems using this approach.

Are you trying to bypass governmental censorship? And if so, which country are you in? Azerbaijan? Russia?

**Comment by parsanoori** [comment]
I'm in Iran.  
It's good to mention that Iran's censorship has got some improvements within the last 2-3 days.

**Comment by parsanoori** [comment]
This is the log of OpenVPN client:
```
⏎[Sep 23, 2022, 10:19:14] Connecting to [my public ip address]:443 (my public ip address) via TCPv4
⏎[Sep 23, 2022, 10:19:24] Server poll timeout, trying next remote entry...
⏎[Sep 23, 2022, 10:19:24] EVENT: RECONNECTING ⏎[Sep 23, 2022, 10:19:24] EVENT: RESOLVE ⏎[Sep 23, 2022, 10:19:24] EVENT: WAIT ⏎[Sep 23, 2022, 10:19:24] UnixCommandAgent: transmitting bypass route to /var/run/agent_ovpnconnect.sock
{
	"host" : "my public ip address",
	"ipv6" : false,
	"pid" : 31038
}
```

**Comment by Nyr** [comment]
> I'm in Iran

You should have mentioned this important bit of information in the first message...

Forget about OpenVPN, you need to use a tool specifically designed to bypass censorship, like V2Ray:
https://www.v2fly.org/en_US/

You can also try Tor, take a look at this:
https://forum.torproject.net/t/iran-circumventing-censorship-with-tor/4590

One of those two solutions is likely to work, at least in a limited capacity.

If you try a tool and it works reliably, please come back here and let us know, you are now the only person contacting me from Iran within the last few days, but we foreigners have limited visibility on what is going on inside.

Good luck.

**Comment by parsanoori** [comment]
I haven't tried V2Ray yet, but shadowsocks over simple-obfs is also malfunctioning.Although it helps using telegram messenger but WhatsApp and web browsing has some problems.
Tor is fine, works flawlessly, but as its architecture demands it reduces the speed.  
Using ProtonVPN I can use OpenVPN protocol to connect to the outside. But I still have the speed problem as the premium version is really unaffordable for Iranians.

**Comment by Nyr** [comment]
Try V2Fly, it has much more than Shadowsocks and is likely to work in my opinion.

I just took a look, and Proton VPN does not do anything special compared to my OpenVPN installer, at least the free .ovpn config from them which I just examined. Please note that if V2Fly is also slow in your country (I do not know) the censors could be intentionally throttling connections. This is a cat and mouse game, and I can not play it with openvpn-install.

With that said, OpenVPN is not a tool designed to evade censorship, that is why I suggest Tor with Snowflake and V2Fly, which are tools specifically designed for this.

I wish you the best.

**Comment by parsanoori** [comment]
Thank you so much.

**Comment by parsanoori** [comment]
Your installer worked too.
I connected to the OpenVPN server using a linux client. 
Seems like there's a problem with OpenVPN-connect on MacOS.

**Comment by Nyr** [comment]
For macOS, the best clients are in order from better to worse (in my opinion):
- [Viscosity](https://www.sparklabs.com/viscosity/)
- [Tunnelblick](https://tunnelblick.net/)
- [OpenVPN community](https://openvpn.net/community-downloads/) (not Connect)

**Comment by misterG13** [comment]
I would like to suggest an idea. Did you try using a hotspot/tether from your phone for your internet connection. Also changing the phone's apn to use only ipv4. With cell connections, they constantly change ip addresses and disabling ipv6 in the apn helps reduce chances of restrictions. I use my phone's tethering to bypass dmca restrictions without using a vpn. Maybe this connection will allow openvpn to connect.

**Comment by Nyr** [comment]
@misterG13 sadly, none of that is likely to work in Iran.

**Comment by parsanoori** [comment]
@misterG13 there's little to no IPV6 in Iran. As @Nyr said Iran's firewall is nowadays extremely restricted and powerful.
