### ISSUE TITLE
tunnel

### ISSUE THREAD

**Issue by Zo0oX** [Nyr/openvpn-install#985]
hello

thanks a lot for your work.

sir i'm in iran and in iran have no internet, we need to use tunnel and 1 server in iran and 1 server out of country, how can i connect this 2 server and make a tunnel ?

thanks

**Comment by Nyr** [comment]
That kind of setup is not supported natively by this installer.

However, take a look at previous discussion with other Iranian users: https://github.com/Nyr/openvpn-install/issues/983 https://github.com/Nyr/openvpn-install/issues/984

Setting up OpenVPN to a server inside Iran, and then using a V2Ray proxy to reach the foreign internet while connected to the VPN could be a reasonable approach based on what other people are telling me. Other than that, until someone in Iran is able to let us know what specifically works and what does not, I am unable to provide more specific advice.

There are other approaches which will potentially work and are better from a technical standpoint, but I am trying to keep things simple here.

Good luck.
