### ISSUE TITLE
Change client's `common name`/`username`/`hostname`

### ISSUE THREAD

**Issue by poulou0** [Nyr/openvpn-install#989]
### Intro
Hello and let me start by thanking for the great script :))

### Quick question
I'm using [openvpn-monitor](https://github.com/furlongm/openvpn-monitor) on the top and i want to change **the names that appear on the first column**

* Is there a way to change the client's `common name`/`username`/`hostname` _(not sure what is the right way to call it)_
Ideally without deleting and making a new client with a different .ovpn file.
* If i have to delete and make a new client, can i reuse the deleted IP?

### What i tried
I tried changing the `CN=name_i_want_to_change` in the files:
* `server/ipp.txt` (later i figured that this is generated on every restart)
* `/etc/openvpn/server/easy-rsa/pki/index.txt`
* `server/easy-rsa/pki/certs_by_serial/XXXXXXXXXXXX.pem`
* `server/easy-rsa/pki/issued/name_i_want_to_change.crt`
I also tried renaming the file above

**Comment by Nyr** [comment]
> Is there a way to change the client's common name/username/hostname (not sure what is the right way to call it)

Since I am not familiar with this piece of software, please provide a screenshot of how it looks for you. For the user name they should be using the client CN, and this should be correctly set by my installer.

Please also provide the output of this:
`openssl x509 -subject -noout -in /etc/openvpn/server/easy-rsa/pki/issued/$client.crt`
Change `$client` with your client name. It should show the name you defined and not something like `ChangeMe`.

Also, I guess you are using the latest version of my installer, right?

**Comment by poulou0** [comment]
Thanks for the quick reply!

I also think the CN must be used..
If its part of the certificate and cannot be changed, is there a way to reuse 10.8.0.5 after i revoke this client?

> please provide a screenshot of how it looks for you.

![image](https://user-images.githubusercontent.com/48758557/193013706-8502748d-c7ed-419d-9c56-ea55f71cc768.png)

> please provide a screenshot of how it looks for you.

```
# openssl x509 -subject -noout -in /etc/openvpn/server/easy-rsa/pki/issued/pi4-048.crt 
subject=CN = pi4-048
```
> Also, I guess you are using the latest version of my installer, right?

Unfortunately this client was created back in May 2020

**Comment by Nyr** [comment]
Sorry, I misunderstood your first message.

You can not change the CN once a certificate is issued. And the IP addresses are not statically assigned, so there is no way to assign a specific IP to a client.

**Comment by poulou0** [comment]
No problem, at least I know now.
Thanks again for resolving it so fast!
:))
