### ISSUE TITLE
No internet after connection (noob)

### ISSUE THREAD

**Issue by timurkalandarov** [Nyr/openvpn-install#99]
Hi! I tried to use this script on Ubuntu 14.04 machine (Microsoft Azure).

1. I set up endpoints
![image](https://cloud.githubusercontent.com/assets/8779881/11634598/53343482-9d33-11e5-935d-129783cbdbbd.png)
2. Then it asked me about IP, Port and DNS (I tried Current system resolvers and Google DNS)
![image](https://cloud.githubusercontent.com/assets/8779881/11634677/c4fa5b0a-9d33-11e5-89ac-652f192a32fa.png)
3. And then I wrote external right IP of server machine (checked it twice)
4. it seems like connection is good and there is a problem with smth on server machine

  ![image](https://cloud.githubusercontent.com/assets/8779881/11634805/8eeb90fa-9d34-11e5-974f-d40ca2b0a331.png)
5. Ping to 8.8.8.8 on local machine

  ![image](https://cloud.githubusercontent.com/assets/8779881/11634827/b06fa4a0-9d34-11e5-98c6-df654562ba5b.png)

Can someone help me with this? Thanks!

**Comment by stefancrain** [comment]
Hi @timurkalandarov, could you post the output of `ifconfig` on the Azure box and the other box you are trying to connect from? Also `iptables -t nat -L` might be helpful. 

It looks you are have set the vpn up with an ip address in the local address range ([see rfc1918](https://tools.ietf.org/html/rfc1918#page-4)), thus unlikely to be reachable outside of that private network.

For what its worth, this reminds me of issue #92

**Comment by Nyr** [comment]
Yeah, @stefancrain is right. This looks like a problem with your setup.

Is your Azure server behind a NAT? If not, you did set the wrong IP address during setup.

**Comment by timurkalandarov** [comment]
Many thanks for the prompt reply!

I found out that after Microsoft changed Azure Portal, it creates VPN with VM by default (it was a problem, as I think). I just open old portal and create new VM without any network and OpenVPN works fine now!

**Comment by Nyr** [comment]
Glad to know it's solved.
