### ISSUE TITLE
Add IPv6 Local Address

### ISSUE THREAD

**Issue by Rishi556** [Nyr/openvpn-install#990]
Without having a local ipv6 address, ex `local 2001:db8::1`, in the server.conf, openvpn prefers ipv4 and uses ipv6 only when ipv4 is not available. Adding this onto my local configuration has let chrome use happy eyeballs again to pick whatever is faster.

**Comment by Rishi556** [comment]
Nevermind, it looks like my ip address extension on chrome just had cached data and it wasn't actually using ipv6 more than v4.

**Comment by TinCanTech** [comment]
@Rishi556 That is quite interesting, thanks for posting.
