### ISSUE TITLE
new users can not access internet

### ISSUE THREAD

**Issue by IMIEEET** [Nyr/openvpn-install#993]
hello there 
my openvpn server was working very fine with a lot of users
but i decided to increase usable hosts by changing the netmask in server.conf from 255.255.255.0 to 255.255.252.0
users that i creted before this change can access internet
but new users can not but they can connect successfully
i think thats because of this change. i must have changed something else

**Comment by IMIEEET** [comment]
update: ipp.txt contains duplicate ip for users 
after 10.8.0.255 for a user it overlaped to 10.8.0.1 for next user

**Comment by Nyr** [comment]
Assuming you are using Debian/Ubuntu, you would need to edit `/etc/systemd/system/openvpn-iptables.service` and change rules from a `/24` to a `/22`.
