### ISSUE TITLE
Manually uninstalling openvpn is not detected

### ISSUE THREAD

**Issue by TinCanTech** [Nyr/openvpn-install#994]
Hi,

I was testing some solutions to https://github.com/OpenVPN/easy-rsa/issues/725

Using `debian-10`, I manually uninstalled `openvpn`: `apt remove openvpn`

The script still detects `/etc/openvpn/server/server.conf` because `apt` does not remove user files.

The result:
```
OpenVPN is already installed.

Select an option:
   1) Add a new client
   2) Revoke an existing client
   3) Remove OpenVPN
   4) Exit
Option: 4
deb10 Nyr # apt remove openvpn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'openvpn' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
deb10 Nyr # 
```

This is a very minor issue, which I can rectify myself. However, I decided to report it here for your information.

**Comment by Nyr** [comment]
Problem is: removing the openvpn package will leave leftovers like firewall rules or sysctl configuration, so during normal usage, this is better avoided. Users wishing to uninstall should really use the removal option in the script, which will cleanup everything that can be safely removed.

Yeah, we could be extra helpful and check multiple things to alert the user of a broken installation, but other than that the uninstall option should "always" be used.
