### ISSUE TITLE
Change interface name

### ISSUE THREAD

**Issue by enboig** [Nyr/openvpn-install#997]
After using your script, I changed my server (moving disks) and network interface name was changed (`en01` -> `eno1`). Now openvpn don't accept connections. What is the easiest way to solve this?

**Comment by Nyr** [comment]
My installer does not reference interface names anywhere.

**Comment by enboig** [comment]
I supposed it added some iptables rules to make openvpn work. I don't know if there is some sort of reinstall which keep created clients/certificates
