### ISSUE TITLE
non-interactive client

### ISSUE THREAD

**Issue by mimooh** [Nyr/openvpn-install#999]
Hi, perhaps it is worth mentioning on your project site, that there is a non-interactive client here:
https://github.com/mimooh/ovclient

I believe many administrators deal with tens or hundreds of vpn users and they might look for such a tool.
Also I have a working google-authenticator  integrated and tested (for extra security user needs to type codes from smartphone during vpn login).

**Comment by Nyr** [comment]
I will remember this if someone asks, but will not advertise it in the main page sorry.
